export type {
  Block,
  DocumentAst,
  DocumentAstMetadata,
  DocumentAstSource,
  HeadingBlock,
  HeadingLevel,
  ImageBlock,
  Inline,
  InlineBlock,
  InlineBold,
  InlineCitation,
  InlineItalic,
  InlineLineBreak,
  InlineLink,
  InlineSubscript,
  InlineSuperscript,
  InlineText,
  InlineUnderline,
  ParagraphBlock,
  ParagraphNote,
  ParagraphRole,
  PersistedAstDegradation,
  TableBlock,
  TableCell,
  WireBlock,
  WireDocumentAst,
  WireTableCell,
} from "@stll/legal-ast/document-ast";

export {
  hasBlockInlines,
  hasInlineChildren,
} from "@stll/legal-ast/document-ast";
export {
  getDocumentAstMetadata,
  hasUsableAst,
  isDocumentAst,
  omitDerivablePlainText,
  parseDocumentAst,
  parseUsableDocumentAst,
  plainTextOf,
  projectPlainText,
  withProjectedPlainText,
} from "@stll/legal-ast/document-ast";
