export type {
  Block,
  DocumentAst,
  DocumentAstMetadata,
  DocumentAstSource,
  HeadingBlock,
  HeadingLevel,
  Inline,
  InlineBold,
  InlineItalic,
  InlineLineBreak,
  InlineLink,
  InlineText,
  ParagraphBlock,
  ParagraphNote,
  ParagraphRole,
  TableBlock,
  TableCell,
  WireBlock,
  WireDocumentAst,
  WireTableCell,
} from "@stll/legal-ast/document-ast";

export {
  getDocumentAstMetadata,
  hasUsableAst,
  isDocumentAst,
  omitDerivablePlainText,
  parseDocumentAst,
  parseUsableDocumentAst,
  plainTextOf,
  projectPlainText,
  withProjectedPlainText,
} from "@stll/legal-ast/document-ast";
