export const CZ_ECLI_COURTS = {
  KSBR: "Krajský soud v Brně",
  KSBRZL: "Krajský soud v Brně – pobočka ve Zlíně",
  KSCB: "Krajský soud v Českých Budějovicích",
  KSCBTA: "Krajský soud v Českých Budějovicích – pobočka v Táboře",
  KSHK: "Krajský soud v Hradci Králové",
  KSHKPA: "Krajský soud v Hradci Králové – pobočka v Pardubicích",
  KSOS: "Krajský soud v Ostravě",
  KSOSOL: "Krajský soud v Ostravě – pobočka v Olomouci",
  KSPH: "Krajský soud v Praze",
  KSPL: "Krajský soud v Plzni",
  KSUL: "Krajský soud v Ústí nad Labem",
  KSULLI: "Krajský soud v Ústí nad Labem – pobočka v Liberci",
  MSBR: "Městský soud v Brně",
  MSPH: "Městský soud v Praze",
  NS: "Nejvyšší soud",
  NSS: "Nejvyšší správní soud",
  OSCK: "Okresní soud v Českém Krumlově",
  OSOV: "Okresní soud v Ostravě",
  OSZR: "Okresní soud ve Žďáru nad Sázavou",
  US: "Ústavní soud",
  VSOL: "Vrchní soud v Olomouci",
  VSPH: "Vrchní soud v Praze",
} as const satisfies Readonly<Record<string, string>>;

export type CzEcliCourtCode = keyof typeof CZ_ECLI_COURTS;

export const SK_ECLI_COURTS = {
  KSBA: "Krajský súd v Bratislave",
  KSBB: "Krajský súd v Banskej Bystrici",
  KSKE: "Krajský súd v Košiciach",
  KSNR: "Krajský súd v Nitre",
  KSPO: "Krajský súd v Prešove",
  KSTN: "Krajský súd v Trenčíne",
  KSTT: "Krajský súd v Trnave",
  KSZA: "Krajský súd v Žiline",
  MSBA1: "Mestský súd Bratislava I",
  MSBA2: "Mestský súd Bratislava II",
  MSBA3: "Mestský súd Bratislava III",
  MSBA4: "Mestský súd Bratislava IV",
  MSKE: "Mestský súd Košice",
  NSSR: "Najvyšší súd Slovenskej republiky",
  NSSSR: "Najvyšší správny súd Slovenskej republiky",
  OSBA1: "Okresný súd Bratislava I",
  OSBA5: "Okresný súd Bratislava V",
  OSBB: "Okresný súd Banská Bystrica",
  OSBJ: "Okresný súd Bardejov",
  OSBN: "Okresný súd Bánovce nad Bebravou",
  OSBR: "Okresný súd Brezno",
  OSCA: "Okresný súd Čadca",
  OSDK: "Okresný súd Dolný Kubín",
  OSDS: "Okresný súd Dunajská Streda",
  OSGA: "Okresný súd Galanta",
  OSHE: "Okresný súd Humenné",
  OSKE1: "Okresný súd Košice I",
  OSKE2: "Okresný súd Košice II",
  OSKE3: "Okresný súd Košice okolie",
  OSKK: "Okresný súd Kežmarok",
  OSKN: "Okresný súd Komárno",
  OSLC: "Okresný súd Lučenec",
  OSLM: "Okresný súd Liptovský Mikuláš",
  OSLV: "Okresný súd Levice",
  OSMA: "Okresný súd Malacky",
  OSMI: "Okresný súd Michalovce",
  OSMT: "Okresný súd Martin",
  OSNM: "Okresný súd Nové Mesto nad Váhom",
  OSNO: "Okresný súd Námestovo",
  OSNR: "Okresný súd Nitra",
  OSNZ: "Okresný súd Nové Zámky",
  OSPB: "Okresný súd Považská Bystrica",
  OSPD: "Okresný súd Prievidza",
  OSPE: "Okresný súd Partizánske",
  OSPK: "Okresný súd Pezinok",
  OSPN: "Okresný súd Piešťany",
  OSPO: "Okresný súd Prešov",
  OSPP: "Okresný súd Poprad",
  OSRA: "Okresný súd Revúca",
  OSRK: "Okresný súd Ružomberok",
  OSRS: "Okresný súd Rimavská Sobota",
  OSRV: "Okresný súd Rožňava",
  OSSE: "Okresný súd Senica",
  OSSI: "Okresný súd Skalica",
  OSSK: "Okresný súd Svidník",
  OSSL: "Okresný súd Stará Ľubovňa",
  OSSN: "Okresný súd Spišská Nová Ves",
  OSTN: "Okresný súd Trenčín",
  OSTO: "Okresný súd Topoľčany",
  OSTT: "Okresný súd Trnava",
  OSTV: "Okresný súd Trebišov",
  OSVK: "Okresný súd Veľký Krtíš",
  OSVT: "Okresný súd Vranov nad Topľou",
  OSZA: "Okresný súd Žilina",
  OSZH: "Okresný súd Žiar nad Hronom",
  OSZV: "Okresný súd Zvolen",
  SSPK: "Špecializovaný trestný súd",
  SpSBA: "Správny súd v Bratislave",
  SpSBB: "Správny súd v Banskej Bystrici",
  SpSKE: "Správny súd v Košiciach",
  USSR: "Ústavný súd SR",
} as const satisfies Readonly<Record<string, string>>;

export const EU_ECLI_COURTS = {
  C: "Court of Justice",
  T: "General Court",
} as const satisfies Readonly<Record<string, string>>;
