/** Court names and citation short codes, shared by ingestion and readers. */
export type RegisteredCourt = {
  name: string;
  shortCode: string;
};

export const CZ_ECLI_COURT_REGISTRY = {
  KSBR: { name: "Krajský soud v Brně", shortCode: "KS" },
  KSBRZL: { name: "Krajský soud v Brně – pobočka ve Zlíně", shortCode: "KS" },
  KSCB: { name: "Krajský soud v Českých Budějovicích", shortCode: "KS" },
  KSCBTA: {
    name: "Krajský soud v Českých Budějovicích – pobočka v Táboře",
    shortCode: "KS",
  },
  KSHK: { name: "Krajský soud v Hradci Králové", shortCode: "KS" },
  KSHKPA: {
    name: "Krajský soud v Hradci Králové – pobočka v Pardubicích",
    shortCode: "KS",
  },
  KSOS: { name: "Krajský soud v Ostravě", shortCode: "KS" },
  KSOSOL: {
    name: "Krajský soud v Ostravě – pobočka v Olomouci",
    shortCode: "KS",
  },
  KSPH: { name: "Krajský soud v Praze", shortCode: "KS" },
  KSPL: { name: "Krajský soud v Plzni", shortCode: "KS" },
  KSUL: { name: "Krajský soud v Ústí nad Labem", shortCode: "KS" },
  KSULLI: {
    name: "Krajský soud v Ústí nad Labem – pobočka v Liberci",
    shortCode: "KS",
  },
  MSBR: { name: "Městský soud v Brně", shortCode: "MS" },
  MSPH: { name: "Městský soud v Praze", shortCode: "MS" },
  NS: { name: "Nejvyšší soud", shortCode: "NS" },
  NSS: { name: "Nejvyšší správní soud", shortCode: "NSS" },
  OSCK: { name: "Okresní soud v Českém Krumlově", shortCode: "OS" },
  OSOV: { name: "Okresní soud v Ostravě", shortCode: "OS" },
  OSZR: { name: "Okresní soud ve Žďáru nad Sázavou", shortCode: "OS" },
  US: { name: "Ústavní soud", shortCode: "ÚS" },
  VSOL: { name: "Vrchní soud v Olomouci", shortCode: "VS" },
  VSPH: { name: "Vrchní soud v Praze", shortCode: "VS" },
} as const satisfies Readonly<Record<string, RegisteredCourt>>;

export const SK_ECLI_COURT_REGISTRY = {
  KSBA: { name: "Krajský súd v Bratislave", shortCode: "KS" },
  KSBB: { name: "Krajský súd v Banskej Bystrici", shortCode: "KS" },
  KSKE: { name: "Krajský súd v Košiciach", shortCode: "KS" },
  KSNR: { name: "Krajský súd v Nitre", shortCode: "KS" },
  KSPO: { name: "Krajský súd v Prešove", shortCode: "KS" },
  KSTN: { name: "Krajský súd v Trenčíne", shortCode: "KS" },
  KSTT: { name: "Krajský súd v Trnave", shortCode: "KS" },
  KSZA: { name: "Krajský súd v Žiline", shortCode: "KS" },
  MSBA1: { name: "Mestský súd Bratislava I", shortCode: "MS" },
  MSBA2: { name: "Mestský súd Bratislava II", shortCode: "MS" },
  MSBA3: { name: "Mestský súd Bratislava III", shortCode: "MS" },
  MSBA4: { name: "Mestský súd Bratislava IV", shortCode: "MS" },
  MSKE: { name: "Mestský súd Košice", shortCode: "MS" },
  NSSR: { name: "Najvyšší súd Slovenskej republiky", shortCode: "NS" },
  NSSSR: {
    name: "Najvyšší správny súd Slovenskej republiky",
    shortCode: "NSS",
  },
  OSBA1: { name: "Okresný súd Bratislava I", shortCode: "OS" },
  OSBA5: { name: "Okresný súd Bratislava V", shortCode: "OS" },
  OSBB: { name: "Okresný súd Banská Bystrica", shortCode: "OS" },
  OSBJ: { name: "Okresný súd Bardejov", shortCode: "OS" },
  OSBN: { name: "Okresný súd Bánovce nad Bebravou", shortCode: "OS" },
  OSBR: { name: "Okresný súd Brezno", shortCode: "OS" },
  OSCA: { name: "Okresný súd Čadca", shortCode: "OS" },
  OSDK: { name: "Okresný súd Dolný Kubín", shortCode: "OS" },
  OSDS: { name: "Okresný súd Dunajská Streda", shortCode: "OS" },
  OSGA: { name: "Okresný súd Galanta", shortCode: "OS" },
  OSHE: { name: "Okresný súd Humenné", shortCode: "OS" },
  OSKE1: { name: "Okresný súd Košice I", shortCode: "OS" },
  OSKE2: { name: "Okresný súd Košice II", shortCode: "OS" },
  OSKE3: { name: "Okresný súd Košice okolie", shortCode: "OS" },
  OSKK: { name: "Okresný súd Kežmarok", shortCode: "OS" },
  OSKN: { name: "Okresný súd Komárno", shortCode: "OS" },
  OSLC: { name: "Okresný súd Lučenec", shortCode: "OS" },
  OSLM: { name: "Okresný súd Liptovský Mikuláš", shortCode: "OS" },
  OSLV: { name: "Okresný súd Levice", shortCode: "OS" },
  OSMA: { name: "Okresný súd Malacky", shortCode: "OS" },
  OSMI: { name: "Okresný súd Michalovce", shortCode: "OS" },
  OSMT: { name: "Okresný súd Martin", shortCode: "OS" },
  OSNM: { name: "Okresný súd Nové Mesto nad Váhom", shortCode: "OS" },
  OSNO: { name: "Okresný súd Námestovo", shortCode: "OS" },
  OSNR: { name: "Okresný súd Nitra", shortCode: "OS" },
  OSNZ: { name: "Okresný súd Nové Zámky", shortCode: "OS" },
  OSPB: { name: "Okresný súd Považská Bystrica", shortCode: "OS" },
  OSPD: { name: "Okresný súd Prievidza", shortCode: "OS" },
  OSPE: { name: "Okresný súd Partizánske", shortCode: "OS" },
  OSPK: { name: "Okresný súd Pezinok", shortCode: "OS" },
  OSPN: { name: "Okresný súd Piešťany", shortCode: "OS" },
  OSPO: { name: "Okresný súd Prešov", shortCode: "OS" },
  OSPP: { name: "Okresný súd Poprad", shortCode: "OS" },
  OSRA: { name: "Okresný súd Revúca", shortCode: "OS" },
  OSRK: { name: "Okresný súd Ružomberok", shortCode: "OS" },
  OSRS: { name: "Okresný súd Rimavská Sobota", shortCode: "OS" },
  OSRV: { name: "Okresný súd Rožňava", shortCode: "OS" },
  OSSE: { name: "Okresný súd Senica", shortCode: "OS" },
  OSSI: { name: "Okresný súd Skalica", shortCode: "OS" },
  OSSK: { name: "Okresný súd Svidník", shortCode: "OS" },
  OSSL: { name: "Okresný súd Stará Ľubovňa", shortCode: "OS" },
  OSSN: { name: "Okresný súd Spišská Nová Ves", shortCode: "OS" },
  OSTN: { name: "Okresný súd Trenčín", shortCode: "OS" },
  OSTO: { name: "Okresný súd Topoľčany", shortCode: "OS" },
  OSTT: { name: "Okresný súd Trnava", shortCode: "OS" },
  OSTV: { name: "Okresný súd Trebišov", shortCode: "OS" },
  OSVK: { name: "Okresný súd Veľký Krtíš", shortCode: "OS" },
  OSVT: { name: "Okresný súd Vranov nad Topľou", shortCode: "OS" },
  OSZA: { name: "Okresný súd Žilina", shortCode: "OS" },
  OSZH: { name: "Okresný súd Žiar nad Hronom", shortCode: "OS" },
  OSZV: { name: "Okresný súd Zvolen", shortCode: "OS" },
  SSPK: { name: "Špecializovaný trestný súd", shortCode: "ŠTS" },
  SpSBA: { name: "Správny súd v Bratislave", shortCode: "SpS" },
  SpSBB: { name: "Správny súd v Banskej Bystrici", shortCode: "SpS" },
  SpSKE: { name: "Správny súd v Košiciach", shortCode: "SpS" },
  USSR: { name: "Ústavný súd SR", shortCode: "ÚS" },
} as const satisfies Readonly<Record<string, RegisteredCourt>>;

export const EU_ECLI_COURT_REGISTRY = {
  C: { name: "Court of Justice", shortCode: "CJEU" },
  T: { name: "General Court", shortCode: "GC" },
} as const satisfies Readonly<Record<string, RegisteredCourt>>;

export const ECLI_COURT_REGISTRY = {
  CZ: CZ_ECLI_COURT_REGISTRY,
  SK: SK_ECLI_COURT_REGISTRY,
  EU: EU_ECLI_COURT_REGISTRY,
} as const;
