import { describe, expect, test } from "bun:test";

import {
  buildDocumentVersionUploadReservationInput,
  buildUploadAbortInput,
  buildUploadFinalizeInput,
  DOCUMENT_VERSION_UPLOAD_TRANSPORT,
} from "./document-version-upload";

describe("document version upload transport contract", () => {
  test("builds the one reservation and lifecycle wire shape", () => {
    const workspaceId = "00000000-0000-4000-8000-000000000001";
    const uploadId = "00000000-0000-4000-8000-000000000002";

    expect(
      buildDocumentVersionUploadReservationInput({
        entityId: "00000000-0000-4000-8000-000000000003",
        file: {
          mimeType: "application/octet-stream",
          name: "agreement.docx",
          sha256Hex: "a".repeat(64),
          size: 42,
        },
        workspaceId,
      }),
    ).toEqual({
      body: {
        purpose: DOCUMENT_VERSION_UPLOAD_TRANSPORT.purpose,
        entityId: "00000000-0000-4000-8000-000000000003",
        mimeType: "application/octet-stream",
        name: "agreement.docx",
        sha256Hex: "a".repeat(64),
        size: 42,
      },
      params: { workspaceId },
    });
    expect(buildUploadFinalizeInput({ uploadId, workspaceId })).toEqual(
      buildUploadAbortInput({ uploadId, workspaceId }),
    );
  });

  test("the published CLI projection is a generated verbatim copy", async () => {
    const canonical = await Bun.file(
      new URL("document-version-upload.ts", import.meta.url),
    ).text();
    const generated = await Bun.file(
      new URL(
        "../../cli/src/generated/document-version-upload-transport.ts",
        import.meta.url,
      ),
    ).text();

    expect(generated).toBe(
      `// GENERATED by \`bun run codegen\`. Do not edit by hand.\n${canonical}`,
    );
  });
});
