import * as v from "valibot";

export type SafeIdType =
  | "accountDeletionRequest"
  | "agentSkill"
  | "agentSkillComment"
  | "agentSkillProposal"
  | "agentSkillResource"
  | "agentSkillRevision"
  | "aiMemory"
  | "anonymizationAllowlistEntry"
  | "anonymizationBlacklistEntry"
  | "auditLog"
  | "billingCode"
  | "caseLawCitation"
  | "caseLawCitationResolutionCensusRun"
  | "caseLawCoverageSlice"
  | "caseLawCourtWeight"
  | "caseLawDecision"
  | "caseLawDecisionAnnotation"
  | "caseLawCorpusUploadIntent"
  | "caseLawIndexJob"
  | "caseLawIngestionEvent"
  | "caseLawIngestionFailure"
  | "caseLawMatterLink"
  | "caseLawPolarityRule"
  | "caseLawProvisionCitation"
  | "caseLawReconciliationItem"
  | "caseLawResearchColumn"
  | "caseLawResearchTable"
  | "caseLawSource"
  | "caseLawSourceIngestionLease"
  | "chatMessage"
  | "chatTurn"
  | "chatThreadCompaction"
  | "chatThread"
  | "fileChatThread"
  | "templateChatThread"
  | "templateDeletionCleanupRequest"
  | "clause"
  | "clauseCategory"
  | "clauseVariant"
  | "clauseVersion"
  | "contact"
  | "contactExtractionUpload"
  | "contactImportRequest"
  | "contactRelationship"
  | "corpusIndexProjectionIntent"
  | "usageAllocation"
  | "usageLaneCounter"
  | "usageSeatAssignment"
  | "usagePolicy"
  | "usageEntitlement"
  | "usageEvent"
  | "desktopEditHandoff"
  | "desktopEditSession"
  | "bilingualTranslationRun"
  | "bilingualTranslationRow"
  | "docxSuggestion"
  | "document"
  | "documentCounter"
  | "entityDeletionCleanupRequest"
  | "accountDeletionEffectChunk"
  | "entityDeletionEffectChunk"
  | "effectLease"
  | "documentProcessingRun"
  | "documentReviewFinding"
  | "documentReviewParty"
  | "documentReviewReferencePassage"
  | "documentReviewRun"
  | "documentTranslationRun"
  | "documentTranslationUnit"
  | "documentType"
  | "entity"
  | "entityVersionAiSummary"
  | "entityVersion"
  | "expense"
  | "extractionRun"
  | "field"
  | "flowDefinition"
  | "flowRun"
  | "flowRunStep"
  | "signal"
  | "signalEvent"
  | "scoutRun"
  | "folioCollabRoom"
  | "folioCollabRoomToken"
  | "folioCollabContribution"
  | "folioCollabPublication"
  | "folder"
  | "infoSoudTrackedCase"
  | "invoice"
  | "justification"
  | "legislationDocument"
  | "legislationIndexJob"
  | "legislationSource"
  | "legalList"
  | "legalListColumn"
  | "legalListGenerationCandidate"
  | "legalListGenerationCandidateSource"
  | "legalListGenerationRun"
  | "legalListGenerationSource"
  | "legalListItemComment"
  | "legalListItemReview"
  | "legalListItemSource"
  | "legalListSection"
  | "matter"
  | "matterCounter"
  | "mcpConnector"
  | "mcpOAuthClient"
  | "mcpUserConnection"
  | "notification"
  | "organization"
  | "organizationSettings"
  | "pendingUpload"
  | "playbook"
  | "playbookDefinition"
  | "playbookDefinitionVersion"
  | "property"
  | "propertyDependency"
  | "rateEntry"
  | "rateTable"
  | "savedSearch"
  | "reportExport"
  | "schedulerJobRun"
  | "sharepointConnection"
  | "sharepointOAuthState"
  | "styleSet"
  | "taskAssignee"
  | "task"
  | "template"
  | "templateCategory"
  | "templateClause"
  | "templateRecipe"
  | "templateFill"
  | "templatePersistenceRequest"
  | "templateVersion"
  | "timeEntry"
  | "user"
  | "userFile"
  | "workspace"
  | "workspaceContact"
  | "workspaceMember"
  | "workspaceView"
  | "workspaceViewTemplate"
  | "workObligationEvent"
  | "entityLink";

export const isSafeIdValue = (value: string): boolean =>
  value.length > 0 && value.isWellFormed();

const safeIdSchema = v.pipe(
  v.string(),
  v.check(isSafeIdValue, "Expected a non-empty, well-formed identifier"),
  v.brand("SafeId"),
);

/**
 * Portable compile-time identifier brand. Runtime validation belongs to the
 * boundary that owns each identifier; the type parameter prevents IDs from
 * different domains being exchanged accidentally inside typed code.
 */
export type SafeId<TType extends string> = v.InferOutput<
  typeof safeIdSchema
> & {
  readonly __safeIdType?: TType;
};

/** Brand an identifier at a boundary that has already established its source. */
export const toSafeId = <TType extends string>(value: string): SafeId<TType> =>
  v.parse(safeIdSchema, value);
