// parser-output-unchanged: Adding the chat revision ID kind does not change parser IDs or parsed records.
import * as v from "valibot";

export { isUuid } from "@stll/uuid-codec";

export type SafeIdType =
  | "accountDeletionRequest"
  | "agentSkill"
  | "agentSkillComment"
  | "agentSkillProposal"
  | "agentSkillResource"
  | "agentSkillRevision"
  | "aiMemory"
  | "anonymizationAllowlistEntry"
  | "anonymizationBlacklistEntry"
  | "auditLog"
  | "billingCode"
  | "savedTimeNarrative"
  | "caseLawCitation"
  | "caseLawCitationReview"
  | "caseLawCitationResolutionCensusRun"
  | "caseLawCoverageSlice"
  | "caseLawCourtWeight"
  | "caseLawDecision"
  | "caseLawCorpusUploadIntent"
  | "caseLawIndexJob"
  | "caseLawIngestionEvent"
  | "caseLawIngestionFailure"
  | "caseLawJudge"
  | "caseLawMatterLink"
  | "caseLawPolarityRule"
  | "caseLawProvisionCitation"
  | "caseLawReconciliationItem"
  | "caseLawResearchAnswerClaim"
  | "caseLawResearchColumn"
  | "caseLawSource"
  | "caseLawSourceIngestionLease"
  | "chatMessage"
  | "chatMessageRevision"
  | "chatTurn"
  | "chatThreadCompaction"
  | "chatThread"
  | "fileChatThread"
  | "templateChatThread"
  | "templateDeletionCleanupRequest"
  | "clause"
  | "clauseCategory"
  | "clauseVariant"
  | "clauseVersion"
  | "contact"
  | "correspondence"
  | "correspondenceFiler"
  | "correspondenceAttachment"
  | "matterInboundAddress"
  | "correspondenceAllowedSender"
  | "correspondenceAllowedSenderMatter"
  | "correspondenceDropLog"
  | "contactExtractionUpload"
  | "contactImportRequest"
  | "contactRelationship"
  | "corpusIndexProjectionIntent"
  | "hostedCheckoutClaim"
  | "usageAllocation"
  | "usageLaneCounter"
  | "usageSeatAssignment"
  | "usagePolicy"
  | "usageEntitlement"
  | "usageEvent"
  | "desktopEditHandoff"
  | "desktopEditSession"
  | "legalListClaim"
  | "legalListClaimReviewEvent"
  | "legalListVerificationRun"
  | "bilingualTranslationRun"
  | "bilingualTranslationRow"
  | "docxSuggestion"
  | "document"
  | "documentCounter"
  | "entityDeletionCleanupRequest"
  | "accountDeletionEffectChunk"
  | "entityDeletionEffectChunk"
  | "effectLease"
  | "documentProcessingRun"
  | "documentReferenceCounter"
  | "documentReviewFinding"
  | "documentReviewParty"
  | "documentReviewReferencePassage"
  | "documentReviewRun"
  | "documentTranslationRun"
  | "documentTranslationUnit"
  | "documentType"
  | "entity"
  | "entityVersionAiSummary"
  | "entityVersion"
  | "expense"
  | "extractionRun"
  | "field"
  | "fileComparisonUpload"
  | "flowDefinition"
  | "flowRun"
  | "flowRunStep"
  | "feedbackReport"
  | "signal"
  | "signalEvent"
  | "scoutRun"
  | "systemScriptRun"
  | "folioCollabRoom"
  | "folioCollabRoomToken"
  | "folioCollabContribution"
  | "folioCollabPublication"
  | "folder"
  | "infoSoudTrackedCase"
  | "invoice"
  | "invoiceLine"
  | "justification"
  | "legislationDocument"
  | "legislationIndexJob"
  | "legislationSource"
  | "softLawSource"
  | "softLawDocument"
  | "softLawDocumentVersion"
  | "softLawDocumentLocator"
  | "softLawIngestionLease"
  | "softLawIngestionAttempt"
  | "legislationWorkName"
  | "legalList"
  | "legalListColumn"
  | "legalListGenerationCandidate"
  | "legalListGenerationCandidateSource"
  | "legalListGenerationRun"
  | "legalListGenerationSource"
  | "legalListItemComment"
  | "legalListItemReview"
  | "legalListItemSource"
  | "legalListSection"
  | "legalReaderAnnotation"
  | "matter"
  | "matterCounter"
  | "mcpConnector"
  | "mcpOAuthClient"
  | "mcpUserConnection"
  | "notification"
  | "organization"
  | "organizationSettings"
  | "pdfSigningSession"
  | "pendingUpload"
  | "playbook"
  | "playbookDefinition"
  | "playbookDefinitionVersion"
  | "property"
  | "propertyDependency"
  | "rateEntry"
  | "rateTable"
  | "sanctionsEdition"
  | "sanctionsScreeningEvent"
  | "savedSearch"
  | "vatRate"
  | "sellerProfile"
  | "numberSeries"
  | "reportExport"
  | "schedulerJobRun"
  | "sharepointConnection"
  | "sharepointOAuthState"
  | "styleSet"
  | "taskAssignee"
  | "task"
  | "template"
  | "templateCategory"
  | "templateLookupFormat"
  | "templateClause"
  | "templateRecipe"
  | "templateFill"
  | "templatePersistenceRequest"
  | "templateVersion"
  | "timeEntry"
  | "timeEntrySuggestion"
  | "timeTimer"
  | "user"
  | "userFile"
  | "workspace"
  | "workspaceContact"
  | "workspaceMember"
  | "workspaceView"
  | "workspaceViewTemplate"
  | "workObligationEvent"
  | "entityLink";

export const isSafeIdValue = (value: string): boolean =>
  value.length > 0 && value.isWellFormed();

/**
 * The one validator behind every brander: a consumer that narrows the id set
 * (the api closes `SafeIdType`) parses with this schema rather than restating
 * the check and its message.
 */
export const safeIdSchema = v.pipe(
  v.string(),
  v.check(isSafeIdValue, "Expected a non-empty, well-formed identifier"),
  v.brand("SafeId"),
);

/**
 * Portable compile-time identifier brand. Runtime validation belongs to the
 * boundary that owns each identifier; the type parameter prevents IDs from
 * different domains being exchanged accidentally inside typed code.
 */
export type SafeId<TType extends string> = v.InferOutput<
  typeof safeIdSchema
> & {
  readonly __safeIdType?: TType;
};

/** Brand an identifier at a boundary that has already established its source. */
export const toSafeId = <TType extends string>(value: string): SafeId<TType> =>
  v.parse(safeIdSchema, value);
