export const SIGNAL_RESET_SCOUT_TABLE = "scout_runs";
export const SIGNAL_RESET_EVENT_TABLE = "signal_events";
export const SIGNAL_RESET_SIGNAL_TABLE = "signals";

/** Ordered organization sweep; each table belongs to exactly one count auditor. */
export const REVIEW_RESET_SWEEP = [
  ["agent_skill_comments", "generic"],
  ["agent_skill_proposals", "generic"],
  ["agent_skill_resources", "generic"],
  ["agent_skill_revisions", "generic"],
  ["agent_skills", "generic"],
  ["ai_memories", "generic"],
  ["anonymization_allowlist_entries", "generic"],
  ["anonymization_blacklist_entries", "generic"],
  ["bilingual_translation_rows", "generic"],
  ["bilingual_translation_runs", "generic"],
  ["billing_arrangements", "generic"],
  ["billing_codes", "generic"],
  ["case_law_research_answers", "generic"],
  ["case_law_research_columns", "generic"],
  ["chat_run_log_entries", "generic"],
  ["chat_run_logs", "generic"],
  ["chat_threads", "generic"],
  ["chat_turns", "generic"],
  ["clause_categories", "generic"],
  ["clause_variants", "generic"],
  ["clause_versions", "generic"],
  ["clauses", "generic"],
  ["contact_extraction_uploads", "generic"],
  ["contact_import_requests", "generic"],
  ["contact_relationships", "generic"],
  ["contact_search_document_preview_passages", "generic"],
  ["contact_search_documents", "generic"],
  ["contacts", "generic"],
  ["correspondence", "generic"],
  ["correspondence_allowed_sender_matters", "generic"],
  ["correspondence_attachments", "generic"],
  ["correspondence_drop_logs", "generic"],
  ["correspondence_filers", "generic"],
  ["desktop_presence", "generic"],
  ["document_processing_runs", "generic"],
  ["document_reference_counters", "generic"],
  ["document_review_findings", "generic"],
  ["document_review_parties", "generic"],
  ["document_review_reference_passages", "generic"],
  ["document_review_runs", "generic"],
  ["document_translation_runs", "generic"],
  ["document_translation_units", "generic"],
  ["entity_version_ai_summaries", "generic"],
  ["entity_views", "generic"],
  ["expenses", "generic"],
  ["extracted_content", "generic"],
  ["extraction_runs", "generic"],
  ["file_chat_threads", "generic"],
  ["file_comparison_uploads", "generic"],
  ["flow_definitions", "flows"],
  ["invoice_lines", "generic"],
  ["invoices", "generic"],
  ["legal_reader_annotations", "generic"],
  ["matter_counters", "generic"],
  ["matter_inbound_addresses", "generic"],
  ["notifications", "generic"],
  ["number_series", "generic"],
  ["number_series_allocations", "generic"],
  ["number_series_counters", "generic"],
  ["office_file_evidence", "generic"],
  ["pending_uploads", "generic"],
  ["playbook_definition_versions", "generic"],
  ["playbook_definitions", "generic"],
  ["rate_tables", "generic"],
  ["sanctions_contact_marks", "generic"],
  ["sanctions_contact_matches", "generic"],
  ["sanctions_contact_screenings", "generic"],
  ["sanctions_screening_events", "generic"],
  ["saved_searches", "generic"],
  ["saved_time_narratives", "generic"],
  [SIGNAL_RESET_SCOUT_TABLE, "signals"],
  ["search_document_preview_passages", "generic"],
  ["search_documents", "generic"],
  ["search_projection_repair_queue", "generic"],
  ["seller_profiles", "generic"],
  [SIGNAL_RESET_EVENT_TABLE, "signals"],
  [SIGNAL_RESET_SIGNAL_TABLE, "signals"],
  ["style_sets", "generic"],
  ["template_categories", "generic"],
  ["template_chat_threads", "generic"],
  ["template_clauses", "generic"],
  ["template_fills", "generic"],
  ["template_lookup_format_user_defaults", "generic"],
  ["template_lookup_formats", "generic"],
  ["template_persistence_requests", "generic"],
  ["template_recipes", "generic"],
  ["template_versions", "generic"],
  ["templates", "generic"],
  ["time_daily_targets", "generic"],
  ["time_entries", "generic"],
  ["time_entry_suggestions", "generic"],
  ["time_entry_timer_states", "generic"],
  ["time_timer_confirmations", "generic"],
  ["time_timers", "generic"],
  ["vat_rates", "generic"],
  ["workspace_contacts", "generic"],
  ["workspace_search_document_preview_passages", "generic"],
  ["workspace_search_documents", "generic"],
  ["workspace_view_templates", "generic"],
  // Referenced without a cascade by tables above.
  ["correspondence_allowed_senders", "generic"],
  ["document_types", "generic"],
] as const;

export const REVIEW_RESET_CLEARED_TABLES = REVIEW_RESET_SWEEP.map(
  ([table]) => table,
);
