import { EyeOffIcon, GlobeIcon, type LucideIcon } from "lucide-react";

import { McpIcon } from "@/components/mcp-icon";
import { sanitizeHref } from "@/lib/sanitize-href";
import { getCatalogueIconImageSrc } from "@/routes/_protected.settings/-components/catalogue/catalogue-entry-icon.logic";

/**
 * Single source of truth for catalogue entry iconography. Resolution
 * order:
 *   1. Slug-specific built-in icons (the three pinned baselines get
 *      distinctive lucide marks).
 *   2. Bundled icon from the catalogue package (`icon.png` or
 *      `icon.svg` encoded as an inert image data URL). Bundled locally
 *      so rendering never makes a runtime network request.
 *   3. Entry's favicon when `iconUrl` is set (legacy / remote fallback).
 *   4. Stella hexagon fallback.
 *
 * Used by both the catalogue rows (settings + onboarding step) and the
 * onboarding stack preview so left + right always agree.
 */
type CatalogueEntryIconProps = {
  slug?: string;
  /** Bundled icon: image data URL generated by `@stll/catalogue`. */
  icon?: string | null;
  iconUrl?: string | null;
  /** Pixel size for both the image and the SVG fallback. */
  size?: number;
  className?: string;
};

/**
 * Custom DOCX mime-style mark: a rounded blue file glyph with a tiny
 * "W". Renders inline as SVG so it scales with `size` and stays in
 * sync with the surrounding icon vocabulary without shipping an
 * external asset.
 */
const DocxMimeIcon = ({
  size,
  className,
}: {
  size: number;
  className: string | undefined;
}) => (
  <svg
    aria-hidden="true"
    className={className}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      d="M5 3.5A1.5 1.5 0 0 1 6.5 2H14l5 5v13.5a1.5 1.5 0 0 1-1.5 1.5h-11A1.5 1.5 0 0 1 5 20.5v-17Z"
      fill="#2B579A"
    />
    <path
      d="M14 2v4.5A1.5 1.5 0 0 0 15.5 8H20"
      stroke="#1B3A6B"
      strokeWidth="1.5"
    />
    <text
      fill="#fff"
      fontFamily="ui-sans-serif, system-ui"
      fontSize="6.5"
      fontWeight="700"
      textAnchor="middle"
      x="12"
      y="17"
    >
      W
    </text>
  </svg>
);

const SLUG_LUCIDE_OVERRIDES: Readonly<Record<string, LucideIcon>> = {
  "web-search": GlobeIcon,
  anonymize: EyeOffIcon,
};

export const CatalogueEntryIcon = ({
  slug,
  icon,
  iconUrl,
  size = 24,
  className,
}: CatalogueEntryIconProps) => {
  if (slug === "create-docx") {
    return <DocxMimeIcon className={className} size={size} />;
  }

  if (slug && slug in SLUG_LUCIDE_OVERRIDES) {
    const Icon = SLUG_LUCIDE_OVERRIDES[slug];
    if (Icon) {
      return (
        <Icon
          className={className ?? "text-foreground"}
          style={{ width: size, height: size }}
        />
      );
    }
  }

  const bundledIconSrc = getCatalogueIconImageSrc(icon);
  if (bundledIconSrc) {
    return (
      <img
        alt=""
        className={`${className ?? ""} rounded-sm object-contain ring-1 ring-black/5 dark:ring-white/10`.trim()}
        height={size}
        src={bundledIconSrc}
        style={{ width: size, height: size }}
        width={size}
      />
    );
  }

  const safeIconHref = iconUrl ? sanitizeHref(iconUrl) : undefined;

  if (safeIconHref) {
    return (
      <img
        alt=""
        className={`${className ?? ""} rounded-sm object-contain ring-1 ring-black/5 dark:ring-white/10`.trim()}
        height={size}
        src={safeIconHref}
        style={{ width: size, height: size }}
        width={size}
      />
    );
  }

  return (
    <McpIcon
      className={className ?? "text-muted-foreground"}
      style={{ width: size, height: size }}
    />
  );
};
