import * as v from "valibot";

import { DAY_IN_MS } from "@stll/time";

const MAX_REQUESTS_PER_WINDOW = 1_000_000;
const MAX_CONCURRENT_REQUESTS = 10_000;
const MAX_WINDOW_SECONDS = 7 * 24 * 60 * 60;
const MAX_DURATION_MS = MAX_WINDOW_SECONDS * 1000;

const boundedInteger = (
  defaultValue: number,
  bounds: { min: number; max: number },
) =>
  v.optional(
    v.pipe(
      v.string(),
      v.digits(),
      v.toNumber(),
      v.integer(),
      v.minValue(bounds.min),
      v.maxValue(bounds.max),
    ),
    String(defaultValue),
  );
const requests = (defaultValue: number) =>
  boundedInteger(defaultValue, { min: 1, max: MAX_REQUESTS_PER_WINDOW });
const concurrency = (defaultValue: number) =>
  boundedInteger(defaultValue, { min: 1, max: MAX_CONCURRENT_REQUESTS });
const seconds = (defaultValue: number) =>
  boundedInteger(defaultValue, { min: 1, max: MAX_WINDOW_SECONDS });
const milliseconds = (defaultValue: number) =>
  boundedInteger(defaultValue, { min: 1000, max: MAX_DURATION_MS });

/** Defaults and hard bounds for HTTP, account-attempt, and MCP request budgets. */
export const rateLimitBudgetEnvSchema = {
  RATE_LIMIT_AUTH_DEFAULT_SENSITIVE_MAX: requests(3),
  RATE_LIMIT_AUTH_DEFAULT_SENSITIVE_WINDOW_SECONDS: seconds(10),
  RATE_LIMIT_AUTH_DEFAULT_EMAIL_MAX: requests(3),
  RATE_LIMIT_AUTH_DEFAULT_EMAIL_WINDOW_SECONDS: seconds(60),
  RATE_LIMIT_AUTH_TWO_FACTOR_MAX: requests(3),
  RATE_LIMIT_AUTH_TWO_FACTOR_WINDOW_SECONDS: seconds(10),
  RATE_LIMIT_AUTH_GLOBAL_MAX: requests(100),
  RATE_LIMIT_AUTH_GLOBAL_WINDOW_SECONDS: seconds(60),
  RATE_LIMIT_AUTH_SIGN_IN_MAX: requests(5),
  RATE_LIMIT_AUTH_SIGN_IN_WINDOW_SECONDS: seconds(60),
  RATE_LIMIT_AUTH_SIGN_UP_MAX: requests(3),
  RATE_LIMIT_AUTH_SIGN_UP_WINDOW_SECONDS: seconds(60),
  RATE_LIMIT_AUTH_SEND_OTP_MAX: requests(5),
  RATE_LIMIT_AUTH_SEND_OTP_WINDOW_SECONDS: seconds(60),
  RATE_LIMIT_AUTH_VERIFY_OTP_MAX: requests(5),
  RATE_LIMIT_AUTH_VERIFY_OTP_WINDOW_SECONDS: seconds(60),
  RATE_LIMIT_AUTH_FORGET_PASSWORD_MAX: requests(3),
  RATE_LIMIT_AUTH_FORGET_PASSWORD_WINDOW_SECONDS: seconds(60),
  RATE_LIMIT_AUTH_RESET_PASSWORD_MAX: requests(5),
  RATE_LIMIT_AUTH_RESET_PASSWORD_WINDOW_SECONDS: seconds(60),
  RATE_LIMIT_AUTH_OAUTH_TOKEN_MAX: requests(20),
  RATE_LIMIT_AUTH_OAUTH_TOKEN_WINDOW_SECONDS: seconds(60),
  RATE_LIMIT_AUTH_OAUTH_AUTHORIZATION_MAX: requests(30),
  RATE_LIMIT_AUTH_OAUTH_AUTHORIZATION_WINDOW_SECONDS: seconds(60),
  RATE_LIMIT_AUTH_OAUTH_CLIENT_REGISTRATION_MAX: requests(30),
  RATE_LIMIT_AUTH_OAUTH_CLIENT_REGISTRATION_WINDOW_SECONDS: seconds(60),
  RATE_LIMIT_AUTH_AUTH_SHARED_ADDRESS_MAX: requests(1200),
  RATE_LIMIT_AUTH_AUTH_SHARED_ADDRESS_WINDOW_SECONDS: seconds(60),
  RATE_LIMIT_AUTH_OAUTH_ANONYMOUS_CLIENT_REGISTRATION_MAX: requests(300),
  RATE_LIMIT_AUTH_OAUTH_ANONYMOUS_CLIENT_REGISTRATION_WINDOW_SECONDS:
    seconds(60),
  RATE_LIMIT_AUTH_OAUTH_ANONYMOUS_ADDRESS_MAX: requests(3000),
  RATE_LIMIT_AUTH_OAUTH_ANONYMOUS_ADDRESS_WINDOW_SECONDS: seconds(60),
  RATE_LIMIT_API_API_MAX: requests(1000),
  RATE_LIMIT_API_API_DURATION_MS: milliseconds(60_000),
  RATE_LIMIT_API_LEGAL_RESOLVE_MAX: requests(120),
  RATE_LIMIT_API_LEGAL_RESOLVE_DURATION_MS: milliseconds(60_000),
  RATE_LIMIT_API_PUBLIC_SANCTIONS_SEARCH_MAX: requests(20),
  RATE_LIMIT_API_PUBLIC_SANCTIONS_SEARCH_DURATION_MS: milliseconds(60_000),
  RATE_LIMIT_API_PUBLIC_SANCTIONS_SEARCH_MAX_CONCURRENT: concurrency(2),
  RATE_LIMIT_API_SKILL_SOURCE_MAX: requests(10),
  RATE_LIMIT_API_SKILL_SOURCE_DURATION_MS: milliseconds(60_000),
  RATE_LIMIT_API_UPLOAD_MAX: requests(500),
  RATE_LIMIT_API_UPLOAD_DURATION_MS: milliseconds(60_000),
  RATE_LIMIT_API_MCP_TRANSPORT_MAX: requests(600),
  RATE_LIMIT_API_MCP_TRANSPORT_DURATION_MS: milliseconds(60_000),
  RATE_LIMIT_API_MCP_TRANSPORT_ADDRESS_MAX: requests(3000),
  RATE_LIMIT_API_MCP_TRANSPORT_ADDRESS_DURATION_MS: milliseconds(60_000),
  RATE_LIMIT_API_FOLIO_COLLAB_MAX: requests(30),
  RATE_LIMIT_API_FOLIO_COLLAB_DURATION_MS: milliseconds(60_000),
  RATE_LIMIT_API_AGENT_AUTH_MAX: requests(60),
  RATE_LIMIT_API_AGENT_AUTH_DURATION_MS: milliseconds(60_000),
  RATE_LIMIT_API_TRANSLATE_MAX: requests(30),
  RATE_LIMIT_API_TRANSLATE_DURATION_MS: milliseconds(60_000),
  RATE_LIMIT_API_HOSTED_USAGE_WEBHOOK_MAX: requests(300),
  RATE_LIMIT_API_HOSTED_USAGE_WEBHOOK_DURATION_MS: milliseconds(60_000),
  RATE_LIMIT_API_DELETE_ACCOUNT_OTP_MAX: requests(5),
  RATE_LIMIT_API_DELETE_ACCOUNT_OTP_DURATION_MS: milliseconds(60_000),
  RATE_LIMIT_API_TWO_FACTOR_MANAGE_OTP_MAX: requests(5),
  RATE_LIMIT_API_TWO_FACTOR_MANAGE_OTP_DURATION_MS: milliseconds(60_000),
  RATE_LIMIT_ACCOUNT_OTP_MAX: requests(10),
  RATE_LIMIT_ACCOUNT_OTP_DURATION_MS: milliseconds(900_000),
  RATE_LIMIT_ACCOUNT_DEMO_OTP_MAX: requests(5),
  RATE_LIMIT_ACCOUNT_DEMO_OTP_DURATION_MS: milliseconds(900_000),
  RATE_LIMIT_ACCOUNT_PASSWORD_MAX: requests(10),
  RATE_LIMIT_ACCOUNT_PASSWORD_DURATION_MS: milliseconds(3_600_000),
  RATE_LIMIT_MCP_CAPABILITY_MAX: requests(60),
  RATE_LIMIT_MCP_CAPABILITY_WINDOW_MS: milliseconds(60_000),
  RATE_LIMIT_MCP_GATEWAY_MAX: requests(60),
  RATE_LIMIT_MCP_GATEWAY_WINDOW_MS: milliseconds(60_000),
  RATE_LIMIT_DEMO_ACTION_MAX: requests(200),
  RATE_LIMIT_DEMO_ACTION_DURATION_MS: milliseconds(DAY_IN_MS),
  RATE_LIMIT_API_KEY_MACHINE_MAX: requests(600),
  RATE_LIMIT_API_KEY_MACHINE_WINDOW_MS: milliseconds(60_000),
  RATE_LIMIT_API_KEY_DESKTOP_MAX: requests(60),
  RATE_LIMIT_API_KEY_DESKTOP_WINDOW_MS: milliseconds(60_000),
  RATE_LIMIT_OTP_DELIVERY_NEW_ACCOUNT_EMAIL_MAX: requests(3),
  RATE_LIMIT_OTP_DELIVERY_NEW_ACCOUNT_EMAIL_DURATION_MS:
    milliseconds(3_600_000),
  RATE_LIMIT_OTP_DELIVERY_NEW_ACCOUNT_ADDRESS_MAX: requests(25),
  RATE_LIMIT_OTP_DELIVERY_NEW_ACCOUNT_ADDRESS_DURATION_MS:
    milliseconds(10_800_000),
  RATE_LIMIT_OTP_DELIVERY_EXISTING_ACCOUNT_EMAIL_MAX: requests(10),
};

export type RateLimitBudgetConfiguration = {
  [Key in keyof typeof rateLimitBudgetEnvSchema]: v.InferOutput<
    (typeof rateLimitBudgetEnvSchema)[Key]
  >;
};
