use ammonia::Builder as HtmlSanitizer;
use base64::{Engine as _, engine::general_purpose::STANDARD};
use chrono::{DateTime, Duration, Utc};
use clipboard_rs::{
  Clipboard, ClipboardContent, ClipboardContext, ClipboardHandler, ClipboardWatcher,
  ClipboardWatcherContext, ContentFormat,
};
use serde::{Deserialize, Serialize};
use std::{
  collections::{HashMap, HashSet},
  io::Cursor,
  sync::{Arc, Mutex},
};
use tauri::{AppHandle, Emitter};

use crate::{
  clipboard_store::ClipboardStore,
  desktop_telemetry::{
    DesktopErrorReport, DesktopTelemetry, DesktopTelemetryErrorCode,
    DesktopTelemetryOperation, DesktopTelemetryWindow,
  },
  keychain,
};

#[cfg(target_os = "macos")]
use icns::{IconFamily, PixelFormat};
#[cfg(target_os = "macos")]
use objc2_app_kit::NSWorkspace;
#[cfg(target_os = "windows")]
use std::path::Path;
#[cfg(target_os = "macos")]
use std::{
  fs::File,
  io::BufReader,
  path::{Component, Path, PathBuf},
  sync::mpsc::sync_channel,
  time::Duration as StdDuration,
};
#[cfg(target_os = "windows")]
use winsafe::{HPROCESS, HVERSIONINFO, HWND, co};

const HISTORY_EVENT: &str = "clipboard-history-changed";
const INTERNAL_CLIPBOARD_FORMAT: &str = "legal.stella.desktop.clipboard";
const MAX_HISTORY_ITEMS: usize = 500;
const MAX_ITEM_TEXT_BYTES: usize = 64 * 1024;
const MAX_ITEM_HTML_BYTES: usize = 128 * 1024;
const MAX_HISTORY_BYTES: usize = 16 * 1024 * 1024;
const RETENTION_DAYS: i64 = 30;
const RETENTION_SWEEP_INTERVAL: std::time::Duration =
  std::time::Duration::from_secs(60 * 60);
const MAX_GROUPS: usize = 24;
const MAX_GROUP_NAME_CHARACTERS: usize = 64;
const MAX_SOURCE_APP_NAME_BYTES: usize = 128;
const MAX_SOURCE_APP_IDENTIFIER_BYTES: usize = 255;
const MAX_SOURCE_APP_ICON_DATA_URL_BYTES: usize = 48 * 1024;
const MAX_SOURCE_APP_VISUALS: usize = 64;
const SOURCE_APP_ICON_SIZE: u32 = 48;
#[cfg(debug_assertions)]
const DEBUG_PERSISTENCE_ENV: &str = "STELLA_ENABLE_DEBUG_CLIPBOARD_PERSISTENCE";

const IGNORED_FORMATS: &[&str] = &[
  "org.nspasteboard.transienttype",
  "org.nspasteboard.concealedtype",
  "org.nspasteboard.autogeneratedtype",
  "pasteboard generator type",
  "com.agilebits.onepassword",
  "com.typeit4me.clipping",
  "de.petermaurer.transientpasteboardtype",
  "net.antelle.keeweb",
];

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum ClipboardCaptureStatus {
  Active,
  Paused,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ClipboardSourceApp {
  pub identifier: Option<String>,
  pub name: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ClipboardSourceAppVisual {
  pub color: Option<String>,
  pub icon_data_url: Option<String>,
  pub key: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "camelCase")]
pub enum ClipboardItem {
  Text {
    #[serde(rename = "copiedAt", alias = "copied_at")]
    copied_at: DateTime<Utc>,
    #[serde(rename = "groupId", alias = "group_id")]
    group_id: Option<String>,
    id: String,
    #[serde(rename = "plainText", alias = "plain_text")]
    plain_text: String,
    #[serde(default, rename = "sourceApp", alias = "source_app")]
    source_app: Option<ClipboardSourceApp>,
  },
  FormattedText {
    #[serde(rename = "copiedAt", alias = "copied_at")]
    copied_at: DateTime<Utc>,
    #[serde(rename = "groupId", alias = "group_id")]
    group_id: Option<String>,
    html: String,
    id: String,
    #[serde(rename = "plainText", alias = "plain_text")]
    plain_text: String,
    #[serde(default, rename = "sourceApp", alias = "source_app")]
    source_app: Option<ClipboardSourceApp>,
  },
}

impl ClipboardItem {
  fn byte_len(&self) -> usize {
    let content_bytes = match self {
      Self::Text { plain_text, .. } => plain_text.len(),
      Self::FormattedText {
        html, plain_text, ..
      } => plain_text.len() + html.len(),
    };
    content_bytes
      + self.source_app().map_or(0, |source_app| {
        source_app.name.len() + source_app.identifier.as_ref().map_or(0, String::len)
      })
  }

  fn copied_at(&self) -> DateTime<Utc> {
    match self {
      Self::Text { copied_at, .. } | Self::FormattedText { copied_at, .. } => {
        *copied_at
      }
    }
  }

  fn id(&self) -> &str {
    match self {
      Self::Text { id, .. } | Self::FormattedText { id, .. } => id,
    }
  }

  fn plain_text(&self) -> &str {
    match self {
      Self::Text { plain_text, .. } | Self::FormattedText { plain_text, .. } => {
        plain_text
      }
    }
  }

  fn html(&self) -> Option<&str> {
    match self {
      Self::Text { .. } => None,
      Self::FormattedText { html, .. } => Some(html),
    }
  }

  fn group_id(&self) -> Option<&str> {
    match self {
      Self::Text { group_id, .. } | Self::FormattedText { group_id, .. } => {
        group_id.as_deref()
      }
    }
  }

  fn source_app(&self) -> Option<&ClipboardSourceApp> {
    match self {
      Self::Text { source_app, .. } | Self::FormattedText { source_app, .. } => {
        source_app.as_ref()
      }
    }
  }

  fn set_group_id(&mut self, new_group_id: Option<String>) {
    match self {
      Self::Text { group_id, .. } | Self::FormattedText { group_id, .. } => {
        *group_id = new_group_id;
      }
    }
  }

  fn replace_content(&mut self, new_plain_text: String, new_html: Option<String>) {
    let (copied_at, group_id, id, source_app) = match self {
      Self::Text {
        copied_at,
        group_id,
        id,
        source_app,
        ..
      }
      | Self::FormattedText {
        copied_at,
        group_id,
        id,
        source_app,
        ..
      } => (*copied_at, group_id.clone(), id.clone(), source_app.clone()),
    };
    *self = match new_html {
      Some(html) => Self::FormattedText {
        copied_at,
        group_id,
        html,
        id,
        plain_text: new_plain_text,
        source_app,
      },
      None => Self::Text {
        copied_at,
        group_id,
        id,
        plain_text: new_plain_text,
        source_app,
      },
    };
  }

  fn same_content(&self, plain_text: &str, html: Option<&str>) -> bool {
    self.plain_text() == plain_text && self.html() == html
  }

  fn duplicate_at(&self, copied_at: DateTime<Utc>) -> Self {
    let id = uuid::Uuid::new_v4().to_string();
    match self {
      Self::Text {
        group_id,
        plain_text,
        source_app,
        ..
      } => Self::Text {
        copied_at,
        group_id: group_id.clone(),
        id,
        plain_text: plain_text.clone(),
        source_app: source_app.clone(),
      },
      Self::FormattedText {
        group_id,
        html,
        plain_text,
        source_app,
        ..
      } => Self::FormattedText {
        copied_at,
        group_id: group_id.clone(),
        html: html.clone(),
        id,
        plain_text: plain_text.clone(),
        source_app: source_app.clone(),
      },
    }
  }
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum ClipboardGroupColor {
  #[default]
  Gray,
  Blue,
  Emerald,
  Amber,
  Rose,
  Violet,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ClipboardGroup {
  #[serde(default)]
  pub color: ClipboardGroupColor,
  pub id: String,
  pub name: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(tag = "status", rename_all = "camelCase")]
pub enum ClipboardPersistenceStatus {
  Initializing,
  Encrypted,
  MemoryOnly,
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ClipboardSnapshot {
  pub capture_status: ClipboardCaptureStatus,
  pub groups: Vec<ClipboardGroup>,
  pub items: Vec<ClipboardItem>,
  pub persistence: ClipboardPersistenceStatus,
  pub source_app_visuals: Vec<ClipboardSourceAppVisual>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PersistedClipboardState {
  pub capture_status: ClipboardCaptureStatus,
  #[serde(default)]
  pub groups: Vec<ClipboardGroup>,
  pub items: Vec<ClipboardItem>,
}

pub struct ClipboardManager {
  capture_status: ClipboardCaptureStatus,
  groups: Vec<ClipboardGroup>,
  items: Vec<ClipboardItem>,
  persistence: ClipboardPersistenceStatus,
  source_app_visuals: HashMap<String, ClipboardSourceAppVisual>,
  store: Option<ClipboardStore>,
  suppressed_content: Option<(String, Option<String>)>,
}

struct ClipboardManagerCheckpoint {
  capture_status: ClipboardCaptureStatus,
  groups: Vec<ClipboardGroup>,
  items: Vec<ClipboardItem>,
  source_app_visuals: HashMap<String, ClipboardSourceAppVisual>,
  suppressed_content: Option<(String, Option<String>)>,
}

pub type ClipboardAppState = Arc<Mutex<ClipboardManager>>;

struct ClipboardCapture {
  copied_at: DateTime<Utc>,
  html: Option<String>,
  plain_text: String,
  source_app: Option<ClipboardSourceApp>,
  source_app_visual: Option<ClipboardSourceAppVisual>,
}

impl ClipboardManager {
  pub fn new() -> Self {
    Self {
      capture_status: ClipboardCaptureStatus::Active,
      groups: Vec::new(),
      items: Vec::new(),
      persistence: ClipboardPersistenceStatus::Initializing,
      source_app_visuals: HashMap::new(),
      store: None,
      suppressed_content: None,
    }
  }

  pub fn initialize(&mut self) {
    #[cfg(debug_assertions)]
    if std::env::var_os(DEBUG_PERSISTENCE_ENV).is_none() {
      self.persistence = ClipboardPersistenceStatus::MemoryOnly;
      tracing::info!(
        "clipboard history is memory-only in debug builds; set \
         STELLA_ENABLE_DEBUG_CLIPBOARD_PERSISTENCE=1 to test encrypted persistence"
      );
      return;
    }

    let Some(data_dir) = dirs::data_dir() else {
      self.persistence = ClipboardPersistenceStatus::MemoryOnly;
      tracing::warn!(
        "clipboard history is memory-only because no data directory is available"
      );
      return;
    };
    let key = match keychain::get_or_create_clipboard_key() {
      Ok(key) => key,
      Err(error) => {
        self.persistence = ClipboardPersistenceStatus::MemoryOnly;
        tracing::warn!(error = %error, "clipboard history key is unavailable");
        return;
      }
    };
    let store = ClipboardStore::new(
      key,
      data_dir
        .join("legal.stella.desktop")
        .join("clipboard-history.json.enc"),
    );
    match store.load() {
      Ok(Some(mut state)) => {
        if prune_items(&mut state.items, Utc::now())
          && let Err(error) = store.persist(&state)
        {
          self.persistence = ClipboardPersistenceStatus::MemoryOnly;
          tracing::warn!(error = %error, "expired clipboard history could not be removed");
          return;
        }
        self.capture_status = state.capture_status;
        self.groups = state.groups;
        self.items = state.items;
      }
      Ok(None) => {}
      Err(error) => {
        self.persistence = ClipboardPersistenceStatus::MemoryOnly;
        tracing::warn!(error = %error, "encrypted clipboard history is unavailable");
        return;
      }
    }
    self.store = Some(store);
    self.persistence = ClipboardPersistenceStatus::Encrypted;
  }

  pub fn snapshot(&self) -> ClipboardSnapshot {
    let mut source_app_visuals = self
      .source_app_visuals
      .values()
      .cloned()
      .collect::<Vec<_>>();
    source_app_visuals.sort_by(|left, right| left.key.cmp(&right.key));
    ClipboardSnapshot {
      capture_status: self.capture_status,
      groups: self.groups.clone(),
      items: self.items.clone(),
      persistence: self.persistence,
      source_app_visuals,
    }
  }

  pub fn set_capture_status(
    &mut self,
    status: ClipboardCaptureStatus,
  ) -> Result<(), String> {
    let checkpoint = self.checkpoint();
    self.capture_status = status;
    self.persist_or_restore(checkpoint)
  }

  pub fn delete_item(&mut self, id: &str) -> Result<bool, String> {
    let original_len = self.items.len();
    let checkpoint = self.checkpoint();
    self.items.retain(|item| item.id() != id);
    let changed = original_len != self.items.len();
    if !changed {
      return Ok(false);
    }
    self.persist_or_restore(checkpoint)?;
    Ok(true)
  }

  pub fn duplicate_item(&mut self, id: &str) -> Result<bool, String> {
    self.duplicate_item_at(id, Utc::now())
  }

  fn duplicate_item_at(
    &mut self,
    id: &str,
    copied_at: DateTime<Utc>,
  ) -> Result<bool, String> {
    let Some(item) = self.items.iter().find(|item| item.id() == id).cloned() else {
      return Ok(false);
    };
    let checkpoint = self.checkpoint();
    let duplicate = item.duplicate_at(copied_at);
    self.items.insert(0, duplicate);
    prune_items(&mut self.items, copied_at);
    self.persist_or_restore(checkpoint)?;
    Ok(true)
  }

  pub fn clear(&mut self) -> Result<(), String> {
    let checkpoint = self.checkpoint();
    self.items.clear();
    self.source_app_visuals.clear();
    self.persist_or_restore(checkpoint)
  }

  pub fn create_group(
    &mut self,
    name: &str,
    color: ClipboardGroupColor,
  ) -> Result<String, String> {
    let name = name.trim();
    if name.is_empty() || name.chars().count() > MAX_GROUP_NAME_CHARACTERS {
      return Err("clipboard group name is invalid".to_string());
    }
    if self.groups.len() >= MAX_GROUPS {
      return Err("clipboard group limit reached".to_string());
    }
    let normalized_name = name.to_lowercase();
    if self
      .groups
      .iter()
      .any(|group| group.name.to_lowercase() == normalized_name)
    {
      return Err("clipboard group name already exists".to_string());
    }
    let id = uuid::Uuid::new_v4().to_string();
    let checkpoint = self.checkpoint();
    self.groups.push(ClipboardGroup {
      color,
      id: id.clone(),
      name: name.to_string(),
    });
    self.persist_or_restore(checkpoint)?;
    Ok(id)
  }

  pub fn delete_group(&mut self, id: &str) -> Result<bool, String> {
    let original_len = self.groups.len();
    let checkpoint = self.checkpoint();
    self.groups.retain(|group| group.id != id);
    if original_len == self.groups.len() {
      return Ok(false);
    }
    for item in &mut self.items {
      if item.group_id() == Some(id) {
        item.set_group_id(None);
      }
    }
    self.persist_or_restore(checkpoint)?;
    Ok(true)
  }

  pub fn update_item(
    &mut self,
    id: &str,
    plain_text: &str,
    html: Option<&str>,
    group_id: Option<String>,
  ) -> Result<bool, String> {
    if plain_text.trim().is_empty() || plain_text.len() > MAX_ITEM_TEXT_BYTES {
      return Err("clipboard item text is invalid".to_string());
    }
    if let Some(group_id) = &group_id
      && !self.groups.iter().any(|group| group.id == *group_id)
    {
      return Err("clipboard group does not exist".to_string());
    }
    if html.is_some_and(|html| html.len() > MAX_ITEM_HTML_BYTES) {
      return Err("clipboard item formatting is invalid".to_string());
    }
    let html = html.and_then(sanitized_html);
    let checkpoint = self.checkpoint();
    let Some(item) = self.items.iter_mut().find(|item| item.id() == id) else {
      return Ok(false);
    };
    if !item.same_content(plain_text, html.as_deref()) {
      item.replace_content(plain_text.to_string(), html);
    }
    item.set_group_id(group_id);
    self.persist_or_restore(checkpoint)?;
    Ok(true)
  }

  pub fn set_item_group(
    &mut self,
    id: &str,
    group_id: Option<String>,
  ) -> Result<bool, String> {
    if let Some(group_id) = &group_id
      && !self.groups.iter().any(|group| group.id == *group_id)
    {
      return Err("clipboard group does not exist".to_string());
    }
    let checkpoint = self.checkpoint();
    let Some(item) = self.items.iter_mut().find(|item| item.id() == id) else {
      return Ok(false);
    };
    item.set_group_id(group_id);
    self.persist_or_restore(checkpoint)?;
    Ok(true)
  }

  pub fn item(&self, id: &str) -> Option<ClipboardItem> {
    self.items.iter().find(|item| item.id() == id).cloned()
  }

  pub fn suppress_next(&mut self, item: &ClipboardItem, plain_text_only: bool) {
    self.suppressed_content = Some((
      item.plain_text().to_string(),
      if plain_text_only {
        None
      } else {
        item.html().map(str::to_string)
      },
    ));
  }

  pub fn clear_suppression(&mut self) {
    self.suppressed_content = None;
  }

  fn capture(&mut self, capture: ClipboardCapture) -> Result<bool, String> {
    if self.capture_status == ClipboardCaptureStatus::Paused {
      return Ok(false);
    }
    let ClipboardCapture {
      copied_at,
      html,
      plain_text,
      source_app,
      source_app_visual,
    } = capture;
    if self.suppressed_content.as_ref() == Some(&(plain_text.clone(), html.clone())) {
      self.suppressed_content = None;
      return Ok(false);
    }
    let checkpoint = self.checkpoint();
    self.suppressed_content = None;

    if let Some(source_app_visual) = source_app_visual
      && (self.source_app_visuals.contains_key(&source_app_visual.key)
        || self.source_app_visuals.len() < MAX_SOURCE_APP_VISUALS)
    {
      self
        .source_app_visuals
        .insert(source_app_visual.key.clone(), source_app_visual);
    }

    let preserved_group_id = self
      .items
      .iter()
      .find(|item| item.same_content(&plain_text, html.as_deref()))
      .and_then(|item| item.group_id().map(str::to_string));
    self
      .items
      .retain(|item| !item.same_content(&plain_text, html.as_deref()));
    let id = uuid::Uuid::new_v4().to_string();
    let item = match html {
      Some(html) => ClipboardItem::FormattedText {
        copied_at,
        group_id: preserved_group_id,
        html,
        id,
        plain_text,
        source_app,
      },
      None => ClipboardItem::Text {
        copied_at,
        group_id: preserved_group_id,
        id,
        plain_text,
        source_app,
      },
    };
    self.items.insert(0, item);
    prune_items(&mut self.items, copied_at);
    self.persist_or_restore(checkpoint)?;
    Ok(true)
  }

  pub fn prune_expired(&mut self, now: DateTime<Utc>) -> Result<bool, String> {
    let checkpoint = self.checkpoint();
    if !prune_items(&mut self.items, now) {
      return Ok(false);
    }
    self.persist_or_restore(checkpoint)?;
    Ok(true)
  }

  fn checkpoint(&self) -> ClipboardManagerCheckpoint {
    ClipboardManagerCheckpoint {
      capture_status: self.capture_status,
      groups: self.groups.clone(),
      items: self.items.clone(),
      source_app_visuals: self.source_app_visuals.clone(),
      suppressed_content: self.suppressed_content.clone(),
    }
  }

  fn restore(&mut self, checkpoint: ClipboardManagerCheckpoint) {
    self.capture_status = checkpoint.capture_status;
    self.groups = checkpoint.groups;
    self.items = checkpoint.items;
    self.source_app_visuals = checkpoint.source_app_visuals;
    self.suppressed_content = checkpoint.suppressed_content;
  }

  fn persist_or_restore(
    &mut self,
    checkpoint: ClipboardManagerCheckpoint,
  ) -> Result<(), String> {
    if let Err(error) = self.persist() {
      self.restore(checkpoint);
      return Err(error);
    }
    Ok(())
  }

  fn persist(&self) -> Result<(), String> {
    let Some(store) = &self.store else {
      return Ok(());
    };
    let state = PersistedClipboardState {
      capture_status: self.capture_status,
      groups: self.groups.clone(),
      items: self.items.clone(),
    };
    store.persist(&state).map_err(|error| {
      tracing::warn!(error = %error, "clipboard history persistence failed");
      error
    })
  }
}

fn prune_items(items: &mut Vec<ClipboardItem>, now: DateTime<Utc>) -> bool {
  let original_len = items.len();
  let oldest = now - Duration::days(RETENTION_DAYS);
  items.retain(|item| item.copied_at() >= oldest);
  items.truncate(MAX_HISTORY_ITEMS);

  let mut total_bytes = 0;
  items.retain(|item| {
    total_bytes += item.byte_len();
    total_bytes <= MAX_HISTORY_BYTES
  });
  items.len() != original_len
}

fn sanitized_html(raw_html: &str) -> Option<String> {
  if raw_html.len() > MAX_ITEM_HTML_BYTES {
    return None;
  }
  let allowed_tags = HashSet::from([
    "b",
    "blockquote",
    "br",
    "code",
    "div",
    "em",
    "i",
    "li",
    "ol",
    "p",
    "pre",
    "s",
    "span",
    "strike",
    "strong",
    "u",
    "ul",
  ]);
  let html = HtmlSanitizer::new()
    .tags(allowed_tags)
    .clean(raw_html)
    .to_string();
  let has_formatting = [
    "<b",
    "<blockquote",
    "<code",
    "<em",
    "<i",
    "<li",
    "<ol",
    "<pre",
    "<s",
    "<strong",
    "<u",
    "<ul",
  ]
  .iter()
  .any(|tag| html.contains(tag));
  if has_formatting { Some(html) } else { None }
}

fn should_ignore_formats(formats: &[String]) -> bool {
  formats.iter().any(|format| {
    let normalized = format.to_lowercase();
    IGNORED_FORMATS.iter().any(|ignored| normalized == *ignored)
  })
}

fn bounded_metadata(value: &str, max_bytes: usize) -> Option<String> {
  let value = value.trim();
  if value.is_empty() {
    return None;
  }
  if value.len() <= max_bytes {
    return Some(value.to_string());
  }
  let mut boundary = 0;
  for (index, character) in value.char_indices() {
    let next_boundary = index + character.len_utf8();
    if next_boundary > max_bytes {
      break;
    }
    boundary = next_boundary;
  }
  Some(value[..boundary].to_string())
}

fn dominant_icon_color(icon: &image::RgbaImage) -> Option<String> {
  let mut buckets = HashMap::<(u8, u8, u8), (u64, u64, u64, u64)>::new();
  for pixel in icon.pixels() {
    let [red, green, blue, alpha] = pixel.0;
    if alpha < 48 {
      continue;
    }
    let maximum = red.max(green).max(blue);
    let minimum = red.min(green).min(blue);
    let chroma = maximum - minimum;
    let weight = u64::from(alpha) * u64::from(chroma.saturating_add(24));
    let bucket = (red / 32, green / 32, blue / 32);
    let entry = buckets.entry(bucket).or_default();
    entry.0 += weight;
    entry.1 += u64::from(red) * weight;
    entry.2 += u64::from(green) * weight;
    entry.3 += u64::from(blue) * weight;
  }
  let (_, (weight, red, green, blue)) =
    buckets.into_iter().max_by_key(|(_, values)| values.0)?;
  if weight == 0 {
    return None;
  }
  Some(format!(
    "#{:02x}{:02x}{:02x}",
    red / weight,
    green / weight,
    blue / weight
  ))
}

fn source_app_visual(icon: image::RgbaImage) -> (Option<String>, Option<String>) {
  let icon = image::DynamicImage::ImageRgba8(icon)
    .thumbnail(SOURCE_APP_ICON_SIZE, SOURCE_APP_ICON_SIZE)
    .to_rgba8();
  let color = dominant_icon_color(&icon);
  let mut png = Cursor::new(Vec::new());
  let icon_data_url = image::DynamicImage::ImageRgba8(icon)
    .write_to(&mut png, image::ImageFormat::Png)
    .ok()
    .and_then(|()| {
      let value = format!(
        "data:image/png;base64,{}",
        STANDARD.encode(png.into_inner())
      );
      (value.len() <= MAX_SOURCE_APP_ICON_DATA_URL_BYTES).then_some(value)
    });
  (icon_data_url, color)
}

struct ClipboardSourceCapture {
  app: ClipboardSourceApp,
  visual: Option<ClipboardSourceAppVisual>,
}

fn source_app_visual_metadata(
  key: String,
  (icon_data_url, color): (Option<String>, Option<String>),
) -> Option<ClipboardSourceAppVisual> {
  if icon_data_url.is_none() && color.is_none() {
    return None;
  }
  Some(ClipboardSourceAppVisual {
    color,
    icon_data_url,
    key,
  })
}

#[cfg(target_os = "macos")]
fn macos_bundle_icon_path(bundle_path: &Path) -> Option<PathBuf> {
  let info = plist::Value::from_file(bundle_path.join("Contents/Info.plist")).ok()?;
  let icon_name = info.as_dictionary()?.get("CFBundleIconFile")?.as_string()?;
  let mut components = Path::new(icon_name).components();
  let Component::Normal(file_name) = components.next()? else {
    return None;
  };
  if components.next().is_some() {
    return None;
  }
  let mut icon_path = bundle_path.join("Contents/Resources").join(file_name);
  if icon_path.extension().is_none() {
    icon_path.set_extension("icns");
  }
  icon_path.is_file().then_some(icon_path)
}

#[cfg(target_os = "macos")]
fn macos_source_app_icon(bundle_path: &Path) -> Option<image::RgbaImage> {
  let icon_path = macos_bundle_icon_path(bundle_path)?;
  let family = IconFamily::read(BufReader::new(File::open(icon_path).ok()?)).ok()?;
  let mut icon_types = family.available_icons();
  icon_types.sort_by_key(|icon_type| {
    let width = icon_type.pixel_width();
    (
      width < SOURCE_APP_ICON_SIZE,
      width.abs_diff(SOURCE_APP_ICON_SIZE),
    )
  });
  icon_types.into_iter().find_map(|icon_type| {
    let icon = family.get_icon_with_type(icon_type).ok()?;
    let icon = icon.convert_to(PixelFormat::RGBA);
    image::RgbaImage::from_raw(icon.width(), icon.height(), icon.into_data().into_vec())
  })
}

#[cfg(target_os = "macos")]
struct MacosSourceCapture {
  app: ClipboardSourceApp,
  bundle_path: Option<String>,
}

#[cfg(target_os = "macos")]
fn frontmost_source_app_on_main_thread() -> Option<MacosSourceCapture> {
  let application = NSWorkspace::sharedWorkspace().frontmostApplication()?;
  let bundle_path = application
    .bundleURL()
    .and_then(|url| url.path())
    .map(|path| path.to_string());
  let name = bundle_path
    .as_deref()
    .and_then(|path| {
      Path::new(path)
        .file_stem()
        .and_then(|name| name.to_str())
        .and_then(|name| bounded_metadata(name, MAX_SOURCE_APP_NAME_BYTES))
    })
    .or_else(|| {
      application
        .localizedName()
        .and_then(|name| bounded_metadata(&name.to_string(), MAX_SOURCE_APP_NAME_BYTES))
    })?;
  let identifier = application.bundleIdentifier().and_then(|bundle_id| {
    bounded_metadata(&bundle_id.to_string(), MAX_SOURCE_APP_IDENTIFIER_BYTES)
  });
  let app = ClipboardSourceApp { identifier, name };
  Some(MacosSourceCapture { app, bundle_path })
}

#[cfg(target_os = "macos")]
fn frontmost_source_app(app: &AppHandle) -> Option<ClipboardSourceCapture> {
  let (sender, receiver) = sync_channel(1);
  app
    .run_on_main_thread(move || {
      let _ = sender.send(frontmost_source_app_on_main_thread());
    })
    .ok()?;
  let source = receiver.recv_timeout(StdDuration::from_secs(1)).ok()??;
  let key = source
    .app
    .identifier
    .clone()
    .unwrap_or_else(|| source.app.name.clone());
  let visual = source
    .bundle_path
    .as_deref()
    .and_then(|bundle_path| macos_source_app_icon(Path::new(bundle_path)))
    .map(source_app_visual)
    .and_then(|visual| source_app_visual_metadata(key, visual));
  Some(ClipboardSourceCapture {
    app: source.app,
    visual,
  })
}

#[cfg(target_os = "windows")]
fn windows_product_name(executable_path: &str) -> Option<String> {
  let version = HVERSIONINFO::GetFileVersionInfo(executable_path).ok()?;
  let language_and_code_page = version.langs_and_cps().ok()?.first().copied()?;
  version
    .str_val(language_and_code_page, "ProductName")
    .ok()
    .and_then(|name| bounded_metadata(&name, MAX_SOURCE_APP_NAME_BYTES))
}

#[cfg(target_os = "windows")]
fn frontmost_source_app(_app: &AppHandle) -> Option<ClipboardSourceCapture> {
  let window = HWND::GetForegroundWindow()?;
  let (_, process_id) = window.GetWindowThreadProcessId();
  let process =
    HPROCESS::OpenProcess(co::PROCESS::QUERY_LIMITED_INFORMATION, false, process_id)
      .ok()?;
  let executable_path = process
    .QueryFullProcessImageName(co::PROCESS_NAME::WIN32)
    .ok()?;
  let executable_name = Path::new(&executable_path)
    .file_name()
    .and_then(|name| name.to_str())
    .and_then(|name| bounded_metadata(name, MAX_SOURCE_APP_IDENTIFIER_BYTES));
  let name = windows_product_name(&executable_path)
    .or_else(|| {
      Path::new(&executable_path)
        .file_stem()
        .and_then(|name| name.to_str())
        .and_then(|name| bounded_metadata(name, MAX_SOURCE_APP_NAME_BYTES))
    })
    .or_else(|| {
      window
        .GetWindowText()
        .ok()
        .and_then(|title| bounded_metadata(&title, MAX_SOURCE_APP_NAME_BYTES))
    })
    .or_else(|| executable_name.clone())?;
  let (icon_data_url, color) = windows_icons::get_icon_by_process_id(process_id)
    .ok()
    .map_or((None, None), source_app_visual);
  let app = ClipboardSourceApp {
    identifier: executable_name,
    name,
  };
  let key = app.identifier.clone().unwrap_or_else(|| app.name.clone());
  let visual = source_app_visual_metadata(key, (icon_data_url, color));
  Some(ClipboardSourceCapture { app, visual })
}

#[cfg(not(any(target_os = "macos", target_os = "windows")))]
fn frontmost_source_app(_app: &AppHandle) -> Option<ClipboardSourceCapture> {
  None
}

struct HistoryClipboardHandler {
  app: AppHandle,
  clipboard: ClipboardContext,
  manager: ClipboardAppState,
  telemetry: DesktopTelemetry,
}

impl ClipboardHandler for HistoryClipboardHandler {
  fn on_clipboard_change(&mut self) {
    let formats = match self.clipboard.available_formats() {
      Ok(formats) => formats,
      Err(error) => {
        tracing::warn!(error = %error, "clipboard formats could not be read");
        self.telemetry.capture(DesktopErrorReport {
          window: DesktopTelemetryWindow::Clipboard,
          operation: DesktopTelemetryOperation::ClipboardWatcherRead,
          code: DesktopTelemetryErrorCode::FormatReadFailed,
        });
        return;
      }
    };
    if formats
      .iter()
      .any(|format| format.eq_ignore_ascii_case(INTERNAL_CLIPBOARD_FORMAT))
    {
      if let Ok(mut manager) = self.manager.lock() {
        manager.clear_suppression();
      }
      return;
    }
    if should_ignore_formats(&formats) || self.clipboard.has(ContentFormat::Files) {
      return;
    }
    let plain_text = match self.clipboard.get_text() {
      Ok(text) if !text.trim().is_empty() && text.len() <= MAX_ITEM_TEXT_BYTES => text,
      Ok(_) => return,
      Err(error) => {
        tracing::debug!(error = %error, "clipboard change did not contain readable text");
        return;
      }
    };
    let html = if self.clipboard.has(ContentFormat::Html) {
      self
        .clipboard
        .get_html()
        .ok()
        .and_then(|raw_html| sanitized_html(&raw_html))
    } else {
      None
    };

    let (source_app, source_app_visual) = frontmost_source_app(&self.app)
      .map(|source| (Some(source.app), source.visual))
      .unwrap_or((None, None));
    let capture = ClipboardCapture {
      copied_at: Utc::now(),
      html,
      plain_text,
      source_app,
      source_app_visual,
    };
    let changed = match self.manager.lock() {
      Ok(mut manager) => match manager.capture(capture) {
        Ok(changed) => changed,
        Err(error) => {
          tracing::error!(error = %error, "clipboard capture could not be persisted");
          self.telemetry.capture(DesktopErrorReport {
            window: DesktopTelemetryWindow::Clipboard,
            operation: DesktopTelemetryOperation::ClipboardWatcherRead,
            code: DesktopTelemetryErrorCode::PersistenceFailed,
          });
          return;
        }
      },
      Err(_) => {
        tracing::error!("clipboard manager lock is poisoned");
        self.telemetry.capture(DesktopErrorReport {
          window: DesktopTelemetryWindow::Clipboard,
          operation: DesktopTelemetryOperation::ClipboardWatcherRead,
          code: DesktopTelemetryErrorCode::LockPoisoned,
        });
        return;
      }
    };
    if changed {
      let _ = self.app.emit(HISTORY_EVENT, ());
    }
  }
}

pub fn initialize_and_watch(
  manager: ClipboardAppState,
  app: AppHandle,
  telemetry: DesktopTelemetry,
) {
  if let Ok(mut manager) = manager.lock() {
    manager.initialize();
  } else {
    tracing::error!("clipboard manager lock is poisoned during initialization");
    telemetry.capture(DesktopErrorReport {
      window: DesktopTelemetryWindow::Clipboard,
      operation: DesktopTelemetryOperation::ClipboardWatcherStart,
      code: DesktopTelemetryErrorCode::LockPoisoned,
    });
    return;
  }
  let _ = app.emit(HISTORY_EVENT, ());

  let retention_manager = Arc::clone(&manager);
  let retention_app = app.clone();
  let retention_telemetry = telemetry.clone();
  tauri::async_runtime::spawn(async move {
    let mut interval = tokio::time::interval(RETENTION_SWEEP_INTERVAL);
    interval.tick().await;
    loop {
      interval.tick().await;
      let changed = match retention_manager.lock() {
        Ok(mut manager) => match manager.prune_expired(Utc::now()) {
          Ok(changed) => changed,
          Err(error) => {
            tracing::error!(error = %error, "expired clipboard history could not be removed");
            retention_telemetry.capture(DesktopErrorReport {
              window: DesktopTelemetryWindow::Clipboard,
              operation: DesktopTelemetryOperation::ClipboardWatcherRead,
              code: DesktopTelemetryErrorCode::PersistenceFailed,
            });
            false
          }
        },
        Err(_) => {
          tracing::error!("clipboard manager lock is poisoned during retention sweep");
          retention_telemetry.capture(DesktopErrorReport {
            window: DesktopTelemetryWindow::Clipboard,
            operation: DesktopTelemetryOperation::ClipboardWatcherRead,
            code: DesktopTelemetryErrorCode::LockPoisoned,
          });
          false
        }
      };
      if changed {
        let _ = retention_app.emit(HISTORY_EVENT, ());
      }
    }
  });

  let clipboard = match ClipboardContext::new() {
    Ok(clipboard) => clipboard,
    Err(error) => {
      tracing::error!(error = %error, "clipboard reader could not start");
      telemetry.capture(DesktopErrorReport {
        window: DesktopTelemetryWindow::Clipboard,
        operation: DesktopTelemetryOperation::ClipboardWatcherStart,
        code: DesktopTelemetryErrorCode::ClipboardUnavailable,
      });
      return;
    }
  };
  let mut handler = HistoryClipboardHandler {
    app,
    clipboard,
    manager,
    telemetry: telemetry.clone(),
  };
  // Reconcile once before polling so a copy made while the desktop process was
  // starting or rebuilding is not lost behind the watcher's initial baseline.
  handler.on_clipboard_change();
  let mut watcher = match ClipboardWatcherContext::new() {
    Ok(watcher) => watcher,
    Err(error) => {
      tracing::error!(error = %error, "clipboard watcher could not start");
      telemetry.capture(DesktopErrorReport {
        window: DesktopTelemetryWindow::Clipboard,
        operation: DesktopTelemetryOperation::ClipboardWatcherStart,
        code: DesktopTelemetryErrorCode::WatcherUnavailable,
      });
      return;
    }
  };
  watcher.add_handler(handler);
  watcher.start_watch();
}

pub fn write_item(item: &ClipboardItem, plain_text_only: bool) -> Result<(), String> {
  let clipboard = ClipboardContext::new()
    .map_err(|error| format!("clipboard is unavailable: {error}"))?;
  let mut contents = vec![ClipboardContent::Text(item.plain_text().to_string())];
  if !plain_text_only && let Some(html) = item.html() {
    contents.push(ClipboardContent::Html(html.to_string()));
  }
  contents.push(ClipboardContent::Other(
    INTERNAL_CLIPBOARD_FORMAT.to_string(),
    Vec::new(),
  ));
  clipboard
    .set(contents)
    .map_err(|error| format!("clipboard write failed: {error}"))
}

#[cfg(test)]
mod tests {
  use super::*;

  fn text_item(copied_at: DateTime<Utc>, text: &str) -> ClipboardItem {
    ClipboardItem::Text {
      copied_at,
      group_id: None,
      id: uuid::Uuid::new_v4().to_string(),
      plain_text: text.to_string(),
      source_app: None,
    }
  }

  fn unique_store_path() -> std::path::PathBuf {
    std::env::temp_dir().join(format!(
      "stella-clipboard-manager-{}.json.enc",
      uuid::Uuid::new_v4()
    ))
  }

  fn capture(
    manager: &mut ClipboardManager,
    plain_text: &str,
    html: Option<&str>,
    copied_at: DateTime<Utc>,
  ) -> bool {
    manager
      .capture(ClipboardCapture {
        copied_at,
        html: html.map(str::to_string),
        plain_text: plain_text.to_string(),
        source_app: None,
        source_app_visual: None,
      })
      .unwrap()
  }

  #[test]
  fn sanitizer_keeps_simple_formatting_and_removes_active_content() {
    let html = sanitized_html(
      r#"<p style="color:red"><strong>Safe</strong><a href="https://example.com">link</a><script>alert(1)</script></p>"#,
    )
    .unwrap();

    assert!(html.contains("<strong>Safe</strong>"));
    assert!(html.contains("link"));
    assert!(!html.contains("href"));
    assert!(!html.contains("script"));
    assert!(!html.contains("style="));
  }

  #[test]
  fn source_app_metadata_is_bounded_without_breaking_unicode() {
    let value = format!("{}x", "ž".repeat(MAX_SOURCE_APP_NAME_BYTES));
    let bounded = bounded_metadata(&value, MAX_SOURCE_APP_NAME_BYTES).unwrap();

    assert!(bounded.len() <= MAX_SOURCE_APP_NAME_BYTES);
    assert!(bounded.chars().all(|character| character == 'ž'));
  }

  #[test]
  fn source_app_visual_uses_the_icon_color_and_a_bounded_png() {
    let icon = image::RgbaImage::from_pixel(
      SOURCE_APP_ICON_SIZE,
      SOURCE_APP_ICON_SIZE,
      image::Rgba([30, 120, 220, 255]),
    );

    let (icon_data_url, color) = source_app_visual(icon);

    assert_eq!(color.as_deref(), Some("#1e78dc"));
    let icon_data_url = icon_data_url.unwrap();
    assert!(icon_data_url.starts_with("data:image/png;base64,"));
    assert!(icon_data_url.len() <= MAX_SOURCE_APP_ICON_DATA_URL_BYTES);
  }

  #[test]
  fn confidential_and_transient_formats_are_ignored() {
    assert!(should_ignore_formats(&[
      "org.nspasteboard.ConcealedType".to_string()
    ]));
    assert!(should_ignore_formats(&[
      "com.agilebits.onepassword".to_string()
    ]));
    assert!(!should_ignore_formats(&[
      "public.utf8-plain-text".to_string()
    ]));
  }

  #[test]
  fn capture_deduplicates_and_moves_content_to_the_front() {
    let now = Utc::now();
    let mut manager = ClipboardManager::new();
    manager.persistence = ClipboardPersistenceStatus::MemoryOnly;

    assert!(capture(&mut manager, "first", None, now));
    assert!(capture(&mut manager, "second", None, now));
    assert!(capture(&mut manager, "first", None, now));

    assert_eq!(manager.items.len(), 2);
    assert_eq!(manager.items[0].plain_text(), "first");
  }

  #[test]
  fn duplicating_an_item_preserves_its_content_metadata_and_group() {
    let original_time = Utc::now() - Duration::minutes(5);
    let duplicate_time = Utc::now();
    let original = ClipboardItem::FormattedText {
      copied_at: original_time,
      group_id: Some("research".to_string()),
      html: "<strong>Clause</strong>".to_string(),
      id: "original".to_string(),
      plain_text: "Clause".to_string(),
      source_app: Some(ClipboardSourceApp {
        identifier: Some("com.microsoft.Word".to_string()),
        name: "Microsoft Word".to_string(),
      }),
    };
    let mut manager = ClipboardManager::new();
    manager.items.push(original.clone());

    assert!(
      manager
        .duplicate_item_at("original", duplicate_time)
        .unwrap()
    );
    assert_eq!(manager.items.len(), 2);
    assert_ne!(manager.items[0].id(), original.id());
    assert_eq!(manager.items[0].copied_at(), duplicate_time);
    assert_eq!(manager.items[0].plain_text(), original.plain_text());
    assert_eq!(manager.items[0].html(), original.html());
    assert_eq!(manager.items[0].group_id(), original.group_id());
    assert_eq!(manager.items[0].source_app(), original.source_app());
    assert_eq!(manager.items[1], original);
  }

  #[test]
  fn duplicating_a_missing_item_does_not_change_history() {
    let mut manager = ClipboardManager::new();

    assert!(!manager.duplicate_item_at("missing", Utc::now()).unwrap());
    assert!(manager.items.is_empty());
  }

  #[test]
  fn pruning_enforces_retention_count_and_byte_bounds() {
    let now = Utc::now();
    let mut items = vec![text_item(now - Duration::days(31), "expired")];
    items.extend(
      (0..=MAX_HISTORY_ITEMS).map(|index| text_item(now, &format!("item-{index}"))),
    );

    prune_items(&mut items, now);

    assert_eq!(items.len(), MAX_HISTORY_ITEMS);
    assert!(items.iter().all(|item| item.plain_text() != "expired"));
    assert!(
      items.iter().map(ClipboardItem::byte_len).sum::<usize>() <= MAX_HISTORY_BYTES
    );
  }

  #[test]
  fn persistence_failure_rolls_back_history_mutations() {
    let store_path = unique_store_path();
    std::fs::create_dir_all(&store_path).unwrap();
    let mut manager = ClipboardManager::new();
    manager.persistence = ClipboardPersistenceStatus::Encrypted;
    manager.store = Some(ClipboardStore::new([7; 32], store_path.clone()));
    manager.items.push(text_item(Utc::now(), "must remain"));

    assert!(manager.clear().is_err());
    assert_eq!(manager.items.len(), 1);
    assert_eq!(manager.items[0].plain_text(), "must remain");

    std::fs::remove_dir(store_path).unwrap();
  }

  #[test]
  fn retention_pruning_is_written_to_encrypted_history() {
    let store_path = unique_store_path();
    let store = ClipboardStore::new([9; 32], store_path.clone());
    let now = Utc::now();
    let state = PersistedClipboardState {
      capture_status: ClipboardCaptureStatus::Active,
      groups: Vec::new(),
      items: vec![
        text_item(now - Duration::days(RETENTION_DAYS + 1), "expired"),
        text_item(now, "current"),
      ],
    };
    store.persist(&state).unwrap();

    let mut manager = ClipboardManager::new();
    manager.persistence = ClipboardPersistenceStatus::Encrypted;
    manager.items = state.items;
    manager.store = Some(store);

    assert!(manager.prune_expired(now).unwrap());
    assert_eq!(manager.items.len(), 1);
    let persisted = ClipboardStore::new([9; 32], store_path.clone())
      .load()
      .unwrap()
      .unwrap();
    assert_eq!(persisted.items.len(), 1);
    assert_eq!(persisted.items[0].plain_text(), "current");

    std::fs::remove_file(store_path).unwrap();
  }

  #[test]
  fn paused_capture_does_not_record_content() {
    let mut manager = ClipboardManager::new();
    manager
      .set_capture_status(ClipboardCaptureStatus::Paused)
      .unwrap();

    assert!(!capture(&mut manager, "ignored", None, Utc::now()));
    assert!(manager.items.is_empty());
  }

  #[test]
  fn clipboard_item_json_matches_the_frontend_contract() {
    let item = ClipboardItem::FormattedText {
      copied_at: Utc::now(),
      group_id: None,
      html: "<strong>formatted</strong>".to_string(),
      id: "item-id".to_string(),
      plain_text: "formatted".to_string(),
      source_app: Some(ClipboardSourceApp {
        identifier: Some("com.apple.TextEdit".to_string()),
        name: "TextEdit".to_string(),
      }),
    };

    let value = serde_json::to_value(item).unwrap();

    assert_eq!(value["type"], "formattedText");
    assert!(value.get("copiedAt").is_some());
    assert_eq!(value["plainText"], "formatted");
    assert!(value.get("groupId").is_some());
    assert_eq!(value["sourceApp"]["identifier"], "com.apple.TextEdit");
    assert_eq!(value["sourceApp"]["name"], "TextEdit");
    assert!(value.get("copied_at").is_none());
    assert!(value.get("plain_text").is_none());
  }

  #[test]
  fn deleting_a_group_preserves_its_items() {
    let mut manager = ClipboardManager::new();
    assert!(capture(&mut manager, "grouped", None, Utc::now()));
    let group_id = manager
      .create_group("Research", ClipboardGroupColor::Blue)
      .unwrap();
    let item_id = manager.items[0].id().to_string();
    assert!(
      manager
        .update_item(&item_id, "grouped", None, Some(group_id.clone()))
        .unwrap()
    );

    assert!(manager.delete_group(&group_id).unwrap());
    assert_eq!(manager.items.len(), 1);
    assert_eq!(manager.items[0].group_id(), None);
  }

  #[test]
  fn group_count_and_names_are_bounded() {
    let mut manager = ClipboardManager::new();
    for index in 0..MAX_GROUPS {
      manager
        .create_group(&format!("Group {index}"), ClipboardGroupColor::Gray)
        .unwrap();
    }

    assert!(
      manager
        .create_group("One too many", ClipboardGroupColor::Gray)
        .is_err()
    );

    let mut manager = ClipboardManager::new();
    assert!(
      manager
        .create_group(
          &"x".repeat(MAX_GROUP_NAME_CHARACTERS + 1),
          ClipboardGroupColor::Gray,
        )
        .is_err()
    );
  }

  #[test]
  fn group_name_limit_counts_unicode_characters() {
    let mut manager = ClipboardManager::new();
    let international_name = "界".repeat(MAX_GROUP_NAME_CHARACTERS);

    assert!(
      manager
        .create_group(&international_name, ClipboardGroupColor::Blue)
        .is_ok()
    );
    assert!(
      manager
        .create_group(
          &format!("{international_name}界"),
          ClipboardGroupColor::Blue,
        )
        .is_err()
    );
  }

  #[test]
  fn persisted_groups_without_a_color_default_to_gray() {
    let group: ClipboardGroup = serde_json::from_value(serde_json::json!({
      "id": "legacy-group",
      "name": "Legacy"
    }))
    .unwrap();

    assert_eq!(group.color, ClipboardGroupColor::Gray);
    assert_eq!(serde_json::to_value(group).unwrap()["color"], "gray");
  }

  #[test]
  fn recopying_grouped_content_keeps_its_group() {
    let now = Utc::now();
    let mut manager = ClipboardManager::new();
    assert!(capture(&mut manager, "grouped", None, now));
    let group_id = manager
      .create_group("Research", ClipboardGroupColor::Emerald)
      .unwrap();
    let item_id = manager.items[0].id().to_string();
    manager
      .update_item(&item_id, "grouped", None, Some(group_id.clone()))
      .unwrap();

    assert!(capture(&mut manager, "grouped", None, now));

    assert_eq!(manager.items[0].group_id(), Some(group_id.as_str()));
  }

  #[test]
  fn editing_formatted_text_produces_a_consistent_plain_text_item() {
    let mut manager = ClipboardManager::new();
    assert!(capture(
      &mut manager,
      "old",
      Some("<strong>old</strong>"),
      Utc::now(),
    ));
    let item_id = manager.items[0].id().to_string();

    assert!(manager.update_item(&item_id, "new", None, None).unwrap());
    assert!(matches!(manager.items[0], ClipboardItem::Text { .. }));
    assert_eq!(manager.items[0].plain_text(), "new");
  }

  #[test]
  fn editing_formatted_text_preserves_safe_formatting() {
    let mut manager = ClipboardManager::new();
    assert!(capture(&mut manager, "old", None, Utc::now()));
    let item_id = manager.items[0].id().to_string();

    assert!(
      manager
        .update_item(
          &item_id,
          "new",
          Some("<strong>new</strong><script>ignored()</script>"),
          None,
        )
        .unwrap()
    );

    let ClipboardItem::FormattedText { html, .. } = &manager.items[0] else {
      panic!("formatted edit should produce formatted clipboard content");
    };
    assert_eq!(html, "<strong>new</strong>");
  }
}
