use ammonia::Builder as HtmlSanitizer;
use base64::{Engine as _, engine::general_purpose::STANDARD};
use chrono::{DateTime, Duration, Utc};
use clipboard_rs::{
  Clipboard, ClipboardContent, ClipboardContext, ClipboardHandler, ClipboardWatcher,
  ClipboardWatcherContext, ContentFormat,
};
use serde::{Deserialize, Serialize};
use std::{
  collections::{HashMap, HashSet},
  io::Cursor,
  sync::{Arc, Mutex},
  time::Instant,
};
use tauri::{AppHandle, Emitter};

use crate::{
  clipboard_store::ClipboardStore,
  clipboard_welcome::{ClipboardWelcome, ClipboardWelcomeStatus},
  config::APP_DATA_DIR_NAME,
  desktop_telemetry::{
    DesktopErrorReport, DesktopTelemetry, DesktopTelemetryErrorCode,
    DesktopTelemetryOperation, DesktopTelemetrySpan, DesktopTelemetryWindow,
    DesktopTimingReport,
  },
  keychain,
};

#[cfg(target_os = "macos")]
use icns::{IconFamily, PixelFormat};
#[cfg(target_os = "macos")]
use objc2_app_kit::NSWorkspace;
#[cfg(target_os = "windows")]
use std::path::Path;
#[cfg(target_os = "macos")]
use std::{
  fs::File,
  io::BufReader,
  path::{Component, Path, PathBuf},
  sync::mpsc::sync_channel,
  time::Duration as StdDuration,
};
#[cfg(target_os = "windows")]
use winsafe::{HPROCESS, HVERSIONINFO, HWND, co};

const HISTORY_EVENT: &str = "clipboard-history-changed";
const HISTORY_LOADING_ERROR: &str = "clipboard history is still loading";
const INTERNAL_CLIPBOARD_FORMAT: &str = "legal.stella.desktop.clipboard";
#[cfg(target_os = "windows")]
const WINDOWS_CLIPBOARD_HISTORY_CONTROL_FORMAT: &str = "CanIncludeInClipboardHistory";
const WINDOWS_MONITOR_PROCESSING_EXCLUSION_FORMAT: &str =
  "ExcludeClipboardContentFromMonitorProcessing";
const MAX_HISTORY_ITEMS: usize = 500;
const MAX_ITEM_TEXT_BYTES: usize = 64 * 1024;
const MAX_ITEM_HTML_BYTES: usize = 128 * 1024;
const MAX_ITEM_RTF_BYTES: usize = 256 * 1024;
const MAX_ITEM_NAME_CHARACTERS: usize = 80;
const MAX_HISTORY_BYTES: usize = 16 * 1024 * 1024;
const RETENTION_SWEEP_INTERVAL: std::time::Duration =
  std::time::Duration::from_secs(60 * 60);
const MAX_GROUPS: usize = 24;
const MAX_GROUP_NAME_CHARACTERS: usize = 64;
const MAX_SOURCE_APP_NAME_BYTES: usize = 128;
const MAX_SOURCE_APP_IDENTIFIER_BYTES: usize = 255;
const MAX_SOURCE_APP_ICON_DATA_URL_BYTES: usize = 48 * 1024;
const MAX_SOURCE_APP_VISUALS: usize = 64;
const SOURCE_APP_ICON_SIZE: u32 = 48;
#[cfg(debug_assertions)]
const DEBUG_PERSISTENCE_ENV: &str = "STELLA_ENABLE_DEBUG_CLIPBOARD_PERSISTENCE";

const IGNORED_FORMATS: &[&str] = &[
  "org.nspasteboard.transienttype",
  "org.nspasteboard.concealedtype",
  "org.nspasteboard.autogeneratedtype",
  "pasteboard generator type",
  "com.agilebits.onepassword",
  "com.typeit4me.clipping",
  "de.petermaurer.transientpasteboardtype",
  "net.antelle.keeweb",
  "x-kde-passwordmanagerhint",
];

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum ClipboardCaptureStatus {
  Active,
  Paused,
}

macro_rules! define_clipboard_retention {
  ($($(#[$attr:meta])* $variant:ident => $days:literal),+ $(,)?) => {
    /// How long copied items stay in history before the hourly sweep drops them.
    #[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub enum ClipboardRetention {
      $($(#[$attr])* $variant),+
    }

    impl ClipboardRetention {
      #[cfg(test)]
      const ALL: &'static [Self] = &[$(Self::$variant),+];

      fn days(self) -> i64 {
        match self {
          $(Self::$variant => $days),+
        }
      }
    }
  };
}

define_clipboard_retention! {
  Week => 7,
  #[default]
  Month => 30,
  Year => 365,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ClipboardSourceApp {
  pub identifier: Option<String>,
  pub name: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ClipboardSourceAppVisual {
  pub color: Option<String>,
  pub icon_data_url: Option<String>,
  pub key: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "camelCase")]
pub enum ClipboardItem {
  Text {
    #[serde(rename = "copiedAt", alias = "copied_at")]
    copied_at: DateTime<Utc>,
    #[serde(rename = "groupId", alias = "group_id")]
    group_id: Option<String>,
    id: String,
    #[serde(default)]
    name: Option<String>,
    #[serde(rename = "plainText", alias = "plain_text")]
    plain_text: String,
    #[serde(default, rename = "sourceApp", alias = "source_app")]
    source_app: Option<ClipboardSourceApp>,
  },
  FormattedText {
    #[serde(rename = "copiedAt", alias = "copied_at")]
    copied_at: DateTime<Utc>,
    #[serde(rename = "groupId", alias = "group_id")]
    group_id: Option<String>,
    html: String,
    id: String,
    #[serde(default)]
    name: Option<String>,
    #[serde(rename = "plainText", alias = "plain_text")]
    plain_text: String,
    /// The source app's RTF, written back verbatim on paste so RTF-first
    /// targets receive the original formatting. Never crosses IPC (see
    /// `for_webview`) and is dropped once the clip is edited.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    rtf: Option<String>,
    #[serde(default, rename = "sourceApp", alias = "source_app")]
    source_app: Option<ClipboardSourceApp>,
  },
}

impl ClipboardItem {
  fn byte_len(&self) -> usize {
    let content_bytes = match self {
      Self::Text { plain_text, .. } => plain_text.len(),
      Self::FormattedText {
        html,
        plain_text,
        rtf,
        ..
      } => plain_text.len() + html.len() + rtf.as_ref().map_or(0, String::len),
    };
    content_bytes
      + self.name().map_or(0, str::len)
      + self.source_app().map_or(0, |source_app| {
        source_app.name.len() + source_app.identifier.as_ref().map_or(0, String::len)
      })
  }

  fn copied_at(&self) -> DateTime<Utc> {
    match self {
      Self::Text { copied_at, .. } | Self::FormattedText { copied_at, .. } => {
        *copied_at
      }
    }
  }

  fn id(&self) -> &str {
    match self {
      Self::Text { id, .. } | Self::FormattedText { id, .. } => id,
    }
  }

  fn plain_text(&self) -> &str {
    match self {
      Self::Text { plain_text, .. } | Self::FormattedText { plain_text, .. } => {
        plain_text
      }
    }
  }

  fn name(&self) -> Option<&str> {
    match self {
      Self::Text { name, .. } | Self::FormattedText { name, .. } => name.as_deref(),
    }
  }

  fn html(&self) -> Option<&str> {
    match self {
      Self::Text { .. } => None,
      Self::FormattedText { html, .. } => Some(html),
    }
  }

  fn rtf(&self) -> Option<&str> {
    match self {
      Self::Text { .. } => None,
      Self::FormattedText { rtf, .. } => rtf.as_deref(),
    }
  }

  /// The item as the webview sees it: the paste-back payload stays native-side.
  pub fn for_webview(mut self) -> Self {
    if let Self::FormattedText { rtf, .. } = &mut self {
      *rtf = None;
    }
    self
  }

  fn group_id(&self) -> Option<&str> {
    match self {
      Self::Text { group_id, .. } | Self::FormattedText { group_id, .. } => {
        group_id.as_deref()
      }
    }
  }

  /// Deliberately kept by the user: named or filed into a group. Such
  /// items are exempt from retention and count pruning.
  fn is_organised(&self) -> bool {
    self.group_id().is_some() || self.name().is_some()
  }

  fn source_app(&self) -> Option<&ClipboardSourceApp> {
    match self {
      Self::Text { source_app, .. } | Self::FormattedText { source_app, .. } => {
        source_app.as_ref()
      }
    }
  }

  /// Key of the item's entry in the source-app visual map; mirrors the
  /// lookup key built in `frontmost_source_app`.
  fn source_visual_key(&self) -> Option<&str> {
    self
      .source_app()
      .map(|source_app| source_app.identifier.as_deref().unwrap_or(&source_app.name))
  }

  fn set_group_id(&mut self, new_group_id: Option<String>) {
    match self {
      Self::Text { group_id, .. } | Self::FormattedText { group_id, .. } => {
        *group_id = new_group_id;
      }
    }
  }

  fn set_name(&mut self, new_name: Option<String>) {
    match self {
      Self::Text { name, .. } | Self::FormattedText { name, .. } => {
        *name = new_name;
      }
    }
  }

  fn set_copied_at(&mut self, new_copied_at: DateTime<Utc>) {
    match self {
      Self::Text { copied_at, .. } | Self::FormattedText { copied_at, .. } => {
        *copied_at = new_copied_at;
      }
    }
  }

  fn replace_content(&mut self, new_plain_text: String, new_html: Option<String>) {
    let (copied_at, group_id, id, name, source_app) = match self {
      Self::Text {
        copied_at,
        group_id,
        id,
        name,
        source_app,
        ..
      }
      | Self::FormattedText {
        copied_at,
        group_id,
        id,
        name,
        source_app,
        ..
      } => (
        *copied_at,
        group_id.clone(),
        id.clone(),
        name.clone(),
        source_app.clone(),
      ),
    };
    *self = match new_html {
      Some(html) => Self::FormattedText {
        copied_at,
        group_id,
        html,
        id,
        name,
        plain_text: new_plain_text,
        rtf: None,
        source_app,
      },
      None => Self::Text {
        copied_at,
        group_id,
        id,
        name,
        plain_text: new_plain_text,
        source_app,
      },
    };
  }

  fn same_content(&self, plain_text: &str, html: Option<&str>) -> bool {
    self.plain_text() == plain_text && self.html() == html
  }

  fn duplicate_at(&self, copied_at: DateTime<Utc>) -> Self {
    let id = uuid::Uuid::new_v4().to_string();
    match self {
      Self::Text {
        group_id,
        name,
        plain_text,
        source_app,
        ..
      } => Self::Text {
        copied_at,
        group_id: group_id.clone(),
        id,
        name: name.clone(),
        plain_text: plain_text.clone(),
        source_app: source_app.clone(),
      },
      Self::FormattedText {
        group_id,
        html,
        name,
        plain_text,
        rtf,
        source_app,
        ..
      } => Self::FormattedText {
        copied_at,
        group_id: group_id.clone(),
        html: html.clone(),
        id,
        name: name.clone(),
        plain_text: plain_text.clone(),
        rtf: rtf.clone(),
        source_app: source_app.clone(),
      },
    }
  }
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum ClipboardGroupColor {
  #[default]
  Gray,
  Blue,
  Emerald,
  Amber,
  Rose,
  Violet,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ClipboardGroup {
  #[serde(default)]
  pub color: ClipboardGroupColor,
  pub id: String,
  pub name: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(tag = "status", rename_all = "camelCase")]
pub enum ClipboardPersistenceStatus {
  Initializing,
  Encrypted,
  MemoryOnly,
  DeletionOnly,
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ClipboardSnapshot {
  pub capture_status: ClipboardCaptureStatus,
  pub groups: Vec<ClipboardGroup>,
  pub items: Vec<ClipboardItem>,
  pub persistence: ClipboardPersistenceStatus,
  pub retention: ClipboardRetention,
  pub source_app_visuals: Vec<ClipboardSourceAppVisual>,
  pub welcome_status: ClipboardWelcomeStatus,
}

impl ClipboardSnapshot {
  /// Content bytes crossing IPC for the items, before JSON framing.
  pub fn history_bytes(&self) -> usize {
    self.items.iter().map(ClipboardItem::byte_len).sum()
  }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PersistedClipboardState {
  pub capture_status: ClipboardCaptureStatus,
  #[serde(default)]
  pub groups: Vec<ClipboardGroup>,
  pub items: Vec<ClipboardItem>,
  #[serde(default)]
  pub retention: ClipboardRetention,
  #[serde(default)]
  pub source_app_visuals: Vec<ClipboardSourceAppVisual>,
}

pub struct ClipboardManager {
  capture_status: ClipboardCaptureStatus,
  groups: Vec<ClipboardGroup>,
  items: Vec<ClipboardItem>,
  persistence: ClipboardPersistence,
  retention: ClipboardRetention,
  source_app_visuals: HashMap<String, ClipboardSourceAppVisual>,
  suppressed_content: Option<(String, Option<String>)>,
  welcome: ClipboardWelcome,
}

enum ClipboardPersistence {
  Initializing,
  Encrypted(ClipboardStore),
  MemoryOnly,
  DeletionOnly(std::path::PathBuf),
}

impl ClipboardPersistence {
  fn status(&self) -> ClipboardPersistenceStatus {
    match self {
      Self::Initializing => ClipboardPersistenceStatus::Initializing,
      Self::Encrypted(_) => ClipboardPersistenceStatus::Encrypted,
      Self::MemoryOnly => ClipboardPersistenceStatus::MemoryOnly,
      Self::DeletionOnly(_) => ClipboardPersistenceStatus::DeletionOnly,
    }
  }
}

struct ClipboardManagerCheckpoint {
  capture_status: ClipboardCaptureStatus,
  groups: Vec<ClipboardGroup>,
  items: Vec<ClipboardItem>,
  retention: ClipboardRetention,
  source_app_visuals: HashMap<String, ClipboardSourceAppVisual>,
  suppressed_content: Option<(String, Option<String>)>,
}

pub type ClipboardAppState = Arc<Mutex<ClipboardManager>>;

/// Durations of the blocking steps inside `load_persisted`; `None` when a step
/// did not run.
#[derive(Debug, Default, Clone, Copy)]
pub struct ClipboardInitTimings {
  pub keychain_read: Option<std::time::Duration>,
  pub store_load: Option<std::time::Duration>,
  pub loaded_items: Option<usize>,
}

/// Persistence resolved without holding the manager mutex.
pub enum ClipboardLoad {
  MemoryOnly,
  DeletionOnly(std::path::PathBuf),
  Encrypted {
    store: ClipboardStore,
    state: Option<PersistedClipboardState>,
  },
}

/// Blocking keychain and encrypted-file work. Runs on the watcher thread
/// before the manager is locked, so snapshot reads never queue behind it.
pub fn load_persisted() -> (ClipboardLoad, ClipboardInitTimings) {
  let mut timings = ClipboardInitTimings::default();
  #[cfg(debug_assertions)]
  if std::env::var_os(DEBUG_PERSISTENCE_ENV).is_none() {
    tracing::info!(
      "clipboard history is memory-only in debug builds; set \
       STELLA_ENABLE_DEBUG_CLIPBOARD_PERSISTENCE=1 to test encrypted persistence"
    );
    return (ClipboardLoad::MemoryOnly, timings);
  }

  let Some(data_dir) = dirs::data_dir() else {
    tracing::warn!(
      "clipboard history is memory-only because no data directory is available"
    );
    return (ClipboardLoad::MemoryOnly, timings);
  };
  let store_path = data_dir
    .join(APP_DATA_DIR_NAME)
    .join("clipboard-history.json.enc");
  let keychain_started = Instant::now();
  let key = keychain::get_clipboard_key().and_then(|lookup| match lookup {
    keychain::ClipboardKeyLookup::Found(key) => Ok(key),
    // A history file whose key is missing must never be re-keyed: the miss
    // may be transient (locked or migrating keychain) and minting a new key
    // would make the file undecryptable for good. Deletion-only lets the
    // user reset it, after which the next launch creates a key.
    keychain::ClipboardKeyLookup::Missing if store_path.is_file() => Err(
      "clipboard history exists but its key is missing from the keychain".to_string(),
    ),
    keychain::ClipboardKeyLookup::Missing => keychain::create_clipboard_key(),
  });
  timings.keychain_read = Some(keychain_started.elapsed());
  let key = match key {
    Ok(key) => key,
    Err(error) => {
      tracing::warn!(error = %error, "clipboard history key is unavailable");
      let load = if store_path.is_file() {
        ClipboardLoad::DeletionOnly(store_path)
      } else {
        ClipboardLoad::MemoryOnly
      };
      return (load, timings);
    }
  };
  let store = ClipboardStore::new(key, store_path.clone());
  let load_started = Instant::now();
  let loaded = store.load();
  timings.store_load = Some(load_started.elapsed());
  match loaded {
    Ok(Some(mut state)) => {
      timings.loaded_items = Some(state.items.len());
      if prune_items(&mut state.items, state.retention, Utc::now())
        && let Err(error) = store.persist(&state)
      {
        tracing::warn!(error = %error, "expired clipboard history could not be removed");
        return (ClipboardLoad::DeletionOnly(store_path), timings);
      }
      (
        ClipboardLoad::Encrypted {
          store,
          state: Some(state),
        },
        timings,
      )
    }
    Ok(None) => (ClipboardLoad::Encrypted { store, state: None }, timings),
    Err(error) => {
      tracing::warn!(error = %error, "encrypted clipboard history is unavailable");
      (ClipboardLoad::DeletionOnly(store_path), timings)
    }
  }
}

struct ClipboardCapture {
  copied_at: DateTime<Utc>,
  html: Option<String>,
  plain_text: String,
  rtf: Option<String>,
  source_app: Option<ClipboardSourceApp>,
  source_app_visual: Option<ClipboardSourceAppVisual>,
}

impl ClipboardManager {
  pub fn new() -> Self {
    Self {
      capture_status: ClipboardCaptureStatus::Active,
      groups: Vec::new(),
      items: Vec::new(),
      persistence: ClipboardPersistence::Initializing,
      retention: ClipboardRetention::default(),
      source_app_visuals: HashMap::new(),
      suppressed_content: None,
      welcome: ClipboardWelcome::new(),
    }
  }

  /// Applies a load resolved off the mutex. Mutations are rejected while the
  /// manager is `Initializing`, so nothing in memory can be overwritten here.
  pub fn install(&mut self, load: ClipboardLoad) {
    self.persistence = match load {
      ClipboardLoad::MemoryOnly => ClipboardPersistence::MemoryOnly,
      ClipboardLoad::DeletionOnly(path) => ClipboardPersistence::DeletionOnly(path),
      ClipboardLoad::Encrypted { store, state } => {
        if let Some(state) = state {
          self.capture_status = state.capture_status;
          self.groups = state.groups;
          self.retention = state.retention;
          // Retention pruning during load can leave the persisted visuals
          // stale; only those still backing an item may occupy the capped
          // map, or they would block icons for new source apps.
          let referenced_keys: HashSet<&str> = state
            .items
            .iter()
            .filter_map(ClipboardItem::source_visual_key)
            .collect();
          self.source_app_visuals = state
            .source_app_visuals
            .into_iter()
            .filter(|visual| referenced_keys.contains(visual.key.as_str()))
            .map(|visual| (visual.key.clone(), visual))
            .collect();
          self.items = state.items;
        }
        ClipboardPersistence::Encrypted(store)
      }
    };
  }

  pub fn snapshot(&self) -> ClipboardSnapshot {
    let mut source_app_visuals = self
      .source_app_visuals
      .values()
      .cloned()
      .collect::<Vec<_>>();
    source_app_visuals.sort_by(|left, right| left.key.cmp(&right.key));
    ClipboardSnapshot {
      capture_status: self.capture_status,
      groups: self.groups.clone(),
      items: self
        .items
        .iter()
        .cloned()
        .map(ClipboardItem::for_webview)
        .collect(),
      persistence: self.persistence.status(),
      retention: self.retention,
      source_app_visuals,
      welcome_status: self.welcome.status(),
    }
  }

  pub fn complete_welcome(&mut self) -> Result<(), String> {
    self.welcome.complete()
  }

  pub fn set_capture_status(
    &mut self,
    status: ClipboardCaptureStatus,
  ) -> Result<(), String> {
    let checkpoint = self.checkpoint();
    self.capture_status = status;
    self.persist_or_restore(checkpoint)
  }

  pub fn set_retention(&mut self, retention: ClipboardRetention) -> Result<(), String> {
    if matches!(&self.persistence, ClipboardPersistence::DeletionOnly(_)) {
      return Err("clipboard history is unavailable".to_string());
    }
    let checkpoint = self.checkpoint();
    self.retention = retention;
    prune_items(&mut self.items, retention, Utc::now());
    self.persist_or_restore(checkpoint)
  }

  pub fn delete_item(&mut self, id: &str) -> Result<bool, String> {
    let original_len = self.items.len();
    let checkpoint = self.checkpoint();
    self.items.retain(|item| item.id() != id);
    let changed = original_len != self.items.len();
    if !changed {
      return Ok(false);
    }
    self.persist_or_restore(checkpoint)?;
    Ok(true)
  }

  pub fn duplicate_item(&mut self, id: &str) -> Result<bool, String> {
    self.duplicate_item_at(id, Utc::now())
  }

  fn duplicate_item_at(
    &mut self,
    id: &str,
    copied_at: DateTime<Utc>,
  ) -> Result<bool, String> {
    let Some(item) = self.items.iter().find(|item| item.id() == id).cloned() else {
      return Ok(false);
    };
    let checkpoint = self.checkpoint();
    let duplicate = item.duplicate_at(copied_at);
    self.items.insert(0, duplicate);
    prune_items(&mut self.items, self.retention, copied_at);
    self.persist_or_restore(checkpoint)?;
    Ok(true)
  }

  /// A clip copied back from history becomes the newest one: the system
  /// clipboard now holds it, and the capture that would have moved it to the
  /// front is suppressed to keep the item's identity and metadata.
  pub fn touch_item(
    &mut self,
    id: &str,
    copied_at: DateTime<Utc>,
  ) -> Result<bool, String> {
    let Some(index) = self.items.iter().position(|item| item.id() == id) else {
      return Ok(false);
    };
    let checkpoint = self.checkpoint();
    let mut item = self.items.remove(index);
    item.set_copied_at(copied_at);
    self.items.insert(0, item);
    self.persist_or_restore(checkpoint)?;
    Ok(true)
  }

  pub fn clear(&mut self) -> Result<(), String> {
    let checkpoint = self.checkpoint();
    self.items.clear();
    self.source_app_visuals.clear();
    if let ClipboardPersistence::DeletionOnly(path) = &self.persistence {
      if let Err(error) = ClipboardStore::remove(path) {
        self.restore(checkpoint);
        return Err(error);
      }
      self.persistence = ClipboardPersistence::MemoryOnly;
      return Ok(());
    }
    self.persist_or_restore(checkpoint)
  }

  pub fn create_group(
    &mut self,
    name: &str,
    color: ClipboardGroupColor,
  ) -> Result<String, String> {
    let name = name.trim();
    if name.is_empty() || name.chars().count() > MAX_GROUP_NAME_CHARACTERS {
      return Err("clipboard group name is invalid".to_string());
    }
    if self.groups.len() >= MAX_GROUPS {
      return Err("clipboard group limit reached".to_string());
    }
    let normalized_name = name.to_lowercase();
    if self
      .groups
      .iter()
      .any(|group| group.name.to_lowercase() == normalized_name)
    {
      return Err("clipboard group name already exists".to_string());
    }
    let id = uuid::Uuid::new_v4().to_string();
    let checkpoint = self.checkpoint();
    self.groups.push(ClipboardGroup {
      color,
      id: id.clone(),
      name: name.to_string(),
    });
    self.persist_or_restore(checkpoint)?;
    Ok(id)
  }

  pub fn delete_group(&mut self, id: &str) -> Result<bool, String> {
    let original_len = self.groups.len();
    let checkpoint = self.checkpoint();
    self.groups.retain(|group| group.id != id);
    if original_len == self.groups.len() {
      return Ok(false);
    }
    for item in &mut self.items {
      if item.group_id() == Some(id) {
        item.set_group_id(None);
      }
    }
    // Clips that just lost their organiser fall under the history rules.
    prune_items(&mut self.items, self.retention, Utc::now());
    self.persist_or_restore(checkpoint)?;
    Ok(true)
  }

  pub fn update_item(
    &mut self,
    id: &str,
    plain_text: &str,
    html: Option<&str>,
    group_id: Option<String>,
  ) -> Result<bool, String> {
    if plain_text.trim().is_empty() || plain_text.len() > MAX_ITEM_TEXT_BYTES {
      return Err("clipboard item text is invalid".to_string());
    }
    if let Some(group_id) = &group_id
      && !self.groups.iter().any(|group| group.id == *group_id)
    {
      return Err("clipboard group does not exist".to_string());
    }
    if html.is_some_and(|html| html.len() > MAX_ITEM_HTML_BYTES) {
      return Err("clipboard item formatting is invalid".to_string());
    }
    let html = html.and_then(sanitized_html);
    let checkpoint = self.checkpoint();
    let Some(item) = self.items.iter_mut().find(|item| item.id() == id) else {
      return Ok(false);
    };
    if !item.same_content(plain_text, html.as_deref()) {
      item.replace_content(plain_text.to_string(), html);
    }
    item.set_group_id(group_id);
    prune_items_preserving(&mut self.items, self.retention, Utc::now(), Some(id));
    self.persist_or_restore(checkpoint)?;
    Ok(true)
  }

  pub fn set_item_group(
    &mut self,
    id: &str,
    group_id: Option<String>,
  ) -> Result<bool, String> {
    if let Some(group_id) = &group_id
      && !self.groups.iter().any(|group| group.id == *group_id)
    {
      return Err("clipboard group does not exist".to_string());
    }
    let checkpoint = self.checkpoint();
    let Some(item) = self.items.iter_mut().find(|item| item.id() == id) else {
      return Ok(false);
    };
    item.set_group_id(group_id);
    // Ungrouping puts the clip back under the history rules.
    prune_items(&mut self.items, self.retention, Utc::now());
    self.persist_or_restore(checkpoint)?;
    Ok(true)
  }

  pub fn set_item_name(&mut self, id: &str, name: &str) -> Result<bool, String> {
    let name = name.trim();
    if name.chars().count() > MAX_ITEM_NAME_CHARACTERS {
      return Err("clipboard item name is invalid".to_string());
    }
    let checkpoint = self.checkpoint();
    let Some(item) = self.items.iter_mut().find(|item| item.id() == id) else {
      return Ok(false);
    };
    item.set_name((!name.is_empty()).then(|| name.to_string()));
    prune_items_preserving(&mut self.items, self.retention, Utc::now(), Some(id));
    self.persist_or_restore(checkpoint)?;
    Ok(true)
  }

  pub fn item(&self, id: &str) -> Option<ClipboardItem> {
    self.items.iter().find(|item| item.id() == id).cloned()
  }

  pub fn suppress_next(&mut self, item: &ClipboardItem, plain_text_only: bool) {
    self.suppressed_content = Some((
      item.plain_text().to_string(),
      if plain_text_only {
        None
      } else {
        item.html().map(str::to_string)
      },
    ));
  }

  pub fn clear_suppression(&mut self) {
    self.suppressed_content = None;
  }

  fn capture(&mut self, capture: ClipboardCapture) -> Result<bool, String> {
    if self.capture_status == ClipboardCaptureStatus::Paused {
      return Ok(false);
    }
    let ClipboardCapture {
      copied_at,
      html,
      plain_text,
      rtf,
      source_app,
      source_app_visual,
    } = capture;
    if self.suppressed_content.as_ref() == Some(&(plain_text.clone(), html.clone())) {
      self.suppressed_content = None;
      return Ok(false);
    }
    let checkpoint = self.checkpoint();
    self.suppressed_content = None;

    if let Some(source_app_visual) = source_app_visual
      && (self.source_app_visuals.contains_key(&source_app_visual.key)
        || self.source_app_visuals.len() < MAX_SOURCE_APP_VISUALS)
    {
      self
        .source_app_visuals
        .insert(source_app_visual.key.clone(), source_app_visual);
    }

    let preserved_metadata = self
      .items
      .iter()
      .find(|item| item.same_content(&plain_text, html.as_deref()))
      .map(|item| {
        (
          item.group_id().map(str::to_string),
          item.name().map(str::to_string),
        )
      });
    self
      .items
      .retain(|item| !item.same_content(&plain_text, html.as_deref()));
    let id = uuid::Uuid::new_v4().to_string();
    let (group_id, name) = preserved_metadata.unwrap_or((None, None));
    let item = match html {
      Some(html) => ClipboardItem::FormattedText {
        copied_at,
        group_id,
        html,
        id,
        name,
        plain_text,
        rtf,
        source_app,
      },
      None => ClipboardItem::Text {
        copied_at,
        group_id,
        id,
        name,
        plain_text,
        source_app,
      },
    };
    self.items.insert(0, item);
    prune_items(&mut self.items, self.retention, copied_at);
    self.persist_or_restore(checkpoint)?;
    Ok(true)
  }

  pub fn prune_expired(&mut self, now: DateTime<Utc>) -> Result<bool, String> {
    let checkpoint = self.checkpoint();
    if !prune_items(&mut self.items, self.retention, now) {
      return Ok(false);
    }
    self.persist_or_restore(checkpoint)?;
    Ok(true)
  }

  fn checkpoint(&self) -> ClipboardManagerCheckpoint {
    ClipboardManagerCheckpoint {
      capture_status: self.capture_status,
      groups: self.groups.clone(),
      items: self.items.clone(),
      retention: self.retention,
      source_app_visuals: self.source_app_visuals.clone(),
      suppressed_content: self.suppressed_content.clone(),
    }
  }

  fn restore(&mut self, checkpoint: ClipboardManagerCheckpoint) {
    self.capture_status = checkpoint.capture_status;
    self.groups = checkpoint.groups;
    self.items = checkpoint.items;
    self.retention = checkpoint.retention;
    self.source_app_visuals = checkpoint.source_app_visuals;
    self.suppressed_content = checkpoint.suppressed_content;
  }

  fn persist_or_restore(
    &mut self,
    checkpoint: ClipboardManagerCheckpoint,
  ) -> Result<(), String> {
    if let Err(error) = self.persist() {
      self.restore(checkpoint);
      return Err(error);
    }
    Ok(())
  }

  fn persist(&mut self) -> Result<(), String> {
    // Rejecting the write makes `persist_or_restore` roll the mutation
    // back, so `install` can never overwrite a change made before the
    // persisted history arrived.
    if matches!(self.persistence, ClipboardPersistence::Initializing) {
      return Err(HISTORY_LOADING_ERROR.to_string());
    }
    // Visuals whose source app no longer backs any item leave the capped map
    // on every persisted mutation; stale entries would otherwise block icons
    // for new source apps once the cap fills. A failed store write restores
    // them through the caller's checkpoint.
    let referenced_keys: HashSet<&str> = self
      .items
      .iter()
      .filter_map(ClipboardItem::source_visual_key)
      .collect();
    self
      .source_app_visuals
      .retain(|key, _| referenced_keys.contains(key.as_str()));
    let ClipboardPersistence::Encrypted(store) = &self.persistence else {
      // MemoryOnly and DeletionOnly keep nothing on disk.
      return Ok(());
    };
    let mut source_app_visuals: Vec<ClipboardSourceAppVisual> =
      self.source_app_visuals.values().cloned().collect();
    source_app_visuals.sort_by(|left, right| left.key.cmp(&right.key));
    let state = PersistedClipboardState {
      capture_status: self.capture_status,
      groups: self.groups.clone(),
      items: self.items.clone(),
      retention: self.retention,
      source_app_visuals,
    };
    store.persist(&state).map_err(|error| {
      tracing::warn!(error = %error, "clipboard history persistence failed");
      error
    })
  }
}

fn prune_items(
  items: &mut Vec<ClipboardItem>,
  retention: ClipboardRetention,
  now: DateTime<Utc>,
) -> bool {
  prune_items_preserving(items, retention, now, None)
}

fn prune_items_preserving(
  items: &mut Vec<ClipboardItem>,
  retention: ClipboardRetention,
  now: DateTime<Utc>,
  preserved_id: Option<&str>,
) -> bool {
  let original_len = items.len();
  let oldest = now - Duration::days(retention.days());
  items.retain(|item| {
    Some(item.id()) == preserved_id || item.is_organised() || item.copied_at() >= oldest
  });

  // Items are newest first, so `rposition` picks the oldest candidate.
  let is_plain =
    |item: &ClipboardItem| Some(item.id()) != preserved_id && !item.is_organised();

  // The count cap bounds plain history; organised items sit outside it.
  let mut plain_count = items.iter().filter(|item| is_plain(item)).count();
  while plain_count > MAX_HISTORY_ITEMS {
    let Some(index) = items.iter().rposition(is_plain) else {
      break;
    };
    items.remove(index);
    plain_count -= 1;
  }

  // The byte cap is the one hard limit: it removes plain history first and
  // touches organised items only once none is left.
  let mut total_bytes = items.iter().map(ClipboardItem::byte_len).sum::<usize>();
  while total_bytes > MAX_HISTORY_BYTES {
    let Some(index) = items.iter().rposition(is_plain).or_else(|| {
      items
        .iter()
        .rposition(|item| Some(item.id()) != preserved_id)
    }) else {
      break;
    };
    total_bytes -= items.remove(index).byte_len();
  }
  items.len() != original_len
}

fn sanitized_html(raw_html: &str) -> Option<String> {
  if raw_html.len() > MAX_ITEM_HTML_BYTES {
    return None;
  }
  let allowed_tags = HashSet::from([
    "b",
    "blockquote",
    "br",
    "code",
    "div",
    "em",
    "i",
    "li",
    "ol",
    "p",
    "pre",
    "s",
    "span",
    "strike",
    "strong",
    "u",
    "ul",
  ]);
  let html = HtmlSanitizer::new()
    .tags(allowed_tags)
    .clean(&without_word_list_spacers(raw_html))
    .to_string();
  let html = collapse_html_whitespace(&html);
  let has_formatting = [
    "b",
    "blockquote",
    "code",
    "em",
    "i",
    "li",
    "ol",
    "pre",
    "s",
    "strong",
    "u",
    "ul",
  ]
  .iter()
  .any(|tag| find_opening_tag(&html, tag).is_some());
  if has_formatting { Some(html) } else { None }
}

/// Word separates an auto-numbered list label from its paragraph with a span in
/// this font holding a run of `&nbsp;`; the run is layout, not text.
const WORD_LIST_SPACER_FONTS: [&str; 2] = [
  "font:7.0pt \"Times New Roman\"",
  "font:7.0pt &quot;Times New Roman&quot;",
];

fn without_word_list_spacers(raw_html: &str) -> String {
  let mut output = String::with_capacity(raw_html.len());
  let mut rest = raw_html;
  while let Some((start, end)) = next_word_list_spacer(rest) {
    output.push_str(&rest[..start]);
    output.push(' ');
    rest = &rest[end..];
  }
  output.push_str(rest);
  output
}

/// Byte range of the next spacer `<span>` whose content is only `&nbsp;` and
/// whitespace. Every index used to slice lands on ASCII, so the slices are valid.
fn next_word_list_spacer(html: &str) -> Option<(usize, usize)> {
  let mut search_from = 0;
  while let Some(offset) = WORD_LIST_SPACER_FONTS
    .iter()
    .filter_map(|font| html[search_from..].find(font))
    .min()
  {
    let font_index = search_from + offset;
    search_from = font_index + 1;
    let Some(span_start) = html[..font_index].rfind("<span") else {
      continue;
    };
    if html[span_start..font_index].contains('>') {
      continue;
    }
    let content_start = font_index + html[font_index..].find('>')? + 1;
    let content_len = html[content_start..].find("</span>")?;
    let content = &html[content_start..content_start + content_len];
    if content
      .split("&nbsp;")
      .all(|chunk| chunk.chars().all(char::is_whitespace))
    {
      return Some((span_start, content_start + content_len + "</span>".len()));
    }
  }
  None
}

/// Collapses source whitespace outside `<pre>` the way HTML renders it, so
/// previews and derived plain text never inherit the source line wrapping that
/// Word and browsers put in clipboard HTML.
fn collapse_html_whitespace(html: &str) -> String {
  let mut output = String::with_capacity(html.len());
  let mut rest = html;
  while let Some(pre_start) = find_opening_tag(rest, "pre") {
    let pre_end = rest[pre_start..]
      .find("</pre>")
      .map_or(rest.len(), |index| pre_start + index + "</pre>".len());
    push_collapsed_whitespace(&mut output, &rest[..pre_start]);
    output.push_str(&rest[pre_start..pre_end]);
    rest = &rest[pre_end..];
  }
  push_collapsed_whitespace(&mut output, rest);
  output.trim().to_string()
}

fn push_collapsed_whitespace(output: &mut String, html: &str) {
  let mut pending_space = false;
  for character in html.chars() {
    if character.is_ascii_whitespace() {
      pending_space = true;
      continue;
    }
    if pending_space {
      output.push(' ');
      pending_space = false;
    }
    output.push(character);
  }
  if pending_space {
    output.push(' ');
  }
}

fn find_opening_tag(html: &str, tag: &str) -> Option<usize> {
  let prefix = format!("<{tag}");
  html.match_indices(&prefix).find_map(|(index, _)| {
    html
      .as_bytes()
      .get(index + prefix.len())
      .is_some_and(|byte| *byte == b'>' || byte.is_ascii_whitespace())
      .then_some(index)
  })
}

fn should_ignore_formats(formats: &[String]) -> bool {
  formats.iter().any(|format| {
    let normalized = format.to_lowercase();
    format.eq_ignore_ascii_case(WINDOWS_MONITOR_PROCESSING_EXCLUSION_FORMAT)
      || IGNORED_FORMATS.iter().any(|ignored| normalized == *ignored)
  })
}

#[cfg(any(target_os = "windows", test))]
fn windows_history_control_allows_capture(value: &[u8]) -> bool {
  let [first, second, third, fourth, ..] = value else {
    return false;
  };
  u32::from_le_bytes([*first, *second, *third, *fourth]) != 0
}

#[cfg(target_os = "windows")]
fn windows_clipboard_history_allows_capture(
  clipboard: &ClipboardContext,
  formats: &[String],
) -> bool {
  if !formats
    .iter()
    .any(|format| format.eq_ignore_ascii_case(WINDOWS_CLIPBOARD_HISTORY_CONTROL_FORMAT))
  {
    return true;
  }
  clipboard
    .get_buffer(WINDOWS_CLIPBOARD_HISTORY_CONTROL_FORMAT)
    .is_ok_and(|value| windows_history_control_allows_capture(&value))
}

fn bounded_metadata(value: &str, max_bytes: usize) -> Option<String> {
  let value = value.trim();
  if value.is_empty() {
    return None;
  }
  if value.len() <= max_bytes {
    return Some(value.to_string());
  }
  let mut boundary = 0;
  for (index, character) in value.char_indices() {
    let next_boundary = index + character.len_utf8();
    if next_boundary > max_bytes {
      break;
    }
    boundary = next_boundary;
  }
  Some(value[..boundary].to_string())
}

fn dominant_icon_color(icon: &image::RgbaImage) -> Option<String> {
  let mut buckets = HashMap::<(u8, u8, u8), (u64, u64, u64, u64)>::new();
  for pixel in icon.pixels() {
    let [red, green, blue, alpha] = pixel.0;
    if alpha < 48 {
      continue;
    }
    let maximum = red.max(green).max(blue);
    let minimum = red.min(green).min(blue);
    let chroma = maximum - minimum;
    let weight = u64::from(alpha) * u64::from(chroma.saturating_add(24));
    let bucket = (red / 32, green / 32, blue / 32);
    let entry = buckets.entry(bucket).or_default();
    entry.0 += weight;
    entry.1 += u64::from(red) * weight;
    entry.2 += u64::from(green) * weight;
    entry.3 += u64::from(blue) * weight;
  }
  let (_, (weight, red, green, blue)) =
    buckets.into_iter().max_by_key(|(_, values)| values.0)?;
  if weight == 0 {
    return None;
  }
  Some(format!(
    "#{:02x}{:02x}{:02x}",
    red / weight,
    green / weight,
    blue / weight
  ))
}

fn source_app_visual(icon: image::RgbaImage) -> (Option<String>, Option<String>) {
  let icon = image::DynamicImage::ImageRgba8(icon)
    .thumbnail(SOURCE_APP_ICON_SIZE, SOURCE_APP_ICON_SIZE)
    .to_rgba8();
  let color = dominant_icon_color(&icon);
  let mut png = Cursor::new(Vec::new());
  let icon_data_url = image::DynamicImage::ImageRgba8(icon)
    .write_to(&mut png, image::ImageFormat::Png)
    .ok()
    .and_then(|()| {
      let value = format!(
        "data:image/png;base64,{}",
        STANDARD.encode(png.into_inner())
      );
      (value.len() <= MAX_SOURCE_APP_ICON_DATA_URL_BYTES).then_some(value)
    });
  (icon_data_url, color)
}

struct ClipboardSourceCapture {
  app: ClipboardSourceApp,
  visual: Option<ClipboardSourceAppVisual>,
}

fn source_app_visual_metadata(
  key: String,
  (icon_data_url, color): (Option<String>, Option<String>),
) -> Option<ClipboardSourceAppVisual> {
  if icon_data_url.is_none() && color.is_none() {
    return None;
  }
  Some(ClipboardSourceAppVisual {
    color,
    icon_data_url,
    key,
  })
}

#[cfg(target_os = "macos")]
fn macos_bundle_icon_path(bundle_path: &Path) -> Option<PathBuf> {
  let info = plist::Value::from_file(bundle_path.join("Contents/Info.plist")).ok()?;
  let icon_name = info.as_dictionary()?.get("CFBundleIconFile")?.as_string()?;
  let mut components = Path::new(icon_name).components();
  let Component::Normal(file_name) = components.next()? else {
    return None;
  };
  if components.next().is_some() {
    return None;
  }
  let mut icon_path = bundle_path.join("Contents/Resources").join(file_name);
  if icon_path.extension().is_none() {
    icon_path.set_extension("icns");
  }
  icon_path.is_file().then_some(icon_path)
}

#[cfg(target_os = "macos")]
fn macos_source_app_icon(bundle_path: &Path) -> Option<image::RgbaImage> {
  let icon_path = macos_bundle_icon_path(bundle_path)?;
  let family = IconFamily::read(BufReader::new(File::open(icon_path).ok()?)).ok()?;
  let mut icon_types = family.available_icons();
  icon_types.sort_by_key(|icon_type| {
    let width = icon_type.pixel_width();
    (
      width < SOURCE_APP_ICON_SIZE,
      width.abs_diff(SOURCE_APP_ICON_SIZE),
    )
  });
  icon_types.into_iter().find_map(|icon_type| {
    let icon = family.get_icon_with_type(icon_type).ok()?;
    let icon = icon.convert_to(PixelFormat::RGBA);
    image::RgbaImage::from_raw(icon.width(), icon.height(), icon.into_data().into_vec())
  })
}

#[cfg(target_os = "macos")]
struct MacosSourceCapture {
  app: ClipboardSourceApp,
  bundle_path: Option<String>,
}

#[cfg(target_os = "macos")]
fn frontmost_source_app_on_main_thread() -> Option<MacosSourceCapture> {
  let application = NSWorkspace::sharedWorkspace().frontmostApplication()?;
  let bundle_path = application
    .bundleURL()
    .and_then(|url| url.path())
    .map(|path| path.to_string());
  let name = bundle_path
    .as_deref()
    .and_then(|path| {
      Path::new(path)
        .file_stem()
        .and_then(|name| name.to_str())
        .and_then(|name| bounded_metadata(name, MAX_SOURCE_APP_NAME_BYTES))
    })
    .or_else(|| {
      application
        .localizedName()
        .and_then(|name| bounded_metadata(&name.to_string(), MAX_SOURCE_APP_NAME_BYTES))
    })?;
  let identifier = application.bundleIdentifier().and_then(|bundle_id| {
    bounded_metadata(&bundle_id.to_string(), MAX_SOURCE_APP_IDENTIFIER_BYTES)
  });
  let app = ClipboardSourceApp { identifier, name };
  Some(MacosSourceCapture { app, bundle_path })
}

#[cfg(target_os = "macos")]
fn frontmost_source_app(app: &AppHandle) -> Option<ClipboardSourceCapture> {
  let (sender, receiver) = sync_channel(1);
  app
    .run_on_main_thread(move || {
      let _ = sender.send(frontmost_source_app_on_main_thread());
    })
    .ok()?;
  let source = receiver.recv_timeout(StdDuration::from_secs(1)).ok()??;
  let key = source
    .app
    .identifier
    .clone()
    .unwrap_or_else(|| source.app.name.clone());
  let visual = source
    .bundle_path
    .as_deref()
    .and_then(|bundle_path| macos_source_app_icon(Path::new(bundle_path)))
    .map(source_app_visual)
    .and_then(|visual| source_app_visual_metadata(key, visual));
  Some(ClipboardSourceCapture {
    app: source.app,
    visual,
  })
}

#[cfg(target_os = "windows")]
fn windows_product_name(executable_path: &str) -> Option<String> {
  let version = HVERSIONINFO::GetFileVersionInfo(executable_path).ok()?;
  let language_and_code_page = version.langs_and_cps().ok()?.first().copied()?;
  version
    .str_val(language_and_code_page, "ProductName")
    .ok()
    .and_then(|name| bounded_metadata(&name, MAX_SOURCE_APP_NAME_BYTES))
}

#[cfg(target_os = "windows")]
fn frontmost_source_app(_app: &AppHandle) -> Option<ClipboardSourceCapture> {
  let window = HWND::GetForegroundWindow()?;
  let (_, process_id) = window.GetWindowThreadProcessId();
  let process =
    HPROCESS::OpenProcess(co::PROCESS::QUERY_LIMITED_INFORMATION, false, process_id)
      .ok()?;
  let executable_path = process
    .QueryFullProcessImageName(co::PROCESS_NAME::WIN32)
    .ok()?;
  let executable_name = Path::new(&executable_path)
    .file_name()
    .and_then(|name| name.to_str())
    .and_then(|name| bounded_metadata(name, MAX_SOURCE_APP_IDENTIFIER_BYTES));
  let name = windows_product_name(&executable_path)
    .or_else(|| {
      Path::new(&executable_path)
        .file_stem()
        .and_then(|name| name.to_str())
        .and_then(|name| bounded_metadata(name, MAX_SOURCE_APP_NAME_BYTES))
    })
    .or_else(|| {
      window
        .GetWindowText()
        .ok()
        .and_then(|title| bounded_metadata(&title, MAX_SOURCE_APP_NAME_BYTES))
    })
    .or_else(|| executable_name.clone())?;
  let (icon_data_url, color) = windows_icons::get_icon_by_process_id(process_id)
    .ok()
    .map_or((None, None), source_app_visual);
  let app = ClipboardSourceApp {
    identifier: executable_name,
    name,
  };
  let key = app.identifier.clone().unwrap_or_else(|| app.name.clone());
  let visual = source_app_visual_metadata(key, (icon_data_url, color));
  Some(ClipboardSourceCapture { app, visual })
}

#[cfg(not(any(target_os = "macos", target_os = "windows")))]
fn frontmost_source_app(_app: &AppHandle) -> Option<ClipboardSourceCapture> {
  None
}

struct HistoryClipboardHandler {
  app: AppHandle,
  clipboard: ClipboardContext,
  manager: ClipboardAppState,
  telemetry: DesktopTelemetry,
}

impl ClipboardHandler for HistoryClipboardHandler {
  fn on_clipboard_change(&mut self) {
    let formats = match self.clipboard.available_formats() {
      Ok(formats) => formats,
      Err(error) => {
        tracing::warn!(error = %error, "clipboard formats could not be read");
        self.telemetry.capture(DesktopErrorReport {
          window: DesktopTelemetryWindow::Clipboard,
          operation: DesktopTelemetryOperation::ClipboardWatcherRead,
          code: DesktopTelemetryErrorCode::FormatReadFailed,
        });
        return;
      }
    };
    if formats
      .iter()
      .any(|format| format.eq_ignore_ascii_case(INTERNAL_CLIPBOARD_FORMAT))
    {
      if let Ok(mut manager) = self.manager.lock() {
        manager.clear_suppression();
      }
      return;
    }
    if should_ignore_formats(&formats) || self.clipboard.has(ContentFormat::Files) {
      return;
    }
    #[cfg(target_os = "windows")]
    if !windows_clipboard_history_allows_capture(&self.clipboard, &formats) {
      return;
    }
    let plain_text = match self.clipboard.get_text() {
      Ok(text) if !text.trim().is_empty() && text.len() <= MAX_ITEM_TEXT_BYTES => text,
      Ok(_) => return,
      Err(error) => {
        tracing::debug!(error = %error, "clipboard change did not contain readable text");
        return;
      }
    };
    let html = if self.clipboard.has(ContentFormat::Html) {
      self
        .clipboard
        .get_html()
        .ok()
        .and_then(|raw_html| sanitized_html(&raw_html))
    } else {
      None
    };
    let rtf = if html.is_some() && self.clipboard.has(ContentFormat::Rtf) {
      self
        .clipboard
        .get_rich_text()
        .ok()
        .filter(|rtf| rtf.len() <= MAX_ITEM_RTF_BYTES)
    } else {
      None
    };

    let (source_app, source_app_visual) = frontmost_source_app(&self.app)
      .map(|source| (Some(source.app), source.visual))
      .unwrap_or((None, None));
    let capture = ClipboardCapture {
      copied_at: Utc::now(),
      html,
      plain_text,
      rtf,
      source_app,
      source_app_visual,
    };
    let changed = match self.manager.lock() {
      Ok(mut manager) => match manager.capture(capture) {
        Ok(changed) => changed,
        Err(error) => {
          tracing::error!(error = %error, "clipboard capture could not be persisted");
          self.telemetry.capture(DesktopErrorReport {
            window: DesktopTelemetryWindow::Clipboard,
            operation: DesktopTelemetryOperation::ClipboardWatcherRead,
            code: DesktopTelemetryErrorCode::PersistenceFailed,
          });
          return;
        }
      },
      Err(_) => {
        tracing::error!("clipboard manager lock is poisoned");
        self.telemetry.capture(DesktopErrorReport {
          window: DesktopTelemetryWindow::Clipboard,
          operation: DesktopTelemetryOperation::ClipboardWatcherRead,
          code: DesktopTelemetryErrorCode::LockPoisoned,
        });
        return;
      }
    };
    if changed {
      let _ = self.app.emit(HISTORY_EVENT, ());
    }
  }
}

fn report_init_timings(
  telemetry: &DesktopTelemetry,
  initialize: std::time::Duration,
  timings: ClipboardInitTimings,
) {
  let spans = [
    (DesktopTelemetrySpan::ClipboardInitialize, Some(initialize)),
    (
      DesktopTelemetrySpan::ClipboardKeychainRead,
      timings.keychain_read,
    ),
    (DesktopTelemetrySpan::ClipboardStoreLoad, timings.store_load),
  ];
  for (span, duration) in spans {
    let Some(duration) = duration else {
      continue;
    };
    telemetry.capture_timing(DesktopTimingReport {
      window: DesktopTelemetryWindow::Clipboard,
      span,
      duration,
      open_kind: None,
      item_count: timings.loaded_items,
      payload_bytes: None,
    });
  }
}

pub fn initialize_and_watch(
  manager: ClipboardAppState,
  app: AppHandle,
  telemetry: DesktopTelemetry,
) {
  let started = Instant::now();
  let (load, timings) = load_persisted();
  if let Ok(mut manager) = manager.lock() {
    manager.install(load);
    drop(manager);
    report_init_timings(&telemetry, started.elapsed(), timings);
  } else {
    tracing::error!("clipboard manager lock is poisoned during initialization");
    telemetry.capture(DesktopErrorReport {
      window: DesktopTelemetryWindow::Clipboard,
      operation: DesktopTelemetryOperation::ClipboardWatcherStart,
      code: DesktopTelemetryErrorCode::LockPoisoned,
    });
    return;
  }
  let _ = app.emit(HISTORY_EVENT, ());

  let retention_manager = Arc::clone(&manager);
  let retention_app = app.clone();
  let retention_telemetry = telemetry.clone();
  tauri::async_runtime::spawn(async move {
    let mut interval = tokio::time::interval(RETENTION_SWEEP_INTERVAL);
    interval.tick().await;
    loop {
      interval.tick().await;
      let changed = match retention_manager.lock() {
        Ok(mut manager) => match manager.prune_expired(Utc::now()) {
          Ok(changed) => changed,
          Err(error) => {
            tracing::error!(error = %error, "expired clipboard history could not be removed");
            retention_telemetry.capture(DesktopErrorReport {
              window: DesktopTelemetryWindow::Clipboard,
              operation: DesktopTelemetryOperation::ClipboardWatcherRead,
              code: DesktopTelemetryErrorCode::PersistenceFailed,
            });
            false
          }
        },
        Err(_) => {
          tracing::error!("clipboard manager lock is poisoned during retention sweep");
          retention_telemetry.capture(DesktopErrorReport {
            window: DesktopTelemetryWindow::Clipboard,
            operation: DesktopTelemetryOperation::ClipboardWatcherRead,
            code: DesktopTelemetryErrorCode::LockPoisoned,
          });
          false
        }
      };
      if changed {
        let _ = retention_app.emit(HISTORY_EVENT, ());
      }
    }
  });

  let clipboard = match ClipboardContext::new() {
    Ok(clipboard) => clipboard,
    Err(error) => {
      tracing::error!(error = %error, "clipboard reader could not start");
      telemetry.capture(DesktopErrorReport {
        window: DesktopTelemetryWindow::Clipboard,
        operation: DesktopTelemetryOperation::ClipboardWatcherStart,
        code: DesktopTelemetryErrorCode::ClipboardUnavailable,
      });
      return;
    }
  };
  let mut handler = HistoryClipboardHandler {
    app,
    clipboard,
    manager,
    telemetry: telemetry.clone(),
  };
  // Reconcile once before polling so a copy made while the desktop process was
  // starting or rebuilding is not lost behind the watcher's initial baseline.
  handler.on_clipboard_change();
  let mut watcher = match ClipboardWatcherContext::new() {
    Ok(watcher) => watcher,
    Err(error) => {
      tracing::error!(error = %error, "clipboard watcher could not start");
      telemetry.capture(DesktopErrorReport {
        window: DesktopTelemetryWindow::Clipboard,
        operation: DesktopTelemetryOperation::ClipboardWatcherStart,
        code: DesktopTelemetryErrorCode::WatcherUnavailable,
      });
      return;
    }
  };
  watcher.add_handler(handler);
  watcher.start_watch();
}

pub fn write_item(item: &ClipboardItem, plain_text_only: bool) -> Result<(), String> {
  let clipboard = ClipboardContext::new()
    .map_err(|error| format!("clipboard is unavailable: {error}"))?;
  let mut contents = vec![ClipboardContent::Text(item.plain_text().to_string())];
  if !plain_text_only && let Some(html) = item.html() {
    contents.push(ClipboardContent::Html(html.to_string()));
  }
  if !plain_text_only && let Some(rtf) = item.rtf() {
    contents.push(ClipboardContent::Rtf(rtf.to_string()));
  }
  contents.push(ClipboardContent::Other(
    INTERNAL_CLIPBOARD_FORMAT.to_string(),
    Vec::new(),
  ));
  clipboard
    .set(contents)
    .map_err(|error| format!("clipboard write failed: {error}"))
}

#[cfg(test)]
mod tests {
  use super::*;

  /// A manager past initialization; a fresh `new()` rejects mutations.
  fn ready_manager() -> ClipboardManager {
    let mut manager = ClipboardManager::new();
    manager.install(ClipboardLoad::MemoryOnly);
    manager
  }

  fn text_item(copied_at: DateTime<Utc>, text: &str) -> ClipboardItem {
    ClipboardItem::Text {
      copied_at,
      group_id: None,
      id: uuid::Uuid::new_v4().to_string(),
      name: None,
      plain_text: text.to_string(),
      source_app: None,
    }
  }

  fn unique_store_path() -> std::path::PathBuf {
    std::env::temp_dir().join(format!(
      "stella-clipboard-manager-{}.json.enc",
      uuid::Uuid::new_v4()
    ))
  }

  fn capture(
    manager: &mut ClipboardManager,
    plain_text: &str,
    html: Option<&str>,
    copied_at: DateTime<Utc>,
  ) -> bool {
    manager
      .capture(ClipboardCapture {
        copied_at,
        html: html.map(str::to_string),
        plain_text: plain_text.to_string(),
        rtf: None,
        source_app: None,
        source_app_visual: None,
      })
      .unwrap()
  }

  const WORD_RTF: &str = r"{\rtf1\ansi{\b Clause}}";

  fn capture_with_rtf(manager: &mut ClipboardManager, html: Option<&str>) -> bool {
    manager
      .capture(ClipboardCapture {
        copied_at: Utc::now(),
        html: html.map(str::to_string),
        plain_text: "Clause".to_string(),
        rtf: Some(WORD_RTF.to_string()),
        source_app: None,
        source_app_visual: None,
      })
      .unwrap()
  }

  #[test]
  fn sanitizer_keeps_simple_formatting_and_removes_active_content() {
    let html = sanitized_html(
      r#"<p style="color:red"><strong>Safe</strong><a href="https://example.com">link</a><script>alert(1)</script></p>"#,
    )
    .unwrap();

    assert!(html.contains("<strong>Safe</strong>"));
    assert!(html.contains("link"));
    assert!(!html.contains("href"));
    assert!(!html.contains("script"));
    assert!(!html.contains("style="));
  }

  #[test]
  fn sanitizer_does_not_treat_plain_layout_tags_as_formatting() {
    assert_eq!(sanitized_html("<span>plain</span>"), None);
    assert_eq!(sanitized_html("line<br>break"), None);
    assert!(sanitized_html("<strong>bold</strong>").is_some());
  }

  /// Shape of the HTML Word puts on the clipboard: document chrome before the
  /// fragment, source lines wrapped at ~72 columns, and an auto-numbered list
  /// label followed by a tiny-font `&nbsp;` spacer.
  const WORD_CLIPBOARD_HTML: &str = concat!(
    "<html xmlns:o=\"urn:schemas-microsoft-com:office:office\"\n",
    "xmlns=\"http://www.w3.org/TR/REC-html40\">\n\n<head>\n",
    "<meta http-equiv=Content-Type content=\"text/html; charset=utf-8\">\n",
    "<meta name=Generator content=\"Microsoft Word 15\">\n",
    "<!--[if gte mso 9]><xml>\n <o:OfficeDocumentSettings>\n",
    " </o:OfficeDocumentSettings>\n</xml><![endif]-->\n",
    "<style>\n<!--\n@list l0:level1\n\t{mso-level-tab-stop:none;}\n-->\n</style>\n",
    "</head>\n\n<body lang=EN-US style='tab-interval:.5in'>\n",
    "<!--StartFragment-->\n\n",
    "<p class=MsoListParagraph style='margin-left:.5in;text-indent:-.25in;\n",
    "mso-list:l0 level1 lfo1'><![if !supportLists]><b><span\n",
    "style='mso-list:Ignore'>11.<span style='font:7.0pt \"Times New Roman\"'>",
    "&nbsp;&nbsp;&nbsp;&nbsp; </span></span></b><![endif]><b>General</b>. ",
    "Neither party has an obligation\nunder this MNDA to disclose ",
    "Confidential Information to the other or proceed with\nany proposed ",
    "transaction.</p>\n\n<!--EndFragment-->\n</body>\n\n</html>\n",
  );

  #[test]
  fn sanitizer_collapses_word_document_chrome_and_source_line_wrapping() {
    let html = sanitized_html(WORD_CLIPBOARD_HTML).unwrap();

    assert!(html.starts_with("<p>"), "{html}");
    assert!(!html.contains('\n'), "{html}");
    assert!(
      html.contains("Neither party has an obligation under this MNDA"),
      "{html}"
    );
    assert!(html.contains("<b>General</b>. Neither"), "{html}");
  }

  #[test]
  fn sanitizer_replaces_word_list_spacers_with_a_single_space() {
    let html = sanitized_html(WORD_CLIPBOARD_HTML).unwrap();

    assert!(!html.contains("&nbsp;"), "{html}");
    assert!(html.contains("11. </span></b><b>General</b>"), "{html}");
  }

  #[test]
  fn sanitizer_keeps_meaningful_non_breaking_spaces() {
    let html = sanitized_html(
      "<p><b>Section</b>&nbsp;5 <span style='font:7.0pt \"Times New Roman\"'>kept</span></p>",
    )
    .unwrap();

    assert_eq!(html, "<p><b>Section</b>&nbsp;5 <span>kept</span></p>");
  }

  #[test]
  fn sanitizer_preserves_preformatted_whitespace() {
    let html = sanitized_html("<p>a\n\n  b</p>\n<pre>a\n  b</pre>\n").unwrap();

    assert_eq!(html, "<p>a b</p> <pre>a\n  b</pre>");
  }

  #[test]
  fn source_app_metadata_is_bounded_without_breaking_unicode() {
    let value = format!("{}x", "ž".repeat(MAX_SOURCE_APP_NAME_BYTES));
    let bounded = bounded_metadata(&value, MAX_SOURCE_APP_NAME_BYTES).unwrap();

    assert!(bounded.len() <= MAX_SOURCE_APP_NAME_BYTES);
    assert!(bounded.chars().all(|character| character == 'ž'));
  }

  #[test]
  fn source_app_visual_uses_the_icon_color_and_a_bounded_png() {
    let icon = image::RgbaImage::from_pixel(
      SOURCE_APP_ICON_SIZE,
      SOURCE_APP_ICON_SIZE,
      image::Rgba([30, 120, 220, 255]),
    );

    let (icon_data_url, color) = source_app_visual(icon);

    assert_eq!(color.as_deref(), Some("#1e78dc"));
    let icon_data_url = icon_data_url.unwrap();
    assert!(icon_data_url.starts_with("data:image/png;base64,"));
    assert!(icon_data_url.len() <= MAX_SOURCE_APP_ICON_DATA_URL_BYTES);
  }

  #[test]
  fn confidential_and_transient_formats_are_ignored() {
    assert!(should_ignore_formats(&[
      "org.nspasteboard.ConcealedType".to_string()
    ]));
    assert!(should_ignore_formats(&[
      "com.agilebits.onepassword".to_string()
    ]));
    assert!(should_ignore_formats(&[
      WINDOWS_MONITOR_PROCESSING_EXCLUSION_FORMAT.to_string()
    ]));
    assert!(should_ignore_formats(&[
      "x-kde-passwordManagerHint".to_string()
    ]));
    assert!(!should_ignore_formats(&[
      "public.utf8-plain-text".to_string()
    ]));
  }

  #[test]
  fn windows_clipboard_history_control_is_privacy_preserving() {
    assert!(!windows_history_control_allows_capture(
      &0_u32.to_le_bytes()
    ));
    assert!(windows_history_control_allows_capture(&1_u32.to_le_bytes()));
    assert!(!windows_history_control_allows_capture(&[1, 0, 0]));
  }

  #[test]
  fn capture_deduplicates_and_moves_content_to_the_front() {
    let now = Utc::now();
    let mut manager = ready_manager();
    manager.persistence = ClipboardPersistence::MemoryOnly;

    assert!(capture(&mut manager, "first", None, now));
    assert!(capture(&mut manager, "second", None, now));
    assert!(capture(&mut manager, "first", None, now));

    assert_eq!(manager.items.len(), 2);
    assert_eq!(manager.items[0].plain_text(), "first");
  }

  #[test]
  fn duplicating_an_item_preserves_its_content_metadata_and_group() {
    let original_time = Utc::now() - Duration::minutes(5);
    let duplicate_time = Utc::now();
    let original = ClipboardItem::FormattedText {
      copied_at: original_time,
      group_id: Some("research".to_string()),
      html: "<strong>Clause</strong>".to_string(),
      rtf: None,
      id: "original".to_string(),
      name: Some("Key clause".to_string()),
      plain_text: "Clause".to_string(),
      source_app: Some(ClipboardSourceApp {
        identifier: Some("com.microsoft.Word".to_string()),
        name: "Microsoft Word".to_string(),
      }),
    };
    let mut manager = ready_manager();
    manager.items.push(original.clone());

    assert!(
      manager
        .duplicate_item_at("original", duplicate_time)
        .unwrap()
    );
    assert_eq!(manager.items.len(), 2);
    assert_ne!(manager.items[0].id(), original.id());
    assert_eq!(manager.items[0].copied_at(), duplicate_time);
    assert_eq!(manager.items[0].plain_text(), original.plain_text());
    assert_eq!(manager.items[0].html(), original.html());
    assert_eq!(manager.items[0].group_id(), original.group_id());
    assert_eq!(manager.items[0].name(), original.name());
    assert_eq!(manager.items[0].source_app(), original.source_app());
    assert_eq!(manager.items[1], original);
  }

  #[test]
  fn touching_an_item_refreshes_its_timestamp_and_moves_it_to_the_front() {
    let now = Utc::now();
    let mut manager = ready_manager();
    let newest = text_item(now - Duration::minutes(1), "newest");
    let older = text_item(now - Duration::hours(2), "older");
    let older_id = older.id().to_string();
    manager.items = vec![newest.clone(), older];

    assert!(manager.touch_item(&older_id, now).unwrap());
    assert_eq!(manager.items.len(), 2);
    assert_eq!(manager.items[0].id(), older_id);
    assert_eq!(manager.items[0].copied_at(), now);
    assert_eq!(manager.items[0].plain_text(), "older");
    assert_eq!(manager.items[1], newest);

    assert!(!manager.touch_item("missing", now).unwrap());
  }

  #[test]
  fn item_names_are_bounded_and_survive_recapture() {
    let now = Utc::now();
    let mut manager = ready_manager();
    manager.persistence = ClipboardPersistence::MemoryOnly;
    assert!(capture(&mut manager, "Named content", None, now));
    let item_id = manager.items[0].id().to_string();

    assert!(manager.set_item_name(&item_id, "  Key clause  ").unwrap());
    assert_eq!(manager.items[0].name(), Some("Key clause"));
    assert!(capture(
      &mut manager,
      "Named content",
      None,
      now + Duration::minutes(1),
    ));
    assert_eq!(manager.items[0].name(), Some("Key clause"));

    let oversized_name = "界".repeat(MAX_ITEM_NAME_CHARACTERS + 1);
    let recaptured_item_id = manager.items[0].id().to_string();
    assert!(
      manager
        .set_item_name(&recaptured_item_id, &oversized_name)
        .is_err()
    );
    assert_eq!(manager.items[0].name(), Some("Key clause"));
  }

  #[test]
  fn renaming_reapplies_the_total_history_byte_limit() {
    let now = Utc::now();
    let mut manager = ready_manager();
    manager.persistence = ClipboardPersistence::MemoryOnly;
    let target = text_item(now, "target");
    let target_id = target.id().to_string();
    manager.items.push(target);
    let large_text = "x".repeat(MAX_ITEM_TEXT_BYTES);
    for _ in 0..(MAX_HISTORY_BYTES / MAX_ITEM_TEXT_BYTES - 1) {
      manager.items.push(text_item(now, &large_text));
    }
    let bytes_before_filler = manager
      .items
      .iter()
      .map(ClipboardItem::byte_len)
      .sum::<usize>();
    let filler_overhead = text_item(now, "").byte_len();
    let filler_size = MAX_HISTORY_BYTES - bytes_before_filler - filler_overhead - 1;
    manager.items.push(text_item(now, &"x".repeat(filler_size)));
    assert_eq!(
      manager
        .items
        .iter()
        .map(ClipboardItem::byte_len)
        .sum::<usize>(),
      MAX_HISTORY_BYTES - 1
    );

    assert!(manager.set_item_name(&target_id, "Key clause").unwrap());

    let renamed = manager.item(&target_id).unwrap();
    assert_eq!(renamed.name(), Some("Key clause"));
    assert!(
      manager
        .items
        .iter()
        .map(ClipboardItem::byte_len)
        .sum::<usize>()
        <= MAX_HISTORY_BYTES
    );
  }

  #[test]
  fn duplicating_a_missing_item_does_not_change_history() {
    let mut manager = ready_manager();

    assert!(!manager.duplicate_item_at("missing", Utc::now()).unwrap());
    assert!(manager.items.is_empty());
  }

  #[test]
  fn pruning_enforces_retention_count_and_byte_bounds() {
    let now = Utc::now();
    let mut items = vec![text_item(now - Duration::days(31), "expired")];
    items.extend(
      (0..=MAX_HISTORY_ITEMS).map(|index| text_item(now, &format!("item-{index}"))),
    );

    prune_items(&mut items, ClipboardRetention::Month, now);

    assert_eq!(items.len(), MAX_HISTORY_ITEMS);
    assert!(items.iter().all(|item| item.plain_text() != "expired"));
    assert!(
      items.iter().map(ClipboardItem::byte_len).sum::<usize>() <= MAX_HISTORY_BYTES
    );
  }

  #[test]
  fn organised_items_outlive_retention_and_count_limits() {
    let now = Utc::now();
    let mut grouped = text_item(now - Duration::days(400), "grouped");
    grouped.set_group_id(Some("templates".to_string()));
    let mut named = text_item(now - Duration::days(400), "named");
    named.set_name(Some("Key clause".to_string()));
    let mut items = vec![text_item(now - Duration::days(31), "expired")];
    items.extend(
      (0..=MAX_HISTORY_ITEMS).map(|index| text_item(now, &format!("item-{index}"))),
    );
    items.push(grouped);
    items.push(named);

    prune_items(&mut items, ClipboardRetention::Month, now);

    let kept: Vec<&str> = items.iter().map(ClipboardItem::plain_text).collect();
    assert!(kept.contains(&"grouped"));
    assert!(kept.contains(&"named"));
    assert!(!kept.contains(&"expired"));
    assert_eq!(
      items.iter().filter(|item| !item.is_organised()).count(),
      MAX_HISTORY_ITEMS
    );
  }

  #[test]
  fn byte_limit_removes_plain_items_before_organised_ones() {
    let now = Utc::now();
    let large_text = "x".repeat(MAX_ITEM_TEXT_BYTES);
    let mut items = vec![text_item(now, "plain")];
    for _ in 0..(MAX_HISTORY_BYTES / MAX_ITEM_TEXT_BYTES + 1) {
      let mut item = text_item(now - Duration::days(1), &large_text);
      item.set_group_id(Some("templates".to_string()));
      items.push(item);
    }

    prune_items(&mut items, ClipboardRetention::Month, now);

    assert!(items.iter().all(|item| item.plain_text() != "plain"));
    assert!(items.iter().all(ClipboardItem::is_organised));
    assert!(!items.is_empty());
    assert!(
      items.iter().map(ClipboardItem::byte_len).sum::<usize>() <= MAX_HISTORY_BYTES
    );
  }

  #[test]
  fn losing_the_last_organiser_reapplies_retention() {
    let now = Utc::now();
    let mut manager = ready_manager();
    let group_id = manager
      .create_group("Templates", ClipboardGroupColor::Gray)
      .unwrap();
    let mut ungrouped = text_item(now - Duration::days(400), "ungrouped");
    ungrouped.set_group_id(Some(group_id.clone()));
    let ungrouped_id = ungrouped.id().to_string();
    let mut orphaned = text_item(now - Duration::days(400), "orphaned");
    orphaned.set_group_id(Some(group_id.clone()));
    manager.items.push(ungrouped);
    manager.items.push(orphaned);

    assert!(manager.set_item_group(&ungrouped_id, None).unwrap());
    assert!(
      manager
        .items
        .iter()
        .all(|item| item.plain_text() != "ungrouped")
    );
    assert!(
      manager
        .items
        .iter()
        .any(|item| item.plain_text() == "orphaned")
    );

    assert!(manager.delete_group(&group_id).unwrap());
    assert!(manager.items.is_empty());
  }

  #[test]
  fn editing_reapplies_the_total_history_byte_limit() {
    let now = Utc::now();
    let mut manager = ready_manager();
    manager.persistence = ClipboardPersistence::MemoryOnly;
    let large_text = "x".repeat(MAX_ITEM_TEXT_BYTES);
    for _ in 0..(MAX_HISTORY_BYTES / MAX_ITEM_TEXT_BYTES - 1) {
      manager.items.push(text_item(now, &large_text));
    }
    manager.items.push(text_item(now, "x"));
    manager
      .items
      .push(text_item(now - Duration::minutes(1), "editable"));

    assert!(
      !manager
        .update_item("missing", &large_text, None, None)
        .unwrap()
    );
    let editable_id = manager.items.last().unwrap().id().to_string();
    assert!(
      manager
        .update_item(&editable_id, &large_text, None, None)
        .unwrap()
    );
    assert!(manager.items.iter().any(|item| item.id() == editable_id));
    assert!(
      manager
        .items
        .iter()
        .map(ClipboardItem::byte_len)
        .sum::<usize>()
        <= MAX_HISTORY_BYTES
    );
  }

  #[test]
  fn persistence_failure_rolls_back_history_mutations() {
    let store_path = unique_store_path();
    std::fs::create_dir_all(&store_path).unwrap();
    let mut manager = ready_manager();
    manager.persistence =
      ClipboardPersistence::Encrypted(ClipboardStore::new([7; 32], store_path.clone()));
    manager.items.push(text_item(Utc::now(), "must remain"));

    assert!(manager.clear().is_err());
    assert_eq!(manager.items.len(), 1);
    assert_eq!(manager.items[0].plain_text(), "must remain");

    std::fs::remove_dir(store_path).unwrap();
  }

  #[test]
  fn deletion_only_clear_removes_unreadable_encrypted_history() {
    let store_path = unique_store_path();
    std::fs::write(&store_path, b"encrypted history").unwrap();
    let mut manager = ready_manager();
    manager.persistence = ClipboardPersistence::DeletionOnly(store_path.clone());

    manager.clear().unwrap();

    assert!(!store_path.exists());
    assert_eq!(
      manager.persistence.status(),
      ClipboardPersistenceStatus::MemoryOnly
    );
  }

  #[test]
  fn deletion_only_rejects_retention_changes() {
    let mut manager = ready_manager();
    manager.persistence = ClipboardPersistence::DeletionOnly(unique_store_path());

    let result = manager.set_retention(ClipboardRetention::Week);

    assert_eq!(result, Err("clipboard history is unavailable".to_string()));
    assert_eq!(manager.retention, ClipboardRetention::Month);
  }

  #[test]
  fn retention_pruning_is_written_to_encrypted_history() {
    let store_path = unique_store_path();
    let store = ClipboardStore::new([9; 32], store_path.clone());
    let now = Utc::now();
    let state = PersistedClipboardState {
      capture_status: ClipboardCaptureStatus::Active,
      groups: Vec::new(),
      items: vec![
        text_item(now - Duration::days(31), "expired"),
        text_item(now, "current"),
      ],
      retention: ClipboardRetention::Month,
      source_app_visuals: Vec::new(),
    };
    store.persist(&state).unwrap();

    let mut manager = ready_manager();
    manager.items = state.items;
    manager.persistence = ClipboardPersistence::Encrypted(store);

    assert!(manager.prune_expired(now).unwrap());
    assert_eq!(manager.items.len(), 1);
    let persisted = ClipboardStore::new([9; 32], store_path.clone())
      .load()
      .unwrap()
      .unwrap();
    assert_eq!(persisted.items.len(), 1);
    assert_eq!(persisted.items[0].plain_text(), "current");

    std::fs::remove_file(store_path).unwrap();
  }

  fn editor_capture() -> ClipboardCapture {
    ClipboardCapture {
      copied_at: Utc::now(),
      html: None,
      plain_text: "clause".to_string(),
      rtf: None,
      source_app: Some(ClipboardSourceApp {
        identifier: Some("com.example.editor".to_string()),
        name: "Editor".to_string(),
      }),
      source_app_visual: Some(ClipboardSourceAppVisual {
        color: Some("#336699".to_string()),
        icon_data_url: Some("data:image/png;base64,QUJD".to_string()),
        key: "com.example.editor".to_string(),
      }),
    }
  }

  #[test]
  fn source_app_visuals_survive_a_restart() {
    let store_path = unique_store_path();
    let mut manager = ClipboardManager::new();
    manager.install(ClipboardLoad::Encrypted {
      store: ClipboardStore::new([9; 32], store_path.clone()),
      state: None,
    });
    assert!(manager.capture(editor_capture()).unwrap());

    let store = ClipboardStore::new([9; 32], store_path.clone());
    let state = store.load().unwrap().unwrap();
    let mut restarted = ClipboardManager::new();
    restarted.install(ClipboardLoad::Encrypted {
      store,
      state: Some(state),
    });

    let snapshot = restarted.snapshot();
    assert_eq!(snapshot.source_app_visuals.len(), 1);
    assert_eq!(snapshot.source_app_visuals[0].key, "com.example.editor");
    assert_eq!(
      snapshot.source_app_visuals[0].icon_data_url.as_deref(),
      Some("data:image/png;base64,QUJD")
    );

    std::fs::remove_file(store_path).unwrap();
  }

  #[test]
  fn unreferenced_source_app_visuals_are_not_persisted() {
    let store_path = unique_store_path();
    let mut manager = ClipboardManager::new();
    manager.install(ClipboardLoad::Encrypted {
      store: ClipboardStore::new([9; 32], store_path.clone()),
      state: None,
    });
    assert!(manager.capture(editor_capture()).unwrap());
    let id = manager.items[0].id().to_string();
    assert!(manager.delete_item(&id).unwrap());

    // The in-memory map is capped, so the stale entry must leave it too or it
    // would eventually block icons for new source apps.
    assert!(manager.source_app_visuals.is_empty());
    let persisted = ClipboardStore::new([9; 32], store_path.clone())
      .load()
      .unwrap()
      .unwrap();
    assert!(persisted.source_app_visuals.is_empty());

    std::fs::remove_file(store_path).unwrap();
  }

  #[test]
  fn install_drops_source_app_visuals_without_a_backing_item() {
    let mut manager = ClipboardManager::new();
    manager.install(ClipboardLoad::Encrypted {
      store: ClipboardStore::new([9; 32], unique_store_path()),
      state: Some(PersistedClipboardState {
        capture_status: ClipboardCaptureStatus::Active,
        groups: Vec::new(),
        items: Vec::new(),
        retention: ClipboardRetention::Month,
        source_app_visuals: vec![ClipboardSourceAppVisual {
          color: None,
          icon_data_url: Some("data:image/png;base64,QUJD".to_string()),
          key: "com.example.expired".to_string(),
        }],
      }),
    });

    assert!(manager.source_app_visuals.is_empty());
  }

  #[test]
  fn retention_choice_bounds_pruning_and_persists() {
    let store_path = unique_store_path();
    let now = Utc::now();
    let mut manager = ready_manager();
    manager.items = vec![
      text_item(now - Duration::days(200), "old"),
      text_item(now - Duration::days(20), "recent"),
      text_item(now, "current"),
    ];
    manager.persistence =
      ClipboardPersistence::Encrypted(ClipboardStore::new([9; 32], store_path.clone()));

    manager.set_retention(ClipboardRetention::Year).unwrap();
    assert_eq!(manager.items.len(), 3);
    assert!(!manager.prune_expired(now).unwrap());

    manager.set_retention(ClipboardRetention::Week).unwrap();
    assert_eq!(manager.items.len(), 1);
    assert_eq!(manager.items[0].plain_text(), "current");

    let persisted = ClipboardStore::new([9; 32], store_path.clone())
      .load()
      .unwrap()
      .unwrap();
    assert_eq!(persisted.retention, ClipboardRetention::Week);
    assert_eq!(persisted.items.len(), 1);

    std::fs::remove_file(store_path).unwrap();
  }

  #[test]
  fn frontend_retention_contract_matches_native_values() {
    let source = include_str!("../../src/clipboard/clipboard-types.ts");
    let list_prefix = "export const CLIPBOARD_RETENTIONS = ";
    let list_start = source
      .find(list_prefix)
      .unwrap_or_else(|| panic!("frontend contract has no retention list"));
    let list = &source[list_start + list_prefix.len()..];
    let list_end = list
      .find(" as const;")
      .unwrap_or_else(|| panic!("frontend retention list has no end"));
    let frontend_values = serde_json::from_str::<Vec<String>>(&list[..list_end])
      .unwrap_or_else(|error| panic!("frontend retention list is invalid: {error}"));
    let native_values = ClipboardRetention::ALL
      .iter()
      .map(|retention| {
        serde_json::to_value(retention)
          .unwrap()
          .as_str()
          .unwrap()
          .to_string()
      })
      .collect::<Vec<_>>();

    assert_eq!(frontend_values, native_values);
  }

  #[test]
  fn paused_capture_does_not_record_content() {
    let mut manager = ready_manager();
    manager
      .set_capture_status(ClipboardCaptureStatus::Paused)
      .unwrap();

    assert!(!capture(&mut manager, "ignored", None, Utc::now()));
    assert!(manager.items.is_empty());
  }

  #[test]
  fn clipboard_item_json_matches_the_frontend_contract() {
    let item = ClipboardItem::FormattedText {
      copied_at: Utc::now(),
      group_id: None,
      html: "<strong>formatted</strong>".to_string(),
      id: "item-id".to_string(),
      name: Some("Formatted note".to_string()),
      plain_text: "formatted".to_string(),
      rtf: None,
      source_app: Some(ClipboardSourceApp {
        identifier: Some("com.apple.TextEdit".to_string()),
        name: "TextEdit".to_string(),
      }),
    };

    let value = serde_json::to_value(item).unwrap();

    assert_eq!(value["type"], "formattedText");
    assert!(value.get("rtf").is_none());
    assert!(value.get("copiedAt").is_some());
    assert_eq!(value["plainText"], "formatted");
    assert_eq!(value["name"], "Formatted note");
    assert!(value.get("groupId").is_some());
    assert_eq!(value["sourceApp"]["identifier"], "com.apple.TextEdit");
    assert_eq!(value["sourceApp"]["name"], "TextEdit");
    assert!(value.get("copied_at").is_none());
    assert!(value.get("plain_text").is_none());
  }

  #[test]
  fn persisted_items_without_a_name_remain_readable() {
    let item = serde_json::from_value::<ClipboardItem>(serde_json::json!({
      "type": "text",
      "copiedAt": Utc::now(),
      "groupId": null,
      "id": "legacy-item",
      "plainText": "Legacy content",
      "sourceApp": null
    }))
    .unwrap();

    assert_eq!(item.name(), None);
  }

  #[test]
  fn deleting_a_group_preserves_its_items() {
    let mut manager = ready_manager();
    assert!(capture(&mut manager, "grouped", None, Utc::now()));
    let group_id = manager
      .create_group("Research", ClipboardGroupColor::Blue)
      .unwrap();
    let item_id = manager.items[0].id().to_string();
    assert!(
      manager
        .update_item(&item_id, "grouped", None, Some(group_id.clone()))
        .unwrap()
    );

    assert!(manager.delete_group(&group_id).unwrap());
    assert_eq!(manager.items.len(), 1);
    assert_eq!(manager.items[0].group_id(), None);
  }

  #[test]
  fn group_count_and_names_are_bounded() {
    let mut manager = ready_manager();
    for index in 0..MAX_GROUPS {
      manager
        .create_group(&format!("Group {index}"), ClipboardGroupColor::Gray)
        .unwrap();
    }

    assert!(
      manager
        .create_group("One too many", ClipboardGroupColor::Gray)
        .is_err()
    );

    let mut manager = ready_manager();
    assert!(
      manager
        .create_group(
          &"x".repeat(MAX_GROUP_NAME_CHARACTERS + 1),
          ClipboardGroupColor::Gray,
        )
        .is_err()
    );
  }

  #[test]
  fn group_name_limit_counts_unicode_characters() {
    let mut manager = ready_manager();
    let international_name = "界".repeat(MAX_GROUP_NAME_CHARACTERS);

    assert!(
      manager
        .create_group(&international_name, ClipboardGroupColor::Blue)
        .is_ok()
    );
    assert!(
      manager
        .create_group(
          &format!("{international_name}界"),
          ClipboardGroupColor::Blue,
        )
        .is_err()
    );
  }

  #[test]
  fn persisted_groups_without_a_color_default_to_gray() {
    let group: ClipboardGroup = serde_json::from_value(serde_json::json!({
      "id": "legacy-group",
      "name": "Legacy"
    }))
    .unwrap();

    assert_eq!(group.color, ClipboardGroupColor::Gray);
    assert_eq!(serde_json::to_value(group).unwrap()["color"], "gray");
  }

  #[test]
  fn recopying_grouped_content_keeps_its_group() {
    let now = Utc::now();
    let mut manager = ready_manager();
    assert!(capture(&mut manager, "grouped", None, now));
    let group_id = manager
      .create_group("Research", ClipboardGroupColor::Emerald)
      .unwrap();
    let item_id = manager.items[0].id().to_string();
    manager
      .update_item(&item_id, "grouped", None, Some(group_id.clone()))
      .unwrap();

    assert!(capture(&mut manager, "grouped", None, now));

    assert_eq!(manager.items[0].group_id(), Some(group_id.as_str()));
  }

  #[test]
  fn editing_formatted_text_produces_a_consistent_plain_text_item() {
    let mut manager = ready_manager();
    assert!(capture(
      &mut manager,
      "old",
      Some("<strong>old</strong>"),
      Utc::now(),
    ));
    let item_id = manager.items[0].id().to_string();

    assert!(manager.update_item(&item_id, "new", None, None).unwrap());
    assert!(matches!(manager.items[0], ClipboardItem::Text { .. }));
    assert_eq!(manager.items[0].plain_text(), "new");
  }

  #[test]
  fn editing_formatted_text_preserves_safe_formatting() {
    let mut manager = ready_manager();
    assert!(capture(&mut manager, "old", None, Utc::now()));
    let item_id = manager.items[0].id().to_string();

    assert!(
      manager
        .update_item(
          &item_id,
          "new",
          Some("<strong>new</strong><script>ignored()</script>"),
          None,
        )
        .unwrap()
    );

    let ClipboardItem::FormattedText { html, .. } = &manager.items[0] else {
      panic!("formatted edit should produce formatted clipboard content");
    };
    assert_eq!(html, "<strong>new</strong>");
  }

  #[test]
  fn captured_rtf_is_persisted_but_never_sent_to_the_webview() {
    let mut manager = ready_manager();
    assert!(capture_with_rtf(&mut manager, Some("<b>Clause</b>")));

    assert_eq!(manager.items[0].rtf(), Some(WORD_RTF));
    let persisted = serde_json::to_value(&manager.items[0]).unwrap();
    assert_eq!(persisted["rtf"], WORD_RTF);
    assert_eq!(manager.snapshot().items[0].rtf(), None);
    let item_id = manager.items[0].id().to_string();
    assert_eq!(manager.item(&item_id).unwrap().for_webview().rtf(), None);
  }

  #[test]
  fn rtf_is_dropped_without_formatting_worth_keeping() {
    let mut manager = ready_manager();
    assert!(capture_with_rtf(&mut manager, None));

    assert!(matches!(manager.items[0], ClipboardItem::Text { .. }));
  }

  #[test]
  fn editing_a_clip_drops_its_rtf_while_metadata_edits_keep_it() {
    let mut manager = ready_manager();
    assert!(capture_with_rtf(&mut manager, Some("<b>Clause</b>")));
    let item_id = manager.items[0].id().to_string();

    assert!(
      manager
        .update_item(&item_id, "Clause", Some("<b>Clause</b>"), None)
        .unwrap()
    );
    assert_eq!(manager.items[0].rtf(), Some(WORD_RTF));

    assert!(
      manager
        .update_item(&item_id, "Clause", Some("<b>Clause</b><i>!</i>"), None)
        .unwrap()
    );
    assert_eq!(manager.items[0].rtf(), None);
  }

  #[test]
  fn recapturing_the_same_content_refreshes_its_rtf() {
    let mut manager = ready_manager();
    assert!(capture(
      &mut manager,
      "Clause",
      Some("<b>Clause</b>"),
      Utc::now()
    ));
    assert_eq!(manager.items[0].rtf(), None);

    assert!(capture_with_rtf(&mut manager, Some("<b>Clause</b>")));
    assert_eq!(manager.items.len(), 1);
    assert_eq!(manager.items[0].rtf(), Some(WORD_RTF));
  }
}
