macro_rules! with_stella_commands {
  ($consumer:ident) => {
    $consumer! {
      commands::get_state => "get_state",
      commands::open_stella_account => "open_stella_account",
      commands::update_notification_preferences => "update_notification_preferences",
      commands::open_session_file => "open_session_file",
      commands::reveal_session => "reveal_session",
      commands::finish_session => "finish_session",
      commands::retry_session => "retry_session",
      commands::respond_to_takeover => "respond_to_takeover",
      commands::takeover_dialog_respond => "takeover_dialog_respond",
      commands::self_host_connect_dialog_respond => "self_host_connect_dialog_respond",
      commands::copy_diagnostics => "copy_diagnostics",
      commands::email_support => "email_support",
      commands::reveal_support_root => "reveal_support_root",
      commands::open_edit_root => "open_edit_root",
      commands::is_autostart_enabled => "is_autostart_enabled",
      commands::set_autostart => "set_autostart",
      clipboard_commands::clipboard_get_snapshot => "clipboard_get_snapshot",
      clipboard_commands::clipboard_complete_welcome => "clipboard_complete_welcome",
      clipboard_commands::clipboard_set_capture_status => "clipboard_set_capture_status",
      clipboard_commands::clipboard_set_retention => "clipboard_set_retention",
      clipboard_commands::clipboard_set_screen_capture => "clipboard_set_screen_capture",
      clipboard_commands::clipboard_delete_item => "clipboard_delete_item",
      clipboard_commands::clipboard_duplicate_item => "clipboard_duplicate_item",
      clipboard_commands::clipboard_clear_history => "clipboard_clear_history",
      clipboard_commands::clipboard_create_group => "clipboard_create_group",
      clipboard_commands::clipboard_delete_group => "clipboard_delete_group",
      clipboard_commands::clipboard_update_group => "clipboard_update_group",
      clipboard_commands::clipboard_update_item => "clipboard_update_item",
      clipboard_commands::clipboard_set_item_group => "clipboard_set_item_group",
      clipboard_commands::clipboard_set_item_name => "clipboard_set_item_name",
      clipboard_commands::clipboard_open_editor => "clipboard_open_editor",
      clipboard_commands::clipboard_get_editor_context => "clipboard_get_editor_context",
      clipboard_commands::clipboard_get_image_preview => "clipboard_get_image_preview",
      clipboard_commands::clipboard_save_editor_item => "clipboard_save_editor_item",
      clipboard_commands::clipboard_close_editor => "clipboard_close_editor",
      clipboard_commands::clipboard_copy_item => "clipboard_copy_item",
      clipboard_commands::clipboard_hide => "clipboard_hide",
      clipboard_commands::clipboard_show => "clipboard_show",
      clipboard_commands::clipboard_open_stella => "clipboard_open_stella",
      desktop_telemetry::desktop_report_error => "desktop_report_error",
      desktop_telemetry::desktop_report_timing => "desktop_report_timing",
    }
  };
}
