// Generated by bun run env:generate.
// parser-output-unchanged: example credential values; no parser output depends on them.
export const SECRET_EXAMPLES = {
  S3_SECRET_ACCESS_KEY: "stella-rustfs-dev-secret",
  GOOGLE_GENERATIVE_AI_API_KEY: "key-test",
  BETTER_AUTH_SECRET: "your-secret-at-least-32-chars-long",
  STELLA_COLLAB_SERVICE_TOKEN: "local-collab-service-token-at-least-32-chars",
  GOTENBERG_PASSWORD: "gotenberg",
} as const;
