// AUTO-GENERATED by packages/scripts/src/model-catalog-capabilities-gen.ts.
// Do not edit by hand: regenerate with
// `bun --filter @stll/ai-catalog gen:capabilities`.
//
// Sources: models.dev per-model `reasoning_options`, `temperature`,
// `modalities.input`, and release dates (first-party, openrouter, and
// amazon-bedrock catalogs);
// OpenRouter's public per-model `default_effort`; plus reviewed provider
// policies and dated entries from capabilities-overrides.ts and
// document-input-overrides.ts.
// The nightly `model-catalog-upstream` check fails CI on unsafe drift.
import type {
  BYOKModelIdByProvider,
  BYOKProvider,
  OfferedBYOKModelId,
  ReasoningEffort,
  TemperaturePolicy,
} from "./index";

/**
 * Offered models whose provider API accepts PDF/file content. Generated from
 * live input-modality metadata plus reviewed source corrections.
 */
export const MODEL_DOCUMENT_INPUT_OPTIONS = {
  google: [
    "gemini-3.7-flash",
    "gemini-3.6-flash",
    "gemini-3.5-flash-lite",
    "gemini-3.1-pro-preview",
    "gemini-3.5-flash",
    "gemini-3.1-flash-lite",
  ],
  openrouter: [
    "openai/gpt-5.6-luna",
    "openai/gpt-5.6-terra",
    "google/gemini-3.7-flash",
    "google/gemini-3.6-flash",
    "google/gemini-3.5-flash-lite",
    "google/gemini-3.1-pro-preview",
    "google/gemini-3.5-flash",
    "google/gemini-3.1-flash-lite",
    "anthropic/claude-sonnet-5",
    "anthropic/claude-opus-5",
    "anthropic/claude-opus-4.8",
    "anthropic/claude-sonnet-4.6",
    "openai/gpt-5.5",
    "openai/gpt-5.4-mini",
  ],
  openai: [
    "gpt-5.6",
    "gpt-5.6-terra",
    "gpt-5.6-luna",
    "gpt-5.5",
    "gpt-5.4",
    // override: 2026-08-20: OpenAI Responses accepts input_file PDF content for this vision-capable model; models.dev currently omits the pdf modality
    "gpt-5.4-mini",
    // override: 2026-08-20: OpenAI Responses accepts input_file PDF content for this vision-capable model; models.dev currently omits the pdf modality
    "gpt-5.4-nano",
    // override: 2026-08-20: OpenAI Responses accepts input_file PDF content for this vision-capable model; models.dev currently omits the pdf modality
    "gpt-5.2",
  ],
  anthropic: [
    "claude-sonnet-5",
    "claude-fable-5-1",
    "claude-fable-5",
    "claude-opus-5",
    "claude-opus-4-8",
    "claude-opus-4-7",
    "claude-sonnet-4-6",
    "claude-opus-4-6",
    "claude-haiku-4-5-20251001",
  ],
  bedrock: [
    "us.anthropic.claude-sonnet-4-5-20250929-v1:0",
    "us.anthropic.claude-haiku-4-5-20251001-v1:0",
    // override: 2026-08-20: AWS documents PDF input for Nova Pro through Bedrock Converse
    "us.amazon.nova-pro-v1:0",
    // override: 2026-08-20: AWS documents PDF input for Nova Lite through Bedrock Converse
    "us.amazon.nova-lite-v1:0",
  ],
  mistral: [],
} as const satisfies {
  [TProvider in BYOKProvider]: readonly BYOKModelIdByProvider[TProvider][];
};

/**
 * Reasoning-effort values each offered model accepts, `null` when the
 * model exposes no effort-style reasoning control. A missing `"none"`
 * means the model's reasoning cannot be disabled; consumers must go
 * through `resolveReasoningEffort`.
 */
export const MODEL_REASONING_EFFORTS = {
  "gemini-3.7-flash": ["low", "medium", "high"],
  "gemini-3.6-flash": ["minimal", "low", "medium", "high"],
  "gemini-3.5-flash-lite": ["minimal", "low", "medium", "high"],
  "gemini-3.1-pro-preview": ["low", "medium", "high"],
  "gemini-3.5-flash": ["minimal", "low", "medium", "high"],
  "gemini-3.1-flash-lite": ["minimal", "low", "medium", "high"],
  "openai/gpt-5.6-luna": ["none", "low", "medium", "high", "xhigh", "max"],
  "openai/gpt-5.6-terra": ["none", "low", "medium", "high", "xhigh", "max"],
  "google/gemini-3.7-flash": ["low", "medium", "high"],
  "google/gemini-3.6-flash": ["minimal", "low", "medium", "high"],
  "google/gemini-3.5-flash-lite": ["minimal", "low", "medium", "high"],
  "google/gemini-3.1-pro-preview": ["low", "medium", "high"],
  "google/gemini-3.5-flash": ["minimal", "low", "medium", "high"],
  "google/gemini-3.1-flash-lite": ["none", "minimal", "low", "medium", "high"],
  "anthropic/claude-sonnet-5": ["none", "low", "medium", "high", "xhigh", "max"],
  "anthropic/claude-opus-5": ["none", "low", "medium", "high", "xhigh", "max"],
  "anthropic/claude-opus-4.8": ["none", "low", "medium", "high", "xhigh", "max"],
  "anthropic/claude-sonnet-4.6": ["none", "low", "medium", "high", "max"],
  "openai/gpt-5.5": ["none", "low", "medium", "high", "xhigh"],
  "openai/gpt-5.4-mini": ["none", "low", "medium", "high", "xhigh"],
  "gpt-5.6": ["none", "low", "medium", "high", "xhigh", "max"],
  "gpt-5.6-terra": ["none", "low", "medium", "high", "xhigh", "max"],
  "gpt-5.6-luna": ["none", "low", "medium", "high", "xhigh", "max"],
  "gpt-5.5": ["none", "low", "medium", "high", "xhigh"],
  "gpt-5.4": ["none", "low", "medium", "high", "xhigh"],
  "gpt-5.4-mini": ["none", "low", "medium", "high", "xhigh"],
  "gpt-5.4-nano": ["none", "low", "medium", "high", "xhigh"],
  "gpt-5.2": ["none", "low", "medium", "high", "xhigh"],
  "claude-sonnet-5": ["none", "low", "medium", "high", "xhigh", "max"],
  "claude-fable-5-1": ["low", "medium", "high", "xhigh", "max"],
  "claude-fable-5": ["low", "medium", "high", "xhigh", "max"],
  "claude-opus-5": ["low", "medium", "high", "xhigh", "max"],
  "claude-opus-4-8": ["low", "medium", "high", "xhigh", "max"],
  "claude-opus-4-7": ["low", "medium", "high", "xhigh", "max"],
  "claude-sonnet-4-6": ["low", "medium", "high", "max"],
  "claude-opus-4-6": ["low", "medium", "high", "max"],
  "claude-haiku-4-5-20251001": null,
  "us.anthropic.claude-sonnet-4-5-20250929-v1:0": null,
  "us.anthropic.claude-haiku-4-5-20251001-v1:0": null,
  // override: 2026-07-20: absent from the models.dev amazon-bedrock catalog; Bedrock Converse accepts temperature and Nova has no reasoning dial
  "us.amazon.nova-pro-v1:0": null,
  // override: 2026-07-20: absent from the models.dev amazon-bedrock catalog; Bedrock Converse accepts temperature and Nova has no reasoning dial
  "us.amazon.nova-lite-v1:0": null,
  // override: 2026-07-20: absent from the models.dev amazon-bedrock catalog; Bedrock Converse accepts temperature and Nova has no reasoning dial
  "us.amazon.nova-micro-v1:0": null,
  "openai.gpt-oss-120b-1:0": ["low", "medium", "high"],
  "openai.gpt-oss-20b-1:0": ["low", "medium", "high"],
  "us.deepseek.r1-v1:0": null,
  "mistral-large-latest": null,
  "mistral-medium-latest": ["none", "high"],
  "mistral-small-latest": ["none", "high"],
  "magistral-medium-latest": null,
  "magistral-small": null,
  "pixtral-large-latest": null,
} as const satisfies Record<
  OfferedBYOKModelId,
  readonly ReasoningEffort[] | null
>;

/**
 * Concrete provider-default effort where the upstream catalogue publishes
 * one. OpenRouter is the source today; null means the provider does not expose
 * a truthful named default, so clients must retain a separate Default choice.
 */
export const MODEL_DEFAULT_REASONING_EFFORTS = {
  "gemini-3.7-flash": null,
  "gemini-3.6-flash": null,
  "gemini-3.5-flash-lite": null,
  "gemini-3.1-pro-preview": null,
  "gemini-3.5-flash": null,
  "gemini-3.1-flash-lite": null,
  "openai/gpt-5.6-luna": "medium",
  "openai/gpt-5.6-terra": "medium",
  "google/gemini-3.7-flash": "medium",
  "google/gemini-3.6-flash": "medium",
  "google/gemini-3.5-flash-lite": "minimal",
  "google/gemini-3.1-pro-preview": "medium",
  "google/gemini-3.5-flash": "medium",
  "google/gemini-3.1-flash-lite": "minimal",
  "anthropic/claude-sonnet-5": "high",
  "anthropic/claude-opus-5": "high",
  "anthropic/claude-opus-4.8": "high",
  "anthropic/claude-sonnet-4.6": "medium",
  "openai/gpt-5.5": "medium",
  "openai/gpt-5.4-mini": "medium",
  "gpt-5.6": null,
  "gpt-5.6-terra": null,
  "gpt-5.6-luna": null,
  "gpt-5.5": null,
  "gpt-5.4": null,
  "gpt-5.4-mini": null,
  "gpt-5.4-nano": null,
  "gpt-5.2": null,
  "claude-sonnet-5": null,
  "claude-fable-5-1": null,
  "claude-fable-5": null,
  "claude-opus-5": null,
  "claude-opus-4-8": null,
  "claude-opus-4-7": null,
  "claude-sonnet-4-6": null,
  "claude-opus-4-6": null,
  "claude-haiku-4-5-20251001": null,
  "us.anthropic.claude-sonnet-4-5-20250929-v1:0": null,
  "us.anthropic.claude-haiku-4-5-20251001-v1:0": null,
  "us.amazon.nova-pro-v1:0": null,
  "us.amazon.nova-lite-v1:0": null,
  "us.amazon.nova-micro-v1:0": null,
  "openai.gpt-oss-120b-1:0": null,
  "openai.gpt-oss-20b-1:0": null,
  "us.deepseek.r1-v1:0": null,
  "mistral-large-latest": null,
  "mistral-medium-latest": null,
  "mistral-small-latest": null,
  "magistral-medium-latest": null,
  "magistral-small": null,
  "pixtral-large-latest": null,
} as const satisfies Record<
  OfferedBYOKModelId,
  ReasoningEffort | null
>;

/**
 * Whether stella should emit a `temperature` sampling override.
 * `"omit"` covers rejected, deprecated, and accepted-but-ignored
 * parameters. Consumers must go through `shouldEmitTemperature`.
 */
export const MODEL_TEMPERATURE_POLICIES = {
  "gemini-3.7-flash": "omit",
  "gemini-3.6-flash": "omit",
  "gemini-3.5-flash-lite": "omit",
  "gemini-3.1-pro-preview": "emit",
  "gemini-3.5-flash": "emit",
  "gemini-3.1-flash-lite": "emit",
  "openai/gpt-5.6-luna": "omit",
  "openai/gpt-5.6-terra": "omit",
  "google/gemini-3.7-flash": "omit",
  "google/gemini-3.6-flash": "omit",
  "google/gemini-3.5-flash-lite": "omit",
  "google/gemini-3.1-pro-preview": "emit",
  "google/gemini-3.5-flash": "emit",
  "google/gemini-3.1-flash-lite": "emit",
  "anthropic/claude-sonnet-5": "omit",
  "anthropic/claude-opus-5": "emit",
  "anthropic/claude-opus-4.8": "emit",
  "anthropic/claude-sonnet-4.6": "emit",
  "openai/gpt-5.5": "omit",
  "openai/gpt-5.4-mini": "omit",
  "gpt-5.6": "omit",
  "gpt-5.6-terra": "omit",
  "gpt-5.6-luna": "omit",
  "gpt-5.5": "omit",
  "gpt-5.4": "emit",
  "gpt-5.4-mini": "emit",
  "gpt-5.4-nano": "emit",
  "gpt-5.2": "emit",
  "claude-sonnet-5": "omit",
  "claude-fable-5-1": "omit",
  "claude-fable-5": "omit",
  "claude-opus-5": "omit",
  "claude-opus-4-8": "omit",
  "claude-opus-4-7": "omit",
  "claude-sonnet-4-6": "emit",
  "claude-opus-4-6": "emit",
  "claude-haiku-4-5-20251001": "emit",
  "us.anthropic.claude-sonnet-4-5-20250929-v1:0": "emit",
  "us.anthropic.claude-haiku-4-5-20251001-v1:0": "emit",
  "us.amazon.nova-pro-v1:0": "emit",
  "us.amazon.nova-lite-v1:0": "emit",
  "us.amazon.nova-micro-v1:0": "emit",
  "openai.gpt-oss-120b-1:0": "emit",
  "openai.gpt-oss-20b-1:0": "emit",
  "us.deepseek.r1-v1:0": "emit",
  "mistral-large-latest": "emit",
  "mistral-medium-latest": "emit",
  "mistral-small-latest": "emit",
  "magistral-medium-latest": "emit",
  "magistral-small": "emit",
  "pixtral-large-latest": "emit",
} as const satisfies Record<OfferedBYOKModelId, TemperaturePolicy>;
