-- requires: 20261005120300_list_verification_access_revoked
-- requires: 20261005120400_verification_read_receipts
-- requires: 20261007090100_validate_case_law_citation_review_provenance
SET lock_timeout = '1s';--> statement-breakpoint
SET statement_timeout = '10s';--> statement-breakpoint
CREATE POLICY "workspace_entity_feature" ON "public"."anonymization_allowlist_entries" AS RESTRICTIVE FOR ALL TO "stella" USING ((CASE WHEN "anonymization_allowlist_entries"."entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "anonymization_allowlist_entries"."entity_id") END)) WITH CHECK ((CASE WHEN "anonymization_allowlist_entries"."entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "anonymization_allowlist_entries"."entity_id") END));
--> statement-breakpoint
CREATE POLICY "workspace_entity_feature" ON "public"."cell_metadata" AS RESTRICTIVE FOR ALL TO "stella" USING ((CASE WHEN "cell_metadata"."entity_version_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entity_versions v WHERE v.id = "cell_metadata"."entity_version_id") END)) WITH CHECK ((CASE WHEN "cell_metadata"."entity_version_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entity_versions v WHERE v.id = "cell_metadata"."entity_version_id") END));
--> statement-breakpoint
CREATE POLICY "workspace_entity_feature" ON "public"."correspondence" AS RESTRICTIVE FOR ALL TO "stella" USING ((CASE WHEN "correspondence"."source_entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "correspondence"."source_entity_id") END)) WITH CHECK ((CASE WHEN "correspondence"."source_entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "correspondence"."source_entity_id") END));
--> statement-breakpoint
CREATE POLICY "workspace_entity_feature" ON "public"."correspondence_attachments" AS RESTRICTIVE FOR ALL TO "stella" USING ((CASE WHEN "correspondence_attachments"."entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "correspondence_attachments"."entity_id") END) AND (CASE WHEN "correspondence_attachments"."correspondence_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM "public"."correspondence" parent_row WHERE parent_row.id = "correspondence_attachments"."correspondence_id") END)) WITH CHECK ((CASE WHEN "correspondence_attachments"."entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "correspondence_attachments"."entity_id") END) AND (CASE WHEN "correspondence_attachments"."correspondence_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM "public"."correspondence" parent_row WHERE parent_row.id = "correspondence_attachments"."correspondence_id") END));
--> statement-breakpoint
CREATE POLICY "workspace_entity_feature" ON "public"."correspondence_filers" AS RESTRICTIVE FOR ALL TO "stella" USING ((CASE WHEN "correspondence_filers"."correspondence_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM "public"."correspondence" parent_row WHERE parent_row.id = "correspondence_filers"."correspondence_id") END)) WITH CHECK ((CASE WHEN "correspondence_filers"."correspondence_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM "public"."correspondence" parent_row WHERE parent_row.id = "correspondence_filers"."correspondence_id") END));
--> statement-breakpoint
CREATE POLICY "workspace_entity_feature" ON "public"."desktop_edit_handoffs" AS RESTRICTIVE FOR ALL TO "stella" USING ((CASE WHEN "desktop_edit_handoffs"."entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "desktop_edit_handoffs"."entity_id") END) AND (CASE WHEN "desktop_edit_handoffs"."desktop_session_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM "public"."desktop_edit_sessions" parent_row WHERE parent_row.id = "desktop_edit_handoffs"."desktop_session_id") END)) WITH CHECK ((CASE WHEN "desktop_edit_handoffs"."entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "desktop_edit_handoffs"."entity_id") END) AND (CASE WHEN "desktop_edit_handoffs"."desktop_session_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM "public"."desktop_edit_sessions" parent_row WHERE parent_row.id = "desktop_edit_handoffs"."desktop_session_id") END));
--> statement-breakpoint
CREATE POLICY "workspace_entity_feature" ON "public"."desktop_edit_sessions" AS RESTRICTIVE FOR ALL TO "stella" USING ((CASE WHEN "desktop_edit_sessions"."base_version_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entity_versions v WHERE v.id = "desktop_edit_sessions"."base_version_id") END) AND (CASE WHEN "desktop_edit_sessions"."finalized_version_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entity_versions v WHERE v.id = "desktop_edit_sessions"."finalized_version_id") END) AND (CASE WHEN "desktop_edit_sessions"."entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "desktop_edit_sessions"."entity_id") END)) WITH CHECK ((CASE WHEN "desktop_edit_sessions"."base_version_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entity_versions v WHERE v.id = "desktop_edit_sessions"."base_version_id") END) AND (CASE WHEN "desktop_edit_sessions"."finalized_version_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entity_versions v WHERE v.id = "desktop_edit_sessions"."finalized_version_id") END) AND (CASE WHEN "desktop_edit_sessions"."entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "desktop_edit_sessions"."entity_id") END));
--> statement-breakpoint
CREATE POLICY "workspace_entity_feature" ON "public"."document_processing_runs" AS RESTRICTIVE FOR ALL TO "stella" USING ((CASE WHEN "document_processing_runs"."entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "document_processing_runs"."entity_id") END) AND (CASE WHEN "document_processing_runs"."entity_version_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entity_versions v WHERE v.id = "document_processing_runs"."entity_version_id") END) AND (CASE WHEN "document_processing_runs"."field_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.fields f WHERE f.id = "document_processing_runs"."field_id") END)) WITH CHECK ((CASE WHEN "document_processing_runs"."entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "document_processing_runs"."entity_id") END) AND (CASE WHEN "document_processing_runs"."entity_version_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entity_versions v WHERE v.id = "document_processing_runs"."entity_version_id") END) AND (CASE WHEN "document_processing_runs"."field_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.fields f WHERE f.id = "document_processing_runs"."field_id") END));
--> statement-breakpoint
CREATE POLICY "workspace_entity_feature" ON "public"."document_review_parties" AS RESTRICTIVE FOR ALL TO "stella" USING ((CASE WHEN "document_review_parties"."entity_version_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entity_versions v WHERE v.id = "document_review_parties"."entity_version_id") END) AND (CASE WHEN "document_review_parties"."entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "document_review_parties"."entity_id") END)) WITH CHECK ((CASE WHEN "document_review_parties"."entity_version_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entity_versions v WHERE v.id = "document_review_parties"."entity_version_id") END) AND (CASE WHEN "document_review_parties"."entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "document_review_parties"."entity_id") END));
--> statement-breakpoint
CREATE POLICY "workspace_entity_feature" ON "public"."document_review_reference_passages" AS RESTRICTIVE FOR ALL TO "stella" USING ((CASE WHEN "document_review_reference_passages"."entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "document_review_reference_passages"."entity_id") END)) WITH CHECK ((CASE WHEN "document_review_reference_passages"."entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "document_review_reference_passages"."entity_id") END));
--> statement-breakpoint
CREATE POLICY "workspace_entity_feature" ON "public"."document_translation_runs" AS RESTRICTIVE FOR ALL TO "stella" USING ((CASE WHEN "document_translation_runs"."entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "document_translation_runs"."entity_id") END)) WITH CHECK ((CASE WHEN "document_translation_runs"."entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "document_translation_runs"."entity_id") END));
--> statement-breakpoint
CREATE POLICY "workspace_entity_feature" ON "public"."document_translation_units" AS RESTRICTIVE FOR ALL TO "stella" USING ((CASE WHEN "document_translation_units"."run_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM "public"."document_translation_runs" parent_row WHERE parent_row.id = "document_translation_units"."run_id") END)) WITH CHECK ((CASE WHEN "document_translation_units"."run_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM "public"."document_translation_runs" parent_row WHERE parent_row.id = "document_translation_units"."run_id") END));
--> statement-breakpoint
CREATE POLICY "workspace_entity_feature" ON "public"."docx_suggestions" AS RESTRICTIVE FOR ALL TO "stella" USING ((CASE WHEN "docx_suggestions"."entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "docx_suggestions"."entity_id") END)) WITH CHECK ((CASE WHEN "docx_suggestions"."entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "docx_suggestions"."entity_id") END));
--> statement-breakpoint
CREATE POLICY "workspace_entity_feature" ON "public"."entities" AS RESTRICTIVE FOR ALL TO "stella" USING (("entities"."list_item_type" IS NULL OR "entities"."list_item_type" = 'task' OR coalesce(nullif(current_setting('app.enabled_features', true), ''), '[]')::jsonb ? 'legal-lists')) WITH CHECK (("entities"."list_item_type" IS NULL OR "entities"."list_item_type" = 'task' OR coalesce(nullif(current_setting('app.enabled_features', true), ''), '[]')::jsonb ? 'legal-lists'));
--> statement-breakpoint
CREATE POLICY "workspace_entity_feature" ON "public"."entity_links" AS RESTRICTIVE FOR ALL TO "stella" USING ((CASE WHEN "entity_links"."source_entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "entity_links"."source_entity_id") END) AND (CASE WHEN "entity_links"."target_entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "entity_links"."target_entity_id") END)) WITH CHECK ((CASE WHEN "entity_links"."source_entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "entity_links"."source_entity_id") END) AND (CASE WHEN "entity_links"."target_entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "entity_links"."target_entity_id") END));
--> statement-breakpoint
CREATE POLICY "workspace_entity_feature" ON "public"."entity_version_ai_summaries" AS RESTRICTIVE FOR ALL TO "stella" USING ((CASE WHEN "entity_version_ai_summaries"."entity_version_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entity_versions v WHERE v.id = "entity_version_ai_summaries"."entity_version_id") END) AND (CASE WHEN "entity_version_ai_summaries"."entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "entity_version_ai_summaries"."entity_id") END)) WITH CHECK ((CASE WHEN "entity_version_ai_summaries"."entity_version_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entity_versions v WHERE v.id = "entity_version_ai_summaries"."entity_version_id") END) AND (CASE WHEN "entity_version_ai_summaries"."entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "entity_version_ai_summaries"."entity_id") END));
--> statement-breakpoint
CREATE POLICY "workspace_entity_feature" ON "public"."entity_versions" AS RESTRICTIVE FOR ALL TO "stella" USING ((CASE WHEN "entity_versions"."entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "entity_versions"."entity_id") END)) WITH CHECK ((CASE WHEN "entity_versions"."entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "entity_versions"."entity_id") END));
--> statement-breakpoint
CREATE POLICY "workspace_entity_feature" ON "public"."extracted_content" AS RESTRICTIVE FOR ALL TO "stella" USING ((CASE WHEN "extracted_content"."source_entity_version_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entity_versions v WHERE v.id = "extracted_content"."source_entity_version_id") END) AND (CASE WHEN "extracted_content"."source_field_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.fields f WHERE f.id = "extracted_content"."source_field_id") END) AND (CASE WHEN "extracted_content"."entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "extracted_content"."entity_id") END)) WITH CHECK ((CASE WHEN "extracted_content"."source_entity_version_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entity_versions v WHERE v.id = "extracted_content"."source_entity_version_id") END) AND (CASE WHEN "extracted_content"."source_field_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.fields f WHERE f.id = "extracted_content"."source_field_id") END) AND (CASE WHEN "extracted_content"."entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "extracted_content"."entity_id") END));
--> statement-breakpoint
CREATE POLICY "workspace_entity_feature" ON "public"."fields" AS RESTRICTIVE FOR ALL TO "stella" USING ((CASE WHEN "fields"."entity_version_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entity_versions v WHERE v.id = "fields"."entity_version_id") END)) WITH CHECK ((CASE WHEN "fields"."entity_version_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entity_versions v WHERE v.id = "fields"."entity_version_id") END));
--> statement-breakpoint
CREATE POLICY "workspace_entity_feature" ON "public"."file_chat_threads" AS RESTRICTIVE FOR ALL TO "stella" USING ((CASE WHEN "file_chat_threads"."entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "file_chat_threads"."entity_id") END) AND (CASE WHEN "file_chat_threads"."field_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.fields f WHERE f.id = "file_chat_threads"."field_id") END)) WITH CHECK ((CASE WHEN "file_chat_threads"."entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "file_chat_threads"."entity_id") END) AND (CASE WHEN "file_chat_threads"."field_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.fields f WHERE f.id = "file_chat_threads"."field_id") END));
--> statement-breakpoint
CREATE POLICY "workspace_entity_feature" ON "public"."flow_run_steps" AS RESTRICTIVE FOR ALL TO "stella" USING ((CASE WHEN "flow_run_steps"."review_task_entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "flow_run_steps"."review_task_entity_id") END)) WITH CHECK ((CASE WHEN "flow_run_steps"."review_task_entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "flow_run_steps"."review_task_entity_id") END));
--> statement-breakpoint
CREATE POLICY "workspace_entity_feature" ON "public"."folio_collab_contributions" AS RESTRICTIVE FOR ALL TO "stella" USING ((CASE WHEN "folio_collab_contributions"."entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "folio_collab_contributions"."entity_id") END) AND (CASE WHEN "folio_collab_contributions"."since_version_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entity_versions v WHERE v.id = "folio_collab_contributions"."since_version_id") END) AND (CASE WHEN "folio_collab_contributions"."room_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM "public"."folio_collab_rooms" parent_row WHERE parent_row.id = "folio_collab_contributions"."room_id") END)) WITH CHECK ((CASE WHEN "folio_collab_contributions"."entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "folio_collab_contributions"."entity_id") END) AND (CASE WHEN "folio_collab_contributions"."since_version_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entity_versions v WHERE v.id = "folio_collab_contributions"."since_version_id") END) AND (CASE WHEN "folio_collab_contributions"."room_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM "public"."folio_collab_rooms" parent_row WHERE parent_row.id = "folio_collab_contributions"."room_id") END));
--> statement-breakpoint
CREATE POLICY "workspace_entity_feature" ON "public"."folio_collab_publications" AS RESTRICTIVE FOR ALL TO "stella" USING ((CASE WHEN "folio_collab_publications"."entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "folio_collab_publications"."entity_id") END) AND (CASE WHEN "folio_collab_publications"."entity_version_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entity_versions v WHERE v.id = "folio_collab_publications"."entity_version_id") END) AND (CASE WHEN "folio_collab_publications"."room_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM "public"."folio_collab_rooms" parent_row WHERE parent_row.id = "folio_collab_publications"."room_id") END)) WITH CHECK ((CASE WHEN "folio_collab_publications"."entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "folio_collab_publications"."entity_id") END) AND (CASE WHEN "folio_collab_publications"."entity_version_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entity_versions v WHERE v.id = "folio_collab_publications"."entity_version_id") END) AND (CASE WHEN "folio_collab_publications"."room_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM "public"."folio_collab_rooms" parent_row WHERE parent_row.id = "folio_collab_publications"."room_id") END));
--> statement-breakpoint
CREATE POLICY "workspace_entity_feature" ON "public"."folio_collab_room_tokens" AS RESTRICTIVE FOR ALL TO "stella" USING ((CASE WHEN "folio_collab_room_tokens"."room_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM "public"."folio_collab_rooms" parent_row WHERE parent_row.id = "folio_collab_room_tokens"."room_id") END)) WITH CHECK ((CASE WHEN "folio_collab_room_tokens"."room_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM "public"."folio_collab_rooms" parent_row WHERE parent_row.id = "folio_collab_room_tokens"."room_id") END));
--> statement-breakpoint
CREATE POLICY "workspace_entity_feature" ON "public"."folio_collab_rooms" AS RESTRICTIVE FOR ALL TO "stella" USING ((CASE WHEN "folio_collab_rooms"."entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "folio_collab_rooms"."entity_id") END) AND (CASE WHEN "folio_collab_rooms"."base_version_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entity_versions v WHERE v.id = "folio_collab_rooms"."base_version_id") END) AND (CASE WHEN "folio_collab_rooms"."source_version_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entity_versions v WHERE v.id = "folio_collab_rooms"."source_version_id") END)) WITH CHECK ((CASE WHEN "folio_collab_rooms"."entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "folio_collab_rooms"."entity_id") END) AND (CASE WHEN "folio_collab_rooms"."base_version_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entity_versions v WHERE v.id = "folio_collab_rooms"."base_version_id") END) AND (CASE WHEN "folio_collab_rooms"."source_version_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entity_versions v WHERE v.id = "folio_collab_rooms"."source_version_id") END));
--> statement-breakpoint
CREATE POLICY "workspace_entity_feature" ON "public"."justifications" AS RESTRICTIVE FOR ALL TO "stella" USING ((CASE WHEN "justifications"."field_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.fields f WHERE f.id = "justifications"."field_id") END)) WITH CHECK ((CASE WHEN "justifications"."field_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.fields f WHERE f.id = "justifications"."field_id") END));
--> statement-breakpoint
CREATE POLICY "workspace_entity_feature" ON "public"."legal_list_claim_review_events" AS RESTRICTIVE FOR ALL TO "stella" USING ((CASE WHEN "legal_list_claim_review_events"."claim_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM "public"."legal_list_claims" parent_row WHERE parent_row.id = "legal_list_claim_review_events"."claim_id") END)) WITH CHECK ((CASE WHEN "legal_list_claim_review_events"."claim_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM "public"."legal_list_claims" parent_row WHERE parent_row.id = "legal_list_claim_review_events"."claim_id") END));
--> statement-breakpoint
CREATE POLICY "workspace_entity_feature" ON "public"."legal_list_claims" AS RESTRICTIVE FOR ALL TO "stella" USING ((CASE WHEN "legal_list_claims"."run_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM "public"."legal_list_verification_runs" parent_row WHERE parent_row.id = "legal_list_claims"."run_id") END)) WITH CHECK ((CASE WHEN "legal_list_claims"."run_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM "public"."legal_list_verification_runs" parent_row WHERE parent_row.id = "legal_list_claims"."run_id") END));
--> statement-breakpoint
CREATE POLICY "workspace_entity_feature" ON "public"."legal_list_fact_details" AS RESTRICTIVE FOR ALL TO "stella" USING ((CASE WHEN "legal_list_fact_details"."item_entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "legal_list_fact_details"."item_entity_id") END)) WITH CHECK ((CASE WHEN "legal_list_fact_details"."item_entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "legal_list_fact_details"."item_entity_id") END));
--> statement-breakpoint
CREATE POLICY "workspace_entity_feature" ON "public"."legal_list_generation_candidate_sources" AS RESTRICTIVE FOR ALL TO "stella" USING ((CASE WHEN "legal_list_generation_candidate_sources"."source_entity_version_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entity_versions v WHERE v.id = "legal_list_generation_candidate_sources"."source_entity_version_id") END) AND (CASE WHEN "legal_list_generation_candidate_sources"."source_entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "legal_list_generation_candidate_sources"."source_entity_id") END) AND (CASE WHEN "legal_list_generation_candidate_sources"."candidate_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM "public"."legal_list_generation_candidates" parent_row WHERE parent_row.id = "legal_list_generation_candidate_sources"."candidate_id") END)) WITH CHECK ((CASE WHEN "legal_list_generation_candidate_sources"."source_entity_version_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entity_versions v WHERE v.id = "legal_list_generation_candidate_sources"."source_entity_version_id") END) AND (CASE WHEN "legal_list_generation_candidate_sources"."source_entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "legal_list_generation_candidate_sources"."source_entity_id") END) AND (CASE WHEN "legal_list_generation_candidate_sources"."candidate_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM "public"."legal_list_generation_candidates" parent_row WHERE parent_row.id = "legal_list_generation_candidate_sources"."candidate_id") END));
--> statement-breakpoint
CREATE POLICY "workspace_entity_feature" ON "public"."legal_list_generation_candidates" AS RESTRICTIVE FOR ALL TO "stella" USING ((CASE WHEN "legal_list_generation_candidates"."accepted_entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "legal_list_generation_candidates"."accepted_entity_id") END)) WITH CHECK ((CASE WHEN "legal_list_generation_candidates"."accepted_entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "legal_list_generation_candidates"."accepted_entity_id") END));
--> statement-breakpoint
CREATE POLICY "workspace_entity_feature" ON "public"."legal_list_generation_sources" AS RESTRICTIVE FOR ALL TO "stella" USING ((CASE WHEN "legal_list_generation_sources"."source_entity_version_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entity_versions v WHERE v.id = "legal_list_generation_sources"."source_entity_version_id") END) AND (CASE WHEN "legal_list_generation_sources"."source_entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "legal_list_generation_sources"."source_entity_id") END)) WITH CHECK ((CASE WHEN "legal_list_generation_sources"."source_entity_version_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entity_versions v WHERE v.id = "legal_list_generation_sources"."source_entity_version_id") END) AND (CASE WHEN "legal_list_generation_sources"."source_entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "legal_list_generation_sources"."source_entity_id") END));
--> statement-breakpoint
CREATE POLICY "workspace_entity_feature" ON "public"."legal_list_item_comments" AS RESTRICTIVE FOR ALL TO "stella" USING ((CASE WHEN "legal_list_item_comments"."item_entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "legal_list_item_comments"."item_entity_id") END)) WITH CHECK ((CASE WHEN "legal_list_item_comments"."item_entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "legal_list_item_comments"."item_entity_id") END));
--> statement-breakpoint
CREATE POLICY "workspace_entity_feature" ON "public"."legal_list_item_reviews" AS RESTRICTIVE FOR ALL TO "stella" USING ((CASE WHEN "legal_list_item_reviews"."item_entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "legal_list_item_reviews"."item_entity_id") END)) WITH CHECK ((CASE WHEN "legal_list_item_reviews"."item_entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "legal_list_item_reviews"."item_entity_id") END));
--> statement-breakpoint
CREATE POLICY "workspace_entity_feature" ON "public"."legal_list_item_sources" AS RESTRICTIVE FOR ALL TO "stella" USING ((CASE WHEN "legal_list_item_sources"."item_entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "legal_list_item_sources"."item_entity_id") END) AND (CASE WHEN "legal_list_item_sources"."source_entity_version_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entity_versions v WHERE v.id = "legal_list_item_sources"."source_entity_version_id") END) AND (CASE WHEN "legal_list_item_sources"."source_entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "legal_list_item_sources"."source_entity_id") END)) WITH CHECK ((CASE WHEN "legal_list_item_sources"."item_entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "legal_list_item_sources"."item_entity_id") END) AND (CASE WHEN "legal_list_item_sources"."source_entity_version_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entity_versions v WHERE v.id = "legal_list_item_sources"."source_entity_version_id") END) AND (CASE WHEN "legal_list_item_sources"."source_entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "legal_list_item_sources"."source_entity_id") END));
--> statement-breakpoint
CREATE POLICY "workspace_entity_feature" ON "public"."legal_list_items" AS RESTRICTIVE FOR ALL TO "stella" USING ((CASE WHEN "legal_list_items"."entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "legal_list_items"."entity_id") END)) WITH CHECK ((CASE WHEN "legal_list_items"."entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "legal_list_items"."entity_id") END));
--> statement-breakpoint
CREATE POLICY "workspace_entity_feature" ON "public"."legal_list_verification_blocks" AS RESTRICTIVE FOR ALL TO "stella" USING ((CASE WHEN "legal_list_verification_blocks"."run_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM "public"."legal_list_verification_runs" parent_row WHERE parent_row.id = "legal_list_verification_blocks"."run_id") END)) WITH CHECK ((CASE WHEN "legal_list_verification_blocks"."run_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM "public"."legal_list_verification_runs" parent_row WHERE parent_row.id = "legal_list_verification_blocks"."run_id") END));
--> statement-breakpoint
CREATE POLICY "workspace_entity_feature" ON "public"."legal_list_verification_read_receipts" AS RESTRICTIVE FOR ALL TO "stella" USING ((CASE WHEN "legal_list_verification_read_receipts"."run_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM "public"."legal_list_verification_runs" parent_row WHERE parent_row.id = "legal_list_verification_read_receipts"."run_id") END)) WITH CHECK ((CASE WHEN "legal_list_verification_read_receipts"."run_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM "public"."legal_list_verification_runs" parent_row WHERE parent_row.id = "legal_list_verification_read_receipts"."run_id") END));
--> statement-breakpoint
CREATE POLICY "workspace_entity_feature" ON "public"."legal_list_verification_runs" AS RESTRICTIVE FOR ALL TO "stella" USING ((CASE WHEN "legal_list_verification_runs"."entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "legal_list_verification_runs"."entity_id") END)) WITH CHECK ((CASE WHEN "legal_list_verification_runs"."entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "legal_list_verification_runs"."entity_id") END));
--> statement-breakpoint
CREATE POLICY "workspace_entity_feature" ON "public"."office_file_evidence" AS RESTRICTIVE FOR ALL TO "stella" USING ((CASE WHEN "office_file_evidence"."entity_version_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entity_versions v WHERE v.id = "office_file_evidence"."entity_version_id") END) AND (CASE WHEN "office_file_evidence"."entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "office_file_evidence"."entity_id") END) AND (CASE WHEN "office_file_evidence"."field_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.fields f WHERE f.id = "office_file_evidence"."field_id") END)) WITH CHECK ((CASE WHEN "office_file_evidence"."entity_version_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entity_versions v WHERE v.id = "office_file_evidence"."entity_version_id") END) AND (CASE WHEN "office_file_evidence"."entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "office_file_evidence"."entity_id") END) AND (CASE WHEN "office_file_evidence"."field_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.fields f WHERE f.id = "office_file_evidence"."field_id") END));
--> statement-breakpoint
CREATE POLICY "workspace_entity_feature" ON "public"."pdf_signing_sessions" AS RESTRICTIVE FOR ALL TO "stella" USING ((CASE WHEN "pdf_signing_sessions"."base_version_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entity_versions v WHERE v.id = "pdf_signing_sessions"."base_version_id") END) AND (CASE WHEN "pdf_signing_sessions"."entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "pdf_signing_sessions"."entity_id") END) AND (CASE WHEN "pdf_signing_sessions"."finalized_version_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entity_versions v WHERE v.id = "pdf_signing_sessions"."finalized_version_id") END)) WITH CHECK ((CASE WHEN "pdf_signing_sessions"."base_version_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entity_versions v WHERE v.id = "pdf_signing_sessions"."base_version_id") END) AND (CASE WHEN "pdf_signing_sessions"."entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "pdf_signing_sessions"."entity_id") END) AND (CASE WHEN "pdf_signing_sessions"."finalized_version_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entity_versions v WHERE v.id = "pdf_signing_sessions"."finalized_version_id") END));
--> statement-breakpoint
CREATE POLICY "workspace_entity_feature" ON "public"."report_exports" AS RESTRICTIVE FOR ALL TO "stella" USING ((CASE WHEN "report_exports"."result_entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "report_exports"."result_entity_id") END) AND (CASE WHEN "report_exports"."result_field_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.fields f WHERE f.id = "report_exports"."result_field_id") END)) WITH CHECK ((CASE WHEN "report_exports"."result_entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "report_exports"."result_entity_id") END) AND (CASE WHEN "report_exports"."result_field_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.fields f WHERE f.id = "report_exports"."result_field_id") END));
--> statement-breakpoint
CREATE POLICY "workspace_entity_feature" ON "public"."search_document_preview_passages" AS RESTRICTIVE FOR ALL TO "stella" USING ((CASE WHEN "search_document_preview_passages"."entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "search_document_preview_passages"."entity_id") END)) WITH CHECK ((CASE WHEN "search_document_preview_passages"."entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "search_document_preview_passages"."entity_id") END));
--> statement-breakpoint
CREATE POLICY "workspace_entity_feature" ON "public"."search_documents" AS RESTRICTIVE FOR ALL TO "stella" USING ((CASE WHEN "search_documents"."entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "search_documents"."entity_id") END)) WITH CHECK ((CASE WHEN "search_documents"."entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "search_documents"."entity_id") END));
--> statement-breakpoint
CREATE POLICY "workspace_entity_feature" ON "public"."task_assignees" AS RESTRICTIVE FOR ALL TO "stella" USING ((CASE WHEN "task_assignees"."entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "task_assignees"."entity_id") END)) WITH CHECK ((CASE WHEN "task_assignees"."entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "task_assignees"."entity_id") END));
--> statement-breakpoint
CREATE POLICY "workspace_entity_feature" ON "public"."work_obligation_events" AS RESTRICTIVE FOR ALL TO "stella" USING ((CASE WHEN "work_obligation_events"."obligation_entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "work_obligation_events"."obligation_entity_id") END)) WITH CHECK ((CASE WHEN "work_obligation_events"."obligation_entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "work_obligation_events"."obligation_entity_id") END));
--> statement-breakpoint
CREATE POLICY "workspace_entity_feature" ON "public"."work_obligations" AS RESTRICTIVE FOR ALL TO "stella" USING ((CASE WHEN "work_obligations"."entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "work_obligations"."entity_id") END)) WITH CHECK ((CASE WHEN "work_obligations"."entity_id" IS NULL THEN true ELSE EXISTS (SELECT 1 FROM public.entities e WHERE e.id = "work_obligations"."entity_id") END));
