/**
 * Generate the city dictionary loader map from the files in
 * `dictionaries/cities/`.
 *
 * A bundler cannot rewrite a computed import specifier, so a
 * `import(\`./cities/${cc}.json\`)` resolves to nothing in a bundled
 * consumer and every city dictionary silently loads as zero entries.
 * The map emitted here gives every country its own literal specifier,
 * which bundlers resolve statically.
 *
 * Output: packages/data/dictionaries/city-loaders.ts
 *
 * Usage:
 *   bun run scripts/generate-city-loaders.ts
 *   bun run scripts/generate-city-loaders.ts --check
 *
 * `--check` fails when the committed map is out of date, so adding a
 * `dictionaries/cities/*.json` file without regenerating cannot ship.
 */

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const CITIES_DIR = join(__dirname, "..", "dictionaries", "cities");
const OUTPUT = join(__dirname, "..", "dictionaries", "city-loaders.ts");

/** Country dictionaries are `<ISO 3166-1 alpha-2>.json`. */
const CITY_FILE_RE = /^([A-Z]{2})\.json$/;

const countryCodes = (): string[] => {
  const codes: string[] = [];
  for (const name of readdirSync(CITIES_DIR)) {
    const match = CITY_FILE_RE.exec(name);
    if (!match) {
      console.error(`generate-city-loaders: unexpected file cities/${name}`);
      process.exit(1);
    }
    codes.push(match[1]);
  }
  codes.sort();
  return codes;
};

const render = (codes: readonly string[]): string => {
  const entries = codes
    .map(
      (cc) =>
        `  ${cc}: async () => import("./cities/${cc}.json") as Promise<CityJsonModule>,`,
    )
    .join("\n");

  return `// Generated by scripts/generate-city-loaders.ts. Do not edit.
//
// One literal import() specifier per country: a computed specifier
// is invisible to bundlers and resolves to nothing in a bundled
// consumer, which turns a missing dictionary into zero redactions.
// Regenerate after adding or removing a dictionaries/cities/*.json.

type CityJsonModule = { default: readonly string[] };

/** City dictionary loaders keyed by ISO 3166-1 alpha-2 code. */
export const CITY_LOADERS = {
${entries}
} as const satisfies Record<string, () => Promise<CityJsonModule>>;

/** ISO 3166-1 alpha-2 code with a bundled city dictionary. */
export type CityCountryCode = keyof typeof CITY_LOADERS;
`;
};

const codes = countryCodes();
const generated = render(codes);

if (process.argv.includes("--check")) {
  const current = readFileSync(OUTPUT, "utf-8");
  if (current === generated) {
    console.log(
      `check:city-loaders: ${codes.length} city loaders match dictionaries/cities/.`,
    );
    process.exit(0);
  }
  console.error(
    "check:city-loaders: dictionaries/city-loaders.ts is out of date.\n" +
      "  Run: bun run --cwd packages/data generate:city-loaders",
  );
  process.exit(1);
}

writeFileSync(OUTPUT, generated);
console.log(`Written: ${OUTPUT}`);
console.log(`  ${codes.length} city dictionaries`);
