/**
 * Reader for the committed Snowball conformance fixtures.
 *
 * Test-only. The fixtures themselves are regenerated by
 * `scripts/generate-snowball-stemmers.ts`; this only parses them, so both the
 * conformance suite and the public-surface suite exercise one vocabulary
 * rather than two hand-kept copies.
 */

import { panic } from "better-result";
import { readdirSync, readFileSync } from "node:fs";
import path from "node:path";

export type VocabularyPair = { readonly word: string; readonly stem: string };

const FIXTURE_SUFFIX = ".conformance.txt";

/** Declared row count, so a truncated fixture cannot pass a thinner sample. */
const DECLARED_PAIRS = /^# pairs: (\d+)$/mu;

/**
 * The algorithms the fixture directory holds, read from disk rather than
 * listed: a generated fixture no test case names would otherwise go
 * unexercised.
 */
export const conformanceAlgorithms = (): readonly string[] =>
  readdirSync(import.meta.dir)
    .filter((entry) => entry.endsWith(FIXTURE_SUFFIX))
    .map((entry) => entry.slice(0, -FIXTURE_SUFFIX.length))
    .sort();

export const readConformanceVocabulary = (
  algorithm: string,
): readonly VocabularyPair[] => {
  const contents = readFileSync(
    path.join(import.meta.dir, `${algorithm}${FIXTURE_SUFFIX}`),
    "utf-8",
  );
  const declared = DECLARED_PAIRS.exec(contents);
  if (declared?.[1] === undefined) {
    panic(`${algorithm}: fixture declares no pair count`);
  }

  const pairs = contents
    .split("\n")
    .filter((line) => line !== "" && !line.startsWith("#"))
    .map((line) => {
      const [word, stem, ...rest] = line.split("\t");
      if (word === undefined || stem === undefined || rest.length > 0) {
        // The fixtures are generated and committed; a malformed line means
        // the generator or the file is broken, never bad runtime input.
        panic(`malformed conformance line: ${JSON.stringify(line)}`);
      }
      return { word, stem };
    });

  if (pairs.length !== Number(declared[1])) {
    panic(
      `${algorithm}: fixture declares ${declared[1]} pairs but holds ${pairs.length}`,
    );
  }
  return pairs;
};
