/**
 * Reader for the committed Snowball conformance fixtures.
 *
 * Test-only. The fixtures themselves are regenerated by
 * `scripts/generate-snowball-stemmers.ts`; this only parses them, so both the
 * conformance suite and the public-surface suite exercise one vocabulary
 * rather than two hand-kept copies.
 */

import { panic } from "better-result";
import { readFileSync } from "node:fs";
import path from "node:path";

export type VocabularyPair = { readonly word: string; readonly stem: string };

/** Snowball algorithm name, i.e. the fixture basename. */
export type ConformanceAlgorithm = "czech" | "polish";

export const readConformanceVocabulary = (
  algorithm: ConformanceAlgorithm,
): readonly VocabularyPair[] =>
  readFileSync(
    path.join(import.meta.dir, `${algorithm}.conformance.txt`),
    "utf-8",
  )
    .split("\n")
    .filter((line) => line !== "" && !line.startsWith("#"))
    .map((line) => {
      const [word, stem, ...rest] = line.split("\t");
      if (word === undefined || stem === undefined || rest.length > 0) {
        // The fixtures are generated and committed; a malformed line means
        // the generator or the file is broken, never bad runtime input.
        panic(`malformed conformance line: ${JSON.stringify(line)}`);
      }
      return { word, stem };
    });
