// Auto-generated by generate-i18n-types.ts
// Do not edit manually.

type Messages = {
  "invitation": {
    "accept": "Accept invitation";
    "body": "You've been invited to join {organizationName} by {invitedByUsername}. Click below to accept.";
    "expires": "This invitation will expire in 48 hours.";
    "heading": "Organization invitation";
    "ignore": "If you didn't expect this invitation, you can safely ignore this email.";
    "subject": "You're invited to join {organizationName}";
  };
  "newDeviceLogin": {
    "action": "Review sessions";
    "body": "Your account was signed in to from a new device or location.";
    "device": "Device";
    "heading": "New sign-in detected";
    "ignore": "If this was you, no action is needed. If you don't recognize this activity, review your active sessions and revoke any you don't recognize.";
    "ipAddress": "IP address";
    "preview": "New sign-in from {device}";
    "subject": "New sign-in to your stella account";
    "time": "Time";
  };
  "otp": {
    "changeEmail": "Use this code to verify your new email address.";
    "deleteAccount": "Use this code to verify deleting your account.";
    "emailVerification": "Use this code to verify your email address.";
    "expires": "This code expires in 5 minutes.";
    "forgetPassword": "Use this code to reset your password.";
    "heading": "Your stella one-time code";
    "ignore": "If you didn't request this code, you can ignore this email.";
    "preview": "Use this code to verify your identity";
    "signIn": "Use this code to sign in to your stella account.";
    "subject": "Your stella verification code";
  };
  "reportExportStatus": {
    "action": "Open stella";
    "completedBody": "Your report export is ready. Open stella to view or download it.";
    "completedHeading": "Report export ready";
    "completedPreview": "Your report export is ready";
    "completedSubject": "Your report export is ready";
    "failedBody": "Your report export could not be completed. Open stella to try again.";
    "failedHeading": "Report export failed";
    "failedPreview": "Your report export could not be completed";
    "failedSubject": "Your report export could not be completed";
    "privacy": "This email contains no report content or file names.";
  };
};

export type { Messages as default };
