/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthOtpRouteImport } from './routes/auth/otp'
import { Route as AuthOrganizationRouteImport } from './routes/auth/organization'
import { Route as ProtectedOrganizationRouteRouteImport } from './routes/_protected.organization/route'
import { Route as ProtectedKnowledgeRouteRouteImport } from './routes/_protected.knowledge/route'
import { Route as ProtectedChatRouteRouteImport } from './routes/_protected.chat/route'
import { Route as ProtectedAccountRouteRouteImport } from './routes/_protected.account/route'
import { Route as ProtectedWorkspacesIndexRouteImport } from './routes/_protected.workspaces/index'
import { Route as ProtectedKnowledgeIndexRouteImport } from './routes/_protected.knowledge/index'
import { Route as ProtectedContactsIndexRouteImport } from './routes/_protected.contacts/index'
import { Route as ProtectedChatIndexRouteImport } from './routes/_protected.chat/index'
import { Route as AuthAcceptInvitationInvitationIdRouteImport } from './routes/auth/accept-invitation.$invitationId'
import { Route as ProtectedOrganizationMembersRouteImport } from './routes/_protected.organization/members'
import { Route as ProtectedOrganizationInvitationsRouteImport } from './routes/_protected.organization/invitations'
import { Route as ProtectedKnowledgeTemplatesRouteImport } from './routes/_protected.knowledge/templates'
import { Route as ProtectedKnowledgeClausesRouteImport } from './routes/_protected.knowledge/clauses'
import { Route as ProtectedKnowledgeAnalyticsRouteImport } from './routes/_protected.knowledge/analytics'
import { Route as ProtectedContactsContactIdRouteImport } from './routes/_protected.contacts/$contactId'
import { Route as ProtectedChatThreadIdRouteImport } from './routes/_protected.chat/$threadId'
import { Route as ProtectedAccountSessionsRouteImport } from './routes/_protected.account/sessions'
import { Route as ProtectedWorkspacesWorkspaceIdRouteRouteImport } from './routes/_protected.workspaces/$workspaceId/route'
import { Route as ProtectedWorkspacesWorkspaceIdIndexRouteImport } from './routes/_protected.workspaces/$workspaceId/index'
import { Route as ProtectedWorkspacesWorkspaceIdTimesheetsRouteImport } from './routes/_protected.workspaces/$workspaceId/timesheets'
import { Route as ProtectedWorkspacesWorkspaceIdPdfRouteImport } from './routes/_protected.workspaces/$workspaceId/pdf'
import { Route as ProtectedWorkspacesWorkspaceIdInvoicesRouteImport } from './routes/_protected.workspaces/$workspaceId/invoices'
import { Route as ProtectedWorkspacesWorkspaceIdExpensesRouteImport } from './routes/_protected.workspaces/$workspaceId/expenses'
import { Route as ProtectedWorkspacesWorkspaceIdAnalyticsRouteImport } from './routes/_protected.workspaces/$workspaceId/analytics'
import { Route as ProtectedWorkspacesWorkspaceIdInvoicesInvoiceIdRouteImport } from './routes/_protected.workspaces/$workspaceId/invoices/$invoiceId'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthOtpRoute = AuthOtpRouteImport.update({
  id: '/auth/otp',
  path: '/auth/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthOrganizationRoute = AuthOrganizationRouteImport.update({
  id: '/auth/organization',
  path: '/auth/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedOrganizationRouteRoute =
  ProtectedOrganizationRouteRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedKnowledgeRouteRoute = ProtectedKnowledgeRouteRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedChatRouteRoute = ProtectedChatRouteRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAccountRouteRoute = ProtectedAccountRouteRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedWorkspacesIndexRoute =
  ProtectedWorkspacesIndexRouteImport.update({
    id: '/workspaces/',
    path: '/workspaces/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedKnowledgeIndexRoute = ProtectedKnowledgeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedKnowledgeRouteRoute,
} as any)
const ProtectedContactsIndexRoute = ProtectedContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedChatIndexRoute = ProtectedChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedChatRouteRoute,
} as any)
const AuthAcceptInvitationInvitationIdRoute =
  AuthAcceptInvitationInvitationIdRouteImport.update({
    id: '/auth/accept-invitation/$invitationId',
    path: '/auth/accept-invitation/$invitationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProtectedOrganizationMembersRoute =
  ProtectedOrganizationMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => ProtectedOrganizationRouteRoute,
  } as any)
const ProtectedOrganizationInvitationsRoute =
  ProtectedOrganizationInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => ProtectedOrganizationRouteRoute,
  } as any)
const ProtectedKnowledgeTemplatesRoute =
  ProtectedKnowledgeTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => ProtectedKnowledgeRouteRoute,
  } as any)
const ProtectedKnowledgeClausesRoute =
  ProtectedKnowledgeClausesRouteImport.update({
    id: '/clauses',
    path: '/clauses',
    getParentRoute: () => ProtectedKnowledgeRouteRoute,
  } as any)
const ProtectedKnowledgeAnalyticsRoute =
  ProtectedKnowledgeAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => ProtectedKnowledgeRouteRoute,
  } as any)
const ProtectedContactsContactIdRoute =
  ProtectedContactsContactIdRouteImport.update({
    id: '/contacts/$contactId',
    path: '/contacts/$contactId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedChatThreadIdRoute = ProtectedChatThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ProtectedChatRouteRoute,
} as any)
const ProtectedAccountSessionsRoute =
  ProtectedAccountSessionsRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => ProtectedAccountRouteRoute,
  } as any)
const ProtectedWorkspacesWorkspaceIdRouteRoute =
  ProtectedWorkspacesWorkspaceIdRouteRouteImport.update({
    id: '/workspaces/$workspaceId',
    path: '/workspaces/$workspaceId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedWorkspacesWorkspaceIdIndexRoute =
  ProtectedWorkspacesWorkspaceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedWorkspacesWorkspaceIdRouteRoute,
  } as any)
const ProtectedWorkspacesWorkspaceIdTimesheetsRoute =
  ProtectedWorkspacesWorkspaceIdTimesheetsRouteImport.update({
    id: '/timesheets',
    path: '/timesheets',
    getParentRoute: () => ProtectedWorkspacesWorkspaceIdRouteRoute,
  } as any)
const ProtectedWorkspacesWorkspaceIdPdfRoute =
  ProtectedWorkspacesWorkspaceIdPdfRouteImport.update({
    id: '/pdf',
    path: '/pdf',
    getParentRoute: () => ProtectedWorkspacesWorkspaceIdRouteRoute,
  } as any)
const ProtectedWorkspacesWorkspaceIdInvoicesRoute =
  ProtectedWorkspacesWorkspaceIdInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => ProtectedWorkspacesWorkspaceIdRouteRoute,
  } as any)
const ProtectedWorkspacesWorkspaceIdExpensesRoute =
  ProtectedWorkspacesWorkspaceIdExpensesRouteImport.update({
    id: '/expenses',
    path: '/expenses',
    getParentRoute: () => ProtectedWorkspacesWorkspaceIdRouteRoute,
  } as any)
const ProtectedWorkspacesWorkspaceIdAnalyticsRoute =
  ProtectedWorkspacesWorkspaceIdAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => ProtectedWorkspacesWorkspaceIdRouteRoute,
  } as any)
const ProtectedWorkspacesWorkspaceIdInvoicesInvoiceIdRoute =
  ProtectedWorkspacesWorkspaceIdInvoicesInvoiceIdRouteImport.update({
    id: '/$invoiceId',
    path: '/$invoiceId',
    getParentRoute: () => ProtectedWorkspacesWorkspaceIdInvoicesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof ProtectedAccountRouteRouteWithChildren
  '/chat': typeof ProtectedChatRouteRouteWithChildren
  '/knowledge': typeof ProtectedKnowledgeRouteRouteWithChildren
  '/organization': typeof ProtectedOrganizationRouteRouteWithChildren
  '/auth/organization': typeof AuthOrganizationRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/': typeof AuthIndexRoute
  '/workspaces/$workspaceId': typeof ProtectedWorkspacesWorkspaceIdRouteRouteWithChildren
  '/account/sessions': typeof ProtectedAccountSessionsRoute
  '/chat/$threadId': typeof ProtectedChatThreadIdRoute
  '/contacts/$contactId': typeof ProtectedContactsContactIdRoute
  '/knowledge/analytics': typeof ProtectedKnowledgeAnalyticsRoute
  '/knowledge/clauses': typeof ProtectedKnowledgeClausesRoute
  '/knowledge/templates': typeof ProtectedKnowledgeTemplatesRoute
  '/organization/invitations': typeof ProtectedOrganizationInvitationsRoute
  '/organization/members': typeof ProtectedOrganizationMembersRoute
  '/auth/accept-invitation/$invitationId': typeof AuthAcceptInvitationInvitationIdRoute
  '/chat/': typeof ProtectedChatIndexRoute
  '/contacts/': typeof ProtectedContactsIndexRoute
  '/knowledge/': typeof ProtectedKnowledgeIndexRoute
  '/workspaces/': typeof ProtectedWorkspacesIndexRoute
  '/workspaces/$workspaceId/analytics': typeof ProtectedWorkspacesWorkspaceIdAnalyticsRoute
  '/workspaces/$workspaceId/expenses': typeof ProtectedWorkspacesWorkspaceIdExpensesRoute
  '/workspaces/$workspaceId/invoices': typeof ProtectedWorkspacesWorkspaceIdInvoicesRouteWithChildren
  '/workspaces/$workspaceId/pdf': typeof ProtectedWorkspacesWorkspaceIdPdfRoute
  '/workspaces/$workspaceId/timesheets': typeof ProtectedWorkspacesWorkspaceIdTimesheetsRoute
  '/workspaces/$workspaceId/': typeof ProtectedWorkspacesWorkspaceIdIndexRoute
  '/workspaces/$workspaceId/invoices/$invoiceId': typeof ProtectedWorkspacesWorkspaceIdInvoicesInvoiceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof ProtectedAccountRouteRouteWithChildren
  '/organization': typeof ProtectedOrganizationRouteRouteWithChildren
  '/auth/organization': typeof AuthOrganizationRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth': typeof AuthIndexRoute
  '/account/sessions': typeof ProtectedAccountSessionsRoute
  '/chat/$threadId': typeof ProtectedChatThreadIdRoute
  '/contacts/$contactId': typeof ProtectedContactsContactIdRoute
  '/knowledge/analytics': typeof ProtectedKnowledgeAnalyticsRoute
  '/knowledge/clauses': typeof ProtectedKnowledgeClausesRoute
  '/knowledge/templates': typeof ProtectedKnowledgeTemplatesRoute
  '/organization/invitations': typeof ProtectedOrganizationInvitationsRoute
  '/organization/members': typeof ProtectedOrganizationMembersRoute
  '/auth/accept-invitation/$invitationId': typeof AuthAcceptInvitationInvitationIdRoute
  '/chat': typeof ProtectedChatIndexRoute
  '/contacts': typeof ProtectedContactsIndexRoute
  '/knowledge': typeof ProtectedKnowledgeIndexRoute
  '/workspaces': typeof ProtectedWorkspacesIndexRoute
  '/workspaces/$workspaceId/analytics': typeof ProtectedWorkspacesWorkspaceIdAnalyticsRoute
  '/workspaces/$workspaceId/expenses': typeof ProtectedWorkspacesWorkspaceIdExpensesRoute
  '/workspaces/$workspaceId/invoices': typeof ProtectedWorkspacesWorkspaceIdInvoicesRouteWithChildren
  '/workspaces/$workspaceId/pdf': typeof ProtectedWorkspacesWorkspaceIdPdfRoute
  '/workspaces/$workspaceId/timesheets': typeof ProtectedWorkspacesWorkspaceIdTimesheetsRoute
  '/workspaces/$workspaceId': typeof ProtectedWorkspacesWorkspaceIdIndexRoute
  '/workspaces/$workspaceId/invoices/$invoiceId': typeof ProtectedWorkspacesWorkspaceIdInvoicesInvoiceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/_protected/account': typeof ProtectedAccountRouteRouteWithChildren
  '/_protected/chat': typeof ProtectedChatRouteRouteWithChildren
  '/_protected/knowledge': typeof ProtectedKnowledgeRouteRouteWithChildren
  '/_protected/organization': typeof ProtectedOrganizationRouteRouteWithChildren
  '/auth/organization': typeof AuthOrganizationRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/': typeof AuthIndexRoute
  '/_protected/workspaces/$workspaceId': typeof ProtectedWorkspacesWorkspaceIdRouteRouteWithChildren
  '/_protected/account/sessions': typeof ProtectedAccountSessionsRoute
  '/_protected/chat/$threadId': typeof ProtectedChatThreadIdRoute
  '/_protected/contacts/$contactId': typeof ProtectedContactsContactIdRoute
  '/_protected/knowledge/analytics': typeof ProtectedKnowledgeAnalyticsRoute
  '/_protected/knowledge/clauses': typeof ProtectedKnowledgeClausesRoute
  '/_protected/knowledge/templates': typeof ProtectedKnowledgeTemplatesRoute
  '/_protected/organization/invitations': typeof ProtectedOrganizationInvitationsRoute
  '/_protected/organization/members': typeof ProtectedOrganizationMembersRoute
  '/auth/accept-invitation/$invitationId': typeof AuthAcceptInvitationInvitationIdRoute
  '/_protected/chat/': typeof ProtectedChatIndexRoute
  '/_protected/contacts/': typeof ProtectedContactsIndexRoute
  '/_protected/knowledge/': typeof ProtectedKnowledgeIndexRoute
  '/_protected/workspaces/': typeof ProtectedWorkspacesIndexRoute
  '/_protected/workspaces/$workspaceId/analytics': typeof ProtectedWorkspacesWorkspaceIdAnalyticsRoute
  '/_protected/workspaces/$workspaceId/expenses': typeof ProtectedWorkspacesWorkspaceIdExpensesRoute
  '/_protected/workspaces/$workspaceId/invoices': typeof ProtectedWorkspacesWorkspaceIdInvoicesRouteWithChildren
  '/_protected/workspaces/$workspaceId/pdf': typeof ProtectedWorkspacesWorkspaceIdPdfRoute
  '/_protected/workspaces/$workspaceId/timesheets': typeof ProtectedWorkspacesWorkspaceIdTimesheetsRoute
  '/_protected/workspaces/$workspaceId/': typeof ProtectedWorkspacesWorkspaceIdIndexRoute
  '/_protected/workspaces/$workspaceId/invoices/$invoiceId': typeof ProtectedWorkspacesWorkspaceIdInvoicesInvoiceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/chat'
    | '/knowledge'
    | '/organization'
    | '/auth/organization'
    | '/auth/otp'
    | '/auth/'
    | '/workspaces/$workspaceId'
    | '/account/sessions'
    | '/chat/$threadId'
    | '/contacts/$contactId'
    | '/knowledge/analytics'
    | '/knowledge/clauses'
    | '/knowledge/templates'
    | '/organization/invitations'
    | '/organization/members'
    | '/auth/accept-invitation/$invitationId'
    | '/chat/'
    | '/contacts/'
    | '/knowledge/'
    | '/workspaces/'
    | '/workspaces/$workspaceId/analytics'
    | '/workspaces/$workspaceId/expenses'
    | '/workspaces/$workspaceId/invoices'
    | '/workspaces/$workspaceId/pdf'
    | '/workspaces/$workspaceId/timesheets'
    | '/workspaces/$workspaceId/'
    | '/workspaces/$workspaceId/invoices/$invoiceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/organization'
    | '/auth/organization'
    | '/auth/otp'
    | '/auth'
    | '/account/sessions'
    | '/chat/$threadId'
    | '/contacts/$contactId'
    | '/knowledge/analytics'
    | '/knowledge/clauses'
    | '/knowledge/templates'
    | '/organization/invitations'
    | '/organization/members'
    | '/auth/accept-invitation/$invitationId'
    | '/chat'
    | '/contacts'
    | '/knowledge'
    | '/workspaces'
    | '/workspaces/$workspaceId/analytics'
    | '/workspaces/$workspaceId/expenses'
    | '/workspaces/$workspaceId/invoices'
    | '/workspaces/$workspaceId/pdf'
    | '/workspaces/$workspaceId/timesheets'
    | '/workspaces/$workspaceId'
    | '/workspaces/$workspaceId/invoices/$invoiceId'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/_protected/account'
    | '/_protected/chat'
    | '/_protected/knowledge'
    | '/_protected/organization'
    | '/auth/organization'
    | '/auth/otp'
    | '/auth/'
    | '/_protected/workspaces/$workspaceId'
    | '/_protected/account/sessions'
    | '/_protected/chat/$threadId'
    | '/_protected/contacts/$contactId'
    | '/_protected/knowledge/analytics'
    | '/_protected/knowledge/clauses'
    | '/_protected/knowledge/templates'
    | '/_protected/organization/invitations'
    | '/_protected/organization/members'
    | '/auth/accept-invitation/$invitationId'
    | '/_protected/chat/'
    | '/_protected/contacts/'
    | '/_protected/knowledge/'
    | '/_protected/workspaces/'
    | '/_protected/workspaces/$workspaceId/analytics'
    | '/_protected/workspaces/$workspaceId/expenses'
    | '/_protected/workspaces/$workspaceId/invoices'
    | '/_protected/workspaces/$workspaceId/pdf'
    | '/_protected/workspaces/$workspaceId/timesheets'
    | '/_protected/workspaces/$workspaceId/'
    | '/_protected/workspaces/$workspaceId/invoices/$invoiceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  AuthOrganizationRoute: typeof AuthOrganizationRoute
  AuthOtpRoute: typeof AuthOtpRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthAcceptInvitationInvitationIdRoute: typeof AuthAcceptInvitationInvitationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/otp': {
      id: '/auth/otp'
      path: '/auth/otp'
      fullPath: '/auth/otp'
      preLoaderRoute: typeof AuthOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/organization': {
      id: '/auth/organization'
      path: '/auth/organization'
      fullPath: '/auth/organization'
      preLoaderRoute: typeof AuthOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/organization': {
      id: '/_protected/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof ProtectedOrganizationRouteRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/knowledge': {
      id: '/_protected/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof ProtectedKnowledgeRouteRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/chat': {
      id: '/_protected/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ProtectedChatRouteRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/account': {
      id: '/_protected/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof ProtectedAccountRouteRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/workspaces/': {
      id: '/_protected/workspaces/'
      path: '/workspaces'
      fullPath: '/workspaces/'
      preLoaderRoute: typeof ProtectedWorkspacesIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/knowledge/': {
      id: '/_protected/knowledge/'
      path: '/'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof ProtectedKnowledgeIndexRouteImport
      parentRoute: typeof ProtectedKnowledgeRouteRoute
    }
    '/_protected/contacts/': {
      id: '/_protected/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof ProtectedContactsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/chat/': {
      id: '/_protected/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof ProtectedChatIndexRouteImport
      parentRoute: typeof ProtectedChatRouteRoute
    }
    '/auth/accept-invitation/$invitationId': {
      id: '/auth/accept-invitation/$invitationId'
      path: '/auth/accept-invitation/$invitationId'
      fullPath: '/auth/accept-invitation/$invitationId'
      preLoaderRoute: typeof AuthAcceptInvitationInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/organization/members': {
      id: '/_protected/organization/members'
      path: '/members'
      fullPath: '/organization/members'
      preLoaderRoute: typeof ProtectedOrganizationMembersRouteImport
      parentRoute: typeof ProtectedOrganizationRouteRoute
    }
    '/_protected/organization/invitations': {
      id: '/_protected/organization/invitations'
      path: '/invitations'
      fullPath: '/organization/invitations'
      preLoaderRoute: typeof ProtectedOrganizationInvitationsRouteImport
      parentRoute: typeof ProtectedOrganizationRouteRoute
    }
    '/_protected/knowledge/templates': {
      id: '/_protected/knowledge/templates'
      path: '/templates'
      fullPath: '/knowledge/templates'
      preLoaderRoute: typeof ProtectedKnowledgeTemplatesRouteImport
      parentRoute: typeof ProtectedKnowledgeRouteRoute
    }
    '/_protected/knowledge/clauses': {
      id: '/_protected/knowledge/clauses'
      path: '/clauses'
      fullPath: '/knowledge/clauses'
      preLoaderRoute: typeof ProtectedKnowledgeClausesRouteImport
      parentRoute: typeof ProtectedKnowledgeRouteRoute
    }
    '/_protected/knowledge/analytics': {
      id: '/_protected/knowledge/analytics'
      path: '/analytics'
      fullPath: '/knowledge/analytics'
      preLoaderRoute: typeof ProtectedKnowledgeAnalyticsRouteImport
      parentRoute: typeof ProtectedKnowledgeRouteRoute
    }
    '/_protected/contacts/$contactId': {
      id: '/_protected/contacts/$contactId'
      path: '/contacts/$contactId'
      fullPath: '/contacts/$contactId'
      preLoaderRoute: typeof ProtectedContactsContactIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/chat/$threadId': {
      id: '/_protected/chat/$threadId'
      path: '/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof ProtectedChatThreadIdRouteImport
      parentRoute: typeof ProtectedChatRouteRoute
    }
    '/_protected/account/sessions': {
      id: '/_protected/account/sessions'
      path: '/sessions'
      fullPath: '/account/sessions'
      preLoaderRoute: typeof ProtectedAccountSessionsRouteImport
      parentRoute: typeof ProtectedAccountRouteRoute
    }
    '/_protected/workspaces/$workspaceId': {
      id: '/_protected/workspaces/$workspaceId'
      path: '/workspaces/$workspaceId'
      fullPath: '/workspaces/$workspaceId'
      preLoaderRoute: typeof ProtectedWorkspacesWorkspaceIdRouteRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/workspaces/$workspaceId/': {
      id: '/_protected/workspaces/$workspaceId/'
      path: '/'
      fullPath: '/workspaces/$workspaceId/'
      preLoaderRoute: typeof ProtectedWorkspacesWorkspaceIdIndexRouteImport
      parentRoute: typeof ProtectedWorkspacesWorkspaceIdRouteRoute
    }
    '/_protected/workspaces/$workspaceId/timesheets': {
      id: '/_protected/workspaces/$workspaceId/timesheets'
      path: '/timesheets'
      fullPath: '/workspaces/$workspaceId/timesheets'
      preLoaderRoute: typeof ProtectedWorkspacesWorkspaceIdTimesheetsRouteImport
      parentRoute: typeof ProtectedWorkspacesWorkspaceIdRouteRoute
    }
    '/_protected/workspaces/$workspaceId/pdf': {
      id: '/_protected/workspaces/$workspaceId/pdf'
      path: '/pdf'
      fullPath: '/workspaces/$workspaceId/pdf'
      preLoaderRoute: typeof ProtectedWorkspacesWorkspaceIdPdfRouteImport
      parentRoute: typeof ProtectedWorkspacesWorkspaceIdRouteRoute
    }
    '/_protected/workspaces/$workspaceId/invoices': {
      id: '/_protected/workspaces/$workspaceId/invoices'
      path: '/invoices'
      fullPath: '/workspaces/$workspaceId/invoices'
      preLoaderRoute: typeof ProtectedWorkspacesWorkspaceIdInvoicesRouteImport
      parentRoute: typeof ProtectedWorkspacesWorkspaceIdRouteRoute
    }
    '/_protected/workspaces/$workspaceId/expenses': {
      id: '/_protected/workspaces/$workspaceId/expenses'
      path: '/expenses'
      fullPath: '/workspaces/$workspaceId/expenses'
      preLoaderRoute: typeof ProtectedWorkspacesWorkspaceIdExpensesRouteImport
      parentRoute: typeof ProtectedWorkspacesWorkspaceIdRouteRoute
    }
    '/_protected/workspaces/$workspaceId/analytics': {
      id: '/_protected/workspaces/$workspaceId/analytics'
      path: '/analytics'
      fullPath: '/workspaces/$workspaceId/analytics'
      preLoaderRoute: typeof ProtectedWorkspacesWorkspaceIdAnalyticsRouteImport
      parentRoute: typeof ProtectedWorkspacesWorkspaceIdRouteRoute
    }
    '/_protected/workspaces/$workspaceId/invoices/$invoiceId': {
      id: '/_protected/workspaces/$workspaceId/invoices/$invoiceId'
      path: '/$invoiceId'
      fullPath: '/workspaces/$workspaceId/invoices/$invoiceId'
      preLoaderRoute: typeof ProtectedWorkspacesWorkspaceIdInvoicesInvoiceIdRouteImport
      parentRoute: typeof ProtectedWorkspacesWorkspaceIdInvoicesRoute
    }
  }
}

interface ProtectedAccountRouteRouteChildren {
  ProtectedAccountSessionsRoute: typeof ProtectedAccountSessionsRoute
}

const ProtectedAccountRouteRouteChildren: ProtectedAccountRouteRouteChildren = {
  ProtectedAccountSessionsRoute: ProtectedAccountSessionsRoute,
}

const ProtectedAccountRouteRouteWithChildren =
  ProtectedAccountRouteRoute._addFileChildren(
    ProtectedAccountRouteRouteChildren,
  )

interface ProtectedChatRouteRouteChildren {
  ProtectedChatThreadIdRoute: typeof ProtectedChatThreadIdRoute
  ProtectedChatIndexRoute: typeof ProtectedChatIndexRoute
}

const ProtectedChatRouteRouteChildren: ProtectedChatRouteRouteChildren = {
  ProtectedChatThreadIdRoute: ProtectedChatThreadIdRoute,
  ProtectedChatIndexRoute: ProtectedChatIndexRoute,
}

const ProtectedChatRouteRouteWithChildren =
  ProtectedChatRouteRoute._addFileChildren(ProtectedChatRouteRouteChildren)

interface ProtectedKnowledgeRouteRouteChildren {
  ProtectedKnowledgeAnalyticsRoute: typeof ProtectedKnowledgeAnalyticsRoute
  ProtectedKnowledgeClausesRoute: typeof ProtectedKnowledgeClausesRoute
  ProtectedKnowledgeTemplatesRoute: typeof ProtectedKnowledgeTemplatesRoute
  ProtectedKnowledgeIndexRoute: typeof ProtectedKnowledgeIndexRoute
}

const ProtectedKnowledgeRouteRouteChildren: ProtectedKnowledgeRouteRouteChildren =
  {
    ProtectedKnowledgeAnalyticsRoute: ProtectedKnowledgeAnalyticsRoute,
    ProtectedKnowledgeClausesRoute: ProtectedKnowledgeClausesRoute,
    ProtectedKnowledgeTemplatesRoute: ProtectedKnowledgeTemplatesRoute,
    ProtectedKnowledgeIndexRoute: ProtectedKnowledgeIndexRoute,
  }

const ProtectedKnowledgeRouteRouteWithChildren =
  ProtectedKnowledgeRouteRoute._addFileChildren(
    ProtectedKnowledgeRouteRouteChildren,
  )

interface ProtectedOrganizationRouteRouteChildren {
  ProtectedOrganizationInvitationsRoute: typeof ProtectedOrganizationInvitationsRoute
  ProtectedOrganizationMembersRoute: typeof ProtectedOrganizationMembersRoute
}

const ProtectedOrganizationRouteRouteChildren: ProtectedOrganizationRouteRouteChildren =
  {
    ProtectedOrganizationInvitationsRoute:
      ProtectedOrganizationInvitationsRoute,
    ProtectedOrganizationMembersRoute: ProtectedOrganizationMembersRoute,
  }

const ProtectedOrganizationRouteRouteWithChildren =
  ProtectedOrganizationRouteRoute._addFileChildren(
    ProtectedOrganizationRouteRouteChildren,
  )

interface ProtectedWorkspacesWorkspaceIdInvoicesRouteChildren {
  ProtectedWorkspacesWorkspaceIdInvoicesInvoiceIdRoute: typeof ProtectedWorkspacesWorkspaceIdInvoicesInvoiceIdRoute
}

const ProtectedWorkspacesWorkspaceIdInvoicesRouteChildren: ProtectedWorkspacesWorkspaceIdInvoicesRouteChildren =
  {
    ProtectedWorkspacesWorkspaceIdInvoicesInvoiceIdRoute:
      ProtectedWorkspacesWorkspaceIdInvoicesInvoiceIdRoute,
  }

const ProtectedWorkspacesWorkspaceIdInvoicesRouteWithChildren =
  ProtectedWorkspacesWorkspaceIdInvoicesRoute._addFileChildren(
    ProtectedWorkspacesWorkspaceIdInvoicesRouteChildren,
  )

interface ProtectedWorkspacesWorkspaceIdRouteRouteChildren {
  ProtectedWorkspacesWorkspaceIdAnalyticsRoute: typeof ProtectedWorkspacesWorkspaceIdAnalyticsRoute
  ProtectedWorkspacesWorkspaceIdExpensesRoute: typeof ProtectedWorkspacesWorkspaceIdExpensesRoute
  ProtectedWorkspacesWorkspaceIdInvoicesRoute: typeof ProtectedWorkspacesWorkspaceIdInvoicesRouteWithChildren
  ProtectedWorkspacesWorkspaceIdPdfRoute: typeof ProtectedWorkspacesWorkspaceIdPdfRoute
  ProtectedWorkspacesWorkspaceIdTimesheetsRoute: typeof ProtectedWorkspacesWorkspaceIdTimesheetsRoute
  ProtectedWorkspacesWorkspaceIdIndexRoute: typeof ProtectedWorkspacesWorkspaceIdIndexRoute
}

const ProtectedWorkspacesWorkspaceIdRouteRouteChildren: ProtectedWorkspacesWorkspaceIdRouteRouteChildren =
  {
    ProtectedWorkspacesWorkspaceIdAnalyticsRoute:
      ProtectedWorkspacesWorkspaceIdAnalyticsRoute,
    ProtectedWorkspacesWorkspaceIdExpensesRoute:
      ProtectedWorkspacesWorkspaceIdExpensesRoute,
    ProtectedWorkspacesWorkspaceIdInvoicesRoute:
      ProtectedWorkspacesWorkspaceIdInvoicesRouteWithChildren,
    ProtectedWorkspacesWorkspaceIdPdfRoute:
      ProtectedWorkspacesWorkspaceIdPdfRoute,
    ProtectedWorkspacesWorkspaceIdTimesheetsRoute:
      ProtectedWorkspacesWorkspaceIdTimesheetsRoute,
    ProtectedWorkspacesWorkspaceIdIndexRoute:
      ProtectedWorkspacesWorkspaceIdIndexRoute,
  }

const ProtectedWorkspacesWorkspaceIdRouteRouteWithChildren =
  ProtectedWorkspacesWorkspaceIdRouteRoute._addFileChildren(
    ProtectedWorkspacesWorkspaceIdRouteRouteChildren,
  )

interface ProtectedRouteChildren {
  ProtectedAccountRouteRoute: typeof ProtectedAccountRouteRouteWithChildren
  ProtectedChatRouteRoute: typeof ProtectedChatRouteRouteWithChildren
  ProtectedKnowledgeRouteRoute: typeof ProtectedKnowledgeRouteRouteWithChildren
  ProtectedOrganizationRouteRoute: typeof ProtectedOrganizationRouteRouteWithChildren
  ProtectedWorkspacesWorkspaceIdRouteRoute: typeof ProtectedWorkspacesWorkspaceIdRouteRouteWithChildren
  ProtectedContactsContactIdRoute: typeof ProtectedContactsContactIdRoute
  ProtectedContactsIndexRoute: typeof ProtectedContactsIndexRoute
  ProtectedWorkspacesIndexRoute: typeof ProtectedWorkspacesIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAccountRouteRoute: ProtectedAccountRouteRouteWithChildren,
  ProtectedChatRouteRoute: ProtectedChatRouteRouteWithChildren,
  ProtectedKnowledgeRouteRoute: ProtectedKnowledgeRouteRouteWithChildren,
  ProtectedOrganizationRouteRoute: ProtectedOrganizationRouteRouteWithChildren,
  ProtectedWorkspacesWorkspaceIdRouteRoute:
    ProtectedWorkspacesWorkspaceIdRouteRouteWithChildren,
  ProtectedContactsContactIdRoute: ProtectedContactsContactIdRoute,
  ProtectedContactsIndexRoute: ProtectedContactsIndexRoute,
  ProtectedWorkspacesIndexRoute: ProtectedWorkspacesIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  AuthOrganizationRoute: AuthOrganizationRoute,
  AuthOtpRoute: AuthOtpRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthAcceptInvitationInvitationIdRoute: AuthAcceptInvitationInvitationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
