/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthOtpRouteImport } from './routes/auth/otp'
import { Route as AuthOrganizationRouteImport } from './routes/auth/organization'
import { Route as ProtectedOrganizationRouteRouteImport } from './routes/_protected.organization/route'
import { Route as ProtectedKnowledgeRouteRouteImport } from './routes/_protected.knowledge/route'
import { Route as ProtectedWorkspacesIndexRouteImport } from './routes/_protected.workspaces/index'
import { Route as ProtectedKnowledgeIndexRouteImport } from './routes/_protected.knowledge/index'
import { Route as ProtectedContactsIndexRouteImport } from './routes/_protected.contacts/index'
import { Route as AuthAcceptInvitationInvitationIdRouteImport } from './routes/auth/accept-invitation.$invitationId'
import { Route as ProtectedOrganizationMembersRouteImport } from './routes/_protected.organization/members'
import { Route as ProtectedOrganizationInvitationsRouteImport } from './routes/_protected.organization/invitations'
import { Route as ProtectedKnowledgeTemplatesRouteImport } from './routes/_protected.knowledge/templates'
import { Route as ProtectedKnowledgeClausesRouteImport } from './routes/_protected.knowledge/clauses'
import { Route as ProtectedContactsContactIdRouteImport } from './routes/_protected.contacts/$contactId'
import { Route as ProtectedWorkspacesWorkspaceIdRouteRouteImport } from './routes/_protected.workspaces/$workspaceId/route'
import { Route as ProtectedWorkspacesWorkspaceIdIndexRouteImport } from './routes/_protected.workspaces/$workspaceId/index'
import { Route as ProtectedWorkspacesWorkspaceIdTimesheetsRouteImport } from './routes/_protected.workspaces/$workspaceId/timesheets'
import { Route as ProtectedWorkspacesWorkspaceIdPdfRouteImport } from './routes/_protected.workspaces/$workspaceId/pdf'
import { Route as ProtectedWorkspacesWorkspaceIdExpensesRouteImport } from './routes/_protected.workspaces/$workspaceId/expenses'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthOtpRoute = AuthOtpRouteImport.update({
  id: '/auth/otp',
  path: '/auth/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthOrganizationRoute = AuthOrganizationRouteImport.update({
  id: '/auth/organization',
  path: '/auth/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedOrganizationRouteRoute =
  ProtectedOrganizationRouteRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedKnowledgeRouteRoute = ProtectedKnowledgeRouteRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedWorkspacesIndexRoute =
  ProtectedWorkspacesIndexRouteImport.update({
    id: '/workspaces/',
    path: '/workspaces/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedKnowledgeIndexRoute = ProtectedKnowledgeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedKnowledgeRouteRoute,
} as any)
const ProtectedContactsIndexRoute = ProtectedContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => ProtectedRoute,
} as any)
const AuthAcceptInvitationInvitationIdRoute =
  AuthAcceptInvitationInvitationIdRouteImport.update({
    id: '/auth/accept-invitation/$invitationId',
    path: '/auth/accept-invitation/$invitationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProtectedOrganizationMembersRoute =
  ProtectedOrganizationMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => ProtectedOrganizationRouteRoute,
  } as any)
const ProtectedOrganizationInvitationsRoute =
  ProtectedOrganizationInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => ProtectedOrganizationRouteRoute,
  } as any)
const ProtectedKnowledgeTemplatesRoute =
  ProtectedKnowledgeTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => ProtectedKnowledgeRouteRoute,
  } as any)
const ProtectedKnowledgeClausesRoute =
  ProtectedKnowledgeClausesRouteImport.update({
    id: '/clauses',
    path: '/clauses',
    getParentRoute: () => ProtectedKnowledgeRouteRoute,
  } as any)
const ProtectedContactsContactIdRoute =
  ProtectedContactsContactIdRouteImport.update({
    id: '/contacts/$contactId',
    path: '/contacts/$contactId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedWorkspacesWorkspaceIdRouteRoute =
  ProtectedWorkspacesWorkspaceIdRouteRouteImport.update({
    id: '/workspaces/$workspaceId',
    path: '/workspaces/$workspaceId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedWorkspacesWorkspaceIdIndexRoute =
  ProtectedWorkspacesWorkspaceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedWorkspacesWorkspaceIdRouteRoute,
  } as any)
const ProtectedWorkspacesWorkspaceIdTimesheetsRoute =
  ProtectedWorkspacesWorkspaceIdTimesheetsRouteImport.update({
    id: '/timesheets',
    path: '/timesheets',
    getParentRoute: () => ProtectedWorkspacesWorkspaceIdRouteRoute,
  } as any)
const ProtectedWorkspacesWorkspaceIdPdfRoute =
  ProtectedWorkspacesWorkspaceIdPdfRouteImport.update({
    id: '/pdf',
    path: '/pdf',
    getParentRoute: () => ProtectedWorkspacesWorkspaceIdRouteRoute,
  } as any)
const ProtectedWorkspacesWorkspaceIdExpensesRoute =
  ProtectedWorkspacesWorkspaceIdExpensesRouteImport.update({
    id: '/expenses',
    path: '/expenses',
    getParentRoute: () => ProtectedWorkspacesWorkspaceIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/knowledge': typeof ProtectedKnowledgeRouteRouteWithChildren
  '/organization': typeof ProtectedOrganizationRouteRouteWithChildren
  '/auth/organization': typeof AuthOrganizationRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/': typeof AuthIndexRoute
  '/workspaces/$workspaceId': typeof ProtectedWorkspacesWorkspaceIdRouteRouteWithChildren
  '/contacts/$contactId': typeof ProtectedContactsContactIdRoute
  '/knowledge/clauses': typeof ProtectedKnowledgeClausesRoute
  '/knowledge/templates': typeof ProtectedKnowledgeTemplatesRoute
  '/organization/invitations': typeof ProtectedOrganizationInvitationsRoute
  '/organization/members': typeof ProtectedOrganizationMembersRoute
  '/auth/accept-invitation/$invitationId': typeof AuthAcceptInvitationInvitationIdRoute
  '/contacts/': typeof ProtectedContactsIndexRoute
  '/knowledge/': typeof ProtectedKnowledgeIndexRoute
  '/workspaces/': typeof ProtectedWorkspacesIndexRoute
  '/workspaces/$workspaceId/expenses': typeof ProtectedWorkspacesWorkspaceIdExpensesRoute
  '/workspaces/$workspaceId/pdf': typeof ProtectedWorkspacesWorkspaceIdPdfRoute
  '/workspaces/$workspaceId/timesheets': typeof ProtectedWorkspacesWorkspaceIdTimesheetsRoute
  '/workspaces/$workspaceId/': typeof ProtectedWorkspacesWorkspaceIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/organization': typeof ProtectedOrganizationRouteRouteWithChildren
  '/auth/organization': typeof AuthOrganizationRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth': typeof AuthIndexRoute
  '/contacts/$contactId': typeof ProtectedContactsContactIdRoute
  '/knowledge/clauses': typeof ProtectedKnowledgeClausesRoute
  '/knowledge/templates': typeof ProtectedKnowledgeTemplatesRoute
  '/organization/invitations': typeof ProtectedOrganizationInvitationsRoute
  '/organization/members': typeof ProtectedOrganizationMembersRoute
  '/auth/accept-invitation/$invitationId': typeof AuthAcceptInvitationInvitationIdRoute
  '/contacts': typeof ProtectedContactsIndexRoute
  '/knowledge': typeof ProtectedKnowledgeIndexRoute
  '/workspaces': typeof ProtectedWorkspacesIndexRoute
  '/workspaces/$workspaceId/expenses': typeof ProtectedWorkspacesWorkspaceIdExpensesRoute
  '/workspaces/$workspaceId/pdf': typeof ProtectedWorkspacesWorkspaceIdPdfRoute
  '/workspaces/$workspaceId/timesheets': typeof ProtectedWorkspacesWorkspaceIdTimesheetsRoute
  '/workspaces/$workspaceId': typeof ProtectedWorkspacesWorkspaceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/_protected/knowledge': typeof ProtectedKnowledgeRouteRouteWithChildren
  '/_protected/organization': typeof ProtectedOrganizationRouteRouteWithChildren
  '/auth/organization': typeof AuthOrganizationRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/': typeof AuthIndexRoute
  '/_protected/workspaces/$workspaceId': typeof ProtectedWorkspacesWorkspaceIdRouteRouteWithChildren
  '/_protected/contacts/$contactId': typeof ProtectedContactsContactIdRoute
  '/_protected/knowledge/clauses': typeof ProtectedKnowledgeClausesRoute
  '/_protected/knowledge/templates': typeof ProtectedKnowledgeTemplatesRoute
  '/_protected/organization/invitations': typeof ProtectedOrganizationInvitationsRoute
  '/_protected/organization/members': typeof ProtectedOrganizationMembersRoute
  '/auth/accept-invitation/$invitationId': typeof AuthAcceptInvitationInvitationIdRoute
  '/_protected/contacts/': typeof ProtectedContactsIndexRoute
  '/_protected/knowledge/': typeof ProtectedKnowledgeIndexRoute
  '/_protected/workspaces/': typeof ProtectedWorkspacesIndexRoute
  '/_protected/workspaces/$workspaceId/expenses': typeof ProtectedWorkspacesWorkspaceIdExpensesRoute
  '/_protected/workspaces/$workspaceId/pdf': typeof ProtectedWorkspacesWorkspaceIdPdfRoute
  '/_protected/workspaces/$workspaceId/timesheets': typeof ProtectedWorkspacesWorkspaceIdTimesheetsRoute
  '/_protected/workspaces/$workspaceId/': typeof ProtectedWorkspacesWorkspaceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/knowledge'
    | '/organization'
    | '/auth/organization'
    | '/auth/otp'
    | '/auth/'
    | '/workspaces/$workspaceId'
    | '/contacts/$contactId'
    | '/knowledge/clauses'
    | '/knowledge/templates'
    | '/organization/invitations'
    | '/organization/members'
    | '/auth/accept-invitation/$invitationId'
    | '/contacts/'
    | '/knowledge/'
    | '/workspaces/'
    | '/workspaces/$workspaceId/expenses'
    | '/workspaces/$workspaceId/pdf'
    | '/workspaces/$workspaceId/timesheets'
    | '/workspaces/$workspaceId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/organization'
    | '/auth/organization'
    | '/auth/otp'
    | '/auth'
    | '/contacts/$contactId'
    | '/knowledge/clauses'
    | '/knowledge/templates'
    | '/organization/invitations'
    | '/organization/members'
    | '/auth/accept-invitation/$invitationId'
    | '/contacts'
    | '/knowledge'
    | '/workspaces'
    | '/workspaces/$workspaceId/expenses'
    | '/workspaces/$workspaceId/pdf'
    | '/workspaces/$workspaceId/timesheets'
    | '/workspaces/$workspaceId'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/_protected/knowledge'
    | '/_protected/organization'
    | '/auth/organization'
    | '/auth/otp'
    | '/auth/'
    | '/_protected/workspaces/$workspaceId'
    | '/_protected/contacts/$contactId'
    | '/_protected/knowledge/clauses'
    | '/_protected/knowledge/templates'
    | '/_protected/organization/invitations'
    | '/_protected/organization/members'
    | '/auth/accept-invitation/$invitationId'
    | '/_protected/contacts/'
    | '/_protected/knowledge/'
    | '/_protected/workspaces/'
    | '/_protected/workspaces/$workspaceId/expenses'
    | '/_protected/workspaces/$workspaceId/pdf'
    | '/_protected/workspaces/$workspaceId/timesheets'
    | '/_protected/workspaces/$workspaceId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  AuthOrganizationRoute: typeof AuthOrganizationRoute
  AuthOtpRoute: typeof AuthOtpRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthAcceptInvitationInvitationIdRoute: typeof AuthAcceptInvitationInvitationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/otp': {
      id: '/auth/otp'
      path: '/auth/otp'
      fullPath: '/auth/otp'
      preLoaderRoute: typeof AuthOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/organization': {
      id: '/auth/organization'
      path: '/auth/organization'
      fullPath: '/auth/organization'
      preLoaderRoute: typeof AuthOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/organization': {
      id: '/_protected/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof ProtectedOrganizationRouteRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/knowledge': {
      id: '/_protected/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof ProtectedKnowledgeRouteRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/workspaces/': {
      id: '/_protected/workspaces/'
      path: '/workspaces'
      fullPath: '/workspaces/'
      preLoaderRoute: typeof ProtectedWorkspacesIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/knowledge/': {
      id: '/_protected/knowledge/'
      path: '/'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof ProtectedKnowledgeIndexRouteImport
      parentRoute: typeof ProtectedKnowledgeRouteRoute
    }
    '/_protected/contacts/': {
      id: '/_protected/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof ProtectedContactsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/auth/accept-invitation/$invitationId': {
      id: '/auth/accept-invitation/$invitationId'
      path: '/auth/accept-invitation/$invitationId'
      fullPath: '/auth/accept-invitation/$invitationId'
      preLoaderRoute: typeof AuthAcceptInvitationInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/organization/members': {
      id: '/_protected/organization/members'
      path: '/members'
      fullPath: '/organization/members'
      preLoaderRoute: typeof ProtectedOrganizationMembersRouteImport
      parentRoute: typeof ProtectedOrganizationRouteRoute
    }
    '/_protected/organization/invitations': {
      id: '/_protected/organization/invitations'
      path: '/invitations'
      fullPath: '/organization/invitations'
      preLoaderRoute: typeof ProtectedOrganizationInvitationsRouteImport
      parentRoute: typeof ProtectedOrganizationRouteRoute
    }
    '/_protected/knowledge/templates': {
      id: '/_protected/knowledge/templates'
      path: '/templates'
      fullPath: '/knowledge/templates'
      preLoaderRoute: typeof ProtectedKnowledgeTemplatesRouteImport
      parentRoute: typeof ProtectedKnowledgeRouteRoute
    }
    '/_protected/knowledge/clauses': {
      id: '/_protected/knowledge/clauses'
      path: '/clauses'
      fullPath: '/knowledge/clauses'
      preLoaderRoute: typeof ProtectedKnowledgeClausesRouteImport
      parentRoute: typeof ProtectedKnowledgeRouteRoute
    }
    '/_protected/contacts/$contactId': {
      id: '/_protected/contacts/$contactId'
      path: '/contacts/$contactId'
      fullPath: '/contacts/$contactId'
      preLoaderRoute: typeof ProtectedContactsContactIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/workspaces/$workspaceId': {
      id: '/_protected/workspaces/$workspaceId'
      path: '/workspaces/$workspaceId'
      fullPath: '/workspaces/$workspaceId'
      preLoaderRoute: typeof ProtectedWorkspacesWorkspaceIdRouteRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/workspaces/$workspaceId/': {
      id: '/_protected/workspaces/$workspaceId/'
      path: '/'
      fullPath: '/workspaces/$workspaceId/'
      preLoaderRoute: typeof ProtectedWorkspacesWorkspaceIdIndexRouteImport
      parentRoute: typeof ProtectedWorkspacesWorkspaceIdRouteRoute
    }
    '/_protected/workspaces/$workspaceId/timesheets': {
      id: '/_protected/workspaces/$workspaceId/timesheets'
      path: '/timesheets'
      fullPath: '/workspaces/$workspaceId/timesheets'
      preLoaderRoute: typeof ProtectedWorkspacesWorkspaceIdTimesheetsRouteImport
      parentRoute: typeof ProtectedWorkspacesWorkspaceIdRouteRoute
    }
    '/_protected/workspaces/$workspaceId/pdf': {
      id: '/_protected/workspaces/$workspaceId/pdf'
      path: '/pdf'
      fullPath: '/workspaces/$workspaceId/pdf'
      preLoaderRoute: typeof ProtectedWorkspacesWorkspaceIdPdfRouteImport
      parentRoute: typeof ProtectedWorkspacesWorkspaceIdRouteRoute
    }
    '/_protected/workspaces/$workspaceId/expenses': {
      id: '/_protected/workspaces/$workspaceId/expenses'
      path: '/expenses'
      fullPath: '/workspaces/$workspaceId/expenses'
      preLoaderRoute: typeof ProtectedWorkspacesWorkspaceIdExpensesRouteImport
      parentRoute: typeof ProtectedWorkspacesWorkspaceIdRouteRoute
    }
  }
}

interface ProtectedKnowledgeRouteRouteChildren {
  ProtectedKnowledgeClausesRoute: typeof ProtectedKnowledgeClausesRoute
  ProtectedKnowledgeTemplatesRoute: typeof ProtectedKnowledgeTemplatesRoute
  ProtectedKnowledgeIndexRoute: typeof ProtectedKnowledgeIndexRoute
}

const ProtectedKnowledgeRouteRouteChildren: ProtectedKnowledgeRouteRouteChildren =
  {
    ProtectedKnowledgeClausesRoute: ProtectedKnowledgeClausesRoute,
    ProtectedKnowledgeTemplatesRoute: ProtectedKnowledgeTemplatesRoute,
    ProtectedKnowledgeIndexRoute: ProtectedKnowledgeIndexRoute,
  }

const ProtectedKnowledgeRouteRouteWithChildren =
  ProtectedKnowledgeRouteRoute._addFileChildren(
    ProtectedKnowledgeRouteRouteChildren,
  )

interface ProtectedOrganizationRouteRouteChildren {
  ProtectedOrganizationInvitationsRoute: typeof ProtectedOrganizationInvitationsRoute
  ProtectedOrganizationMembersRoute: typeof ProtectedOrganizationMembersRoute
}

const ProtectedOrganizationRouteRouteChildren: ProtectedOrganizationRouteRouteChildren =
  {
    ProtectedOrganizationInvitationsRoute:
      ProtectedOrganizationInvitationsRoute,
    ProtectedOrganizationMembersRoute: ProtectedOrganizationMembersRoute,
  }

const ProtectedOrganizationRouteRouteWithChildren =
  ProtectedOrganizationRouteRoute._addFileChildren(
    ProtectedOrganizationRouteRouteChildren,
  )

interface ProtectedWorkspacesWorkspaceIdRouteRouteChildren {
  ProtectedWorkspacesWorkspaceIdExpensesRoute: typeof ProtectedWorkspacesWorkspaceIdExpensesRoute
  ProtectedWorkspacesWorkspaceIdPdfRoute: typeof ProtectedWorkspacesWorkspaceIdPdfRoute
  ProtectedWorkspacesWorkspaceIdTimesheetsRoute: typeof ProtectedWorkspacesWorkspaceIdTimesheetsRoute
  ProtectedWorkspacesWorkspaceIdIndexRoute: typeof ProtectedWorkspacesWorkspaceIdIndexRoute
}

const ProtectedWorkspacesWorkspaceIdRouteRouteChildren: ProtectedWorkspacesWorkspaceIdRouteRouteChildren =
  {
    ProtectedWorkspacesWorkspaceIdExpensesRoute:
      ProtectedWorkspacesWorkspaceIdExpensesRoute,
    ProtectedWorkspacesWorkspaceIdPdfRoute:
      ProtectedWorkspacesWorkspaceIdPdfRoute,
    ProtectedWorkspacesWorkspaceIdTimesheetsRoute:
      ProtectedWorkspacesWorkspaceIdTimesheetsRoute,
    ProtectedWorkspacesWorkspaceIdIndexRoute:
      ProtectedWorkspacesWorkspaceIdIndexRoute,
  }

const ProtectedWorkspacesWorkspaceIdRouteRouteWithChildren =
  ProtectedWorkspacesWorkspaceIdRouteRoute._addFileChildren(
    ProtectedWorkspacesWorkspaceIdRouteRouteChildren,
  )

interface ProtectedRouteChildren {
  ProtectedKnowledgeRouteRoute: typeof ProtectedKnowledgeRouteRouteWithChildren
  ProtectedOrganizationRouteRoute: typeof ProtectedOrganizationRouteRouteWithChildren
  ProtectedWorkspacesWorkspaceIdRouteRoute: typeof ProtectedWorkspacesWorkspaceIdRouteRouteWithChildren
  ProtectedContactsContactIdRoute: typeof ProtectedContactsContactIdRoute
  ProtectedContactsIndexRoute: typeof ProtectedContactsIndexRoute
  ProtectedWorkspacesIndexRoute: typeof ProtectedWorkspacesIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedKnowledgeRouteRoute: ProtectedKnowledgeRouteRouteWithChildren,
  ProtectedOrganizationRouteRoute: ProtectedOrganizationRouteRouteWithChildren,
  ProtectedWorkspacesWorkspaceIdRouteRoute:
    ProtectedWorkspacesWorkspaceIdRouteRouteWithChildren,
  ProtectedContactsContactIdRoute: ProtectedContactsContactIdRoute,
  ProtectedContactsIndexRoute: ProtectedContactsIndexRoute,
  ProtectedWorkspacesIndexRoute: ProtectedWorkspacesIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  AuthOrganizationRoute: AuthOrganizationRoute,
  AuthOtpRoute: AuthOtpRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthAcceptInvitationInvitationIdRoute: AuthAcceptInvitationInvitationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
