/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DevRouteImport } from './routes/dev'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as OnboardingRouteRouteImport } from './routes/onboarding/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as McpOauthCallbackRouteImport } from './routes/mcp.oauth-callback'
import { Route as AuthOtpRouteImport } from './routes/auth/otp'
import { Route as AuthOrganizationRouteImport } from './routes/auth/organization'
import { Route as ProtectedSettingsRouteRouteImport } from './routes/_protected.settings/route'
import { Route as ProtectedKnowledgeRouteRouteImport } from './routes/_protected.knowledge/route'
import { Route as ProtectedChatRouteRouteImport } from './routes/_protected.chat/route'
import { Route as ProtectedWorkspacesIndexRouteImport } from './routes/_protected.workspaces/index'
import { Route as ProtectedTodosIndexRouteImport } from './routes/_protected.todos/index'
import { Route as ProtectedSettingsIndexRouteImport } from './routes/_protected.settings/index'
import { Route as ProtectedKnowledgeIndexRouteImport } from './routes/_protected.knowledge/index'
import { Route as ProtectedContactsIndexRouteImport } from './routes/_protected.contacts/index'
import { Route as ProtectedChatIndexRouteImport } from './routes/_protected.chat/index'
import { Route as AuthAcceptInvitationInvitationIdRouteImport } from './routes/auth/accept-invitation.$invitationId'
import { Route as ProtectedKnowledgeTemplatesRouteImport } from './routes/_protected.knowledge/templates'
import { Route as ProtectedKnowledgeSkillsRouteImport } from './routes/_protected.knowledge/skills'
import { Route as ProtectedKnowledgePromptsRouteImport } from './routes/_protected.knowledge/prompts'
import { Route as ProtectedKnowledgeMcpRouteImport } from './routes/_protected.knowledge/mcp'
import { Route as ProtectedKnowledgeClausesRouteImport } from './routes/_protected.knowledge/clauses'
import { Route as ProtectedContactsContactIdRouteImport } from './routes/_protected.contacts/$contactId'
import { Route as ProtectedChatNewRouteImport } from './routes/_protected.chat/new'
import { Route as ProtectedChatThreadIdRouteImport } from './routes/_protected.chat/$threadId'
import { Route as ProtectedWorkspacesWorkspaceIdRouteRouteImport } from './routes/_protected.workspaces/$workspaceId/route'
import { Route as ProtectedSettingsOrganizationRouteRouteImport } from './routes/_protected.settings/organization.route'
import { Route as ProtectedKnowledgeCaseRouteRouteImport } from './routes/_protected.knowledge/case/route'
import { Route as ProtectedWorkspacesWorkspaceIdIndexRouteImport } from './routes/_protected.workspaces/$workspaceId/index'
import { Route as ProtectedSettingsOrganizationIndexRouteImport } from './routes/_protected.settings/organization.index'
import { Route as ProtectedKnowledgeCaseIndexRouteImport } from './routes/_protected.knowledge/case/index'
import { Route as ProtectedWorkspacesWorkspaceIdTimesheetsRouteImport } from './routes/_protected.workspaces/$workspaceId/timesheets'
import { Route as ProtectedWorkspacesWorkspaceIdInvoicesRouteImport } from './routes/_protected.workspaces/$workspaceId/invoices'
import { Route as ProtectedWorkspacesWorkspaceIdExpensesRouteImport } from './routes/_protected.workspaces/$workspaceId/expenses'
import { Route as ProtectedSettingsOrganizationMembersRouteImport } from './routes/_protected.settings/organization.members'
import { Route as ProtectedSettingsOrganizationMatterNumberingRouteImport } from './routes/_protected.settings/organization.matter-numbering'
import { Route as ProtectedSettingsOrganizationAnonymizationRouteImport } from './routes/_protected.settings/organization.anonymization'
import { Route as ProtectedSettingsOrganizationAiRouteImport } from './routes/_protected.settings/organization.ai'
import { Route as ProtectedSettingsAccountProfileRouteImport } from './routes/_protected.settings/account.profile'
import { Route as ProtectedSettingsAccountDesktopRouteImport } from './routes/_protected.settings/account.desktop'
import { Route as ProtectedKnowledgeCaseDecisionIdRouteImport } from './routes/_protected.knowledge/case/$decisionId'
import { Route as ProtectedWorkspacesWorkspaceIdViewIdRouteRouteImport } from './routes/_protected.workspaces/$workspaceId/$viewId.route'
import { Route as ProtectedWorkspacesWorkspaceIdViewIdIndexRouteImport } from './routes/_protected.workspaces/$workspaceId/$viewId.index'
import { Route as ProtectedWorkspacesWorkspaceIdInvoicesInvoiceIdRouteImport } from './routes/_protected.workspaces/$workspaceId/invoices/$invoiceId'
import { Route as ProtectedWorkspacesWorkspaceIdEntitiesEntityIdRouteImport } from './routes/_protected.workspaces/$workspaceId/entities/$entityId'
import { Route as ProtectedWorkspacesWorkspaceIdViewIdDocumentRouteImport } from './routes/_protected.workspaces/$workspaceId/$viewId.document'
import { Route as ProtectedChatWorkspacesWorkspaceIdNewRouteImport } from './routes/_protected.chat/workspaces/$workspaceId/new'
import { Route as ProtectedChatWorkspacesWorkspaceIdThreadIdRouteImport } from './routes/_protected.chat/workspaces/$workspaceId/$threadId'

const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRouteRoute = OnboardingRouteRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const McpOauthCallbackRoute = McpOauthCallbackRouteImport.update({
  id: '/mcp/oauth-callback',
  path: '/mcp/oauth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthOtpRoute = AuthOtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthOrganizationRoute = AuthOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ProtectedSettingsRouteRoute = ProtectedSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedKnowledgeRouteRoute = ProtectedKnowledgeRouteRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedChatRouteRoute = ProtectedChatRouteRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedWorkspacesIndexRoute =
  ProtectedWorkspacesIndexRouteImport.update({
    id: '/workspaces/',
    path: '/workspaces/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedTodosIndexRoute = ProtectedTodosIndexRouteImport.update({
  id: '/todos/',
  path: '/todos/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsIndexRoute = ProtectedSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedSettingsRouteRoute,
} as any)
const ProtectedKnowledgeIndexRoute = ProtectedKnowledgeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedKnowledgeRouteRoute,
} as any)
const ProtectedContactsIndexRoute = ProtectedContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedChatIndexRoute = ProtectedChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedChatRouteRoute,
} as any)
const AuthAcceptInvitationInvitationIdRoute =
  AuthAcceptInvitationInvitationIdRouteImport.update({
    id: '/accept-invitation/$invitationId',
    path: '/accept-invitation/$invitationId',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const ProtectedKnowledgeTemplatesRoute =
  ProtectedKnowledgeTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => ProtectedKnowledgeRouteRoute,
  } as any)
const ProtectedKnowledgeSkillsRoute =
  ProtectedKnowledgeSkillsRouteImport.update({
    id: '/skills',
    path: '/skills',
    getParentRoute: () => ProtectedKnowledgeRouteRoute,
  } as any)
const ProtectedKnowledgePromptsRoute =
  ProtectedKnowledgePromptsRouteImport.update({
    id: '/prompts',
    path: '/prompts',
    getParentRoute: () => ProtectedKnowledgeRouteRoute,
  } as any)
const ProtectedKnowledgeMcpRoute = ProtectedKnowledgeMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => ProtectedKnowledgeRouteRoute,
} as any)
const ProtectedKnowledgeClausesRoute =
  ProtectedKnowledgeClausesRouteImport.update({
    id: '/clauses',
    path: '/clauses',
    getParentRoute: () => ProtectedKnowledgeRouteRoute,
  } as any)
const ProtectedContactsContactIdRoute =
  ProtectedContactsContactIdRouteImport.update({
    id: '/contacts/$contactId',
    path: '/contacts/$contactId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedChatNewRoute = ProtectedChatNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProtectedChatRouteRoute,
} as any)
const ProtectedChatThreadIdRoute = ProtectedChatThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ProtectedChatRouteRoute,
} as any)
const ProtectedWorkspacesWorkspaceIdRouteRoute =
  ProtectedWorkspacesWorkspaceIdRouteRouteImport.update({
    id: '/workspaces/$workspaceId',
    path: '/workspaces/$workspaceId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedSettingsOrganizationRouteRoute =
  ProtectedSettingsOrganizationRouteRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => ProtectedSettingsRouteRoute,
  } as any)
const ProtectedKnowledgeCaseRouteRoute =
  ProtectedKnowledgeCaseRouteRouteImport.update({
    id: '/case',
    path: '/case',
    getParentRoute: () => ProtectedKnowledgeRouteRoute,
  } as any)
const ProtectedWorkspacesWorkspaceIdIndexRoute =
  ProtectedWorkspacesWorkspaceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedWorkspacesWorkspaceIdRouteRoute,
  } as any)
const ProtectedSettingsOrganizationIndexRoute =
  ProtectedSettingsOrganizationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedSettingsOrganizationRouteRoute,
  } as any)
const ProtectedKnowledgeCaseIndexRoute =
  ProtectedKnowledgeCaseIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedKnowledgeCaseRouteRoute,
  } as any)
const ProtectedWorkspacesWorkspaceIdTimesheetsRoute =
  ProtectedWorkspacesWorkspaceIdTimesheetsRouteImport.update({
    id: '/timesheets',
    path: '/timesheets',
    getParentRoute: () => ProtectedWorkspacesWorkspaceIdRouteRoute,
  } as any)
const ProtectedWorkspacesWorkspaceIdInvoicesRoute =
  ProtectedWorkspacesWorkspaceIdInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => ProtectedWorkspacesWorkspaceIdRouteRoute,
  } as any)
const ProtectedWorkspacesWorkspaceIdExpensesRoute =
  ProtectedWorkspacesWorkspaceIdExpensesRouteImport.update({
    id: '/expenses',
    path: '/expenses',
    getParentRoute: () => ProtectedWorkspacesWorkspaceIdRouteRoute,
  } as any)
const ProtectedSettingsOrganizationMembersRoute =
  ProtectedSettingsOrganizationMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => ProtectedSettingsOrganizationRouteRoute,
  } as any)
const ProtectedSettingsOrganizationMatterNumberingRoute =
  ProtectedSettingsOrganizationMatterNumberingRouteImport.update({
    id: '/matter-numbering',
    path: '/matter-numbering',
    getParentRoute: () => ProtectedSettingsOrganizationRouteRoute,
  } as any)
const ProtectedSettingsOrganizationAnonymizationRoute =
  ProtectedSettingsOrganizationAnonymizationRouteImport.update({
    id: '/anonymization',
    path: '/anonymization',
    getParentRoute: () => ProtectedSettingsOrganizationRouteRoute,
  } as any)
const ProtectedSettingsOrganizationAiRoute =
  ProtectedSettingsOrganizationAiRouteImport.update({
    id: '/ai',
    path: '/ai',
    getParentRoute: () => ProtectedSettingsOrganizationRouteRoute,
  } as any)
const ProtectedSettingsAccountProfileRoute =
  ProtectedSettingsAccountProfileRouteImport.update({
    id: '/account/profile',
    path: '/account/profile',
    getParentRoute: () => ProtectedSettingsRouteRoute,
  } as any)
const ProtectedSettingsAccountDesktopRoute =
  ProtectedSettingsAccountDesktopRouteImport.update({
    id: '/account/desktop',
    path: '/account/desktop',
    getParentRoute: () => ProtectedSettingsRouteRoute,
  } as any)
const ProtectedKnowledgeCaseDecisionIdRoute =
  ProtectedKnowledgeCaseDecisionIdRouteImport.update({
    id: '/$decisionId',
    path: '/$decisionId',
    getParentRoute: () => ProtectedKnowledgeCaseRouteRoute,
  } as any)
const ProtectedWorkspacesWorkspaceIdViewIdRouteRoute =
  ProtectedWorkspacesWorkspaceIdViewIdRouteRouteImport.update({
    id: '/$viewId',
    path: '/$viewId',
    getParentRoute: () => ProtectedWorkspacesWorkspaceIdRouteRoute,
  } as any)
const ProtectedWorkspacesWorkspaceIdViewIdIndexRoute =
  ProtectedWorkspacesWorkspaceIdViewIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedWorkspacesWorkspaceIdViewIdRouteRoute,
  } as any)
const ProtectedWorkspacesWorkspaceIdInvoicesInvoiceIdRoute =
  ProtectedWorkspacesWorkspaceIdInvoicesInvoiceIdRouteImport.update({
    id: '/$invoiceId',
    path: '/$invoiceId',
    getParentRoute: () => ProtectedWorkspacesWorkspaceIdInvoicesRoute,
  } as any)
const ProtectedWorkspacesWorkspaceIdEntitiesEntityIdRoute =
  ProtectedWorkspacesWorkspaceIdEntitiesEntityIdRouteImport.update({
    id: '/entities/$entityId',
    path: '/entities/$entityId',
    getParentRoute: () => ProtectedWorkspacesWorkspaceIdRouteRoute,
  } as any)
const ProtectedWorkspacesWorkspaceIdViewIdDocumentRoute =
  ProtectedWorkspacesWorkspaceIdViewIdDocumentRouteImport.update({
    id: '/document',
    path: '/document',
    getParentRoute: () => ProtectedWorkspacesWorkspaceIdViewIdRouteRoute,
  } as any)
const ProtectedChatWorkspacesWorkspaceIdNewRoute =
  ProtectedChatWorkspacesWorkspaceIdNewRouteImport.update({
    id: '/workspaces/$workspaceId/new',
    path: '/workspaces/$workspaceId/new',
    getParentRoute: () => ProtectedChatRouteRoute,
  } as any)
const ProtectedChatWorkspacesWorkspaceIdThreadIdRoute =
  ProtectedChatWorkspacesWorkspaceIdThreadIdRouteImport.update({
    id: '/workspaces/$workspaceId/$threadId',
    path: '/workspaces/$workspaceId/$threadId',
    getParentRoute: () => ProtectedChatRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRoute
  '/consent': typeof ConsentRoute
  '/dev': typeof DevRoute
  '/chat': typeof ProtectedChatRouteRouteWithChildren
  '/knowledge': typeof ProtectedKnowledgeRouteRouteWithChildren
  '/settings': typeof ProtectedSettingsRouteRouteWithChildren
  '/auth/organization': typeof AuthOrganizationRoute
  '/auth/otp': typeof AuthOtpRoute
  '/mcp/oauth-callback': typeof McpOauthCallbackRoute
  '/auth/': typeof AuthIndexRoute
  '/knowledge/case': typeof ProtectedKnowledgeCaseRouteRouteWithChildren
  '/settings/organization': typeof ProtectedSettingsOrganizationRouteRouteWithChildren
  '/workspaces/$workspaceId': typeof ProtectedWorkspacesWorkspaceIdRouteRouteWithChildren
  '/chat/$threadId': typeof ProtectedChatThreadIdRoute
  '/chat/new': typeof ProtectedChatNewRoute
  '/contacts/$contactId': typeof ProtectedContactsContactIdRoute
  '/knowledge/clauses': typeof ProtectedKnowledgeClausesRoute
  '/knowledge/mcp': typeof ProtectedKnowledgeMcpRoute
  '/knowledge/prompts': typeof ProtectedKnowledgePromptsRoute
  '/knowledge/skills': typeof ProtectedKnowledgeSkillsRoute
  '/knowledge/templates': typeof ProtectedKnowledgeTemplatesRoute
  '/auth/accept-invitation/$invitationId': typeof AuthAcceptInvitationInvitationIdRoute
  '/chat/': typeof ProtectedChatIndexRoute
  '/contacts/': typeof ProtectedContactsIndexRoute
  '/knowledge/': typeof ProtectedKnowledgeIndexRoute
  '/settings/': typeof ProtectedSettingsIndexRoute
  '/todos/': typeof ProtectedTodosIndexRoute
  '/workspaces/': typeof ProtectedWorkspacesIndexRoute
  '/workspaces/$workspaceId/$viewId': typeof ProtectedWorkspacesWorkspaceIdViewIdRouteRouteWithChildren
  '/knowledge/case/$decisionId': typeof ProtectedKnowledgeCaseDecisionIdRoute
  '/settings/account/desktop': typeof ProtectedSettingsAccountDesktopRoute
  '/settings/account/profile': typeof ProtectedSettingsAccountProfileRoute
  '/settings/organization/ai': typeof ProtectedSettingsOrganizationAiRoute
  '/settings/organization/anonymization': typeof ProtectedSettingsOrganizationAnonymizationRoute
  '/settings/organization/matter-numbering': typeof ProtectedSettingsOrganizationMatterNumberingRoute
  '/settings/organization/members': typeof ProtectedSettingsOrganizationMembersRoute
  '/workspaces/$workspaceId/expenses': typeof ProtectedWorkspacesWorkspaceIdExpensesRoute
  '/workspaces/$workspaceId/invoices': typeof ProtectedWorkspacesWorkspaceIdInvoicesRouteWithChildren
  '/workspaces/$workspaceId/timesheets': typeof ProtectedWorkspacesWorkspaceIdTimesheetsRoute
  '/knowledge/case/': typeof ProtectedKnowledgeCaseIndexRoute
  '/settings/organization/': typeof ProtectedSettingsOrganizationIndexRoute
  '/workspaces/$workspaceId/': typeof ProtectedWorkspacesWorkspaceIdIndexRoute
  '/chat/workspaces/$workspaceId/$threadId': typeof ProtectedChatWorkspacesWorkspaceIdThreadIdRoute
  '/chat/workspaces/$workspaceId/new': typeof ProtectedChatWorkspacesWorkspaceIdNewRoute
  '/workspaces/$workspaceId/$viewId/document': typeof ProtectedWorkspacesWorkspaceIdViewIdDocumentRoute
  '/workspaces/$workspaceId/entities/$entityId': typeof ProtectedWorkspacesWorkspaceIdEntitiesEntityIdRoute
  '/workspaces/$workspaceId/invoices/$invoiceId': typeof ProtectedWorkspacesWorkspaceIdInvoicesInvoiceIdRoute
  '/workspaces/$workspaceId/$viewId/': typeof ProtectedWorkspacesWorkspaceIdViewIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRouteRoute
  '/consent': typeof ConsentRoute
  '/dev': typeof DevRoute
  '/auth/organization': typeof AuthOrganizationRoute
  '/auth/otp': typeof AuthOtpRoute
  '/mcp/oauth-callback': typeof McpOauthCallbackRoute
  '/auth': typeof AuthIndexRoute
  '/chat/$threadId': typeof ProtectedChatThreadIdRoute
  '/chat/new': typeof ProtectedChatNewRoute
  '/contacts/$contactId': typeof ProtectedContactsContactIdRoute
  '/knowledge/clauses': typeof ProtectedKnowledgeClausesRoute
  '/knowledge/mcp': typeof ProtectedKnowledgeMcpRoute
  '/knowledge/prompts': typeof ProtectedKnowledgePromptsRoute
  '/knowledge/skills': typeof ProtectedKnowledgeSkillsRoute
  '/knowledge/templates': typeof ProtectedKnowledgeTemplatesRoute
  '/auth/accept-invitation/$invitationId': typeof AuthAcceptInvitationInvitationIdRoute
  '/chat': typeof ProtectedChatIndexRoute
  '/contacts': typeof ProtectedContactsIndexRoute
  '/knowledge': typeof ProtectedKnowledgeIndexRoute
  '/settings': typeof ProtectedSettingsIndexRoute
  '/todos': typeof ProtectedTodosIndexRoute
  '/workspaces': typeof ProtectedWorkspacesIndexRoute
  '/knowledge/case/$decisionId': typeof ProtectedKnowledgeCaseDecisionIdRoute
  '/settings/account/desktop': typeof ProtectedSettingsAccountDesktopRoute
  '/settings/account/profile': typeof ProtectedSettingsAccountProfileRoute
  '/settings/organization/ai': typeof ProtectedSettingsOrganizationAiRoute
  '/settings/organization/anonymization': typeof ProtectedSettingsOrganizationAnonymizationRoute
  '/settings/organization/matter-numbering': typeof ProtectedSettingsOrganizationMatterNumberingRoute
  '/settings/organization/members': typeof ProtectedSettingsOrganizationMembersRoute
  '/workspaces/$workspaceId/expenses': typeof ProtectedWorkspacesWorkspaceIdExpensesRoute
  '/workspaces/$workspaceId/invoices': typeof ProtectedWorkspacesWorkspaceIdInvoicesRouteWithChildren
  '/workspaces/$workspaceId/timesheets': typeof ProtectedWorkspacesWorkspaceIdTimesheetsRoute
  '/knowledge/case': typeof ProtectedKnowledgeCaseIndexRoute
  '/settings/organization': typeof ProtectedSettingsOrganizationIndexRoute
  '/workspaces/$workspaceId': typeof ProtectedWorkspacesWorkspaceIdIndexRoute
  '/chat/workspaces/$workspaceId/$threadId': typeof ProtectedChatWorkspacesWorkspaceIdThreadIdRoute
  '/chat/workspaces/$workspaceId/new': typeof ProtectedChatWorkspacesWorkspaceIdNewRoute
  '/workspaces/$workspaceId/$viewId/document': typeof ProtectedWorkspacesWorkspaceIdViewIdDocumentRoute
  '/workspaces/$workspaceId/entities/$entityId': typeof ProtectedWorkspacesWorkspaceIdEntitiesEntityIdRoute
  '/workspaces/$workspaceId/invoices/$invoiceId': typeof ProtectedWorkspacesWorkspaceIdInvoicesInvoiceIdRoute
  '/workspaces/$workspaceId/$viewId': typeof ProtectedWorkspacesWorkspaceIdViewIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/consent': typeof ConsentRoute
  '/dev': typeof DevRoute
  '/_protected/chat': typeof ProtectedChatRouteRouteWithChildren
  '/_protected/knowledge': typeof ProtectedKnowledgeRouteRouteWithChildren
  '/_protected/settings': typeof ProtectedSettingsRouteRouteWithChildren
  '/auth/organization': typeof AuthOrganizationRoute
  '/auth/otp': typeof AuthOtpRoute
  '/mcp/oauth-callback': typeof McpOauthCallbackRoute
  '/auth/': typeof AuthIndexRoute
  '/_protected/knowledge/case': typeof ProtectedKnowledgeCaseRouteRouteWithChildren
  '/_protected/settings/organization': typeof ProtectedSettingsOrganizationRouteRouteWithChildren
  '/_protected/workspaces/$workspaceId': typeof ProtectedWorkspacesWorkspaceIdRouteRouteWithChildren
  '/_protected/chat/$threadId': typeof ProtectedChatThreadIdRoute
  '/_protected/chat/new': typeof ProtectedChatNewRoute
  '/_protected/contacts/$contactId': typeof ProtectedContactsContactIdRoute
  '/_protected/knowledge/clauses': typeof ProtectedKnowledgeClausesRoute
  '/_protected/knowledge/mcp': typeof ProtectedKnowledgeMcpRoute
  '/_protected/knowledge/prompts': typeof ProtectedKnowledgePromptsRoute
  '/_protected/knowledge/skills': typeof ProtectedKnowledgeSkillsRoute
  '/_protected/knowledge/templates': typeof ProtectedKnowledgeTemplatesRoute
  '/auth/accept-invitation/$invitationId': typeof AuthAcceptInvitationInvitationIdRoute
  '/_protected/chat/': typeof ProtectedChatIndexRoute
  '/_protected/contacts/': typeof ProtectedContactsIndexRoute
  '/_protected/knowledge/': typeof ProtectedKnowledgeIndexRoute
  '/_protected/settings/': typeof ProtectedSettingsIndexRoute
  '/_protected/todos/': typeof ProtectedTodosIndexRoute
  '/_protected/workspaces/': typeof ProtectedWorkspacesIndexRoute
  '/_protected/workspaces/$workspaceId/$viewId': typeof ProtectedWorkspacesWorkspaceIdViewIdRouteRouteWithChildren
  '/_protected/knowledge/case/$decisionId': typeof ProtectedKnowledgeCaseDecisionIdRoute
  '/_protected/settings/account/desktop': typeof ProtectedSettingsAccountDesktopRoute
  '/_protected/settings/account/profile': typeof ProtectedSettingsAccountProfileRoute
  '/_protected/settings/organization/ai': typeof ProtectedSettingsOrganizationAiRoute
  '/_protected/settings/organization/anonymization': typeof ProtectedSettingsOrganizationAnonymizationRoute
  '/_protected/settings/organization/matter-numbering': typeof ProtectedSettingsOrganizationMatterNumberingRoute
  '/_protected/settings/organization/members': typeof ProtectedSettingsOrganizationMembersRoute
  '/_protected/workspaces/$workspaceId/expenses': typeof ProtectedWorkspacesWorkspaceIdExpensesRoute
  '/_protected/workspaces/$workspaceId/invoices': typeof ProtectedWorkspacesWorkspaceIdInvoicesRouteWithChildren
  '/_protected/workspaces/$workspaceId/timesheets': typeof ProtectedWorkspacesWorkspaceIdTimesheetsRoute
  '/_protected/knowledge/case/': typeof ProtectedKnowledgeCaseIndexRoute
  '/_protected/settings/organization/': typeof ProtectedSettingsOrganizationIndexRoute
  '/_protected/workspaces/$workspaceId/': typeof ProtectedWorkspacesWorkspaceIdIndexRoute
  '/_protected/chat/workspaces/$workspaceId/$threadId': typeof ProtectedChatWorkspacesWorkspaceIdThreadIdRoute
  '/_protected/chat/workspaces/$workspaceId/new': typeof ProtectedChatWorkspacesWorkspaceIdNewRoute
  '/_protected/workspaces/$workspaceId/$viewId/document': typeof ProtectedWorkspacesWorkspaceIdViewIdDocumentRoute
  '/_protected/workspaces/$workspaceId/entities/$entityId': typeof ProtectedWorkspacesWorkspaceIdEntitiesEntityIdRoute
  '/_protected/workspaces/$workspaceId/invoices/$invoiceId': typeof ProtectedWorkspacesWorkspaceIdInvoicesInvoiceIdRoute
  '/_protected/workspaces/$workspaceId/$viewId/': typeof ProtectedWorkspacesWorkspaceIdViewIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/consent'
    | '/dev'
    | '/chat'
    | '/knowledge'
    | '/settings'
    | '/auth/organization'
    | '/auth/otp'
    | '/mcp/oauth-callback'
    | '/auth/'
    | '/knowledge/case'
    | '/settings/organization'
    | '/workspaces/$workspaceId'
    | '/chat/$threadId'
    | '/chat/new'
    | '/contacts/$contactId'
    | '/knowledge/clauses'
    | '/knowledge/mcp'
    | '/knowledge/prompts'
    | '/knowledge/skills'
    | '/knowledge/templates'
    | '/auth/accept-invitation/$invitationId'
    | '/chat/'
    | '/contacts/'
    | '/knowledge/'
    | '/settings/'
    | '/todos/'
    | '/workspaces/'
    | '/workspaces/$workspaceId/$viewId'
    | '/knowledge/case/$decisionId'
    | '/settings/account/desktop'
    | '/settings/account/profile'
    | '/settings/organization/ai'
    | '/settings/organization/anonymization'
    | '/settings/organization/matter-numbering'
    | '/settings/organization/members'
    | '/workspaces/$workspaceId/expenses'
    | '/workspaces/$workspaceId/invoices'
    | '/workspaces/$workspaceId/timesheets'
    | '/knowledge/case/'
    | '/settings/organization/'
    | '/workspaces/$workspaceId/'
    | '/chat/workspaces/$workspaceId/$threadId'
    | '/chat/workspaces/$workspaceId/new'
    | '/workspaces/$workspaceId/$viewId/document'
    | '/workspaces/$workspaceId/entities/$entityId'
    | '/workspaces/$workspaceId/invoices/$invoiceId'
    | '/workspaces/$workspaceId/$viewId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/consent'
    | '/dev'
    | '/auth/organization'
    | '/auth/otp'
    | '/mcp/oauth-callback'
    | '/auth'
    | '/chat/$threadId'
    | '/chat/new'
    | '/contacts/$contactId'
    | '/knowledge/clauses'
    | '/knowledge/mcp'
    | '/knowledge/prompts'
    | '/knowledge/skills'
    | '/knowledge/templates'
    | '/auth/accept-invitation/$invitationId'
    | '/chat'
    | '/contacts'
    | '/knowledge'
    | '/settings'
    | '/todos'
    | '/workspaces'
    | '/knowledge/case/$decisionId'
    | '/settings/account/desktop'
    | '/settings/account/profile'
    | '/settings/organization/ai'
    | '/settings/organization/anonymization'
    | '/settings/organization/matter-numbering'
    | '/settings/organization/members'
    | '/workspaces/$workspaceId/expenses'
    | '/workspaces/$workspaceId/invoices'
    | '/workspaces/$workspaceId/timesheets'
    | '/knowledge/case'
    | '/settings/organization'
    | '/workspaces/$workspaceId'
    | '/chat/workspaces/$workspaceId/$threadId'
    | '/chat/workspaces/$workspaceId/new'
    | '/workspaces/$workspaceId/$viewId/document'
    | '/workspaces/$workspaceId/entities/$entityId'
    | '/workspaces/$workspaceId/invoices/$invoiceId'
    | '/workspaces/$workspaceId/$viewId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/onboarding'
    | '/_protected'
    | '/consent'
    | '/dev'
    | '/_protected/chat'
    | '/_protected/knowledge'
    | '/_protected/settings'
    | '/auth/organization'
    | '/auth/otp'
    | '/mcp/oauth-callback'
    | '/auth/'
    | '/_protected/knowledge/case'
    | '/_protected/settings/organization'
    | '/_protected/workspaces/$workspaceId'
    | '/_protected/chat/$threadId'
    | '/_protected/chat/new'
    | '/_protected/contacts/$contactId'
    | '/_protected/knowledge/clauses'
    | '/_protected/knowledge/mcp'
    | '/_protected/knowledge/prompts'
    | '/_protected/knowledge/skills'
    | '/_protected/knowledge/templates'
    | '/auth/accept-invitation/$invitationId'
    | '/_protected/chat/'
    | '/_protected/contacts/'
    | '/_protected/knowledge/'
    | '/_protected/settings/'
    | '/_protected/todos/'
    | '/_protected/workspaces/'
    | '/_protected/workspaces/$workspaceId/$viewId'
    | '/_protected/knowledge/case/$decisionId'
    | '/_protected/settings/account/desktop'
    | '/_protected/settings/account/profile'
    | '/_protected/settings/organization/ai'
    | '/_protected/settings/organization/anonymization'
    | '/_protected/settings/organization/matter-numbering'
    | '/_protected/settings/organization/members'
    | '/_protected/workspaces/$workspaceId/expenses'
    | '/_protected/workspaces/$workspaceId/invoices'
    | '/_protected/workspaces/$workspaceId/timesheets'
    | '/_protected/knowledge/case/'
    | '/_protected/settings/organization/'
    | '/_protected/workspaces/$workspaceId/'
    | '/_protected/chat/workspaces/$workspaceId/$threadId'
    | '/_protected/chat/workspaces/$workspaceId/new'
    | '/_protected/workspaces/$workspaceId/$viewId/document'
    | '/_protected/workspaces/$workspaceId/entities/$entityId'
    | '/_protected/workspaces/$workspaceId/invoices/$invoiceId'
    | '/_protected/workspaces/$workspaceId/$viewId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  OnboardingRouteRoute: typeof OnboardingRouteRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  ConsentRoute: typeof ConsentRoute
  DevRoute: typeof DevRoute
  McpOauthCallbackRoute: typeof McpOauthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/mcp/oauth-callback': {
      id: '/mcp/oauth-callback'
      path: '/mcp/oauth-callback'
      fullPath: '/mcp/oauth-callback'
      preLoaderRoute: typeof McpOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/otp': {
      id: '/auth/otp'
      path: '/otp'
      fullPath: '/auth/otp'
      preLoaderRoute: typeof AuthOtpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/organization': {
      id: '/auth/organization'
      path: '/organization'
      fullPath: '/auth/organization'
      preLoaderRoute: typeof AuthOrganizationRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/knowledge': {
      id: '/_protected/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof ProtectedKnowledgeRouteRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/chat': {
      id: '/_protected/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ProtectedChatRouteRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/workspaces/': {
      id: '/_protected/workspaces/'
      path: '/workspaces'
      fullPath: '/workspaces/'
      preLoaderRoute: typeof ProtectedWorkspacesIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/todos/': {
      id: '/_protected/todos/'
      path: '/todos'
      fullPath: '/todos/'
      preLoaderRoute: typeof ProtectedTodosIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/': {
      id: '/_protected/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof ProtectedSettingsIndexRouteImport
      parentRoute: typeof ProtectedSettingsRouteRoute
    }
    '/_protected/knowledge/': {
      id: '/_protected/knowledge/'
      path: '/'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof ProtectedKnowledgeIndexRouteImport
      parentRoute: typeof ProtectedKnowledgeRouteRoute
    }
    '/_protected/contacts/': {
      id: '/_protected/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof ProtectedContactsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/chat/': {
      id: '/_protected/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof ProtectedChatIndexRouteImport
      parentRoute: typeof ProtectedChatRouteRoute
    }
    '/auth/accept-invitation/$invitationId': {
      id: '/auth/accept-invitation/$invitationId'
      path: '/accept-invitation/$invitationId'
      fullPath: '/auth/accept-invitation/$invitationId'
      preLoaderRoute: typeof AuthAcceptInvitationInvitationIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_protected/knowledge/templates': {
      id: '/_protected/knowledge/templates'
      path: '/templates'
      fullPath: '/knowledge/templates'
      preLoaderRoute: typeof ProtectedKnowledgeTemplatesRouteImport
      parentRoute: typeof ProtectedKnowledgeRouteRoute
    }
    '/_protected/knowledge/skills': {
      id: '/_protected/knowledge/skills'
      path: '/skills'
      fullPath: '/knowledge/skills'
      preLoaderRoute: typeof ProtectedKnowledgeSkillsRouteImport
      parentRoute: typeof ProtectedKnowledgeRouteRoute
    }
    '/_protected/knowledge/prompts': {
      id: '/_protected/knowledge/prompts'
      path: '/prompts'
      fullPath: '/knowledge/prompts'
      preLoaderRoute: typeof ProtectedKnowledgePromptsRouteImport
      parentRoute: typeof ProtectedKnowledgeRouteRoute
    }
    '/_protected/knowledge/mcp': {
      id: '/_protected/knowledge/mcp'
      path: '/mcp'
      fullPath: '/knowledge/mcp'
      preLoaderRoute: typeof ProtectedKnowledgeMcpRouteImport
      parentRoute: typeof ProtectedKnowledgeRouteRoute
    }
    '/_protected/knowledge/clauses': {
      id: '/_protected/knowledge/clauses'
      path: '/clauses'
      fullPath: '/knowledge/clauses'
      preLoaderRoute: typeof ProtectedKnowledgeClausesRouteImport
      parentRoute: typeof ProtectedKnowledgeRouteRoute
    }
    '/_protected/contacts/$contactId': {
      id: '/_protected/contacts/$contactId'
      path: '/contacts/$contactId'
      fullPath: '/contacts/$contactId'
      preLoaderRoute: typeof ProtectedContactsContactIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/chat/new': {
      id: '/_protected/chat/new'
      path: '/new'
      fullPath: '/chat/new'
      preLoaderRoute: typeof ProtectedChatNewRouteImport
      parentRoute: typeof ProtectedChatRouteRoute
    }
    '/_protected/chat/$threadId': {
      id: '/_protected/chat/$threadId'
      path: '/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof ProtectedChatThreadIdRouteImport
      parentRoute: typeof ProtectedChatRouteRoute
    }
    '/_protected/workspaces/$workspaceId': {
      id: '/_protected/workspaces/$workspaceId'
      path: '/workspaces/$workspaceId'
      fullPath: '/workspaces/$workspaceId'
      preLoaderRoute: typeof ProtectedWorkspacesWorkspaceIdRouteRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/organization': {
      id: '/_protected/settings/organization'
      path: '/organization'
      fullPath: '/settings/organization'
      preLoaderRoute: typeof ProtectedSettingsOrganizationRouteRouteImport
      parentRoute: typeof ProtectedSettingsRouteRoute
    }
    '/_protected/knowledge/case': {
      id: '/_protected/knowledge/case'
      path: '/case'
      fullPath: '/knowledge/case'
      preLoaderRoute: typeof ProtectedKnowledgeCaseRouteRouteImport
      parentRoute: typeof ProtectedKnowledgeRouteRoute
    }
    '/_protected/workspaces/$workspaceId/': {
      id: '/_protected/workspaces/$workspaceId/'
      path: '/'
      fullPath: '/workspaces/$workspaceId/'
      preLoaderRoute: typeof ProtectedWorkspacesWorkspaceIdIndexRouteImport
      parentRoute: typeof ProtectedWorkspacesWorkspaceIdRouteRoute
    }
    '/_protected/settings/organization/': {
      id: '/_protected/settings/organization/'
      path: '/'
      fullPath: '/settings/organization/'
      preLoaderRoute: typeof ProtectedSettingsOrganizationIndexRouteImport
      parentRoute: typeof ProtectedSettingsOrganizationRouteRoute
    }
    '/_protected/knowledge/case/': {
      id: '/_protected/knowledge/case/'
      path: '/'
      fullPath: '/knowledge/case/'
      preLoaderRoute: typeof ProtectedKnowledgeCaseIndexRouteImport
      parentRoute: typeof ProtectedKnowledgeCaseRouteRoute
    }
    '/_protected/workspaces/$workspaceId/timesheets': {
      id: '/_protected/workspaces/$workspaceId/timesheets'
      path: '/timesheets'
      fullPath: '/workspaces/$workspaceId/timesheets'
      preLoaderRoute: typeof ProtectedWorkspacesWorkspaceIdTimesheetsRouteImport
      parentRoute: typeof ProtectedWorkspacesWorkspaceIdRouteRoute
    }
    '/_protected/workspaces/$workspaceId/invoices': {
      id: '/_protected/workspaces/$workspaceId/invoices'
      path: '/invoices'
      fullPath: '/workspaces/$workspaceId/invoices'
      preLoaderRoute: typeof ProtectedWorkspacesWorkspaceIdInvoicesRouteImport
      parentRoute: typeof ProtectedWorkspacesWorkspaceIdRouteRoute
    }
    '/_protected/workspaces/$workspaceId/expenses': {
      id: '/_protected/workspaces/$workspaceId/expenses'
      path: '/expenses'
      fullPath: '/workspaces/$workspaceId/expenses'
      preLoaderRoute: typeof ProtectedWorkspacesWorkspaceIdExpensesRouteImport
      parentRoute: typeof ProtectedWorkspacesWorkspaceIdRouteRoute
    }
    '/_protected/settings/organization/members': {
      id: '/_protected/settings/organization/members'
      path: '/members'
      fullPath: '/settings/organization/members'
      preLoaderRoute: typeof ProtectedSettingsOrganizationMembersRouteImport
      parentRoute: typeof ProtectedSettingsOrganizationRouteRoute
    }
    '/_protected/settings/organization/matter-numbering': {
      id: '/_protected/settings/organization/matter-numbering'
      path: '/matter-numbering'
      fullPath: '/settings/organization/matter-numbering'
      preLoaderRoute: typeof ProtectedSettingsOrganizationMatterNumberingRouteImport
      parentRoute: typeof ProtectedSettingsOrganizationRouteRoute
    }
    '/_protected/settings/organization/anonymization': {
      id: '/_protected/settings/organization/anonymization'
      path: '/anonymization'
      fullPath: '/settings/organization/anonymization'
      preLoaderRoute: typeof ProtectedSettingsOrganizationAnonymizationRouteImport
      parentRoute: typeof ProtectedSettingsOrganizationRouteRoute
    }
    '/_protected/settings/organization/ai': {
      id: '/_protected/settings/organization/ai'
      path: '/ai'
      fullPath: '/settings/organization/ai'
      preLoaderRoute: typeof ProtectedSettingsOrganizationAiRouteImport
      parentRoute: typeof ProtectedSettingsOrganizationRouteRoute
    }
    '/_protected/settings/account/profile': {
      id: '/_protected/settings/account/profile'
      path: '/account/profile'
      fullPath: '/settings/account/profile'
      preLoaderRoute: typeof ProtectedSettingsAccountProfileRouteImport
      parentRoute: typeof ProtectedSettingsRouteRoute
    }
    '/_protected/settings/account/desktop': {
      id: '/_protected/settings/account/desktop'
      path: '/account/desktop'
      fullPath: '/settings/account/desktop'
      preLoaderRoute: typeof ProtectedSettingsAccountDesktopRouteImport
      parentRoute: typeof ProtectedSettingsRouteRoute
    }
    '/_protected/knowledge/case/$decisionId': {
      id: '/_protected/knowledge/case/$decisionId'
      path: '/$decisionId'
      fullPath: '/knowledge/case/$decisionId'
      preLoaderRoute: typeof ProtectedKnowledgeCaseDecisionIdRouteImport
      parentRoute: typeof ProtectedKnowledgeCaseRouteRoute
    }
    '/_protected/workspaces/$workspaceId/$viewId': {
      id: '/_protected/workspaces/$workspaceId/$viewId'
      path: '/$viewId'
      fullPath: '/workspaces/$workspaceId/$viewId'
      preLoaderRoute: typeof ProtectedWorkspacesWorkspaceIdViewIdRouteRouteImport
      parentRoute: typeof ProtectedWorkspacesWorkspaceIdRouteRoute
    }
    '/_protected/workspaces/$workspaceId/$viewId/': {
      id: '/_protected/workspaces/$workspaceId/$viewId/'
      path: '/'
      fullPath: '/workspaces/$workspaceId/$viewId/'
      preLoaderRoute: typeof ProtectedWorkspacesWorkspaceIdViewIdIndexRouteImport
      parentRoute: typeof ProtectedWorkspacesWorkspaceIdViewIdRouteRoute
    }
    '/_protected/workspaces/$workspaceId/invoices/$invoiceId': {
      id: '/_protected/workspaces/$workspaceId/invoices/$invoiceId'
      path: '/$invoiceId'
      fullPath: '/workspaces/$workspaceId/invoices/$invoiceId'
      preLoaderRoute: typeof ProtectedWorkspacesWorkspaceIdInvoicesInvoiceIdRouteImport
      parentRoute: typeof ProtectedWorkspacesWorkspaceIdInvoicesRoute
    }
    '/_protected/workspaces/$workspaceId/entities/$entityId': {
      id: '/_protected/workspaces/$workspaceId/entities/$entityId'
      path: '/entities/$entityId'
      fullPath: '/workspaces/$workspaceId/entities/$entityId'
      preLoaderRoute: typeof ProtectedWorkspacesWorkspaceIdEntitiesEntityIdRouteImport
      parentRoute: typeof ProtectedWorkspacesWorkspaceIdRouteRoute
    }
    '/_protected/workspaces/$workspaceId/$viewId/document': {
      id: '/_protected/workspaces/$workspaceId/$viewId/document'
      path: '/document'
      fullPath: '/workspaces/$workspaceId/$viewId/document'
      preLoaderRoute: typeof ProtectedWorkspacesWorkspaceIdViewIdDocumentRouteImport
      parentRoute: typeof ProtectedWorkspacesWorkspaceIdViewIdRouteRoute
    }
    '/_protected/chat/workspaces/$workspaceId/new': {
      id: '/_protected/chat/workspaces/$workspaceId/new'
      path: '/workspaces/$workspaceId/new'
      fullPath: '/chat/workspaces/$workspaceId/new'
      preLoaderRoute: typeof ProtectedChatWorkspacesWorkspaceIdNewRouteImport
      parentRoute: typeof ProtectedChatRouteRoute
    }
    '/_protected/chat/workspaces/$workspaceId/$threadId': {
      id: '/_protected/chat/workspaces/$workspaceId/$threadId'
      path: '/workspaces/$workspaceId/$threadId'
      fullPath: '/chat/workspaces/$workspaceId/$threadId'
      preLoaderRoute: typeof ProtectedChatWorkspacesWorkspaceIdThreadIdRouteImport
      parentRoute: typeof ProtectedChatRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthOrganizationRoute: typeof AuthOrganizationRoute
  AuthOtpRoute: typeof AuthOtpRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthAcceptInvitationInvitationIdRoute: typeof AuthAcceptInvitationInvitationIdRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthOrganizationRoute: AuthOrganizationRoute,
  AuthOtpRoute: AuthOtpRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthAcceptInvitationInvitationIdRoute: AuthAcceptInvitationInvitationIdRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface ProtectedChatRouteRouteChildren {
  ProtectedChatThreadIdRoute: typeof ProtectedChatThreadIdRoute
  ProtectedChatNewRoute: typeof ProtectedChatNewRoute
  ProtectedChatIndexRoute: typeof ProtectedChatIndexRoute
  ProtectedChatWorkspacesWorkspaceIdThreadIdRoute: typeof ProtectedChatWorkspacesWorkspaceIdThreadIdRoute
  ProtectedChatWorkspacesWorkspaceIdNewRoute: typeof ProtectedChatWorkspacesWorkspaceIdNewRoute
}

const ProtectedChatRouteRouteChildren: ProtectedChatRouteRouteChildren = {
  ProtectedChatThreadIdRoute: ProtectedChatThreadIdRoute,
  ProtectedChatNewRoute: ProtectedChatNewRoute,
  ProtectedChatIndexRoute: ProtectedChatIndexRoute,
  ProtectedChatWorkspacesWorkspaceIdThreadIdRoute:
    ProtectedChatWorkspacesWorkspaceIdThreadIdRoute,
  ProtectedChatWorkspacesWorkspaceIdNewRoute:
    ProtectedChatWorkspacesWorkspaceIdNewRoute,
}

const ProtectedChatRouteRouteWithChildren =
  ProtectedChatRouteRoute._addFileChildren(ProtectedChatRouteRouteChildren)

interface ProtectedKnowledgeCaseRouteRouteChildren {
  ProtectedKnowledgeCaseDecisionIdRoute: typeof ProtectedKnowledgeCaseDecisionIdRoute
  ProtectedKnowledgeCaseIndexRoute: typeof ProtectedKnowledgeCaseIndexRoute
}

const ProtectedKnowledgeCaseRouteRouteChildren: ProtectedKnowledgeCaseRouteRouteChildren =
  {
    ProtectedKnowledgeCaseDecisionIdRoute:
      ProtectedKnowledgeCaseDecisionIdRoute,
    ProtectedKnowledgeCaseIndexRoute: ProtectedKnowledgeCaseIndexRoute,
  }

const ProtectedKnowledgeCaseRouteRouteWithChildren =
  ProtectedKnowledgeCaseRouteRoute._addFileChildren(
    ProtectedKnowledgeCaseRouteRouteChildren,
  )

interface ProtectedKnowledgeRouteRouteChildren {
  ProtectedKnowledgeCaseRouteRoute: typeof ProtectedKnowledgeCaseRouteRouteWithChildren
  ProtectedKnowledgeClausesRoute: typeof ProtectedKnowledgeClausesRoute
  ProtectedKnowledgeMcpRoute: typeof ProtectedKnowledgeMcpRoute
  ProtectedKnowledgePromptsRoute: typeof ProtectedKnowledgePromptsRoute
  ProtectedKnowledgeSkillsRoute: typeof ProtectedKnowledgeSkillsRoute
  ProtectedKnowledgeTemplatesRoute: typeof ProtectedKnowledgeTemplatesRoute
  ProtectedKnowledgeIndexRoute: typeof ProtectedKnowledgeIndexRoute
}

const ProtectedKnowledgeRouteRouteChildren: ProtectedKnowledgeRouteRouteChildren =
  {
    ProtectedKnowledgeCaseRouteRoute:
      ProtectedKnowledgeCaseRouteRouteWithChildren,
    ProtectedKnowledgeClausesRoute: ProtectedKnowledgeClausesRoute,
    ProtectedKnowledgeMcpRoute: ProtectedKnowledgeMcpRoute,
    ProtectedKnowledgePromptsRoute: ProtectedKnowledgePromptsRoute,
    ProtectedKnowledgeSkillsRoute: ProtectedKnowledgeSkillsRoute,
    ProtectedKnowledgeTemplatesRoute: ProtectedKnowledgeTemplatesRoute,
    ProtectedKnowledgeIndexRoute: ProtectedKnowledgeIndexRoute,
  }

const ProtectedKnowledgeRouteRouteWithChildren =
  ProtectedKnowledgeRouteRoute._addFileChildren(
    ProtectedKnowledgeRouteRouteChildren,
  )

interface ProtectedSettingsOrganizationRouteRouteChildren {
  ProtectedSettingsOrganizationAiRoute: typeof ProtectedSettingsOrganizationAiRoute
  ProtectedSettingsOrganizationAnonymizationRoute: typeof ProtectedSettingsOrganizationAnonymizationRoute
  ProtectedSettingsOrganizationMatterNumberingRoute: typeof ProtectedSettingsOrganizationMatterNumberingRoute
  ProtectedSettingsOrganizationMembersRoute: typeof ProtectedSettingsOrganizationMembersRoute
  ProtectedSettingsOrganizationIndexRoute: typeof ProtectedSettingsOrganizationIndexRoute
}

const ProtectedSettingsOrganizationRouteRouteChildren: ProtectedSettingsOrganizationRouteRouteChildren =
  {
    ProtectedSettingsOrganizationAiRoute: ProtectedSettingsOrganizationAiRoute,
    ProtectedSettingsOrganizationAnonymizationRoute:
      ProtectedSettingsOrganizationAnonymizationRoute,
    ProtectedSettingsOrganizationMatterNumberingRoute:
      ProtectedSettingsOrganizationMatterNumberingRoute,
    ProtectedSettingsOrganizationMembersRoute:
      ProtectedSettingsOrganizationMembersRoute,
    ProtectedSettingsOrganizationIndexRoute:
      ProtectedSettingsOrganizationIndexRoute,
  }

const ProtectedSettingsOrganizationRouteRouteWithChildren =
  ProtectedSettingsOrganizationRouteRoute._addFileChildren(
    ProtectedSettingsOrganizationRouteRouteChildren,
  )

interface ProtectedSettingsRouteRouteChildren {
  ProtectedSettingsOrganizationRouteRoute: typeof ProtectedSettingsOrganizationRouteRouteWithChildren
  ProtectedSettingsIndexRoute: typeof ProtectedSettingsIndexRoute
  ProtectedSettingsAccountDesktopRoute: typeof ProtectedSettingsAccountDesktopRoute
  ProtectedSettingsAccountProfileRoute: typeof ProtectedSettingsAccountProfileRoute
}

const ProtectedSettingsRouteRouteChildren: ProtectedSettingsRouteRouteChildren =
  {
    ProtectedSettingsOrganizationRouteRoute:
      ProtectedSettingsOrganizationRouteRouteWithChildren,
    ProtectedSettingsIndexRoute: ProtectedSettingsIndexRoute,
    ProtectedSettingsAccountDesktopRoute: ProtectedSettingsAccountDesktopRoute,
    ProtectedSettingsAccountProfileRoute: ProtectedSettingsAccountProfileRoute,
  }

const ProtectedSettingsRouteRouteWithChildren =
  ProtectedSettingsRouteRoute._addFileChildren(
    ProtectedSettingsRouteRouteChildren,
  )

interface ProtectedWorkspacesWorkspaceIdViewIdRouteRouteChildren {
  ProtectedWorkspacesWorkspaceIdViewIdDocumentRoute: typeof ProtectedWorkspacesWorkspaceIdViewIdDocumentRoute
  ProtectedWorkspacesWorkspaceIdViewIdIndexRoute: typeof ProtectedWorkspacesWorkspaceIdViewIdIndexRoute
}

const ProtectedWorkspacesWorkspaceIdViewIdRouteRouteChildren: ProtectedWorkspacesWorkspaceIdViewIdRouteRouteChildren =
  {
    ProtectedWorkspacesWorkspaceIdViewIdDocumentRoute:
      ProtectedWorkspacesWorkspaceIdViewIdDocumentRoute,
    ProtectedWorkspacesWorkspaceIdViewIdIndexRoute:
      ProtectedWorkspacesWorkspaceIdViewIdIndexRoute,
  }

const ProtectedWorkspacesWorkspaceIdViewIdRouteRouteWithChildren =
  ProtectedWorkspacesWorkspaceIdViewIdRouteRoute._addFileChildren(
    ProtectedWorkspacesWorkspaceIdViewIdRouteRouteChildren,
  )

interface ProtectedWorkspacesWorkspaceIdInvoicesRouteChildren {
  ProtectedWorkspacesWorkspaceIdInvoicesInvoiceIdRoute: typeof ProtectedWorkspacesWorkspaceIdInvoicesInvoiceIdRoute
}

const ProtectedWorkspacesWorkspaceIdInvoicesRouteChildren: ProtectedWorkspacesWorkspaceIdInvoicesRouteChildren =
  {
    ProtectedWorkspacesWorkspaceIdInvoicesInvoiceIdRoute:
      ProtectedWorkspacesWorkspaceIdInvoicesInvoiceIdRoute,
  }

const ProtectedWorkspacesWorkspaceIdInvoicesRouteWithChildren =
  ProtectedWorkspacesWorkspaceIdInvoicesRoute._addFileChildren(
    ProtectedWorkspacesWorkspaceIdInvoicesRouteChildren,
  )

interface ProtectedWorkspacesWorkspaceIdRouteRouteChildren {
  ProtectedWorkspacesWorkspaceIdViewIdRouteRoute: typeof ProtectedWorkspacesWorkspaceIdViewIdRouteRouteWithChildren
  ProtectedWorkspacesWorkspaceIdExpensesRoute: typeof ProtectedWorkspacesWorkspaceIdExpensesRoute
  ProtectedWorkspacesWorkspaceIdInvoicesRoute: typeof ProtectedWorkspacesWorkspaceIdInvoicesRouteWithChildren
  ProtectedWorkspacesWorkspaceIdTimesheetsRoute: typeof ProtectedWorkspacesWorkspaceIdTimesheetsRoute
  ProtectedWorkspacesWorkspaceIdIndexRoute: typeof ProtectedWorkspacesWorkspaceIdIndexRoute
  ProtectedWorkspacesWorkspaceIdEntitiesEntityIdRoute: typeof ProtectedWorkspacesWorkspaceIdEntitiesEntityIdRoute
}

const ProtectedWorkspacesWorkspaceIdRouteRouteChildren: ProtectedWorkspacesWorkspaceIdRouteRouteChildren =
  {
    ProtectedWorkspacesWorkspaceIdViewIdRouteRoute:
      ProtectedWorkspacesWorkspaceIdViewIdRouteRouteWithChildren,
    ProtectedWorkspacesWorkspaceIdExpensesRoute:
      ProtectedWorkspacesWorkspaceIdExpensesRoute,
    ProtectedWorkspacesWorkspaceIdInvoicesRoute:
      ProtectedWorkspacesWorkspaceIdInvoicesRouteWithChildren,
    ProtectedWorkspacesWorkspaceIdTimesheetsRoute:
      ProtectedWorkspacesWorkspaceIdTimesheetsRoute,
    ProtectedWorkspacesWorkspaceIdIndexRoute:
      ProtectedWorkspacesWorkspaceIdIndexRoute,
    ProtectedWorkspacesWorkspaceIdEntitiesEntityIdRoute:
      ProtectedWorkspacesWorkspaceIdEntitiesEntityIdRoute,
  }

const ProtectedWorkspacesWorkspaceIdRouteRouteWithChildren =
  ProtectedWorkspacesWorkspaceIdRouteRoute._addFileChildren(
    ProtectedWorkspacesWorkspaceIdRouteRouteChildren,
  )

interface ProtectedRouteChildren {
  ProtectedChatRouteRoute: typeof ProtectedChatRouteRouteWithChildren
  ProtectedKnowledgeRouteRoute: typeof ProtectedKnowledgeRouteRouteWithChildren
  ProtectedSettingsRouteRoute: typeof ProtectedSettingsRouteRouteWithChildren
  ProtectedWorkspacesWorkspaceIdRouteRoute: typeof ProtectedWorkspacesWorkspaceIdRouteRouteWithChildren
  ProtectedContactsContactIdRoute: typeof ProtectedContactsContactIdRoute
  ProtectedContactsIndexRoute: typeof ProtectedContactsIndexRoute
  ProtectedTodosIndexRoute: typeof ProtectedTodosIndexRoute
  ProtectedWorkspacesIndexRoute: typeof ProtectedWorkspacesIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedChatRouteRoute: ProtectedChatRouteRouteWithChildren,
  ProtectedKnowledgeRouteRoute: ProtectedKnowledgeRouteRouteWithChildren,
  ProtectedSettingsRouteRoute: ProtectedSettingsRouteRouteWithChildren,
  ProtectedWorkspacesWorkspaceIdRouteRoute:
    ProtectedWorkspacesWorkspaceIdRouteRouteWithChildren,
  ProtectedContactsContactIdRoute: ProtectedContactsContactIdRoute,
  ProtectedContactsIndexRoute: ProtectedContactsIndexRoute,
  ProtectedTodosIndexRoute: ProtectedTodosIndexRoute,
  ProtectedWorkspacesIndexRoute: ProtectedWorkspacesIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  OnboardingRouteRoute: OnboardingRouteRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  ConsentRoute: ConsentRoute,
  DevRoute: DevRoute,
  McpOauthCallbackRoute: McpOauthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
