import { panic } from "better-result";

import type { RegistryHit } from "@/components/templates/registry-autofill";
import type { TranslationKey } from "@/i18n/types";

type RegistryDetails = NonNullable<RegistryHit["details"]>;
type RegistryRecord<Details> = Details extends unknown
  ? Details[Exclude<keyof Details, "registry">]
  : never;
type NestedFieldKey<Value> = Value extends readonly (infer Item)[]
  ? NestedFieldKey<Item>
  : Value extends object
    ? { [Key in keyof Value]-?: Key | NestedFieldKey<Value[Key]> }[keyof Value]
    : never;
type RegistryDetailKey = NestedFieldKey<RegistryRecord<RegistryDetails>>;

const DETAIL_LABELS = {
  acceptanceDateTime: "search.registryDetails.acceptedAt",
  accessionNumber: "search.registryDetails.accessionNumber",
  accounts: "search.registryDetails.accounts",
  actingClause: "search.registryDetails.actingClause",
  activityClass: "tasks.activity",
  activityCode: "search.registryDetails.industryCodes",
  address: "common.anonymizationLabels.address",
  addresses: "contacts.communication.addresses",
  addressLine1: "contacts.importStudio.fields.address_line_1",
  addressLine2: "contacts.importStudio.fields.address_line_2",
  alternateNames: "search.registryDetails.alternateNames",
  amount: "billing.amount",
  birthYear: "search.registryDetails.birthYear",
  business: "search.registryDetails.businessAddress",
  businessAddress: "search.registryDetails.businessAddress",
  businessId: "search.registryDetails.identifier",
  capitalAmount: "search.registryDetails.capital",
  careOf: "search.registryDetails.careOf",
  ceasedAt: "search.registryDetails.ceased",
  ceasedOn: "search.registryDetails.ceasedOn",
  cik: "search.registryDetails.identifier",
  city: "contacts.fields.billingAddressCity",
  clee: "search.registryDetails.establishmentId",
  closedAt: "search.registryDetails.closed",
  code: "billing.codes.codeLabel",
  commune: "search.registryDetails.municipality",
  companyNumber: "search.registryDetails.identifier",
  confirmationStatement: "search.registryDetails.confirmationStatement",
  coordinates: "search.registryDetails.coordinates",
  country: "common.country",
  county: "search.registryDetails.county",
  court: "common.court",
  courtFile: "search.registryDetails.courtFile",
  createdAt: "search.registryDetails.established",
  currency: "common.currency",
  czNace: "search.registryDetails.industryCodes",
  dateEstablished: "search.registryDetails.established",
  dateOfCessation: "search.registryDetails.ceased",
  dateOfCreation: "search.registryDetails.established",
  dateRegistered: "search.registryDetails.registered",
  deletedAt: "search.registryDetails.removed",
  description: "common.description",
  directors: "search.registryDetails.directors",
  dissolvedAt: "search.registryDetails.dissolved",
  district: "search.registryDetails.district",
  effectiveFrom: "billing.rates.effectiveFrom",
  ein: "search.registryDetails.taxId",
  email: "common.email",
  employeeStratum: "search.registryDetails.employeeStratum",
  endedAt: "search.registryDetails.ceased",
  establishedAt: "search.registryDetails.established",
  exchanges: "search.registryDetails.exchanges",
  filingDate: "search.registryDetails.filingDate",
  form: "search.registryDetails.filingForm",
  formerNames: "search.registryDetails.previousNames",
  from: "search.dateFrom",
  fullName: "common.name",
  hasBeenLiquidated: "search.registryDetails.liquidated",
  hasCharges: "search.registryDetails.charges",
  hasInsolvencyHistory: "search.registryDetails.insolvency",
  headOffice: "search.registryDetails.headOffice",
  houseNumber: "search.registryDetails.houseNumber",
  ico: "contacts.create.icoPlaceholder",
  id: "search.registryDetails.identifier",
  identifier: "search.registryDetails.identifier",
  identifiers: "search.registryDetails.identifiers",
  industryCodes: "search.registryDetails.industryCodes",
  insert: "search.registryDetails.courtInsert",
  insertNumber: "search.registryDetails.courtInsert",
  isCurrent: "search.registryDetails.current",
  isHeadOffice: "search.registryDetails.isHeadOffice",
  jurisdiction: "onboarding.stepJurisdiction",
  krsNumber: "search.registryDetails.identifier",
  lastChangeDate: "search.registryDetails.lastChanged",
  lastChangeDateRoc: "search.registryDetails.rocDate",
  lastEntryAt: "search.registryDetails.lastChanged",
  lastFilingDate: "search.registryDetails.lastFilingDate",
  lastMadeUpTo: "search.registryDetails.lastMadeUpTo",
  latitude: "search.registryDetails.latitude",
  legalForm: "search.registryDetails.legalForm",
  legalFormCode: "search.registryDetails.legalForm",
  legalName: "search.registryDetails.legalName",
  line1: "contacts.importStudio.fields.address_line_1",
  line2: "contacts.importStudio.fields.address_line_2",
  locality: "search.registryDetails.locality",
  location: "common.anonymizationLabels.address",
  longitude: "search.registryDetails.longitude",
  mailing: "search.registryDetails.postalAddress",
  mainBusinessLine: "search.registryDetails.businessLine",
  matchedEstablishment: "search.registryDetails.matchedEstablishment",
  members: "search.registryDetails.bodyMembers",
  municipality: "search.registryDetails.municipality",
  municipalityPart: "search.registryDetails.municipalityPart",
  name: "common.name",
  nextDue: "search.registryDetails.nextDue",
  nextMadeUpTo: "search.registryDetails.nextMadeUpTo",
  nip: "search.registryDetails.taxId",
  numberOfEmployees: "search.registryDetails.employees",
  openedAt: "search.registryDetails.opened",
  organName: "search.registryDetails.bodyName",
  orgnr: "search.registryDetails.identifier",
  orientationLetter: "search.registryDetails.orientationLetter",
  orientationNumber: "search.registryDetails.orientationNumber",
  overdue: "tasks.overdue",
  paidInCapitalAmount: "search.registryDetails.paidInCapital",
  phone: "contacts.columns.phone",
  poBox: "search.registryDetails.poBox",
  position: "common.role",
  postalAddress: "search.registryDetails.postalAddress",
  postalCode: "contacts.fields.billingAddressPostalCode",
  premises: "search.registryDetails.premises",
  previousNames: "search.registryDetails.previousNames",
  primaryDocDescription: "search.registryDetails.filingDescription",
  primaryDocument: "search.registryDetails.primaryDocument",
  recentFilings: "search.registryDetails.filings",
  region: "search.registryDetails.region",
  register: "search.registryDetails.register",
  registeredAt: "search.registryDetails.registered",
  registeredOfficeAddress: "search.registryDetails.registeredOffice",
  registeredSeat: "search.registryDetails.registeredSeat",
  registerOrganization: "search.registryDetails.registeringAuthority",
  registryUrl: "common.source",
  regon: "search.registryDetails.statisticalId",
  reportDate: "search.registryDetails.reportDate",
  requestDate: "search.registryDetails.validationDate",
  responsibleName: "contacts.attorneys.responsible",
  role: "common.role",
  section: "search.registryDetails.courtSection",
  serviceAddress: "search.registryDetails.serviceAddress",
  setupDate: "search.registryDetails.established",
  setupDateRoc: "search.registryDetails.rocDate",
  share: "search.registryDetails.share",
  shareCapital: "search.registryDetails.shareCapital",
  shareCapitalPaid: "search.registryDetails.shareCapitalPaid",
  shoppingCenter: "search.registryDetails.shoppingCenter",
  shoppingCenterType: "search.registryDetails.shoppingCenterType",
  shortName: "search.registryDetails.shortName",
  sic: "search.registryDetails.industryCodes",
  sicCodes: "search.registryDetails.industryCodes",
  sicDescription: "search.registryDetails.sicDescription",
  since: "billing.rates.effectiveFrom",
  siren: "search.registryDetails.identifier",
  siret: "search.registryDetails.establishmentId",
  stakeholders: "search.registryDetails.stakeholders",
  state: "contacts.fields.billingAddressState",
  status: "common.status",
  statusDescription: "search.registryDetails.statusDetail",
  statusDetail: "search.registryDetails.statusDetail",
  statutoryBodies: "search.registryDetails.statutoryBodies",
  street: "contacts.fields.billingAddressLine1",
  streetAddress: "search.registryDetails.streetAddress",
  subtype: "search.registryDetails.subtype",
  taxId: "search.registryDetails.taxId",
  terminatedAt: "search.registryDetails.ceased",
  textAddress: "common.anonymizationLabels.address",
  tickers: "search.registryDetails.tickers",
  to: "search.dateTo",
  tradeRegisterRegistered: "search.registryDetails.tradeRegistered",
  type: "common.type",
  unitNumber: "search.registryDetails.unitNumber",
  unitType: "search.registryDetails.unitType",
  userError: "search.registryDetails.validationError",
  valid: "search.registryDetails.validVat",
  vat: "search.registryDetails.vatNumber",
  vatNumber: "search.registryDetails.vatNumber",
  vatRegistered: "search.registryDetails.vatRegistered",
  voivodeship: "search.registryDetails.region",
  vrEnrichmentStatus: "search.registryDetails.enrichmentStatus",
  website: "search.registryDetails.website",
} as const satisfies Record<RegistryDetailKey, TranslationKey>;

const isRegistryDetailKey = (key: string): key is keyof typeof DETAIL_LABELS =>
  Object.hasOwn(DETAIL_LABELS, key);

export const registryDetailLabel = (key: string) => {
  if (!isRegistryDetailKey(key)) {
    return panic(`Missing business-registry field label: ${key}`);
  }
  return DETAIL_LABELS[key];
};
