import { panic } from "better-result";

import type { RegistryHit } from "@/components/templates/registry-autofill";

type Details = NonNullable<RegistryHit["details"]>;
type Registry = Details["registry"];
type RecordOf<D> = D extends unknown ? D[Exclude<keyof D, "registry">] : never;
type NestedKey<Value> = Value extends readonly (infer Item)[]
  ? NestedKey<Item>
  : Value extends object
    ? { [Key in keyof Value]-?: Key | NestedKey<Value[Key]> }[keyof Value]
    : never;
type LabelMaps = {
  [Detail in Details as Detail["registry"]]: Record<
    Extract<NestedKey<RecordOf<Detail>>, string>,
    string
  >;
};

// Source-language field titles stay independent of the viewer's UI language.
// The adapters normalize field keys, so each registry restores its own vocabulary.
const DETAIL_LABELS = {
  ares: {
    ico: "IČO",
    name: "Obchodní jméno",
    legalForm: "Právní forma",
    address: "Sídlo",
    street: "Ulice",
    houseNumber: "Číslo domovní",
    orientationNumber: "Číslo orientační",
    orientationLetter: "Písmeno čísla orientační",
    municipalityPart: "Část obce",
    municipality: "Obec",
    postalCode: "PSČ",
    district: "Okres",
    country: "Stát",
    textAddress: "Textová adresa",
    dateEstablished: "Datum vzniku",
    dateRegistered: "Datum zápisu",
    czNace: "CZ-NACE",
    registryUrl: "Zdroj",
    status: "Stav subjektu",
    courtFile: "Spisová značka",
    court: "Soud",
    section: "Oddíl",
    insert: "Vložka",
    shareCapital: "Základní kapitál",
    statutoryBodies: "Statutární orgány",
    organName: "Název orgánu",
    members: "Členové orgánu",
    role: "Funkce",
    since: "Ve funkci od",
    actingClause: "Způsob jednání",
    vrEnrichmentStatus: "Dostupnost údajů obchodního rejstříku",
  },
  brreg: {
    orgnr: "Organisasjonsnummer",
    name: "Navn",
    legalForm: "Organisasjonsform",
    legalFormCode: "Organisasjonsformkode",
    businessAddress: "Forretningsadresse",
    postalAddress: "Postadresse",
    street: "Adresse",
    postalCode: "Postnummer",
    city: "Poststed",
    municipality: "Kommune",
    country: "Land",
    textAddress: "Fullstendig adresse",
    registeredAt: "Registreringsdato i Enhetsregisteret",
    establishedAt: "Stiftelsesdato",
    industryCodes: "Næringskoder",
    code: "Kode",
    description: "Beskrivelse",
    numberOfEmployees: "Antall ansatte",
    status: "Status",
    type: "Status",
    openedAt: "Åpningsdato",
    deletedAt: "Slettedato",
    vatRegistered: "Registrert i Merverdiavgiftsregisteret",
    registryUrl: "Kilde",
  },
  "companies-house": {
    companyNumber: "Company number",
    name: "Company name",
    status: "Company status",
    type: "Company type",
    dissolvedAt: "Dissolved on",
    closedAt: "Closed on",
    statusDetail: "Status detail",
    subtype: "Company subtype",
    jurisdiction: "Jurisdiction",
    dateOfCreation: "Date of creation",
    dateOfCessation: "Date of cessation",
    registeredOfficeAddress: "Registered office address",
    serviceAddress: "Service address",
    premises: "Premises",
    addressLine1: "Address line 1",
    addressLine2: "Address line 2",
    locality: "Locality",
    region: "Region",
    postalCode: "Postal code",
    country: "Country",
    poBox: "PO box",
    careOf: "Care of",
    textAddress: "Full address",
    sicCodes: "SIC codes",
    accounts: "Accounts",
    nextDue: "Next due",
    nextMadeUpTo: "Next made up to",
    lastMadeUpTo: "Last made up to",
    overdue: "Overdue",
    confirmationStatement: "Confirmation statement",
    hasCharges: "Charges",
    hasInsolvencyHistory: "Insolvency history",
    hasBeenLiquidated: "Previous liquidation",
    previousNames: "Previous company names",
    effectiveFrom: "Effective from",
    ceasedOn: "Ceased on",
    registryUrl: "Source",
  },
  denue: {
    id: "Id establecimiento",
    clee: "CLEE",
    name: "Nombre de la unidad económica",
    legalName: "Razón social",
    activityClass: "Clase de actividad",
    employeeStratum: "Estrato de personal ocupado",
    unitType: "Tipo de unidad económica",
    address: "Domicilio",
    line1: "Calle y número",
    line2: "Colonia",
    postalCode: "Código postal",
    locality: "Localidad",
    municipality: "Municipio",
    state: "Entidad federativa",
    country: "País",
    textAddress: "Domicilio completo",
    coordinates: "Coordenadas",
    latitude: "Latitud",
    longitude: "Longitud",
    phone: "Teléfono",
    email: "Correo electrónico",
    website: "Sitio web",
    shoppingCenter: "Centro comercial",
    shoppingCenterType: "Tipo de centro comercial",
    unitNumber: "Número de local",
    registryUrl: "Fuente",
  },
  edgar: {
    cik: "CIK",
    name: "Registrant name",
    sic: "SIC",
    sicDescription: "SIC description",
    tickers: "Ticker symbols",
    exchanges: "Exchanges",
    ein: "EIN",
    addresses: "Addresses",
    mailing: "Mailing address",
    business: "Business address",
    street: "Street address",
    city: "City",
    region: "State or region",
    postalCode: "ZIP code",
    country: "Country",
    textAddress: "Full address",
    formerNames: "Former names",
    from: "From",
    to: "To",
    recentFilings: "Recent filings",
    accessionNumber: "Accession number",
    form: "Form",
    filingDate: "Filing date",
    reportDate: "Report date",
    acceptanceDateTime: "Acceptance date and time",
    primaryDocument: "Primary document",
    primaryDocDescription: "Primary document description",
    status: "Filing status",
    type: "Status",
    lastFilingDate: "Last filing date",
    registryUrl: "Source",
  },
  gcis: {
    taxId: "統一編號",
    name: "公司名稱",
    capitalAmount: "資本總額",
    paidInCapitalAmount: "實收資本額",
    responsibleName: "代表人姓名",
    location: "公司所在地",
    registerOrganization: "登記機關",
    setupDateRoc: "核准設立日期（民國）",
    setupDate: "核准設立日期",
    lastChangeDateRoc: "最後核准變更日期（民國）",
    lastChangeDate: "最後核准變更日期",
    status: "公司狀況",
    type: "狀況",
    statusDescription: "公司狀況說明",
    registryUrl: "資料來源",
  },
  krs: {
    krsNumber: "Numer KRS",
    register: "Rejestr",
    name: "Nazwa",
    legalForm: "Forma prawna",
    identifiers: "Identyfikatory",
    nip: "NIP",
    regon: "REGON",
    shareCapital: "Kapitał zakładowy",
    amount: "Wysokość kapitału",
    currency: "Waluta",
    address: "Adres",
    street: "Ulica",
    postalCode: "Kod pocztowy",
    city: "Miejscowość",
    country: "Kraj",
    textAddress: "Pełny adres",
    registeredSeat: "Siedziba",
    voivodeship: "Województwo",
    county: "Powiat",
    commune: "Gmina",
    locality: "Miejscowość",
    email: "Adres poczty elektronicznej",
    website: "Adres strony internetowej",
    status: "Stan pozycji",
    type: "Stan",
    registeredAt: "Data rejestracji w KRS",
    lastEntryAt: "Data ostatniego wpisu",
    registryUrl: "Źródło",
  },
  orsr: {
    ico: "IČO",
    name: "Obchodné meno",
    legalForm: "Právna forma",
    address: "Adresa",
    street: "Ulica",
    postalCode: "PSČ",
    city: "Obec",
    country: "Štát",
    textAddress: "Úplná adresa",
    courtFile: "Spisová značka",
    court: "Súd",
    courtName: "Súd",
    section: "Oddiel",
    insertNumber: "Vložka číslo",
    establishedAt: "Deň zápisu",
    terminatedAt: "Deň výmazu",
    shareCapital: "Základné imanie",
    shareCapitalPaid: "Rozsah splatenia",
    actingClause: "Spôsob konania",
    status: "Stav",
    type: "Stav",
    statutoryBodies: "Štatutárne orgány",
    organName: "Názov orgánu",
    members: "Členovia orgánu",
    position: "Funkcia",
    since: "Vznik funkcie",
    stakeholders: "Spoločníci a iné osoby",
    identifier: "Identifikátor",
    share: "Výška vkladu / rozsah splatenia",
    registryUrl: "Zdroj",
  },
  prh: {
    businessId: "Y-tunnus",
    name: "Yrityksen nimi",
    alternateNames: "Aputoiminimet ja rinnakkaistoiminimet",
    isCurrent: "Voimassa oleva nimi",
    legalForm: "Yritysmuoto",
    legalFormCode: "Yritysmuodon koodi",
    streetAddress: "Käyntiosoite",
    postalAddress: "Postiosoite",
    street: "Katuosoite",
    postalCode: "Postinumero",
    city: "Postitoimipaikka",
    country: "Maa",
    textAddress: "Täydellinen osoite",
    mainBusinessLine: "Päätoimiala",
    code: "Toimialakoodi",
    description: "Toimiala",
    status: "Yrityksen tila",
    type: "Tila",
    endedAt: "Päättymispäivä",
    tradeRegisterRegistered: "Kaupparekisterissä",
    registeredAt: "Rekisteröintipäivä",
    registryUrl: "Lähde",
  },
  "recherche-entreprises": {
    siren: "SIREN",
    name: "Dénomination",
    legalFormCode: "Catégorie juridique",
    shortName: "Sigle",
    headOffice: "Siège social",
    matchedEstablishment: "Établissement correspondant",
    siret: "SIRET",
    isHeadOffice: "Établissement siège",
    address: "Adresse",
    street: "Voie",
    postalCode: "Code postal",
    city: "Commune",
    country: "Pays",
    textAddress: "Adresse complète",
    activityCode: "Activité principale",
    status: "État administratif",
    type: "Type",
    closedAt: "Date de fermeture",
    createdAt: "Date de création",
    registeredAt: "Date d'immatriculation",
    ceasedAt: "Date de cessation",
    directors: "Dirigeants",
    fullName: "Nom complet",
    role: "Qualité",
    birthYear: "Année de naissance",
    registryUrl: "Source",
  },
  vies: {
    vatNumber: "VAT number",
    country: "Country code",
    vat: "National VAT number",
    valid: "Valid VAT number",
    status: "Validation status",
    type: "Status",
    userError: "Validation error",
    requestDate: "Validation date",
    name: "Registered name",
    address: "Registered address",
  },
} as const satisfies LabelMaps;

export const registryDetailLabel = ({
  registry,
  key,
}: {
  registry: Registry;
  key: string;
}): string => {
  const labels: Record<string, string> = DETAIL_LABELS[registry];
  const label = Object.hasOwn(labels, key) ? labels[key] : undefined;
  if (label === undefined) {
    return panic(`Missing ${registry} registry field label: ${key}`);
  }
  return label;
};
