/**
 * Globs `entries/<kind>/<slug>/manifest.json` + `icon.svg`, emits
 * `src/catalogue.gen.ts` with all manifests pre-imported. Same trick as
 * `packages/skills/scripts/generate-manifest.ts`: keeps production code
 * filesystem-free and lets bundlers tree-shake.
 *
 * Run via `bun run generate` after adding/editing an entry; CI
 * verifies the file is up to date via `--check`.
 */
import { panic } from "better-result";
import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import path from "node:path";

import { CATALOGUE_KINDS } from "../src/schema";

const packageRoot = path.join(import.meta.dirname, "..");
const entriesRoot = path.join(packageRoot, "entries");
const outputPath = path.join(packageRoot, "src", "catalogue.gen.ts");

type GeneratedEntry = {
  importName: string;
  manifestPath: string;
  /** JSON-encoded string literal — already wrapped in quotes — or "null". */
  iconLiteral: string;
  bodyLiteral: string | null;
};

const entries = CATALOGUE_KINDS.flatMap((kind) => {
  const kindDir = path.join(entriesRoot, pluralize(kind));
  if (!existsSync(kindDir)) {
    return [];
  }
  return readdirSync(kindDir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort((a, b) => a.localeCompare(b))
    .map((slug): GeneratedEntry | null => {
      const folder = path.join(kindDir, slug);
      const manifest = path.join(folder, "manifest.json");
      if (!existsSync(manifest)) {
        return null;
      }
      const importName = toImportName(kind, slug);

      let bodyLiteral: string | null = null;
      if (kind === "skill") {
        const manifestRaw: { entryPath?: string } = JSON.parse(
          readFileSync(manifest, "utf-8"),
        );
        const entryPath = manifestRaw.entryPath ?? "SKILL.md";
        const bodyFile = path.join(folder, entryPath);
        if (existsSync(bodyFile)) {
          bodyLiteral = JSON.stringify(readFileSync(bodyFile, "utf-8"));
        }
      }

      // Icons are inlined as a string literal: data URL for binary
      // (PNG/ICO) icons, the raw SVG text for SVG icons. Bundling
      // locally means catalogue rendering never makes a network
      // request at runtime — same trust model self-hosters expect for
      // everything else.
      const iconPng = path.join(folder, "icon.png");
      const iconSvg = path.join(folder, "icon.svg");
      let iconLiteral = "null";
      if (existsSync(iconPng)) {
        const base64 = readFileSync(iconPng).toString("base64");
        iconLiteral = JSON.stringify(`data:image/png;base64,${base64}`);
      } else if (existsSync(iconSvg)) {
        iconLiteral = JSON.stringify(readFileSync(iconSvg, "utf-8"));
      }

      return {
        importName,
        manifestPath: toImportPath(manifest),
        iconLiteral,
        bodyLiteral,
      };
    })
    .filter((entry): entry is GeneratedEntry => entry !== null);
});

const importLines = entries.map(
  (entry) =>
    `import ${entry.importName} from "${entry.manifestPath}" with { type: "json" };`,
);

const recommendedPath = toImportPath(
  path.join(packageRoot, "entries", "recommended.json"),
);
importLines.push(
  `import recommended from "${recommendedPath}" with { type: "json" };`,
);

const entryRows = entries.map(
  (entry) =>
    `  { manifest: ${entry.importName}, icon: ${entry.iconLiteral}, body: ${entry.bodyLiteral ?? "null"} }`,
);

const output = `// Generated by packages/catalogue/scripts/generate-manifest.ts. Do not edit.

${importLines.join("\n")}

export const GENERATED_ENTRIES = [
${entryRows.join(",\n")},
] as const;

export const GENERATED_RECOMMENDED = recommended;
`;

if (process.argv.includes("--check")) {
  if (!existsSync(outputPath)) {
    panic(
      "Generated catalogue manifest does not exist; run `bun run generate`",
    );
  }
  const current = readFileSync(outputPath, "utf-8");
  if (current !== output) {
    panic(
      "Generated catalogue manifest is out of date; run `bun run generate`",
    );
  }
} else {
  writeFileSync(outputPath, output);
}

function pluralize(kind: (typeof CATALOGUE_KINDS)[number]): string {
  if (kind === "native-tool") {
    return "native-tools";
  }
  return `${kind}s`;
}

function toImportName(kind: string, slug: string): string {
  const camel = `${kind}-${slug}`.replace(/-([a-z0-9])/gu, (_, ch: string) =>
    ch.toUpperCase(),
  );
  return camel.replace(/^[a-z]/u, (ch) => ch.toLowerCase());
}

function toImportPath(absolutePath: string): string {
  const srcDir = path.join(packageRoot, "src");
  const relative = path.relative(srcDir, absolutePath);
  return relative.startsWith(".") ? relative : `./${relative}`;
}
