/**
 * Globs `entries/<kind>/<slug>/manifest.json` + `icon.svg`, emits
 * `src/catalogue.gen.ts` with public manifests pre-imported, and emits
 * API-only skill install payloads into a separate module. Same trick
 * as `packages/skills/scripts/generate-manifest.ts`: keeps production
 * code filesystem-free and lets bundlers tree-shake.
 *
 * Run via `bun run generate` after adding/editing an entry; CI
 * verifies the file is up to date via `--check`.
 */
import { panic } from "better-result";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

import { CATALOGUE_KINDS } from "../src/schema";
import {
  getInspectedDirectoryEntries,
  getInspectedFilePath,
  inspectCatalogueFilesystem,
  type InspectedCatalogueFilesystem,
} from "./catalogue-filesystem";

const packageRoot = path.join(import.meta.dirname, "..");
const defaultEntriesRoot = path.join(packageRoot, "entries");
const outputPath = path.join(packageRoot, "src", "catalogue.gen.ts");
const installPayloadsOutputPath = path.join(
  packageRoot,
  "src",
  "catalogue-install-payloads.gen.ts",
);

export type GeneratedEntry = {
  importName: string;
  manifestPath: string;
  /** JSON-encoded string literal — already wrapped in quotes — or "null". */
  iconLiteral: string;
  skillPayload: GeneratedSkillPayload | null;
};

type GeneratedResourceFile = {
  content: string;
  path: string;
  sizeBytes: number;
};

type GeneratedSkillPayload = {
  bodyLiteral: string;
  resourceFilesLiteral: string;
  slugLiteral: string;
};

/**
 * Scans `entriesRoot` and returns one GeneratedEntry per manifest.
 * Every entry (including github-sourced skills) is emitted into the
 * public catalogue bundle; only in-tree skills carry a `skillPayload`,
 * so github content is structurally excluded from the install-payload
 * bundle. Exported for tests; the CLI main below drives it.
 */
export const collectEntries = (entriesRoot: string): GeneratedEntry[] => {
  const filesystem = inspectCatalogueFilesystem(entriesRoot);
  return CATALOGUE_KINDS.flatMap((kind) => {
    const kindDir = path.join(entriesRoot, pluralize(kind));
    const kindEntries = getInspectedDirectoryEntries(filesystem, kindDir);
    if (kindEntries === null) {
      return [];
    }
    return kindEntries
      .filter((entry) => entry.type === "directory")
      .map((entry) => entry.name)
      .sort((a, b) => a.localeCompare(b))
      .map((slug): GeneratedEntry | null => {
        const folder = path.join(kindDir, slug);
        const manifest = path.join(folder, "manifest.json");
        const inspectedManifest = getInspectedFilePath(filesystem, manifest);
        if (inspectedManifest === null) {
          return null;
        }
        const importName = toImportName(kind, slug);

        let skillPayload: GeneratedSkillPayload | null = null;
        if (kind === "skill") {
          const manifestRaw: {
            source?: "in-tree" | "github";
            entryPath?: string;
            resources?: string[];
          } = JSON.parse(readFileSync(inspectedManifest, "utf-8"));
          // github-sourced skills keep their content upstream; no
          // install payload is bundled for them.
          if (manifestRaw.source !== "github") {
            skillPayload = buildInTreeSkillPayload({
              filesystem,
              folder,
              kind,
              manifestRaw,
              slug,
            });
          }
        }

        return {
          importName,
          manifestPath: toImportPath(manifest),
          iconLiteral: iconLiteralFor(filesystem, folder),
          skillPayload,
        };
      })
      .filter((entry): entry is GeneratedEntry => entry !== null);
  });
};

const importLines = (entries: readonly GeneratedEntry[]): string[] =>
  entries.map(
    (entry) =>
      `import ${entry.importName} from "${entry.manifestPath}" with { type: "json" };`,
  );

type RenderedOutputs = {
  catalogue: string;
  installPayloads: string;
};

const renderOutputs = (entries: readonly GeneratedEntry[]): RenderedOutputs => {
  const lines = importLines(entries);
  const recommendedPath = toImportPath(
    path.join(packageRoot, "entries", "recommended.json"),
  );
  lines.push(
    `import recommended from "${recommendedPath}" with { type: "json" };`,
  );

  const entryRows = entries.map(
    (entry) =>
      `  { manifest: ${entry.importName}, icon: ${entry.iconLiteral} }`,
  );

  const skillPayloadRows = entries
    .map((entry) => entry.skillPayload)
    .filter((payload): payload is GeneratedSkillPayload => payload !== null)
    .map(
      (payload) =>
        `  { slug: ${payload.slugLiteral}, body: ${payload.bodyLiteral}, resourceFiles: ${payload.resourceFilesLiteral} }`,
    );

  const catalogue = `// Generated by packages/catalogue/scripts/generate-manifest.ts. Do not edit.

${lines.join("\n")}

export const GENERATED_ENTRIES = [
${formatRows(entryRows)}
] as const;

export const GENERATED_RECOMMENDED = recommended;
`;

  const installPayloads = `// Generated by packages/catalogue/scripts/generate-manifest.ts. Do not edit.

export const GENERATED_SKILL_INSTALL_PAYLOADS = [
${formatRows(skillPayloadRows)}
] as const;
`;

  return { catalogue, installPayloads };
};

if (import.meta.main) {
  const { catalogue, installPayloads } = renderOutputs(
    collectEntries(defaultEntriesRoot),
  );
  if (process.argv.includes("--check")) {
    assertGeneratedFileCurrent({ content: catalogue, path: outputPath });
    assertGeneratedFileCurrent({
      content: installPayloads,
      path: installPayloadsOutputPath,
    });
  } else {
    writeFileSync(outputPath, catalogue);
    writeFileSync(installPayloadsOutputPath, installPayloads);
  }
}

type BuildInTreeSkillPayloadArgs = {
  filesystem: InspectedCatalogueFilesystem;
  folder: string;
  kind: string;
  manifestRaw: { entryPath?: string; resources?: string[] };
  slug: string;
};

function buildInTreeSkillPayload({
  filesystem,
  folder,
  kind,
  manifestRaw,
  slug,
}: BuildInTreeSkillPayloadArgs): GeneratedSkillPayload {
  const entryPath = normalizeManifestPath(manifestRaw.entryPath ?? "SKILL.md");
  const entryDirectory = path.dirname(entryPath);
  const resourceRoot =
    entryDirectory === "." ? folder : path.join(folder, entryDirectory);
  const bodyFile = path.join(folder, entryPath);
  const inspectedBodyFile = getInspectedFilePath(filesystem, bodyFile);
  if (inspectedBodyFile === null) {
    panic(`${kind}/${slug}: entry file not found: ${entryPath}`);
  }
  const resourceFiles: GeneratedResourceFile[] = (
    manifestRaw.resources ?? []
  ).map((resourcePath) => {
    const normalizedPath = normalizeManifestPath(resourcePath);
    const resourceFile = path.join(resourceRoot, normalizedPath);
    const inspectedResourceFile = getInspectedFilePath(
      filesystem,
      resourceFile,
    );
    if (inspectedResourceFile === null) {
      panic(`${kind}/${slug}: resource file not found: ${normalizedPath}`);
    }
    const content = readFileSync(inspectedResourceFile, "utf-8");
    return {
      content,
      path: normalizedPath,
      sizeBytes: Buffer.byteLength(content, "utf-8"),
    };
  });
  return {
    bodyLiteral: JSON.stringify(readFileSync(inspectedBodyFile, "utf-8")),
    resourceFilesLiteral: JSON.stringify(resourceFiles),
    slugLiteral: JSON.stringify(slug),
  };
}

// Icons are inlined as inert image data URLs. SVGs are encoded rather
// than injected as markup so contributor-provided icons cannot execute
// active content in the app context.
function iconLiteralFor(
  filesystem: InspectedCatalogueFilesystem,
  folder: string,
): string {
  const iconPng = path.join(folder, "icon.png");
  const iconSvg = path.join(folder, "icon.svg");
  const inspectedIconPng = getInspectedFilePath(filesystem, iconPng);
  if (inspectedIconPng !== null) {
    const base64 = readFileSync(inspectedIconPng).toString("base64");
    return JSON.stringify(`data:image/png;base64,${base64}`);
  }
  const inspectedIconSvg = getInspectedFilePath(filesystem, iconSvg);
  if (inspectedIconSvg !== null) {
    const base64 = Buffer.from(
      readFileSync(inspectedIconSvg, "utf-8"),
      "utf-8",
    ).toString("base64");
    return JSON.stringify(`data:image/svg+xml;base64,${base64}`);
  }
  return "null";
}

function assertGeneratedFileCurrent({
  content,
  path: targetPath,
}: {
  content: string;
  path: string;
}) {
  if (!existsSync(targetPath)) {
    panic(
      "Generated catalogue manifest does not exist; run `bun run generate`",
    );
  }
  const current = readFileSync(targetPath, "utf-8");
  if (current !== content) {
    panic(
      "Generated catalogue manifest is out of date; run `bun run generate`",
    );
  }
}

function formatRows(rows: readonly string[]): string {
  if (rows.length === 0) {
    return "";
  }
  return `${rows.join(",\n")},`;
}

function pluralize(kind: (typeof CATALOGUE_KINDS)[number]): string {
  if (kind === "native-tool") {
    return "native-tools";
  }
  return `${kind}s`;
}

function toImportName(kind: string, slug: string): string {
  const camel = `${kind}-${slug}`.replace(
    /-(?<ch>[a-z0-9])/gu,
    (_, ch: string) => ch.toUpperCase(),
  );
  return camel.replace(/^[a-z]/u, (ch) => ch.toLowerCase());
}

function toImportPath(absolutePath: string): string {
  const srcDir = path.join(packageRoot, "src");
  const relative = path.relative(srcDir, absolutePath);
  return relative.startsWith(".") ? relative : `./${relative}`;
}

function normalizeManifestPath(rawPath: string): string {
  if (rawPath.startsWith("/")) {
    panic(`Catalogue path must be relative: ${rawPath}`);
  }

  const normalized = path.posix.normalize(rawPath.replaceAll("\\", "/"));
  if (
    normalized === "." ||
    normalized === ".." ||
    normalized.startsWith("../")
  ) {
    panic(`Catalogue path escapes its entry folder: ${rawPath}`);
  }

  return normalized;
}
