name: "\u26A1 Epic"
description: Epic
title: "epic: "
labels: ["⚡ epic"]
type: "task"
projects: ["stll-ai/1"]

body:
  - type: textarea
    id: epic-description
    validations:
      required: true
    attributes:
      label: Epic description
      description: |
        A description of the epic.

  - type: textarea
    id: motivation
    validations:
      required: true
    attributes:
      label: Motivation
      description: |
        Motivation for the proposal, if relevant (inspiration from users' feedback,
        similar projects, etc.)

  - type: textarea
    id: sources
    validations:
      required: false
    attributes:
      label: Relevant sources
      description: |
        Links to any relevant GitHub repos, papers, or other resources, if relevant.
