import type { OPS } from "pdfjs-dist";

// Text extraction cannot inspect pixels, outlined lettering, or pattern data.
// Only these state/text operators are supported; unknown operators fail closed.
export const hasUnsupportedAnonymizationContent = (
  operators: readonly number[],
  ops: typeof OPS,
) => {
  const supported = new Set([
    ops.dependency,
    ops.save,
    ops.restore,
    ops.transform,
    ops.setLineWidth,
    ops.setLineCap,
    ops.setLineJoin,
    ops.setMiterLimit,
    ops.setDash,
    ops.setRenderingIntent,
    ops.setFlatness,
    ops.setGState,
    ops.beginText,
    ops.endText,
    ops.setCharSpacing,
    ops.setWordSpacing,
    ops.setHScale,
    ops.setLeading,
    ops.setFont,
    ops.setTextRenderingMode,
    ops.setTextRise,
    ops.moveText,
    ops.setLeadingMoveText,
    ops.setTextMatrix,
    ops.nextLine,
    ops.showText,
    ops.showSpacedText,
    ops.nextLineShowText,
    ops.nextLineSetSpacingShowText,
    ops.setCharWidth,
    ops.setCharWidthAndBounds,
    ops.setStrokeColorSpace,
    ops.setFillColorSpace,
    ops.setStrokeColor,
    ops.setFillColor,
    ops.setStrokeGray,
    ops.setFillGray,
    ops.setStrokeRGBColor,
    ops.setFillRGBColor,
    ops.setStrokeCMYKColor,
    ops.setFillCMYKColor,
    ops.setStrokeTransparent,
    ops.setFillTransparent,
    ops.markPoint,
    ops.markPointProps,
    ops.beginMarkedContent,
    ops.beginMarkedContentProps,
    ops.endMarkedContent,
    ops.beginCompat,
    ops.endCompat,
    ops.paintFormXObjectBegin,
    ops.paintFormXObjectEnd,
    ops.beginGroup,
    ops.endGroup,
  ]);
  return operators.some((operator) => !supported.has(operator));
};
