import { useNavigate } from "@tanstack/react-router";
import {
  ContactIcon,
  FileTextIcon,
  FolderIcon,
  LandmarkIcon,
  LayersIcon,
  ScrollTextIcon,
} from "lucide-react";

import { cn } from "@stella/ui/lib/utils";

import type { MentionCategory } from "@/components/chat-mention-extension";
import { isFileDisplayable } from "@/lib/types";
import type { WorkspaceEntity } from "@/lib/types";
import { DocumentIcon } from "@/routes/_protected.workspaces/$workspaceId/-components/document-icon";
import { usePeekStore } from "@/routes/_protected.workspaces/$workspaceId/-components/peek/peek-store";
import { getFirstFile } from "@/routes/_protected.workspaces/$workspaceId/-utils";

const DECISION_HASH_PREFIX = "#stella-decision=";

/** Hash prefix → category mapping. */
const HASH_PREFIXES: { prefix: string; category: MentionCategory }[] = [
  { prefix: "#stella-entity=", category: "entity" },
  { prefix: "#stella-workspace=", category: "workspace" },
  { prefix: "#stella-contact=", category: "contact" },
  { prefix: "#stella-template=", category: "template" },
  { prefix: "#stella-clause=", category: "clause" },
];

/** Parse a href into category + id, or null if not a stella link. */
const parseStellaMentionHref = (
  href: string,
): { category: MentionCategory; id: string } | null => {
  for (const { prefix, category } of HASH_PREFIXES) {
    if (href.startsWith(prefix)) {
      return { category, id: href.slice(prefix.length) };
    }
  }
  return null;
};

/** Open the entity's file in the peek panel. */
export const openEntityInPeek = (entityId: string, label: string) => {
  const entities: WorkspaceEntity[] = [];
  const entity = entities.find((e) => e.entityId === entityId);
  if (!entity) {
    return;
  }

  for (const field of Object.values(entity.fields)) {
    if (field.content.type === "file" && isFileDisplayable(field.content)) {
      usePeekStore.getState().openTab({
        fieldId: field.id,
        entityId,
        label,
      });
      return;
    }
  }
};

/** Resolve the icon for an entity by its ID. */
// TODO: fix me
export const EntityMentionIcon = ({ entityId: _ }: { entityId: string }) => {
  // TODO: fix me
  const entity: WorkspaceEntity | undefined = undefined;
  const file = entity ? getFirstFile(entity) : null;
  const kind: string = "document";

  if (kind === "folder") {
    return <FolderIcon className="inline size-3 shrink-0" />;
  }
  if (file?.mimeType) {
    return (
      <DocumentIcon
        className="inline size-3 shrink-0"
        mimeType={file.mimeType}
      />
    );
  }
  return <FileTextIcon className="inline size-3 shrink-0" />;
};

const CATEGORY_ICON: Record<
  Exclude<MentionCategory, "entity">,
  React.ComponentType<{ className?: string }>
> = {
  workspace: LayersIcon,
  contact: ContactIcon,
  template: FileTextIcon,
  clause: ScrollTextIcon,
};

/** Renders `#stella-*=` and `#stella-decision=` links as
 *  clickable references; all other links render as
 *  normal anchors. */
export const EntityLink = ({
  href,
  children,
  ...props
}: React.AnchorHTMLAttributes<HTMLAnchorElement>) => {
  const navigate = useNavigate();
  // TODO: fix me
  const hasWorkspace = false;

  if (!href) {
    return (
      <a href={href} {...props}>
        {children}
      </a>
    );
  }

  // Decision links are separate from the mention system
  // (not @-mentionable; generated by AI in responses).
  if (href.startsWith(DECISION_HASH_PREFIX)) {
    const decisionId = href.slice(DECISION_HASH_PREFIX.length);

    return (
      <button
        className={cn(
          "inline-flex items-center gap-0.5",
          "text-foreground decoration-muted-foreground/40 underline",
          "underline-offset-2 transition-colors",
          "hover:decoration-foreground cursor-pointer",
        )}
        // eslint-disable-next-line typescript/no-misused-promises
        onClick={() =>
          navigate({
            to: "/knowledge/case-law/$decisionId",
            params: { decisionId },
          })
        }
        type="button"
      >
        <LandmarkIcon className="inline size-3 shrink-0" />
        {children}
      </button>
    );
  }

  const parsed = parseStellaMentionHref(href);
  if (!parsed) {
    return (
      <a href={href} rel="noopener noreferrer" target="_blank" {...props}>
        {children}
      </a>
    );
  }

  const { category, id: rawId } = parsed;
  // Cross-workspace entity mentions use WS_ID:ENTITY_ID format
  const id =
    category === "entity" && rawId.includes(":")
      ? rawId.slice(rawId.indexOf(":") + 1)
      : rawId;
  const label = typeof children === "string" ? children : "Reference";

  // Entity links without workspace context can't be resolved;
  // render as plain text to avoid a broken click handler.
  if (category === "entity" && !hasWorkspace) {
    return <span {...props}>{children}</span>;
  }

  const handleClick = () => {
    if (category === "entity") {
      openEntityInPeek(id, label);
      return;
    }
    if (category === "workspace") {
      // eslint-disable-next-line @typescript-eslint/no-floating-promises
      navigate({
        to: "/workspaces/$workspaceId",
        params: { workspaceId: id },
      });
      return;
    }
    // Phase 2: contact, template, clause navigation
  };

  const icon =
    category === "entity" ? (
      <EntityMentionIcon entityId={id} />
    ) : (
      (() => {
        const Icon = CATEGORY_ICON[category];
        return <Icon className="inline size-3 shrink-0" />;
      })()
    );

  return (
    <button
      className={cn(
        "inline-flex items-center gap-0.5",
        "text-foreground decoration-muted-foreground/40 underline",
        "underline-offset-2 transition-colors",
        "hover:decoration-foreground cursor-pointer",
      )}
      onClick={handleClick}
      type="button"
    >
      {icon}
      {children}
    </button>
  );
};
