import { useNavigate, useRouterState } from "@tanstack/react-router";
import { LandmarkIcon } from "lucide-react";

import { parseChatResourceHref, RESOURCE_TYPE } from "@stll/api-contract";
import { cn } from "@stll/ui/lib/utils";

import { openCaseLawDecision } from "@/components/chat/case-law-open";
import {
  parseStellaMentionHref,
  resolveMentionWorkspaceId,
} from "@/components/chat/chat-mention-href";
import { useEntityIconSource } from "@/components/chat/entity-icon-source";
import { openEntityInInspector } from "@/components/chat/entity-open";
import { navigateToWorkspaceFolder } from "@/components/chat/folder-navigation";
import { MatterIcon } from "@/components/matter-icon";
import { EntityIcon } from "@/components/workspaces/entity-kind-icon";
import { detached } from "@/lib/detached";
import { sanitizeHref } from "@/lib/sanitize-href";

const ICON_CLASS = "inline size-3 shrink-0";

export const EntityMentionIcon = ({
  entityId,
  workspaceId,
}: {
  entityId: string;
  workspaceId: string | undefined;
}) => {
  const source = useEntityIconSource({ entityId, workspaceId });
  return <EntityIcon className={ICON_CLASS} source={source} />;
};

/** Renders `#stella-*=` and `#stella-decision=` links as
 *  clickable references; all other links render as
 *  normal anchors. */
export const EntityLink = ({
  href,
  children,
  workspaceId,
  ...props
}: React.AnchorHTMLAttributes<HTMLAnchorElement> & {
  workspaceId?: string | undefined;
}) => {
  const navigate = useNavigate();
  const pathname = useRouterState({
    select: (state) => state.location.pathname,
  });

  if (!href) {
    return (
      <a href={sanitizeHref(href)} {...props}>
        {children}
      </a>
    );
  }

  // Decision links are separate from the mention system
  // (not @-mentionable; generated by AI in responses).
  const resourceTarget = parseChatResourceHref(href);
  if (resourceTarget?.resource.type === RESOURCE_TYPE.CASE_LAW_DECISION) {
    return (
      <button
        className={cn(
          "inline-flex items-center gap-0.5",
          "text-foreground decoration-foreground-disabled underline",
          "underline-offset-2 transition-colors",
          "hover:decoration-foreground cursor-pointer",
        )}
        onClick={() =>
          detached(
            openCaseLawDecision(resourceTarget.resource.id, navigate),
            "entity-link.open-case-law-decision",
          )
        }
        type="button"
      >
        <LandmarkIcon className="inline size-3 shrink-0" />
        {children}
      </button>
    );
  }

  const parsed = parseStellaMentionHref(href);
  if (!parsed) {
    return (
      <a
        href={sanitizeHref(href)}
        rel="noopener noreferrer"
        target="_blank"
        {...props}
      >
        {children}
      </a>
    );
  }

  const { category, target } = parsed;
  const mentionWorkspaceId = resolveMentionWorkspaceId(target, workspaceId);
  const id = target.resource.id;

  const label = typeof children === "string" ? children : "Reference";

  if (category === "entity" && !mentionWorkspaceId) {
    return <span {...props}>{children}</span>;
  }

  const handleClick = () => {
    if (category === "entity") {
      detached(
        (async () => {
          const result = await openEntityInInspector(
            id,
            label,
            mentionWorkspaceId,
          );

          if (result.type === "folder") {
            await navigateToWorkspaceFolder({
              folderId: result.entityId,
              navigate,
              pathname,
              targetWorkspaceId: result.workspaceId,
            });
          }
        })(),
        "entity-link.open-entity-in-inspector",
      );
      return;
    }
    detached(
      navigate({
        to: "/workspaces/$workspaceId",
        params: { workspaceId: id },
      }),
      "entity-link.navigate",
    );
  };

  const icon =
    category === "entity" ? (
      <EntityMentionIcon entityId={id} workspaceId={mentionWorkspaceId} />
    ) : (
      <MatterIcon
        className="inline size-3 shrink-0"
        matter={{ id, color: null }}
      />
    );

  return (
    <button
      className={cn(
        "inline-flex items-center gap-0.5",
        "text-foreground decoration-foreground-disabled underline",
        "underline-offset-2 transition-colors",
        "hover:decoration-foreground cursor-pointer",
      )}
      onClick={handleClick}
      type="button"
    >
      {icon}
      {children}
    </button>
  );
};
