import { skipToken, useQuery } from "@tanstack/react-query";
import { useNavigate, useRouterState } from "@tanstack/react-router";
import {
  FileTextIcon,
  FolderIcon,
  LandmarkIcon,
  ListTodoIcon,
} from "lucide-react";

import { cn } from "@stll/ui/lib/utils";

import { openCaseLawDecision } from "@/components/chat/case-law-open";
import { parseStellaMentionHref } from "@/components/chat/chat-mention-href";
import { openEntityInInspector } from "@/components/chat/entity-open";
import { navigateToWorkspaceFolder } from "@/components/chat/folder-navigation";
import { MatterIcon } from "@/components/matter-icon";
import { detached } from "@/lib/detached";
import { DocumentIcon } from "@/routes/_protected.workspaces/$workspaceId/-components/document-icon";
import { entityOptions } from "@/routes/_protected.workspaces/$workspaceId/-queries/entities";

const DECISION_HASH_PREFIX = "#stella-decision=";

const ICON_CLASS = "inline size-3 shrink-0";

const useResolvedEntity = ({
  entityId,
  workspaceId,
}: {
  entityId: string;
  workspaceId: string | undefined;
}) => {
  const { data } = useQuery({
    ...(workspaceId
      ? entityOptions(workspaceId, entityId)
      : {
          queryKey: ["entity-link-disabled"] as const,
          queryFn: skipToken,
        }),
    enabled: workspaceId !== undefined,
    staleTime: Number.POSITIVE_INFINITY,
  });

  return data;
};

export const EntityMentionIcon = ({
  entityId,
  workspaceId,
}: {
  entityId: string;
  workspaceId: string | undefined;
}) => {
  const entity = useResolvedEntity({ entityId, workspaceId });

  if (entity?.kind === "folder") {
    return <FolderIcon className={ICON_CLASS} />;
  }

  if (entity?.kind === "task") {
    return <ListTodoIcon className={ICON_CLASS} />;
  }

  for (const field of Object.values(entity?.fields ?? {})) {
    if (field.content.type === "file" && field.content.mimeType.length > 0) {
      return (
        <DocumentIcon
          className={ICON_CLASS}
          mimeType={field.content.mimeType}
        />
      );
    }
  }

  return <FileTextIcon className={ICON_CLASS} />;
};

/** Renders `#stella-*=` and `#stella-decision=` links as
 *  clickable references; all other links render as
 *  normal anchors. */
export const EntityLink = ({
  href,
  children,
  workspaceId,
  ...props
}: React.AnchorHTMLAttributes<HTMLAnchorElement> & {
  workspaceId?: string | undefined;
}) => {
  const navigate = useNavigate();
  const pathname = useRouterState({
    select: (state) => state.location.pathname,
  });

  if (!href) {
    return (
      <a href={href} {...props}>
        {children}
      </a>
    );
  }

  // Decision links are separate from the mention system
  // (not @-mentionable; generated by AI in responses).
  if (href.startsWith(DECISION_HASH_PREFIX)) {
    const decisionRef = href.slice(DECISION_HASH_PREFIX.length);

    return (
      <button
        className={cn(
          "inline-flex items-center gap-0.5",
          "text-foreground decoration-foreground-disabled underline",
          "underline-offset-2 transition-colors",
          "hover:decoration-foreground cursor-pointer",
        )}
        onClick={() =>
          detached(openCaseLawDecision(decisionRef, navigate), "EntityLink")
        }
        type="button"
      >
        <LandmarkIcon className="inline size-3 shrink-0" />
        {children}
      </button>
    );
  }

  const parsed = parseStellaMentionHref(href);
  if (!parsed) {
    return (
      <a href={href} rel="noopener noreferrer" target="_blank" {...props}>
        {children}
      </a>
    );
  }

  const { category, id: rawId } = parsed;
  // Cross-workspace entity mentions use WS_ID:ENTITY_ID format
  const separator = rawId.indexOf(":");
  const mentionWorkspaceId =
    category === "entity" && separator !== -1
      ? rawId.slice(0, separator)
      : workspaceId;
  const id = separator !== -1 ? rawId.slice(separator + 1) : rawId;

  const label = typeof children === "string" ? children : "Reference";

  // Entity links without workspace context can't be resolved;
  // render as plain text to avoid a broken click handler.
  if (category === "entity" && !mentionWorkspaceId) {
    return <span {...props}>{children}</span>;
  }

  const handleClick = () => {
    if (category === "entity") {
      detached(
        (async () => {
          const result = await openEntityInInspector(
            id,
            label,
            mentionWorkspaceId,
          );

          if (result.type === "folder") {
            await navigateToWorkspaceFolder({
              folderId: result.entityId,
              navigate,
              pathname,
              targetWorkspaceId: result.workspaceId,
            });
          }
        })(),
        "handleClick",
      );
      return;
    }
    detached(
      navigate({
        to: "/workspaces/$workspaceId",
        params: { workspaceId: id },
      }),
      "handleClick",
    );
  };

  const icon =
    category === "entity" ? (
      <EntityMentionIcon entityId={id} workspaceId={mentionWorkspaceId} />
    ) : (
      <MatterIcon
        className="inline size-3 shrink-0"
        matter={{ id, color: null }}
      />
    );

  return (
    <button
      className={cn(
        "inline-flex items-center gap-0.5",
        "text-foreground decoration-foreground-disabled underline",
        "underline-offset-2 transition-colors",
        "hover:decoration-foreground cursor-pointer",
      )}
      onClick={handleClick}
      type="button"
    >
      {icon}
      {children}
    </button>
  );
};
