export type {
  DocDefaults,
  FontInfo,
  FontTable,
  MediaFile,
  Relationship,
  RelationshipMap,
  RelationshipType,
  Style,
  StyleDefinitions,
  StyleType,
  Theme,
  ThemeColorScheme,
  ThemeFont,
  ThemeFontScheme,
} from "@stll/docx-core/model";
