// Official Czech names from ČSÚ FORMA (code list 56), valid 2026-09-06.
// https://apl2.czso.cz/iSMS/do_cis_export?kodcis=56&typdat=0&cisjaz=203&format=2&datpohl=06.09.2026
// These are registry data, not translated UI labels. Unknown codes remain
// available to callers; never infer a different legal form from an unknown code.
const LEGAL_FORMS: Readonly<Record<string, string>> = {
  "000": "Zatím neurčeno",
  "101": "Fyzická osoba podnikající dle živnostenského zákona",
  "105":
    "Fyzická osoba podnikající dle jiných zákonů než živnostenského a zákona o zemědělství",
  "107": "Zemědělský podnikatel - fyzická osoba",
  "111": "Veřejná obchodní společnost",
  "112": "Společnost s ručením omezeným",
  "113": "Společnost komanditní",
  "115": "Společný podnik",
  "116": "Zájmové sdružení",
  "117": "Nadace",
  "118": "Nadační fond",
  "121": "Akciová společnost",
  "141": "Obecně prospěšná společnost",
  "145": "Společenství vlastníků jednotek",
  "151": "Komoditní burza",
  "161": "Ústav",
  "205": "Družstvo",
  "301": "Státní podnik",
  "313": "Česká národní banka",
  "325": "Organizační složka státu",
  "326": "Stálý rozhodčí soud",
  "331": "Příspěvková organizace zřízená územním samosprávným celkem",
  "332": "Státní příspěvková organizace",
  "334": "Veřejná kulturní instituce",
  "352": "Státní organizace Správa železnic",
  "353": "Rada pro veřejný dohled nad auditem",
  "361": "Veřejnoprávní instituce (ČT,ČRo,ČTK)",
  "381": "Fond (ze zákona)",
  "391": "Zdravotní pojišťovna",
  "421": "Odštěpný závod zahraniční právnické osoby",
  "422": "Organizační složka zahraničního nadačního fondu",
  "423": "Organizační složka zahraniční nadace",
  "424": "Zahraniční fyzická osoba",
  "425": "Odštěpný závod zahraniční fyzické osoby",
  "426": "Zastoupení zahraniční banky",
  "501":
    "Odštěpný závod nebo jiná organizační složka podniku zapisující se do obchodního rejstříku",
  "521": "Samostatná drobná provozovna obecního úřadu",
  "541": "Podílový, penzijní fond",
  "601": "Vysoká škola (veřejná, státní)",
  "641": "Školská právnická osoba",
  "661": "Veřejná výzkumná instituce",
  "704":
    "Zvláštní organizace pro zastoupení českých zájmů v mezinárodních nevládních organizacích",
  "705": "Podnik nebo hospodářské zařízení sdružení",
  "706": "Spolek",
  "707": "Odborová organizace",
  "708": "Organizace zaměstnavatelů",
  "711": "Politická strana, politické hnutí",
  "715": "Podnik nebo hospodářské zařízení politické strany",
  "721": "Církve a náboženské společnosti",
  "722": "Evidované církevní právnické osoby",
  "723": "Svazy církví a náboženských společností",
  "733": "Organizační jednotka odborové organizace a organizace zaměstnavatelů",
  "734":
    "Organizační jednotka zvláštní organizace pro zastoupení českých zájmů v mezinárodních nevládních organizacích",
  "736": "Pobočný spolek",
  "741": "Stavovská organizace - profesní komora",
  "745": "Komora (s výjimkou profesních komor)",
  "751": "Zájmové sdružení právnických osob",
  "761": "Honební společenstvo",
  "771": "Dobrovolný svazek obcí",
  "801": "Obec nebo městská část hlavního města Prahy",
  "804": "Kraj a hl.m.Praha",
  "901": "Zastupitelský orgán jiných států",
  "906": "Zahraniční spolek",
  "907": "Mezinárodní odborová organizace",
  "908": "Mezinárodní organizace zaměstnavatelů",
  "911":
    "Zahraniční kulturní, informační středisko, rozhlasová, tisková a televizní agentura",
  "921": "Mezinárodní nevládní organizace",
  "922": "Organizační jednotka mezinárodní nevládní organizace",
  "931": "Evropské hospodářské zájmové sdružení",
  "932": "Evropská společnost",
  "933": "Evropská družstevní společnost",
  "936": "Zahraniční pobočný spolek",
  "941": "Evropské seskupení pro územní spolupráci",
  "950": "Subjekt právním řádem výslovně neupravený",
  "951":
    "Mezinárodní vojenská organizace vzniklá na základě mezinárodní smlouvy",
  "952": "Konsorcium evropské výzkumné infrastruktury",
  "960":
    "Právnická osoba zřízená zvláštním zákonem zapisovaná do veřejného rejstříku",
  "963": "Národní akreditační úřad pro terciární vzdělávání",
  "964": "Historická právnická osoba – církevní fond",
};

export const getAresLegalFormName = (code: string): string | null =>
  Object.hasOwn(LEGAL_FORMS, code) ? (LEGAL_FORMS[code] ?? null) : null;
