import {
  RESOURCE_TYPE,
  toResourceName,
  type ResourceRef,
  type ResourceType,
} from "@stll/api-contract";

type SearchDisposition = { type: "searchable" } | { type: "not_searched" };

const NOT_SEARCHED = { type: "not_searched" } as const;

/** Every canonical resource kind must explicitly choose global-search behavior. */
export const SEARCH_RESOURCE_DISPOSITION = {
  [RESOURCE_TYPE.AGENT_SKILL]: NOT_SEARCHED,
  [RESOURCE_TYPE.AGENT_SKILL_COMMENT]: NOT_SEARCHED,
  [RESOURCE_TYPE.AGENT_SKILL_PROPOSAL]: NOT_SEARCHED,
  [RESOURCE_TYPE.AGENT_SKILL_RESOURCE]: NOT_SEARCHED,
  [RESOURCE_TYPE.AGENT_SKILL_REVISION]: NOT_SEARCHED,
  [RESOURCE_TYPE.AI_MEMORY]: NOT_SEARCHED,
  [RESOURCE_TYPE.BILLING_CODE]: NOT_SEARCHED,
  [RESOURCE_TYPE.CASE_LAW_DECISION]: { type: "searchable" },
  [RESOURCE_TYPE.CASE_LAW_SOURCE]: NOT_SEARCHED,
  [RESOURCE_TYPE.CHAT_MESSAGE]: NOT_SEARCHED,
  [RESOURCE_TYPE.CHAT_THREAD]: { type: "searchable" },
  [RESOURCE_TYPE.CLAUSE]: NOT_SEARCHED,
  [RESOURCE_TYPE.CLAUSE_CATEGORY]: NOT_SEARCHED,
  [RESOURCE_TYPE.CLAUSE_VARIANT]: NOT_SEARCHED,
  [RESOURCE_TYPE.CLAUSE_VERSION]: NOT_SEARCHED,
  [RESOURCE_TYPE.CONTACT]: { type: "searchable" },
  [RESOURCE_TYPE.DOCUMENT_TYPE]: NOT_SEARCHED,
  [RESOURCE_TYPE.ENTITY]: { type: "searchable" },
  [RESOURCE_TYPE.ENTITY_VERSION]: NOT_SEARCHED,
  [RESOURCE_TYPE.EXPENSE]: NOT_SEARCHED,
  [RESOURCE_TYPE.FIELD]: NOT_SEARCHED,
  [RESOURCE_TYPE.FLOW_DEFINITION]: NOT_SEARCHED,
  [RESOURCE_TYPE.FLOW_RUN]: NOT_SEARCHED,
  [RESOURCE_TYPE.INVOICE]: NOT_SEARCHED,
  [RESOURCE_TYPE.LEGAL_LIST]: NOT_SEARCHED,
  [RESOURCE_TYPE.LEGISLATION_DOCUMENT]: NOT_SEARCHED,
  [RESOURCE_TYPE.LEGISLATION_SOURCE]: NOT_SEARCHED,
  [RESOURCE_TYPE.MCP_CONNECTOR]: NOT_SEARCHED,
  [RESOURCE_TYPE.ORGANIZATION]: NOT_SEARCHED,
  [RESOURCE_TYPE.PLAYBOOK]: NOT_SEARCHED,
  [RESOURCE_TYPE.PLAYBOOK_VERSION]: NOT_SEARCHED,
  [RESOURCE_TYPE.PROPERTY]: NOT_SEARCHED,
  [RESOURCE_TYPE.RATE_ENTRY]: NOT_SEARCHED,
  [RESOURCE_TYPE.RATE_TABLE]: NOT_SEARCHED,
  [RESOURCE_TYPE.REPORT_EXPORT]: NOT_SEARCHED,
  [RESOURCE_TYPE.SAVED_SEARCH]: NOT_SEARCHED,
  [RESOURCE_TYPE.STYLE_SET]: NOT_SEARCHED,
  [RESOURCE_TYPE.TEMPLATE]: NOT_SEARCHED,
  [RESOURCE_TYPE.TEMPLATE_CATEGORY]: NOT_SEARCHED,
  [RESOURCE_TYPE.TEMPLATE_VERSION]: NOT_SEARCHED,
  [RESOURCE_TYPE.TIME_ENTRY]: NOT_SEARCHED,
  [RESOURCE_TYPE.USER]: NOT_SEARCHED,
  [RESOURCE_TYPE.USER_FILE]: NOT_SEARCHED,
  [RESOURCE_TYPE.WORKSPACE]: { type: "searchable" },
  [RESOURCE_TYPE.WORKSPACE_VIEW]: NOT_SEARCHED,
  [RESOURCE_TYPE.WORKSPACE_VIEW_TEMPLATE]: NOT_SEARCHED,
} as const satisfies Record<ResourceType, SearchDisposition>;

type SearchableResourceType = {
  [TType in ResourceType]: (typeof SEARCH_RESOURCE_DISPOSITION)[TType]["type"] extends "searchable"
    ? TType
    : never;
}[ResourceType];

/** Bind a search hit's public id to the exact resource it projects. */
export const globalSearchIdentity = <
  TResource extends ResourceRef<SearchableResourceType>,
>(
  resource: TResource,
) => ({ resource, resourceName: toResourceName(resource) });
