import { toolDefinition } from "@tanstack/ai";
import * as v from "valibot";

import type { FolioAIEditSkipReason } from "@stll/folio-core/ai-edits";
import { FOLIO_DOCUMENT_OPERATION_CONTRACT_VERSION } from "@stll/folio-core/server";

import { normalizeActiveDocxEditToolInput } from "@/api/handlers/chat/tools/active-docx-edit-tool-repair";
import { toTanStackToolSchema } from "@/api/handlers/chat/tools/tanstack-tool-schema";

export const APPLY_ACTIVE_DOCX_EDITS_TOOL_NAME = "apply-active-docx-edits";

/**
 * Input, validation, and result shapes below are derived mechanically from
 * folio's versioned document-operation contract: `FolioAIEditOperation` /
 * `FolioDocumentOperationBatch` / `parseFolioDocumentOperationBatch` in
 * `@stll/folio-core` (see `dist/document-operations.d.ts` and
 * `dist/ai-edits/types.d.ts`). Folio exports a strict throwing parser, not a
 * standard schema, and TanStack tool definitions need a standard schema with
 * a JSON-Schema projection — so the shapes are mirrored in valibot here and
 * `active-docx-edit-tool.test.ts` keeps them honest by round-tripping every
 * accepted operation through `parseFolioDocumentOperationBatch`.
 *
 * Deliberate divergences from the folio batch contract, all narrowing:
 * - `severity` / `area` are REQUIRED (folio's `FolioAIEditReviewMeta` has
 *   them optional): the review panel sorts by severity and groups by area.
 * - `formatRange` is not accepted: it is a direct-only operation (see
 *   `FOLIO_DOCUMENT_OPERATION_MODES_BY_TYPE`) and this surface queues
 *   suggestions into a tracked-changes review flow whose prompt explicitly
 *   promises no run-formatting changes.
 * - `precondition` (blockTextHash) is not accepted: the model never sees
 *   block text hashes on this surface, so it could only fabricate them.
 * - `mode` / `atomic` / `dryRun` are not accepted on the batch: operations
 *   are queued for per-suggestion human review, not applied, so none of the
 *   three can be honored. The strict envelope rejects them loudly instead of
 *   silently dropping them.
 */

const commentSchema = v.strictObject({
  text: v.pipe(
    v.string(),
    v.minLength(1),
    v.maxLength(2000),
    v.description("Optional Word comment text to attach to this edit."),
  ),
});

const severitySchema = v.pipe(
  v.picklist(["low", "medium", "high"]),
  v.description(
    'Required. "low" for typos, spelling, minor style; "medium" for ' +
      'wording or terminology fixes; "high" for substantive changes ' +
      "(numbers, dates, parties, legal effect). The review panel " +
      "sorts by this — pick one.",
  ),
);

const areaSchema = v.pipe(
  v.string(),
  v.minLength(1),
  v.maxLength(64),
  v.description(
    "Required. Short topic label that groups related operations: " +
      '"Spelling", "Names", "Penalty", "Arbitration", "Payment Terms", ' +
      '"Cross-references", "General". The review panel groups by this — ' +
      "use a consistent label across operations that belong together.",
  ),
);

// Optional caller-supplied operation id, same semantics as folio's
// `suggest_changes` tool: echoed back in `queued` / `skipped`, generated by
// the executor when omitted. NOT a block id — the target block goes in
// `blockId` (or `range.blockId`).
const operationIdSchema = v.pipe(
  v.string(),
  v.minLength(1),
  v.maxLength(64),
  v.description(
    "Optional operation id, echoed back in `queued`/`skipped` so results " +
      "can be matched to operations. Auto-generated when omitted. This is " +
      "NOT the target block — that goes in `blockId`.",
  ),
);

const blockIdSchema = v.pipe(
  v.string(),
  v.minLength(1),
  v.description(
    'Block id from the active DOCX editing snapshot, for example "b-0010".',
  ),
);

// Shared review metadata for every operation variant.
const baseOperationSchema = {
  id: v.optional(operationIdSchema),
  severity: severitySchema,
  area: areaSchema,
} as const;

const blockOperationSchema = {
  ...baseOperationSchema,
  blockId: blockIdSchema,
} as const;

// Mirrors folio's `FolioAITextRangeHandle`: a serializable range over one
// block's visible text. Strict (like folio's range parser) because a handle
// is only valid when copied verbatim from `find_text`; `selectedTextHash`
// makes a shifted or changed selection fail with `staleRange` instead of
// editing the wrong text.
const textRangeHandleSchema = v.pipe(
  v.strictObject({
    type: v.literal("textRange"),
    story: v.literal("main"),
    blockId: blockIdSchema,
    startOffset: v.pipe(v.number(), v.integer(), v.minValue(0)),
    endOffset: v.pipe(v.number(), v.integer(), v.minValue(1)),
    selectedTextHash: v.pipe(v.string(), v.minLength(1)),
  }),
  v.description(
    "Text-range handle. Copy the `range` object returned by `find_text` " +
      "verbatim — the offsets and hash are not guessable.",
  ),
);

const styleIdSchema = v.pipe(
  v.string(),
  v.minLength(1),
  v.maxLength(64),
  v.description(
    "Optional Word paragraph style id to apply to the inserted or " +
      "replaced paragraph. Use canonical legal-source ids: " +
      '"ClauseHeading1", "ClauseHeading2", "ClauseHeading3" for ' +
      "numbered headings. Leave unset for plain body paragraphs.",
  ),
);

const signaturePartySchema = v.strictObject({
  name: v.pipe(
    v.string(),
    v.minLength(1),
    v.description(
      "Legal name of the party. Rendered bold above the signature line.",
    ),
  ),
  signatory: v.optional(
    v.pipe(
      v.string(),
      v.minLength(1),
      v.description(
        "Name of the person signing for this party. Rendered below " +
          "the signature line; omit to leave it blank for hand-fill.",
      ),
    ),
  ),
  title: v.optional(
    v.pipe(
      v.string(),
      v.minLength(1),
      v.description(
        "Optional role/title of the signatory, e.g. 'CEO'. Rendered " +
          "in italics below the signatory name.",
      ),
    ),
  ),
});

// `v.object` (not `strictObject`): the model occasionally tacks on
// fields valid on one variant but not another (e.g. `position` on
// `insertAfterBlock`). Strict mode rejects the whole batch over a
// single stray key and the user's approved edit silently vanishes.
// Liberal mode strips the unknown field and proceeds.
const operationSchema = v.variant("type", [
  v.object({
    ...blockOperationSchema,
    type: v.literal("replaceInBlock"),
    find: v.pipe(
      v.string(),
      v.minLength(1),
      v.description("Exact text to replace inside the target block."),
    ),
    replace: v.pipe(v.string(), v.description("Replacement text.")),
    comment: v.optional(commentSchema),
  }),
  v.object({
    ...baseOperationSchema,
    type: v.literal("replaceRange"),
    range: textRangeHandleSchema,
    replace: v.pipe(v.string(), v.description("Replacement text.")),
    comment: v.optional(commentSchema),
  }),
  v.object({
    ...baseOperationSchema,
    type: v.literal("commentOnRange"),
    range: textRangeHandleSchema,
    comment: commentSchema,
  }),
  v.object({
    ...blockOperationSchema,
    type: v.union([
      v.literal("insertAfterBlock"),
      v.literal("insertBeforeBlock"),
    ]),
    text: v.pipe(
      v.string(),
      v.description(
        "Text for the inserted block. May be empty when " +
          "`pageBreakBefore` is true (the inserted paragraph " +
          "exists only to force a page break).",
      ),
    ),
    inheritFormatting: v.optional(v.boolean()),
    pageBreakBefore: v.optional(
      v.pipe(
        v.boolean(),
        v.description(
          "When true, the inserted paragraph carries `pageBreakBefore` " +
            "so the layout starts it on a new page. Use this for " +
            "explicit page breaks instead of literal directive text.",
        ),
      ),
    ),
    styleId: v.optional(styleIdSchema),
    comment: v.optional(commentSchema),
  }),
  v.object({
    ...blockOperationSchema,
    type: v.literal("replaceBlock"),
    // Allow empty text — the client normalizes
    // `replaceBlock(text: "")` to a `deleteBlock`, so the model
    // doesn't have to pick between the two when its intent is
    // "remove this paragraph". Schema stays liberal; the apply path
    // produces the canonical op.
    text: v.pipe(
      v.string(),
      v.description("Full replacement text for the target block."),
    ),
    preserveFormatting: v.optional(v.boolean()),
    styleId: v.optional(styleIdSchema),
    comment: v.optional(commentSchema),
  }),
  v.object({
    ...blockOperationSchema,
    type: v.literal("deleteBlock"),
    comment: v.optional(commentSchema),
  }),
  v.object({
    ...blockOperationSchema,
    type: v.literal("commentOnBlock"),
    quote: v.optional(
      v.pipe(
        v.string(),
        v.minLength(1),
        v.description("Optional exact quote inside the target block."),
      ),
    ),
    comment: commentSchema,
  }),
  v.object({
    ...blockOperationSchema,
    type: v.literal("insertSignatureTable"),
    position: v.optional(
      v.pipe(
        v.picklist(["after", "before"]),
        v.description(
          "Where to insert the signature table relative to the " +
            'anchor block. Defaults to "after".',
        ),
      ),
    ),
    parties: v.pipe(
      v.array(signaturePartySchema),
      v.minLength(1),
      v.maxLength(8),
      v.description(
        "Parties to render side-by-side in the signature table, " +
          "one column per party. Each column has the party name " +
          "bold, two blank spacer lines, an underscore signature " +
          "rule, then optional signatory and italic title lines.",
      ),
    ),
    comment: v.optional(commentSchema),
  }),
]);

// Every skip reason folio's ai-edits engine can produce
// (`FolioAIEditSkipReason` in `@stll/folio-core`). `satisfies` keeps each
// entry checked against the folio union, so a folio rename/removal fails
// typecheck here instead of silently drifting.
const FOLIO_AI_EDIT_SKIP_REASONS = [
  "missingBlock",
  "changedBlock",
  "ambiguousFind",
  "missingFind",
  "unsupportedBlock",
  "unsupportedMode",
  "atomicBatchRejected",
  "preconditionFailed",
  "staleRange",
  "emptyOperation",
  "noopOperation",
] as const satisfies readonly FolioAIEditSkipReason[];

const skippedOperationSchema = v.strictObject({
  id: v.string(),
  reason: v.picklist([
    ...FOLIO_AI_EDIT_SKIP_REASONS,
    // Stella-surface extension: the call arrived with no editable DOCX
    // open, so nothing could even be queued. Not a folio skip reason —
    // folio's executor is never invoked in that state.
    "documentNotEditable",
  ]),
});

// Mirrors folio's `FolioAIEditAppliedOperation` receipt (kept honest by the
// typed fixture in `active-docx-edit-tool.test.ts`): `commentId` for a
// created Word comment, `revisionId` / `revisionIds` for the tracked-change
// marks the operation produced (a replace carries separate deletion- and
// insertion-side ids).
const appliedOperationSchema = v.strictObject({
  id: v.string(),
  commentId: v.optional(v.number()),
  revisionId: v.optional(v.number()),
  revisionIds: v.optional(v.array(v.number())),
});

const outputSchema = v.strictObject({
  version: v.pipe(
    v.literal(FOLIO_DOCUMENT_OPERATION_CONTRACT_VERSION),
    v.description(
      "Document-operation contract version the executor speaks " +
        "(mirrors folio's `FolioDocumentOperationResult.version`).",
    ),
  ),
  applied: v.pipe(
    v.array(appliedOperationSchema),
    v.description(
      "Operations already written to the document by this tool call. " +
        "With the queued flow this list is normally empty; only claim a " +
        "change was made for ids that appear here.",
    ),
  ),
  queued: v.pipe(
    v.optional(
      v.array(
        v.strictObject({
          id: v.string(),
        }),
      ),
    ),
    v.description(
      "Operations now visible to the user as suggestions in the review " +
        "panel. NOT yet written to the document — the user reviews them " +
        "and applies each individually (or all at once). Tell the user " +
        "the suggestions are ready for review; do NOT claim the document " +
        "was changed. Do not retry these operations.",
    ),
  ),
  skipped: v.pipe(
    v.array(skippedOperationSchema),
    v.description(
      "Operations that could not be queued (e.g. no active file, " +
        "missing block). Tell the user plainly what is missing.",
    ),
  ),
});

const inputSchema = v.strictObject({
  version: v.pipe(
    // Optional with a pinned default rather than required: pending
    // approvals created before the versioned contract round-trip through
    // input validation when the user approves them, and they carry no
    // version. Absent means the original (current) contract; any OTHER
    // value is rejected, matching folio's
    // `assertSupportedFolioDocumentOperationVersion` semantics.
    v.optional(
      v.literal(FOLIO_DOCUMENT_OPERATION_CONTRACT_VERSION),
      FOLIO_DOCUMENT_OPERATION_CONTRACT_VERSION,
    ),
    v.description("Document-operation contract version. Always 1."),
  ),
  operations: v.pipe(
    v.array(operationSchema),
    v.minLength(1),
    // Long contracts routinely produce 50+ legitimate ops in
    // one redline pass (verified in trace: a 40-op
    // cross-reference cleanup hit the old 20 cap and the
    // tool returned error-text — the model then claimed "40
    // ready" because it didn't read the validation failure).
    // The review panel sorts/groups large batches fine; the
    // ceiling here is just a sanity guard, not a UX limit.
    v.maxLength(200),
    v.description("Operations to apply to the active DOCX."),
  ),
});

const inputToolSchema = toTanStackToolSchema(inputSchema);

const repairingInputToolSchema = {
  ...inputToolSchema,
  "~standard": {
    ...inputToolSchema["~standard"],
    validate: async (input: unknown) => {
      const initial = await inputToolSchema["~standard"].validate(input);
      if (initial.issues === undefined) {
        return initial;
      }

      const serialized = JSON.stringify(input);
      if (typeof serialized !== "string") {
        return initial;
      }

      const repaired = normalizeActiveDocxEditToolInput(serialized);
      if (repaired === null) {
        return initial;
      }

      return await inputToolSchema["~standard"].validate(JSON.parse(repaired));
    },
  },
} satisfies typeof inputToolSchema;

export const createActiveDocxEditTool = () =>
  toolDefinition({
    name: APPLY_ACTIVE_DOCX_EDITS_TOOL_NAME,
    description:
      "Propose edits for the DOCX currently open in the document " +
      "editor. Use this whenever the user asks to change, edit, " +
      "replace, rewrite, revise, or update text in the open DOCX, or asks " +
      "for a review/redline. Send a versioned operation batch: " +
      '`{"version": 1, "operations": [...]}`. ' +
      "Operations are queued for the user to review " +
      "and apply themselves; this tool does NOT write to the document. " +
      "Write document prose, not markdown: no `#` headings, list dashes, " +
      "or backticks. For a bold heading set `styleId` (e.g. ClauseHeading1). " +
      "Inserted block `text` may use `**bold**` / `***bold italic***` for " +
      "inline emphasis; in `replace` write plain text, since redlined " +
      "replacements are not re-formatted. See each schema field for its " +
      "semantics.",
    needsApproval: true,
    inputSchema: repairingInputToolSchema,
    outputSchema: toTanStackToolSchema(outputSchema),
  });
