export const VISUAL_SHOWCASE_GUIDANCE = `CASE-LAW VISUALS:
Use search_case_law's first-page facets.courtYear for the court/year distribution of the first phrasing. Never infer the whole distribution from returned hits or passage counts. Preserve court filter values, courtName, courtAbbreviation, tier, year, count, nullable citationSum/treatment, and truncated. If the aggregate is null, search page one again or explain its absence; never invent counts. Distinct-decision cardinality counts are estimates. When truncated, label the sum as covering displayed groups only.

Write a content-first page with a clear title and query scope, a headline row (estimated decisions in displayed groups, courts, years, highest citationCount among returned decisions), a court → year treemap, and a ranked list. Use stella.charts.treemap(el, {data: tree, value: 'count', color: {mode: 'category', field: 'tier', legend: true}, onSelect}). Groups have {type:'group', id, label, tier, children}; year leaves have {type:'bucket', id, label, count, citationSum, treatment, tier, court, year}. Group by the exact court filter value. NS and NSS both have tier 'supreme'; their identical color is correct. Court names and the localized legend carry the meaning. Aggregate citations and treatment are unavailable today: retain null, offer no citation color or treatment toggle.

Deduplicate returned passage hits by decision, omit hits with unknown citationCount, and rank the remaining hits by citationCount. Label the list 'most cited among top results' and explain that it covers this results page, not the whole corpus. Use read_case_law_citations when citation detail is needed; a bounded citation page is not a corpus total. Never call synthetic fixture decision ids in a real answer.

Pass only the data the page renders. Read it from stella.data; use inline scripts and the supplied chart runtime without imports, external assets, or network requests. Render names and case numbers with textContent. Provide links as {id, decisionId}; list buttons call stella.openDecision(id). A selected bucket calls stella.drill({court: node.court, year: node.year}); a group only zooms. The user sends the offered follow-up chip. On that follow-up, search with those filters and build a new visual from the new aggregate and results, with an updated scope.

Localize every label to the user's language, including chart help, scope, ranking, and empty states; format numbers with the user's full formatting locale. Show unavailable aggregate statistics as unavailable, not zero. Call stella.ready() after mounting the chart and list, including empty states. The reference page is fixtures/showcase/court-year-showcase.html; its matching JSON is synthetic demonstration data, with separate Czech and English labels.`;
