/**
 * Function words per corpus language: the words a reader's question is built
 * out of rather than the words it is about.
 *
 * Why this exists. Every token of a free-text query is AND-ed, so a
 * nine-word question like "jak velký musí být dluh na nájemném pro výpověď z
 * nájmu" asks the engine for decisions carrying all nine, and no judgment is
 * written the way a question is asked. The content words are in the corpus;
 * "jak", "musí", "být", "pro" and "na" are what empty the result set. So the
 * query builder keeps the content words required and drops these.
 *
 * Dropped entirely, not kept as an optional alternative. The clause this
 * builder emits is a conjunction of required terms, so a word is either
 * required or absent from it. Absent costs the ranking almost nothing: these
 * are the highest-frequency words in the corpus, so their contribution to a
 * relevance score is near zero either way.
 *
 * ## Lower-cased and NFC, accents kept — deliberately not ASCII-folded
 *
 * The index folds accents (`FOLDED_TOKENIZER`), and matching these lists the
 * same way would be the obvious choice. It is wrong here: Czech "být" (to
 * be) and "byt" (a flat) fold to the same token, and so do Slovak "byť" and
 * "byt". A flat is the subject of most tenancy disputes in the corpus, so a
 * folded list drops a content word from every query about one. Matching with
 * accents kept drops only what the reader unambiguously wrote as a function
 * word; a reader who types no diacritics keeps a word the clause then
 * requires, which is the pre-existing behaviour and never worse than losing
 * the noun. `function-words.test.ts` pins the collision so the rule cannot
 * be "simplified" back to folding.
 *
 * ## Polarity words are never function words
 *
 * A word whose removal can make the query match decisions asserting the
 * OPPOSITE proposition stays required, however grammatical it looks. So the
 * negations ("ne", "není", "nie", "nicht", "not") and the privatives ("bez",
 * "kromě", "ohne", "without") are deliberately absent from every list below:
 * "smlouva je neplatná bez podpisu" read without "bez" is a claim about
 * contracts WITH a signature, and a reader researching one proposition must
 * never be handed the other. Loosening a query is the point of this module;
 * inverting one is a different thing entirely, and `function-words.test.ts`
 * holds the class out of every language.
 *
 * ## Coverage, not discrimination
 *
 * Words shared by Czech and Slovak appear in both lists. This is the
 * opposite of `LANGUAGE_STOPWORDS` in `lib/templates/template-languages.ts`,
 * whose sets are deliberately pairwise disjoint because it detects which
 * language a document is written in; that list must not be reused here, and
 * this one must not be reused there.
 */

import { CORPUS_MORPHOLOGY_LANGUAGES } from "@/api/lib/legal-search/morphology/corpus-language";
import type { MorphologyLanguage } from "@/api/lib/legal-search/morphology/stem";

/**
 * Languages whose function words a query may drop: every language the
 * corpus's own jurisdictions are written in, plus English, each once.
 *
 * English is listed explicitly as well because the multi-language EU index
 * spans 24 languages under one jurisdiction, so it has no jurisdiction
 * language, and its queries stem — and drop function words — only under the
 * language a request names.
 *
 * Derived from the jurisdiction set rather than hand-listed, so a new
 * single-language corpus cannot land without a list: {@link FUNCTION_WORDS}
 * is total over this union and fails to compile until one is authored.
 */
export const FUNCTION_WORD_LANGUAGES = [
  ...new Set([...CORPUS_MORPHOLOGY_LANGUAGES, "en" as const]),
] satisfies readonly MorphologyLanguage[];

export type FunctionWordLanguage = (typeof FUNCTION_WORD_LANGUAGES)[number];

/**
 * Czech. Interrogatives first because they are what makes a question a
 * question, then prepositions, conjunctions, the copula and the modals, then
 * demonstratives and personal pronouns.
 */
const CZECH_FUNCTION_WORDS = [
  "jak",
  "jaká",
  "jaké",
  "jakou",
  "jaký",
  "kde",
  "kdo",
  "kdy",
  "kolik",
  "která",
  "které",
  "kteří",
  "který",
  "proč",
  "co",
  "čeho",
  "čemu",
  "čím",
  "koho",
  "komu",
  "během",
  "do",
  "k",
  "ke",
  "kolem",
  "mezi",
  "na",
  "nad",
  "o",
  "od",
  "po",
  "pod",
  "podle",
  "pro",
  "proti",
  "před",
  "přes",
  "při",
  "s",
  "se",
  "u",
  "v",
  "ve",
  "vůči",
  "z",
  "za",
  "ze",
  "a",
  "aby",
  "ačkoli",
  "ale",
  "anebo",
  "či",
  "i",
  "jestliže",
  "když",
  "nebo",
  "neboť",
  "pokud",
  "protože",
  "takže",
  "že",
  "být",
  "bude",
  "budou",
  "budu",
  "byl",
  "byla",
  "byli",
  "bylo",
  "byly",
  "je",
  "jsem",
  "jsou",
  "jste",
  "mohl",
  "může",
  "musel",
  "musí",
  "ho",
  "jeho",
  "jej",
  "jejich",
  "ji",
  "jim",
  "jí",
  "mu",
  "si",
  "své",
  "svého",
  "svůj",
  "ta",
  "tato",
  "ten",
  "tento",
  "této",
  "ti",
  "tím",
  "to",
  "tom",
  "tomu",
  "toto",
  "ty",
  "tyto",
  "již",
  "ještě",
  "jen",
  "pouze",
  "tak",
  "také",
  "tedy",
] as const;

/** Slovak. Shares most of its shape with Czech, and shares the words too. */
const SLOVAK_FUNCTION_WORDS = [
  "ako",
  "aká",
  "aké",
  "aký",
  "kde",
  "kedy",
  "koľko",
  "kto",
  "ktorá",
  "ktoré",
  "ktorí",
  "ktorý",
  "prečo",
  "čo",
  "koho",
  "komu",
  "cez",
  "do",
  "k",
  "ku",
  "medzi",
  "na",
  "nad",
  "o",
  "od",
  "okolo",
  "po",
  "počas",
  "pod",
  "podľa",
  "pre",
  "pred",
  "pri",
  "proti",
  "s",
  "so",
  "u",
  "v",
  "vo",
  "voči",
  "z",
  "za",
  "zo",
  "a",
  "aby",
  "ak",
  "ale",
  "alebo",
  "či",
  "hoci",
  "i",
  "keď",
  "lebo",
  "pretože",
  "takže",
  "že",
  "byť",
  "bol",
  "bola",
  "boli",
  "bolo",
  "bude",
  "budú",
  "je",
  "mohol",
  "musel",
  "musí",
  "môže",
  "som",
  "ste",
  "sú",
  "ho",
  "ich",
  "im",
  "jeho",
  "jej",
  "mu",
  "sa",
  "si",
  "svoj",
  "tejto",
  "ten",
  "tento",
  "tí",
  "to",
  "tom",
  "toto",
  "tá",
  "táto",
  "tým",
  "ty",
  "už",
  "ešte",
  "iba",
  "len",
  "tak",
  "teda",
  "tiež",
  "všetko",
] as const;

/** Polish. */
const POLISH_FUNCTION_WORDS = [
  "czy",
  "dlaczego",
  "gdzie",
  "ile",
  "jak",
  "jaka",
  "jaki",
  "jakie",
  "kiedy",
  "kto",
  "co",
  "która",
  "które",
  "który",
  "dla",
  "do",
  "ku",
  "między",
  "na",
  "nad",
  "o",
  "od",
  "około",
  "po",
  "pod",
  "podczas",
  "przed",
  "przez",
  "przy",
  "u",
  "w",
  "we",
  "według",
  "wobec",
  "z",
  "za",
  "ze",
  "a",
  "aby",
  "albo",
  "ale",
  "chociaż",
  "gdy",
  "i",
  "jeśli",
  "jeżeli",
  "lub",
  "oraz",
  "ponieważ",
  "więc",
  "że",
  "być",
  "będą",
  "będzie",
  "byli",
  "była",
  "było",
  "były",
  "był",
  "jest",
  "mogą",
  "może",
  "mógł",
  "musi",
  "musiał",
  "są",
  "go",
  "ich",
  "im",
  "jego",
  "jej",
  "mu",
  "się",
  "swój",
  "ta",
  "te",
  "tego",
  "tej",
  "ten",
  "to",
  "tym",
  "już",
  "jeszcze",
  "tak",
  "także",
  "tylko",
] as const;

/** German. Articles carry case here, so every declined form is listed. */
const GERMAN_FUNCTION_WORDS = [
  "das",
  "dem",
  "den",
  "der",
  "des",
  "die",
  "ein",
  "eine",
  "einem",
  "einen",
  "einer",
  "eines",
  "am",
  "an",
  "auf",
  "aus",
  "bei",
  "beim",
  "bis",
  "durch",
  "für",
  "gegen",
  "gemäß",
  "hinter",
  "im",
  "in",
  "laut",
  "mit",
  "nach",
  "neben",
  "seit",
  "trotz",
  "um",
  "unter",
  "vom",
  "von",
  "vor",
  "während",
  "wegen",
  "zu",
  "zum",
  "zur",
  "zwischen",
  "über",
  "aber",
  "als",
  "damit",
  "dass",
  "denn",
  "doch",
  "ob",
  "oder",
  "sondern",
  "sowie",
  "und",
  "weil",
  "wenn",
  "wie",
  "darf",
  "dürfen",
  "haben",
  "hat",
  "hatte",
  "hatten",
  "ist",
  "kann",
  "können",
  "muss",
  "müssen",
  "sein",
  "sind",
  "soll",
  "sollen",
  "war",
  "waren",
  "werden",
  "wird",
  "worden",
  "wurde",
  "wurden",
  "warum",
  "was",
  "welche",
  "welcher",
  "welches",
  "wer",
  "wo",
  "wann",
  "auch",
  "da",
  "dann",
  "dies",
  "diese",
  "dieser",
  "dieses",
  "er",
  "es",
  "hier",
  "ich",
  "ihr",
  "man",
  "noch",
  "nur",
  "schon",
  "sich",
  "sie",
  "so",
  "wir",
] as const;

/**
 * Hungarian. Interrogatives first, then the articles, the postpositions that
 * do the work prepositions do elsewhere, the conjunctions, the copula and
 * existential forms of `van` and `lesz` with the modals, then the
 * demonstratives, relatives and pronouns.
 *
 * The negations (`nem`, `ne`, `sem`) and the privative postposition `nélkül`
 * are absent for the reason stated above: they invert what a query asks
 * rather than loosen it.
 */
const HUNGARIAN_FUNCTION_WORDS = [
  "hány",
  "hogyan",
  "hol",
  "ki",
  "kik",
  "kinek",
  "kit",
  "melyik",
  "mennyi",
  "mi",
  "miért",
  "mikor",
  "milyen",
  "mit",
  "a",
  "az",
  "egy",
  "alatt",
  "által",
  "ellen",
  "előtt",
  "felett",
  "fölött",
  "helyett",
  "iránt",
  "körül",
  "között",
  "mellett",
  "miatt",
  "óta",
  "részére",
  "számára",
  "szerint",
  "után",
  "amennyiben",
  "azonban",
  "de",
  "és",
  "ha",
  "hanem",
  "hogy",
  "illetve",
  "illetőleg",
  "mert",
  "mint",
  "mivel",
  "továbbá",
  "ugyanis",
  "vagy",
  "valamint",
  "kell",
  "kellett",
  "legyen",
  "lehet",
  "lehetett",
  "lenne",
  "lesz",
  "lesznek",
  "lett",
  "szabad",
  "tud",
  "van",
  "vannak",
  "volna",
  "volt",
  "voltak",
  "abban",
  "annak",
  "arra",
  "azok",
  "azon",
  "azt",
  "ebben",
  "egyik",
  "ennek",
  "erre",
  "ez",
  "ezek",
  "ezen",
  "ezt",
  "ahol",
  "aki",
  "akik",
  "ami",
  "amely",
  "amelyek",
  "amelyet",
  "amelynek",
  "amit",
  "én",
  "nekem",
  "neki",
  "nekik",
  "ő",
  "ők",
  "őket",
  "őt",
  "te",
  "ti",
  "akkor",
  "csak",
  "így",
  "is",
  "itt",
  "majd",
  "már",
  "még",
  "ott",
  "pedig",
  "tehát",
  "úgy",
] as const;

/** English: a jurisdiction language, and one the EU index is asked in. */
const ENGLISH_FUNCTION_WORDS = [
  "a",
  "an",
  "the",
  "about",
  "after",
  "against",
  "at",
  "before",
  "between",
  "by",
  "during",
  "for",
  "from",
  "in",
  "into",
  "of",
  "on",
  "over",
  "per",
  "through",
  "to",
  "under",
  "upon",
  "with",
  "within",
  "although",
  "and",
  "as",
  "because",
  "but",
  "if",
  "or",
  "so",
  "than",
  "that",
  "when",
  "whether",
  "while",
  "am",
  "are",
  "be",
  "been",
  "being",
  "can",
  "could",
  "did",
  "do",
  "does",
  "had",
  "has",
  "have",
  "is",
  "may",
  "might",
  "must",
  "shall",
  "should",
  "was",
  "were",
  "will",
  "would",
  "how",
  "many",
  "much",
  "what",
  "where",
  "which",
  "who",
  "whom",
  "whose",
  "why",
  "all",
  "also",
  "any",
  "both",
  "he",
  "it",
  "its",
  "more",
  "most",
  "only",
  "she",
  "some",
  "such",
  "their",
  "them",
  "there",
  "these",
  "they",
  "this",
  "those",
] as const;

/**
 * Total over the languages that have one, so a new corpus language has to
 * author a list rather than silently inherit no exclusions.
 */
export const FUNCTION_WORDS = {
  cs: new Set<string>(CZECH_FUNCTION_WORDS),
  de: new Set<string>(GERMAN_FUNCTION_WORDS),
  en: new Set<string>(ENGLISH_FUNCTION_WORDS),
  hu: new Set<string>(HUNGARIAN_FUNCTION_WORDS),
  pl: new Set<string>(POLISH_FUNCTION_WORDS),
  sk: new Set<string>(SLOVAK_FUNCTION_WORDS),
} as const satisfies Record<FunctionWordLanguage, ReadonlySet<string>>;

/**
 * The comparison key a token is looked up by: NFC, lower-cased, accents
 * kept. The one place the rule lives, so the lists and the lookup cannot
 * disagree about what "the same word" means.
 */
export const functionWordKey = (token: string): string =>
  token.normalize("NFC").toLowerCase();

/**
 * Whether a list is authored for this language. Asked of the map itself
 * rather than of {@link FUNCTION_WORD_LANGUAGES}, so the narrowing is the
 * same fact as the lookup below succeeding.
 */
const isFunctionWordLanguage = (
  language: MorphologyLanguage,
): language is FunctionWordLanguage => Object.hasOwn(FUNCTION_WORDS, language);

/**
 * The function words to drop from a query in this language, or null where
 * nothing is dropped: a language the corpus does not serve, or a request
 * whose scope names no language at all (an unscoped search spans every
 * jurisdiction of a generation, so no one language describes its text).
 */
export const functionWordsFor = (
  language: MorphologyLanguage | null,
): ReadonlySet<string> | null => {
  if (language === null || !isFunctionWordLanguage(language)) {
    return null;
  }
  return FUNCTION_WORDS[language];
};
