/**
 * Inspector chat tab — full-fat chat surface backed by the same
 * `/chat` endpoint, persistence layer, and `useChat` runtime as the
 * legacy right-panel chat. We layer that runtime under our own
 * shell (ribbon + matter picker + glass-pill bar) so the surface
 * looks like it belongs to the inspector while every "real chat"
 * concern (streaming, mentions, tool approvals, drafts, history)
 * is handled by the existing primitives.
 *
 * Responsibilities here:
 *   - resolve a `Chat` instance from `chatThreadOptions`
 *   - drive `useChatSession` to expose messages + send/stop + tool
 *     approval handlers
 *   - render `ChatThreadMessages` for the transcript
 *   - render the shared `PromptBar` for the composer
 *
 * Phase D-full (multi-matter context) is not honoured server-side
 * yet — `tab.contextMatterIds` is captured intent only.
 */

import { useEffect, useEffectEvent, useMemo, useState } from "react";
import type { MouseEvent } from "react";

import { Button } from "@stll/ui/components/button";
import { toastManager } from "@stll/ui/components/toast";
import { useSuspenseQuery } from "@tanstack/react-query";
import { ExternalLinkIcon, PrinterIcon, SparklesIcon } from "lucide-react";
import { useTranslations } from "use-intl";
import { useShallow } from "zustand/react/shallow";

import {
  Conversation,
  ConversationContent,
  ConversationScrollButton,
} from "@/components/ai-elements/conversation";
import { PromptBar } from "@/components/ai-suggestions/host";
import { useChatEditor } from "@/components/chat-editor-provider";
import { ChatThreadMessages } from "@/components/chat/chat-thread-messages";
import Tooltip from "@/components/tooltip";
import type { ChatThreadRef } from "@/lib/chat-thread-ref";
import { useDevStore } from "@/lib/dev-store";
import { toSafeId } from "@/lib/safe-id";
import { useChatSession } from "@/routes/_protected.chat/-hooks/use-chat-session";
import { useChatUserContext } from "@/routes/_protected.chat/-hooks/use-chat-user-context";
import { chatThreadOptions } from "@/routes/_protected.chat/-queries";
import { ChatMatterPicker } from "@/routes/_protected.workspaces/$workspaceId/-components/inspector/chat-matter-picker";
import type { ChatTab } from "@/routes/_protected.workspaces/$workspaceId/-components/inspector/inspector-store";
import { useInspectorStore } from "@/routes/_protected.workspaces/$workspaceId/-components/inspector/inspector-store";
import { InspectorTabHeader } from "@/routes/_protected.workspaces/$workspaceId/-components/inspector/inspector-tab-header";

type ChatTabPanelProps = {
  tab: ChatTab;
  workspaceId: string;
  onClose: () => void;
  onLabelContextMenu: (event: MouseEvent<HTMLElement>) => void;
};

export const ChatTabPanel = ({
  tab,
  workspaceId,
  onClose,
  onLabelContextMenu,
}: ChatTabPanelProps) => {
  const t = useTranslations();
  const userContext = useChatUserContext();
  // useEffectEvent so the chat transport's `getUserContext` is a
  // stable reference across renders (matches legacy chat's pattern
  // — keeps Chat<>'s prepareSendMessagesRequest from re-binding).
  const getUserContext = useEffectEvent(() => userContext);
  // Same pattern for the decision context — it's per-tab metadata
  // that changes only when openChat() is re-invoked, so capturing
  // the current value via useEffectEvent keeps the transport's
  // request shape stable across renders.
  const tabDecisionId = tab.activeDecisionId;
  const getActiveDecision = useEffectEvent(() =>
    tabDecisionId
      ? { decisionId: toSafeId<"caseLawDecision">(tabDecisionId) }
      : undefined,
  );
  const showToolCalls = useDevStore((s) => s.showToolCalls);

  const { setChatContext, updateLabel } = useInspectorStore(
    useShallow((s) => ({
      setChatContext: s.setChatContext,
      updateLabel: s.updateLabel,
    })),
  );

  const threadRef = useMemo<ChatThreadRef>(
    () => ({
      scope: "workspace",
      // tab.id is already a UUID generated by openChat() —
      // backend validates as SafeId<"chatThread"> so we pass it
      // bare (no prefix).
      threadId: tab.id,
      workspaceId,
    }),
    [tab.id, workspaceId],
  );

  // Tab id is generated client-side at openChat() time; the thread
  // doesn't exist server-side until the first message lands. Allow
  // the missing-thread response so the GET doesn't 404 on a fresh
  // tab; the thread will be created idempotently on the first send.
  const { data: chat } = useSuspenseQuery(
    chatThreadOptions({
      key: threadRef,
      context: {
        allowMissingThread: true,
        getUserContext,
        getActiveDecision,
      },
    }),
  );

  const {
    messages,
    sendMessage,
    stop,
    isGenerating,
    autoApprovedTools,
    handleApprove,
    handleDeny,
    handleAlwaysAllow,
    streamdownComponents,
    approvalPendingMessageId,
  } = useChatSession({ chat, threadRef, workspaceId });

  // TipTap composer for this thread — `@`-mention chips, drafts,
  // attachments come from the same provider as the right-panel
  // chat. Thread ref is shared with `chatThreadOptions` above so
  // drafts persist across tab close/open.
  const editorController = useChatEditor({ threadRef });

  // Inline rename — same UX as file tabs.
  const [editingLabel, setEditingLabel] = useState(false);
  const [labelDraft, setLabelDraft] = useState(tab.label);
  const startRename = () => {
    setLabelDraft(tab.label);
    setEditingLabel(true);
  };
  const commitRename = () => {
    const trimmed = labelDraft.trim();
    setEditingLabel(false);
    if (trimmed && trimmed !== tab.label) {
      updateLabel(tab.id, trimmed);
    }
  };

  // The shared tab context menu (right-click on rail icon or
  // ribbon label) dispatches `requestRename(tabId)` to the store.
  // PDF tabs read that flag in InspectorPanel; chat tabs own their
  // rename state locally so they consume the flag here.
  const pendingRenameTabId = useInspectorStore((s) => s.pendingRenameTabId);
  const clearRenameRequest = useInspectorStore((s) => s.clearRenameRequest);
  useEffect(() => {
    if (pendingRenameTabId === tab.id) {
      setLabelDraft(tab.label);
      setEditingLabel(true);
      clearRenameRequest();
    }
  }, [pendingRenameTabId, tab.id, tab.label, clearRenameRequest]);

  const chatActions = (
    <>
      <Tooltip
        content={t("common.print")}
        render={
          <Button
            onClick={() => {
              toastManager.add({
                title: t("chat.actionPrint.toastTitle"),
                description: t("chat.actionPrint.toastDescription"),
                type: "info",
              });
            }}
            size="icon-xs"
            variant="ghost"
          >
            <PrinterIcon className="size-3.5" />
          </Button>
        }
      />
      <Tooltip
        content={t("workspaces.pdf.openFullView")}
        render={
          <Button
            onClick={() => {
              toastManager.add({
                title: t("chat.actionExpand.toastTitle"),
                description: t("chat.actionExpand.toastDescription"),
                type: "info",
              });
            }}
            size="icon-xs"
            variant="ghost"
          >
            <ExternalLinkIcon className="size-3.5" />
          </Button>
        }
      />
    </>
  );

  return (
    <div className="bg-muted/40 relative flex min-w-0 flex-1 flex-col">
      <InspectorTabHeader
        actions={chatActions}
        label={tab.label}
        matter={
          <ChatMatterPicker
            matterIds={tab.contextMatterIds}
            onChange={(next) => setChatContext(tab.id, next)}
          />
        }
        onClose={onClose}
        onLabelContextMenu={onLabelContextMenu}
        onStartRename={startRename}
        rename={{
          active: editingLabel,
          value: labelDraft,
          onChange: setLabelDraft,
          onCommit: commitRename,
          onCancel: () => setEditingLabel(false),
        }}
      />

      {/* Subtle dot-grid backdrop, same as before — gives the
          translucent bar something to layer on. */}
      <div
        aria-hidden="true"
        className="pointer-events-none absolute inset-0 opacity-25"
        style={{
          backgroundImage:
            "radial-gradient(circle, var(--color-border) 1px, transparent 1px)",
          backgroundSize: "18px 18px",
        }}
      />

      <div className="relative flex min-h-0 flex-1 flex-col">
        <Conversation className="min-h-0 flex-1">
          <ConversationContent className="gap-4 p-4">
            {messages.length === 0 && !isGenerating ? (
              <ChatEmptyState />
            ) : (
              <ChatThreadMessages
                approvalPendingMessageId={approvalPendingMessageId}
                autoApprovedTools={autoApprovedTools}
                handleAlwaysAllow={handleAlwaysAllow}
                handleApprove={handleApprove}
                handleDeny={handleDeny}
                isGenerating={isGenerating}
                messages={messages}
                onAskUserSubmit={async (text) => {
                  await sendMessage({ text });
                }}
                showThinkingIndicator
                showToolCalls={showToolCalls}
                streamdownComponents={streamdownComponents}
                workspaceId={workspaceId}
              />
            )}
          </ConversationContent>
          <ConversationScrollButton />
        </Conversation>

        <PromptBar
          editorController={editorController}
          layout="standalone"
          onStop={() => {
            void stop();
          }}
          onSubmit={({ prompt }) => {
            // PromptBar emits the raw editor HTML; the legacy
            // backend already parses `<entity-mention>` tags out
            // of the `text` field, so we forward unchanged.
            void sendMessage({ text: prompt });
          }}
          onTogglePanel={() => {
            // Standalone has no thread toggle; never called.
          }}
          panelOpen={false}
          pendingCount={0}
          showThreadToggle={false}
          status={isGenerating ? "generating" : "idle"}
        />
      </div>
    </div>
  );
};

const ChatEmptyState = () => {
  const t = useTranslations();
  return (
    <div className="text-muted-foreground m-auto flex max-w-[28ch] flex-col items-center gap-2 py-8 text-center">
      <SparklesIcon className="size-5 opacity-70" />
      <p className="text-foreground text-sm font-medium">
        {t("chat.emptyState.title")}
      </p>
      <p className="text-xs leading-snug text-pretty">
        {t("chat.emptyState.description")}
      </p>
    </div>
  );
};
