//! `regex_meta` (full) and `regex_patterns` (partial prefix): ports the static
//! regex assembly from `detectors/regex.ts` and `build-unified-search.ts`.
//!
//! # What is assembled
//!
//! `buildNativeStaticConfig` builds `regex_patterns` from `allRegex` (static
//! defs + dynamically generated currency/date/signing patterns) minus the
//! `omitRegexRanges` (currency, date, and the `getSigningClausePatterns`
//! output), then appends the `getNativeSigningClausePatterns` output, then the
//! legal-form patterns (permanently empty after the v2 rewrite) and the trigger
//! patterns. The parallel `regex_meta` covers the surviving static defs plus one
//! `SIGNING_CLAUSE_META` per native signing pattern (legal-form and trigger
//! patterns get NO meta).
//!
//! So the C1 boundary is:
//! - `regex_meta` = static-defs-filtered-by-label ++ signing (FULL)
//! - `regex_patterns` = static-defs-filtered-by-label ++ signing ++
//!   \[legal-form (empty) ++ trigger (slice C2)\] (PARTIAL)
//!
//! `regex_meta` is fully reproduced here. `regex_patterns` reproduces the prefix
//! (everything up to the trigger tail); the trigger patterns come from
//! `trigger_data`, a later slice, so `regex_patterns` stays in `FIELDS_PENDING`
//! and the parity harness compares only the prefix (see the `assemble_parity`
//! test). The prefix length equals `regex_meta.len()`.
//!
//! # Static regex table
//!
//! The static regex source strings are derived at TypeScript module load from
//! the `@stll/stdnum` validators (`toRegex(validator).source`), so they cannot
//! be hand-transcribed. They are captured verbatim into the embedded
//! `native-regex-table.json` artifact (regenerated by
//! `packages/anonymize/scripts/capture-assemble-fixtures.mjs`). The label
//! filtering, validator gating, and signing-clause pattern generation below are
//! ported logic; the fixtures cross-check the embedded table byte-for-byte.

use serde::Deserialize;
use stella_anonymize_core::assemble::{
  AssembleError, OrderedMap, parse_data_file,
};

use super::AssembleContext;
use super::language::signing_clause_language_matches;
use crate::{
  BindingPreparedArtifactPolicy, BindingRegexMatchMeta, BindingSearchPattern,
};

/// `CONTEXT_REGEX_PREFILTER_WINDOW_BYTES` from `detectors/regex.ts`.
const CONTEXT_REGEX_PREFILTER_WINDOW_BYTES: u32 = 160;

/// Validator ids the native static config supports (`NATIVE_REGEX_VALIDATOR_IDS`
/// in `detectors/regex.ts`).
const NATIVE_REGEX_VALIDATOR_IDS: &[&str] = &[
  "au.abn",
  "au.acn",
  "at.businessid",
  "at.tin",
  "at.uid",
  "be.nn",
  "be.vat",
  "bg.vat",
  "br.cnpj",
  "br.cpf",
  "ch.uid",
  "cn.ric",
  "crypto.wallet",
  "cy.vat",
  "cz.dic",
  "cz.rc",
  "de.idnr",
  "de.stnr",
  "de.svnr",
  "de.vat",
  "dk.cpr",
  "dk.vat",
  "ee.ik",
  "ee.vat",
  "es.cif",
  "es.dni",
  "es.nie",
  "es.nss",
  "es.vat",
  "fi.hetu",
  "fi.vat",
  "fi.ytunnus",
  "fr.nir",
  "fr.siren",
  "fr.siret",
  "fr.tva",
  "gb.nhs",
  "gb.nino",
  "gb.vat",
  "gr.vat",
  "hr.vat",
  "hu.vat",
  "ie.pps",
  "ie.vat",
  "it.codiceFiscale",
  "it.iva",
  "lt.asmens",
  "lt.vat",
  "lu.vat",
  "lv.vat",
  "mt.vat",
  "nl.vat",
  "no.mva",
  "no.orgnr",
  "pl.nip",
  "pl.pesel",
  "pt.cc",
  "pt.vat",
  "phone.international",
  "phone.nanp",
  "ro.cnp",
  "ro.vat",
  "se.personnummer",
  "si.vat",
  "sk.dic",
  "us.ein",
  "us.rtn",
];

/// Embedded static regex table, generated from the TypeScript source of truth.
const NATIVE_REGEX_TABLE_JSON: &str = include_str!("native-regex-table.json");

/// One row of the embedded static regex table: the already-native pattern plus
/// the raw meta fields needed to reproduce `toNativeRegexMeta` (including its
/// validator gating).
#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct RawRegexRow {
  pattern: BindingSearchPattern,
  label: String,
  score: f64,
  #[serde(default)]
  validator_id: Option<String>,
  #[serde(default)]
  validator_input_kind: Option<String>,
  #[serde(default)]
  min_byte_length: Option<u32>,
}

/// Result of the static + signing regex assembly.
pub(super) struct RegexAssembly {
  /// `regex_patterns` prefix: static-filtered patterns then signing patterns.
  pub patterns: Vec<BindingSearchPattern>,
  /// `regex_meta`: fully reproduced (parallel to `patterns`).
  pub meta: Vec<BindingRegexMatchMeta>,
}

/// Mirrors `toNativeRegexMeta` for a static-table row, including the validator
/// gating that throws in the TypeScript source.
///
/// Static rows never carry a `sourceDetail`, so it is always absent here.
fn to_native_regex_meta(
  row: &RawRegexRow,
) -> Result<BindingRegexMatchMeta, AssembleError> {
  let mut meta = BindingRegexMatchMeta {
    label: row.label.clone(),
    score: row.score,
    ..BindingRegexMatchMeta::default()
  };
  if let Some(validator_id) = row.validator_id.as_deref() {
    // Mirrors `nativeSupportsRegexMeta`: id must be known and the input kind
    // (when present) must be one the native validator can rebuild.
    let input_supported = matches!(
      row.validator_input_kind.as_deref(),
      None | Some("digits-only" | "crypto-wallet-candidate")
    );
    if !NATIVE_REGEX_VALIDATOR_IDS.contains(&validator_id) || !input_supported {
      return Err(AssembleError::UnsupportedRegexValidator {
        validator: validator_id.to_string(),
      });
    }
    meta.requires_validation = Some(true);
    meta.validator_id = Some(validator_id.to_string());
    if let Some(kind) = row.validator_input_kind.as_ref() {
      meta.validator_input = Some(kind.clone());
    }
  }
  if let Some(min_byte_length) = row.min_byte_length {
    meta.min_byte_length = Some(min_byte_length);
  }
  Ok(meta)
}

/// `SIGNING_CLAUSE_META`: `{ label: "address", score: 0.9 }`.
fn signing_clause_meta() -> BindingRegexMatchMeta {
  BindingRegexMatchMeta {
    label: "address".to_string(),
    score: 0.9,
    ..BindingRegexMatchMeta::default()
  }
}

#[derive(Deserialize)]
struct SigningClauses {
  #[serde(default)]
  patterns: Vec<SigningClauseEntry>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct SigningClauseEntry {
  #[serde(default)]
  lang: String,
  #[serde(default)]
  prefix: String,
  #[serde(default)]
  suffix: String,
  #[serde(default)]
  prepositions: Vec<String>,
  #[serde(default)]
  prefilter_phrases: Option<Vec<String>>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct EmailObfuscationTokens {
  #[serde(default)]
  at_tokens: Vec<String>,
  #[serde(default)]
  dot_tokens: Vec<String>,
}

fn regex_literal(value: &str) -> String {
  let mut escaped = String::with_capacity(value.len());
  for character in value.chars() {
    if matches!(
      character,
      '\\'
        | '.'
        | '^'
        | '$'
        | '|'
        | '?'
        | '*'
        | '+'
        | '('
        | ')'
        | '['
        | ']'
        | '{'
        | '}'
    ) {
      escaped.push('\\');
    }
    escaped.push(character);
  }
  escaped
}

fn token_alternation(tokens: &[String]) -> Option<String> {
  let escaped: Vec<String> = non_empty_tokens(tokens)
    .iter()
    .map(|token| regex_literal(token))
    .collect();
  (!escaped.is_empty()).then(|| escaped.join("|"))
}

fn non_empty_tokens(tokens: &[String]) -> Vec<String> {
  tokens
    .iter()
    .filter(|token| !token.is_empty())
    .cloned()
    .collect()
}

/// Builds conservative written-email patterns from language-scoped data.
///
/// The `at`/`dot` structure is adapted from Scrubadub's email recognizer at
/// pinned commit 53772cbef417da290d25c95373031f786ab3b5c6. Tokens remain in
/// `email-obfuscation-tokens.json`; this code only supplies the grammar.
fn build_obfuscated_email_patterns(
  languages: Option<&[String]>,
) -> Result<Vec<BindingSearchPattern>, AssembleError> {
  let vocabularies: OrderedMap<EmailObfuscationTokens> =
    parse_data_file("email-obfuscation-tokens.json")?;
  let mut patterns = Vec::new();
  for (language, vocabulary) in &vocabularies {
    if !super::language::language_config_matches(language, languages) {
      continue;
    }
    let Some(at_tokens) = token_alternation(&vocabulary.at_tokens) else {
      continue;
    };
    let Some(dot_tokens) = token_alternation(&vocabulary.dot_tokens) else {
      continue;
    };
    let pattern = format!(
      concat!(
        r"(?i)",
        r"(?<![\p{{L}}\p{{N}}\p{{M}}_!#$%&'*+/=?^`{{|}}~.\-])",
        r"[\p{{L}}\p{{N}}_!#$%&'*+/=?^`{{|}}~-]",
        r"[\p{{L}}\p{{N}}\p{{M}}_!#$%&'*+/=?^`{{|}}~-]*",
        r"(?:\.[\p{{L}}\p{{N}}_!#$%&'*+/=?^`{{|}}~-]",
        r"[\p{{L}}\p{{N}}\p{{M}}_!#$%&'*+/=?^`{{|}}~-]*)*",
        r"[^\S\n]+(?:{})[^\S\n]+",
        r"[\p{{L}}\p{{N}}](?:[\p{{L}}\p{{N}}\p{{M}}-]{{0,61}}[\p{{L}}\p{{N}}\p{{M}}])?",
        r"(?:[^\S\n]+(?:{})[^\S\n]+",
        r"[\p{{L}}\p{{N}}](?:[\p{{L}}\p{{N}}\p{{M}}-]{{0,61}}[\p{{L}}\p{{N}}\p{{M}}])?)+\b"
      ),
      at_tokens, dot_tokens
    );
    patterns.push(BindingSearchPattern {
      kind: "regex".to_string(),
      pattern,
      distance: None,
      case_insensitive: None,
      whole_words: None,
      lazy: Some(true),
      // Every accepted address contains one of the language-owned dot tokens.
      // A literal necessary-condition gate avoids compiling and scanning a
      // second regex while the main regex remains the exact authority.
      prefilter_any: Some(non_empty_tokens(&vocabulary.dot_tokens)),
      prefilter_case_insensitive: Some(true),
      prefilter_regex: None,
      prefilter_window_bytes: None,
      prepared_artifact_policy: None,
    });
  }
  Ok(patterns)
}

fn obfuscated_email_meta() -> BindingRegexMatchMeta {
  BindingRegexMatchMeta {
    label: "email address".to_string(),
    score: 0.85,
    ..BindingRegexMatchMeta::default()
  }
}

/// Mirrors `buildSigningClausePattern`.
fn build_signing_clause_pattern(entry: &SigningClauseEntry) -> String {
  let place = if entry.prepositions.is_empty() {
    r"(\p{Lu}\p{Ll}+(?:[- ]\p{Lu}\p{Ll}+)*)".to_string()
  } else {
    let prep_alt = entry.prepositions.join("|");
    let mut place = String::from(r"(\p{Lu}\p{Ll}+(?:\s+(?:");
    place.push_str(&prep_alt);
    place.push_str(r")\s+\p{Lu}\p{Ll}+)*(?:\s+\p{Lu}\p{Ll}+)*)");
    place
  };
  let mut pattern = String::from(r"(?:^|\n|[^\S\n])");
  pattern.push_str(&entry.prefix);
  pattern.push_str(&place);
  if !entry.suffix.is_empty() {
    pattern.push_str("(?:");
    pattern.push_str(&entry.suffix);
    pattern.push(')');
  }
  pattern
}

/// Mirrors `getNativeSigningClausePatterns` + `toNativeRegexPattern`: a
/// language-scoped, lazy regex with the entry's prefilter phrases.
fn build_native_signing_patterns(
  languages: Option<&[String]>,
) -> Result<Vec<BindingSearchPattern>, AssembleError> {
  let data: SigningClauses = parse_data_file("signing-clauses.json")?;
  let mut patterns = Vec::new();
  for entry in &data.patterns {
    if !signing_clause_language_matches(&entry.lang, languages) {
      continue;
    }
    patterns.push(BindingSearchPattern {
      kind: "regex".to_string(),
      pattern: build_signing_clause_pattern(entry),
      distance: None,
      case_insensitive: None,
      whole_words: None,
      lazy: Some(true),
      // `entry.prefilterPhrases ?? []` is always assigned, so the field is
      // present (possibly empty) rather than absent.
      prefilter_any: Some(entry.prefilter_phrases.clone().unwrap_or_default()),
      prefilter_case_insensitive: Some(false),
      prefilter_regex: None,
      prefilter_window_bytes: Some(CONTEXT_REGEX_PREFILTER_WINDOW_BYTES),
      prepared_artifact_policy: Some(BindingPreparedArtifactPolicy::Omit),
    });
  }
  Ok(patterns)
}

/// # Errors
///
/// Returns [`AssembleError`] when the embedded regex table or
/// `signing-clauses.json` fails to parse, or when a static regex references a
/// validator the native config cannot support.
pub(super) fn build_regex(
  ctx: &AssembleContext<'_>,
) -> Result<RegexAssembly, AssembleError> {
  let mut patterns = Vec::new();
  let mut meta = Vec::new();

  if ctx.enable_regex() {
    let table: Vec<RawRegexRow> = serde_json::from_str(NATIVE_REGEX_TABLE_JSON)
      .map_err(|error| AssembleError::DataParse {
        name: "native-regex-table.json".to_string(),
        message: error.to_string(),
      })?;
    for row in &table {
      if !ctx.label_allowed(&row.label) {
        continue;
      }
      patterns.push(row.pattern.clone());
      meta.push(to_native_regex_meta(row)?);
      if row.label == "email address" {
        for pattern in
          build_obfuscated_email_patterns(ctx.content_languages.as_deref())?
        {
          patterns.push(pattern);
          meta.push(obfuscated_email_meta());
        }
      }
    }

    // Native signing-clause patterns: `enableRegex && labelIsAllowed("address")`,
    // scoped to the content languages.
    if ctx.label_allowed("address") {
      let signing =
        build_native_signing_patterns(ctx.content_languages.as_deref())?;
      for pattern in signing {
        patterns.push(pattern);
        meta.push(signing_clause_meta());
      }
    }
  }

  Ok(RegexAssembly { patterns, meta })
}
