import { EyeOffIcon, GlobeIcon, type LucideIcon } from "lucide-react";

import { McpIcon } from "@/components/mcp-icon";
import { sanitizeHref } from "@/lib/sanitize-href";
import { getCatalogueIconImageSrc } from "@/routes/_protected.knowledge/-components/catalogue/catalogue-entry-icon.logic";
import { DocxIcon } from "@/routes/_protected.workspaces/$workspaceId/-components/document-icon";

/**
 * Single source of truth for catalogue entry iconography. Resolution
 * order:
 *   1. Slug-specific built-in icons (the three pinned baselines get
 *      distinctive lucide marks).
 *   2. Bundled icon from the catalogue package (`icon.png` or
 *      `icon.svg` encoded as an inert image data URL). Bundled locally
 *      so rendering never makes a runtime network request.
 *   3. Entry's favicon when `iconUrl` is set (legacy / remote fallback).
 *   4. Stella hexagon fallback.
 *
 * Used by both the catalogue rows (settings + onboarding step) and the
 * onboarding stack preview so left + right always agree.
 */
type CatalogueEntryIconProps = {
  slug?: string;
  /** Bundled icon: image data URL generated by `@stll/catalogue`. */
  icon?: string | null;
  iconUrl?: string | null;
  /** Pixel size for both the image and the SVG fallback. */
  size?: number;
  className?: string;
};

const SLUG_LUCIDE_OVERRIDES: Readonly<Record<string, LucideIcon>> = {
  "web-search": GlobeIcon,
  anonymize: EyeOffIcon,
};

export const CatalogueEntryIcon = ({
  slug,
  icon,
  iconUrl,
  size = 24,
  className,
}: CatalogueEntryIconProps) => {
  if (slug === "create-docx") {
    return <DocxIcon className={className} height={size} width={size} />;
  }

  if (slug && slug in SLUG_LUCIDE_OVERRIDES) {
    const Icon = SLUG_LUCIDE_OVERRIDES[slug];
    if (Icon) {
      return (
        <Icon
          className={className ?? "text-foreground"}
          style={{ width: size, height: size }}
        />
      );
    }
  }

  const bundledIconSrc = getCatalogueIconImageSrc(icon);
  if (bundledIconSrc) {
    return (
      <img
        alt=""
        className={`${className ?? ""} rounded-sm object-contain ring-1 ring-black/5 dark:ring-white/10`.trim()}
        height={size}
        src={bundledIconSrc}
        style={{ width: size, height: size }}
        width={size}
      />
    );
  }

  const safeIconHref = iconUrl ? sanitizeHref(iconUrl) : undefined;

  if (safeIconHref) {
    return (
      <img
        alt=""
        className={`${className ?? ""} rounded-sm object-contain ring-1 ring-black/5 dark:ring-white/10`.trim()}
        height={size}
        src={safeIconHref}
        style={{ width: size, height: size }}
        width={size}
      />
    );
  }

  return (
    <McpIcon
      className={className ?? "text-muted-foreground"}
      style={{ width: size, height: size }}
    />
  );
};
