import { describe, expect, test } from "bun:test";

import { getCatalogueIconImageSrc } from "@/routes/_protected.knowledge/-components/catalogue/catalogue-entry-icon.logic";

describe("catalogue bundled icon source", () => {
  test("allows base64 image data URLs generated by the catalogue package", () => {
    expect(getCatalogueIconImageSrc("data:image/png;base64,aGVsbG8=")).toBe(
      "data:image/png;base64,aGVsbG8=",
    );
    expect(getCatalogueIconImageSrc("data:image/svg+xml;base64,PHN2Zy8+")).toBe(
      "data:image/svg+xml;base64,PHN2Zy8+",
    );
  });

  test("rejects raw SVG markup and executable data URLs", () => {
    expect(
      getCatalogueIconImageSrc('<svg onload="alert(1)"></svg>'),
    ).toBeUndefined();
    expect(
      getCatalogueIconImageSrc(
        "data:text/html;base64,PHNjcmlwdD5hbGVydCgxKTwvc2NyaXB0Pg==",
      ),
    ).toBeUndefined();
  });
});
