export const AUDIT_ACTION = {
  CREATE: "create",
  UPDATE: "update",
  DELETE: "delete",
  DOWNLOAD: "download",
  EXECUTE: "execute",
  ACCESS: "access",
  CANCEL: "cancel",
  REVIEW: "review",
} as const;

export type AuditAction = (typeof AUDIT_ACTION)[keyof typeof AUDIT_ACTION];

export const AUDIT_RESOURCE_TYPE = {
  SERVICE_OAUTH_CLIENT: "service_oauth_client",
  LEGAL_RESOLVE: "legal_resolve",
  AUDIT_LOG: "audit_log",
  AGENT_SKILL: "agent_skill",
  AGENT_SKILL_COMMENT: "agent_skill_comment",
  AGENT_SKILL_PROPOSAL: "agent_skill_proposal",
  AI_MEMORY: "ai_memory",
  ANNOUNCEMENT: "announcement",
  BILLING_CODE: "billing_code",
  CASE_LAW_MATTER_LINK: "case_law_matter_link",
  CASE_LAW_DECISION_ANNOTATION: "case_law_decision_annotation",
  CASE_LAW_RESEARCH_COLUMN: "case_law_research_column",
  CHAT_FILE: "chat_file",
  CHAT_MESSAGE: "chat_message",
  CHAT_THREAD: "chat_thread",
  CLAUSE: "clause",
  CLAUSE_CATEGORY: "clause_category",
  CLAUSE_TEMPLATE_LINK: "clause_template_link",
  CLAUSE_VARIANT: "clause_variant",
  CONTACT: "contact",
  CONTACT_DIRECTORY: "contact_directory",
  CORRESPONDENCE: "correspondence",
  DOCUMENT_TYPE: "document_type",
  USAGE_ALLOCATION: "usage_allocation",
  USAGE_ENTITLEMENT: "usage_entitlement",
  USAGE_EVENT: "usage_event",
  USAGE_PROVIDER_EVENT: "usage_provider_event",
  DESKTOP_EDIT_SESSION: "desktop_edit_session",
  BILINGUAL_TRANSLATION_RUN: "bilingual_translation_run",
  DOCUMENT_TRANSLATION_RUN: "document_translation_run",
  DOCUMENT_REVIEW_RUN: "document_review_run",
  ENTITY: "entity",
  ENTITY_VERSION: "entity_version",
  EXPENSE: "expense",
  FEEDBACK_REPORT: "feedback_report",
  FIELD: "field",
  FILE_COMPARISON: "file_comparison",
  FLOW_DEFINITION: "flow_definition",
  FLOW_RUN: "flow_run",
  FOLIO_COLLAB_ROOM: "folio_collab_room",
  SIGNAL: "signal",
  INVOICE: "invoice",
  PERSONAL_API_KEY: "personal_api_key",
  MACHINE_API_KEY: "machine_api_key",
  LEGAL_LIST: "legal_list",
  LEGAL_LIST_GENERATION: "legal_list_generation",
  LEGAL_LIST_ITEM: "legal_list_item",
  LEGAL_LIST_VERIFICATION: "legal_list_verification",
  MCP_GATEWAY_TOOL: "mcp_gateway_tool",
  ORGANIZATION_SETTINGS: "organization_settings",
  PDF_SIGNING_SESSION: "pdf_signing_session",
  PLAYBOOK: "playbook",
  PROPERTY: "property",
  RATE_ENTRY: "rate_entry",
  REPORT_EXPORT: "report_export",
  RATE_TABLE: "rate_table",
  SAVED_SEARCH: "saved_search",
  SELLER_PROFILE: "seller_profile",
  SAVED_TIME_NARRATIVE: "saved_time_narrative",
  VAT_RATE: "vat_rate",
  NUMBER_SERIES: "number_series",
  STATUTE_ANNOTATION: "statute_annotation",
  STYLE_SET: "style_set",
  TEMPLATE: "template",
  TEMPLATE_LOOKUP_FORMAT: "template_lookup_format",
  TIME_ENTRY: "time_entry",
  TIME_DAILY_TARGET: "time_daily_target",
  TIME_TIMER: "time_timer",
  USER_FILE: "user_file",
  VIEW: "view",
  VIEW_TEMPLATE: "view_template",
  WORKSPACE: "workspace",
  WORKSPACE_CONTACT: "workspace_contact",
  WORKSPACE_MEMBER: "workspace_member",
  WORK_OBLIGATION: "work_obligation",
} as const;

export type AuditResourceType =
  (typeof AUDIT_RESOURCE_TYPE)[keyof typeof AUDIT_RESOURCE_TYPE];
