declare const __brand: unique symbol;

export type SafeIdType =
  | "agentSkill"
  | "agentSkillResource"
  | "anonymizationAllowlistEntry"
  | "anonymizationBlacklistEntry"
  | "auditLog"
  | "billingCode"
  | "caseLawCitation"
  | "caseLawCourtWeight"
  | "caseLawDecision"
  | "caseLawIngestionEvent"
  | "caseLawIngestionFailure"
  | "caseLawMatterLink"
  | "caseLawPolarityRule"
  | "caseLawSource"
  | "chatMessage"
  | "chatThread"
  | "fileChatThread"
  | "clause"
  | "clauseCategory"
  | "clauseVariant"
  | "clauseVersion"
  | "contact"
  | "contactRelationship"
  | "usageAllocation"
  | "usagePolicy"
  | "usageEntitlement"
  | "usageEvent"
  | "desktopEditHandoff"
  | "desktopEditSession"
  | "document"
  | "documentCounter"
  | "entity"
  | "entityVersionAiSummary"
  | "entityVersion"
  | "expense"
  | "field"
  | "folioCollabSession"
  | "folioCollabSessionToken"
  | "folder"
  | "infoSoudTrackedCase"
  | "invoice"
  | "justification"
  | "matter"
  | "matterCounter"
  | "mcpConnector"
  | "mcpOAuthClient"
  | "mcpUserConnection"
  | "organization"
  | "organizationSettings"
  | "pendingUpload"
  | "property"
  | "promptShortcut"
  | "propertyDependency"
  | "rateEntry"
  | "rateTable"
  | "schedulerJobRun"
  | "taskAssignee"
  | "task"
  | "template"
  | "templateCategory"
  | "templateClause"
  | "templateFill"
  | "templateVersion"
  | "timeEntry"
  | "user"
  | "userFile"
  | "workspace"
  | "workspaceContact"
  | "workspaceMember"
  | "workspaceView"
  | "workspaceViewTemplate"
  | "entityLink";

export type SafeId<T extends SafeIdType> = string & {
  readonly [__brand]: T;
};

// SAFETY: SafeId is a nominal brand; runtime validation happens at call sites
export const toSafeId = <T extends SafeIdType>(value: string): SafeId<T> =>
  // eslint-disable-next-line typescript/no-unsafe-type-assertion
  value as SafeId<T>;

export const createSafeId = <T extends SafeIdType>(): SafeId<T> =>
  toSafeId<T>(Bun.randomUUIDv7());
