import * as v from "valibot";

const safeIdSchema = v.pipe(v.string(), v.brand("SafeId"));

export type SafeIdType =
  | "accountDeletionRequest"
  | "agentSkill"
  | "agentSkillResource"
  | "aiMemory"
  | "anonymizationAllowlistEntry"
  | "anonymizationBlacklistEntry"
  | "auditLog"
  | "billingCode"
  | "caseLawCitation"
  | "caseLawCourtWeight"
  | "caseLawDecision"
  | "caseLawIndexJob"
  | "caseLawIngestionEvent"
  | "caseLawIngestionFailure"
  | "caseLawMatterLink"
  | "caseLawPolarityRule"
  | "caseLawSource"
  | "chatMessage"
  | "chatThreadCompaction"
  | "chatThread"
  | "fileChatThread"
  | "templateChatThread"
  | "clause"
  | "clauseCategory"
  | "clauseVariant"
  | "clauseVersion"
  | "contact"
  | "contactRelationship"
  | "usageAllocation"
  | "usagePolicy"
  | "usageEntitlement"
  | "usageEvent"
  | "desktopEditHandoff"
  | "desktopEditSession"
  | "docxSuggestion"
  | "document"
  | "documentCounter"
  | "documentType"
  | "entity"
  | "entityVersionAiSummary"
  | "entityVersion"
  | "expense"
  | "extractionRun"
  | "field"
  | "flowDefinition"
  | "flowRun"
  | "flowRunStep"
  | "folioCollabSession"
  | "folioCollabSessionToken"
  | "folder"
  | "infoSoudTrackedCase"
  | "invoice"
  | "justification"
  | "legislationDocument"
  | "legislationIndexJob"
  | "legislationSource"
  | "matter"
  | "matterCounter"
  | "mcpConnector"
  | "mcpOAuthClient"
  | "mcpUserConnection"
  | "organization"
  | "organizationSettings"
  | "pendingUpload"
  | "playbook"
  | "playbookDefinition"
  | "playbookDefinitionVersion"
  | "property"
  | "propertyDependency"
  | "rateEntry"
  | "rateTable"
  | "reportExport"
  | "schedulerJobRun"
  | "styleSet"
  | "taskAssignee"
  | "task"
  | "template"
  | "templateCategory"
  | "templateClause"
  | "templateRecipe"
  | "templateFill"
  | "templateVersion"
  | "timeEntry"
  | "user"
  | "userFile"
  | "workspace"
  | "workspaceContact"
  | "workspaceMember"
  | "workspaceView"
  | "workspaceViewTemplate"
  | "entityLink";

export type SafeId<T extends SafeIdType> = v.InferOutput<
  typeof safeIdSchema
> & {
  /** Compile-time resource discriminator; boundary-specific schemas validate syntax. */
  readonly __safeIdType?: T;
};

export const toSafeId = <T extends SafeIdType>(value: string): SafeId<T> =>
  v.parse(safeIdSchema, value);

export const createSafeId = <T extends SafeIdType>(): SafeId<T> =>
  toSafeId<T>(Bun.randomUUIDv7());
