/**
 * Deployment built-in report templates.
 *
 * Two kinds share the picker:
 *
 * - `docx`: a committed marker-DOCX asset (generated by
 *   `apps/api/scripts/generate-dd-report-template.ts`). "Customize" clones it
 *   into the org's templates (Template Studio); org report templates then
 *   appear alongside the built-in. No per-org seeding or backfill.
 * - `spec`: a declarative report spec (`spec/report-spec.ts`) rendered through
 *   the Folio document model. Specs are bundled defaults plus the runtime set
 *   under `REPORT_SPECS_DIR` or `REPORT_SPECS_S3_PREFIX` (see
 *   `spec/load-report-specs.ts`); they have no DOCX to clone, so they are not
 *   customizable in Template Studio.
 *
 * The DOCX is the template: the AI-drafted fields are configured by the filters
 * on their own markers, so a clone carries its configuration with its bytes.
 *
 * The asset is pulled in through a `with { type: "file" }` import rather than
 * resolved from `import.meta.url`. `bun build --compile` (see
 * `apps/api/Dockerfile`) links the server into a standalone binary whose
 * `import.meta.url` is `file:///$bunfs/root/server`, so a URL built relative to
 * it points at `/$bunfs/root/assets/dd-report.docx`: a path that exists in the
 * source tree but not in the binary, making every read fail with ENOENT. The
 * import attribute instead makes the bundler embed the asset and resolve the
 * specifier to a readable path, so the bytes travel with the code and cannot
 * drift out of the build.
 */

import { panic, Result } from "better-result";

import { env } from "@/api/env";
import type { ReportSpecRuntimeSource } from "@/api/handlers/reports/spec/load-report-specs";
import {
  bundledReportSpecSources,
  loadReportSpecs,
  parseS3SpecPrefix,
} from "@/api/handlers/reports/spec/load-report-specs";
import type { ReportSpec } from "@/api/handlers/reports/spec/report-spec";
import { listS3ObjectKeys, readS3ObjectBounded } from "@/api/lib/s3";

import ddReportDocx from "./assets/dd-report.docx" with { type: "file" };

export type BuiltinReportTemplate =
  | {
      kind: "docx";
      key: string;
      name: string;
      /** Load the committed DOCX bytes. */
      loadBuffer: () => Promise<Buffer>;
    }
  | {
      kind: "spec";
      key: string;
      name: string;
      spec: ReportSpec;
      /** Prompt texts by `ref` (`prompts/<ref>.md`). */
      prompts: Map<string, string>;
    };

/** Whether "Customize" (clone into Template Studio) applies to a built-in. */
export const isCloneableBuiltin = (
  template: BuiltinReportTemplate,
): template is Extract<BuiltinReportTemplate, { kind: "docx" }> => {
  switch (template.kind) {
    case "docx":
      return true;
    case "spec":
      return false;
    default: {
      template satisfies never;
      return panic(`Unhandled template: ${String(template)}`);
    }
  }
};

export const DD_REPORT_KEY = "dd-report";

const ddReportTemplate: BuiltinReportTemplate = {
  kind: "docx",
  key: DD_REPORT_KEY,
  name: "Due Diligence Report",
  loadBuffer: async () =>
    Buffer.from(await Bun.file(ddReportDocx).arrayBuffer()),
};

let registry: readonly BuiltinReportTemplate[] | null = null;

/** The runtime spec source the env selects; the env invariant rejects both. */
const runtimeSpecSource = (): ReportSpecRuntimeSource => {
  if (env.REPORT_SPECS_DIR !== undefined) {
    return { type: "dir", specsDir: env.REPORT_SPECS_DIR };
  }
  if (env.REPORT_SPECS_S3_PREFIX === undefined) {
    return { type: "none" };
  }
  const location = parseS3SpecPrefix(env.REPORT_SPECS_S3_PREFIX);
  if (Result.isError(location)) {
    return panic(location.error.message);
  }
  return {
    type: "s3",
    location: location.value,
    store: { listKeys: listS3ObjectKeys, readObject: readS3ObjectBounded },
  };
};

/** Load (and so validate) every built-in report spec into the registry. Runs
 *  once at boot, after the S3 client is ready; an invalid spec panics so the
 *  boot fails rather than the first export that picks it. */
export const initBuiltinReportTemplates = async (): Promise<void> => {
  const specs = await loadReportSpecs({
    bundled: bundledReportSpecSources(),
    runtime: runtimeSpecSource(),
  });
  if (Result.isError(specs)) {
    return panic(specs.error.message);
  }
  const templates: BuiltinReportTemplate[] = [ddReportTemplate];
  for (const { key, spec, prompts } of specs.value.values()) {
    if (key === DD_REPORT_KEY) {
      return panic(`Report spec key "${key}" collides with the DOCX built-in.`);
    }
    templates.push({ kind: "spec", key, name: spec.name, spec, prompts });
  }
  registry = templates;
};

/** The registry; reading it before {@link initBuiltinReportTemplates} is a
 *  boot-order bug. */
const builtinReportTemplates = (): readonly BuiltinReportTemplate[] =>
  registry ??
  panic("Built-in report templates read before initBuiltinReportTemplates().");

/** Minimal picker surface: key, display name, and whether "Customize" (clone
 *  into Template Studio) is offered. */
export const listBuiltinReportTemplates = (): {
  key: string;
  name: string;
  cloneable: boolean;
}[] =>
  builtinReportTemplates().map((template) => ({
    key: template.key,
    name: template.name,
    cloneable: isCloneableBuiltin(template),
  }));

export const getBuiltinReportTemplate = (
  key: string,
): BuiltinReportTemplate | undefined =>
  builtinReportTemplates().find((template) => template.key === key);
