/**
 * Export a single chat message to a Word (.docx) document.
 *
 * `POST /chat/threads/:threadId/export`. Thread-scoped (the thread must belong
 * to the caller) and permission-gated. The message body is rendered to DOCX via
 * the SAME markdown -> Stella-styled DOCX renderer the create-document chat tool
 * uses (semantic Word styles: headings, lists), never a second generator.
 *
 * Citations are resolved SERVER-SIDE via the shared citation model
 * (`citation-footnotes.ts`): the chosen `citationStyle` is threaded end to end
 * with no hidden backend default, and only grounded sources are surfaced —
 * an ungrounded `unverified` citation never becomes a fabricated source.
 *
 * The generated bytes are written to object storage and returned as a presigned
 * download URL (consistent with the upload/download pattern), never streamed
 * through the response.
 */

import { Result } from "better-result";
import { t } from "elysia";

import { normalizePersistedChatMessageContent } from "@/api/handlers/chat/chat-message-parts";
import {
  assertChatThreadScopeMatches,
  resolveChatScope,
} from "@/api/handlers/chat/chat-scope";
import {
  buildCitationSection,
  sourceDocumentsToCitations,
} from "@/api/handlers/chat/export/citation-footnotes";
import {
  assembleMessageMarkdown,
  buildChatExportDownload,
  composeExportMarkdown,
} from "@/api/handlers/chat/export/export-shared";
import { markdownToStellaDocx } from "@/api/handlers/chat/tools/create-workspace-document-tools";
import { createSafeRootHandler } from "@/api/lib/api-handlers";
import type { HandlerConfig } from "@/api/lib/api-handlers";
import { AUDIT_ACTION, AUDIT_RESOURCE_TYPE } from "@/api/lib/audit-log";
import { tSafeId } from "@/api/lib/custom-schema";
import { HandlerError } from "@/api/lib/errors/tagged-errors";
import { getS3, presignDownloadUrl } from "@/api/lib/s3";
import { sanitizeFilename } from "@/api/lib/sanitize-filename";
import { DOCX_MIME_TYPE } from "@/api/mime-types";

/** How long the presigned download stays valid (seconds). Short: the URL is
 *  handed straight to the browser to fetch, not stored. */
const CHAT_EXPORT_URL_TTL_SECONDS = 300;

/** Bound the referenced-document set a single export folds into its Sources
 *  section, so one export can never assemble an unbounded citation list. */
const CHAT_EXPORT_MAX_SOURCE_DOCUMENTS = 50;

const config = {
  permissions: { chat: ["create"] },
  access: "read",
  mcp: { type: "internal", reason: "assistant_chat" },
  params: t.Object({ threadId: tSafeId("chatThread") }),
  query: t.Object({ workspaceId: t.Optional(tSafeId("workspace")) }),
  body: t.Object({
    messageId: tSafeId("chatMessage"),
    // Discriminators are threaded through explicitly (no hidden default). DOCX
    // is the only Phase 1 format; PDF is deferred.
    format: t.Literal("docx"),
    citationStyle: t.Union([
      t.Literal("footnotes"),
      t.Literal("inline"),
      t.Literal("none"),
    ]),
  }),
} satisfies HandlerConfig;

const exportMessage = createSafeRootHandler(
  config,
  async function* ({
    body: { messageId, citationStyle },
    getWorkspaceAccess,
    params: { threadId },
    query: { workspaceId },
    recordAuditEvent,
    safeDb,
    session,
    user,
  }) {
    const scope = yield* resolveChatScope({ getWorkspaceAccess, workspaceId });

    const thread = yield* Result.await(
      safeDb((tx) =>
        tx.query.chatThreads.findFirst({
          where: { id: { eq: threadId }, userId: { eq: user.id } },
          columns: { title: true, workspaceId: true },
        }),
      ),
    );
    if (!thread) {
      return Result.err(
        new HandlerError({ status: 404, message: "Chat thread not found" }),
      );
    }
    yield* assertChatThreadScopeMatches({
      persistedWorkspaceId: thread.workspaceId ?? null,
      scope,
    });

    const message = yield* Result.await(
      safeDb((tx) =>
        tx.query.chatMessages.findFirst({
          where: { id: { eq: messageId }, threadId: { eq: threadId } },
          columns: { content: true },
        }),
      ),
    );
    if (!message) {
      return Result.err(
        new HandlerError({ status: 404, message: "Message not found" }),
      );
    }

    const { parts, metadata } = normalizePersistedChatMessageContent(
      message.content,
    );
    const body = assembleMessageMarkdown(parts);
    if (body.length === 0) {
      return Result.err(
        new HandlerError({
          status: 400,
          message: "This message has no exportable text.",
        }),
      );
    }

    // Resolve the answer's grounded provenance for the chosen style. Only
    // verified sources are surfaced; unverified citations are counted, never
    // rendered as a fabricated source.
    const section = buildCitationSection(
      sourceDocumentsToCitations(
        metadata.sourceDocuments,
        CHAT_EXPORT_MAX_SOURCE_DOCUMENTS,
      ),
      citationStyle,
    );

    const markdown = composeExportMarkdown(body, section);

    const docxResult = yield* Result.await(
      Result.tryPromise({
        try: async () => await markdownToStellaDocx(markdown),
        catch: (cause) =>
          new HandlerError({
            status: 500,
            message: "The message could not be rendered to DOCX.",
            cause,
          }),
      }),
    );

    const fileName = sanitizeFilename(`${thread.title}.docx`);
    // `exports/` must lead the key so object-lifecycle prefix filters anchor at
    // the key start; org + thread keep it tenant-scoped, the random suffix
    // avoids collisions across concurrent exports of the same message.
    const key = `exports/${session.activeOrganizationId}/chat/${threadId}/${messageId}-${Bun.randomUUIDv7()}.docx`;
    yield* Result.await(
      Result.tryPromise({
        try: async () =>
          await getS3().write(key, docxResult, { type: DOCX_MIME_TYPE }),
        catch: (cause) =>
          new HandlerError({
            status: 502,
            message: "The exported document could not be stored.",
            cause,
          }),
      }),
    );

    const downloadUrl = presignDownloadUrl(key, {
      expiresIn: CHAT_EXPORT_URL_TTL_SECONDS,
      fileName,
    });

    yield* Result.await(
      safeDb(async (tx) => {
        await recordAuditEvent(tx, {
          action: AUDIT_ACTION.DOWNLOAD,
          resourceType: AUDIT_RESOURCE_TYPE.CHAT_MESSAGE,
          resourceId: messageId,
          metadata: {
            format: "docx",
            citationStyle,
            verifiedCitations: section.verifiedCount,
            unverifiedCitations: section.unverifiedCount,
          },
        });
      }),
    );

    return Result.ok(
      buildChatExportDownload({
        downloadUrl,
        fileName,
        expiresInSeconds: CHAT_EXPORT_URL_TTL_SECONDS,
        now: new Date(),
      }),
    );
  },
);

export default exportMessage;
