#!/usr/bin/env bun
// Build-time codegen (spec 051 S5.2, build-time call site). Reads the committed
// registry snapshot (produced by `apps/api/scripts/export-mcp-tool-registry.ts`,
// the only place the heavy registry imports resolve), runs the pure
// `generateRouteMap` with the baked-in Annotation Table, and writes the result
// to `generated/route-map.ts`. The snapshot keeps `@stll/cli` free of any
// `apps/api` import; the committed output means registry drift shows as a diff.
//
// Run via `bun run codegen` (which regenerates the snapshot first).

import { panic } from "better-result";
import * as v from "valibot";

import packageJson from "../package.json" with { type: "json" };
import { TOOL_ANNOTATIONS } from "./annotations.js";
import { generateResourceTree } from "./generate-resource-tree.js";
import { generateRouteMap } from "./generate-route-map.js";
import type { ResourceListing } from "./resource-types.js";
import type { RegistryToolListing } from "./route-types.js";

const snapshotUrl = new URL(
  "generated/registry-snapshot.json",
  import.meta.url,
);
const outputUrl = new URL("generated/route-map.ts", import.meta.url);
const resourceSnapshotUrl = new URL(
  "generated/resources-snapshot.json",
  import.meta.url,
);
const resourceOutputUrl = new URL(
  "generated/resource-tree.ts",
  import.meta.url,
);

// Validate the snapshot into the four wire fields so the codegen input is typed
// (not `any` off `.json()`) and a malformed snapshot fails loudly.
const listingSchema = v.array(
  v.looseObject({
    name: v.string(),
    description: v.string(),
    inputSchema: v.record(v.string(), v.unknown()),
    annotations: v.optional(
      v.looseObject({
        readOnlyHint: v.optional(v.boolean()),
        destructiveHint: v.optional(v.boolean()),
      }),
    ),
  }),
);

const snapshot = v.safeParse(listingSchema, await Bun.file(snapshotUrl).json());
if (!snapshot.success) {
  panic("registry-snapshot.json does not match the expected listing shape");
}

// Project the validated snapshot to the exact `RegistryToolListing` shape
// (dropping valibot's `| undefined` widening on optional annotation hints).
const listings: RegistryToolListing[] = [];
for (const tool of snapshot.output) {
  const annotations: { readOnlyHint?: boolean; destructiveHint?: boolean } = {};
  if (tool.annotations?.readOnlyHint !== undefined) {
    annotations.readOnlyHint = tool.annotations.readOnlyHint;
  }
  if (tool.annotations?.destructiveHint !== undefined) {
    annotations.destructiveHint = tool.annotations.destructiveHint;
  }
  listings.push({
    name: tool.name,
    description: tool.description,
    inputSchema: tool.inputSchema,
    ...(tool.annotations === undefined ? {} : { annotations }),
  });
}

const routeMap = generateRouteMap(listings, TOOL_ANNOTATIONS);

const header = `/* eslint-disable unicorn/numeric-separators-style -- generated JSON literals */
// GENERATED by \`bun run codegen\` (spec 051 S5.2). Do not edit by hand.
//
// The committed route tree built from the MCP tool registry snapshot through
// \`generateRouteMap\`. Regenerate after any registry change; drift shows up here
// as a diff instead of a runtime surprise.

import type { RouteNode } from "../route-types.js";

export const generatedRouteMap: RouteNode = `;

await Bun.write(outputUrl, `${header}${JSON.stringify(routeMap, null, 2)};\n`);

process.stderr.write(`Wrote ${outputUrl.pathname}\n`);

// The resource tree (spec 051 S5.4) is generated the same way from its own
// snapshot so `reference list`/`reference show` can never drift from the
// server's static resources.
const resourceSchema = v.array(
  v.strictObject({
    uri: v.string(),
    name: v.string(),
    title: v.optional(v.string()),
    description: v.optional(v.string()),
    mimeType: v.optional(v.string()),
  }),
);

const resourceSnapshot = v.safeParse(
  resourceSchema,
  await Bun.file(resourceSnapshotUrl).json(),
);
if (!resourceSnapshot.success) {
  panic("resources-snapshot.json does not match the expected listing shape");
}

// Project to the exact `ResourceListing` shape, dropping valibot's `| undefined`
// widening on the optional fields under `exactOptionalPropertyTypes`.
const resourceListings: ResourceListing[] = [];
for (const resource of resourceSnapshot.output) {
  const listing: ResourceListing = { uri: resource.uri, name: resource.name };
  if (resource.title !== undefined) {
    listing.title = resource.title;
  }
  if (resource.description !== undefined) {
    listing.description = resource.description;
  }
  if (resource.mimeType !== undefined) {
    listing.mimeType = resource.mimeType;
  }
  resourceListings.push(listing);
}

const resourceTree = generateResourceTree(resourceListings);

const resourceHeader = `// GENERATED by \`bun run codegen\` (spec 051 S5.4). Do not edit by hand.
//
// The committed resource tree built from the MCP \`resources/list\` snapshot
// through \`generateResourceTree\`. Regenerate after any resource change; drift
// shows up here as a diff instead of a runtime surprise.

import type { ResourceNode } from "../resource-types.js";

export const generatedResourceTree: ResourceNode = `;

await Bun.write(
  resourceOutputUrl,
  `${resourceHeader}${JSON.stringify(resourceTree, null, 2)};\n`,
);

process.stderr.write(`Wrote ${resourceOutputUrl.pathname}\n`);

// Bake the package version in at codegen time (spec 051 addendum: the CLI update
// nudge must not read package.json at runtime from dist). Regenerating after a
// version bump keeps this in lockstep with package.json.
const versionOutputUrl = new URL("generated/cli-version.ts", import.meta.url);
const versionHeader = `// GENERATED by \`bun run codegen\`. Do not edit by hand.
//
// The running CLI's own version, baked in at codegen time so the update nudge
// (spec 051 addendum) never reads package.json from the published dist.

export const CLI_VERSION = `;
await Bun.write(
  versionOutputUrl,
  `${versionHeader}${JSON.stringify(packageJson.version)};\n`,
);

process.stderr.write(`Wrote ${versionOutputUrl.pathname}\n`);
