#!/usr/bin/env bun
// Build-time codegen (spec 051 S5.2, build-time call site). Reads the committed
// registry snapshot (produced by `apps/api/scripts/export-mcp-tool-registry.ts`,
// the only place the heavy registry imports resolve), runs the pure
// `generateRouteMap` with the baked-in Annotation Table, and writes the result
// to `generated/route-map.ts`. The snapshot keeps `@stll/cli` free of any
// `apps/api` import; the committed output means registry drift shows as a diff.
//
// Run via `bun run codegen` (which regenerates the snapshot first).

import { panic } from "better-result";
import * as v from "valibot";

import { TOOL_ANNOTATIONS } from "./annotations.js";
import { generateRouteMap } from "./generate-route-map.js";
import type { RegistryToolListing } from "./route-types.js";

const snapshotUrl = new URL(
  "generated/registry-snapshot.json",
  import.meta.url,
);
const outputUrl = new URL("generated/route-map.ts", import.meta.url);

// Validate the snapshot into the four wire fields so the codegen input is typed
// (not `any` off `.json()`) and a malformed snapshot fails loudly.
const listingSchema = v.array(
  v.looseObject({
    name: v.string(),
    description: v.string(),
    inputSchema: v.record(v.string(), v.unknown()),
    annotations: v.optional(
      v.looseObject({
        readOnlyHint: v.optional(v.boolean()),
        destructiveHint: v.optional(v.boolean()),
      }),
    ),
  }),
);

const snapshot = v.safeParse(listingSchema, await Bun.file(snapshotUrl).json());
if (!snapshot.success) {
  panic("registry-snapshot.json does not match the expected listing shape");
}

// Project the validated snapshot to the exact `RegistryToolListing` shape
// (dropping valibot's `| undefined` widening on optional annotation hints).
const listings: RegistryToolListing[] = [];
for (const tool of snapshot.output) {
  const annotations: { readOnlyHint?: boolean; destructiveHint?: boolean } = {};
  if (tool.annotations?.readOnlyHint !== undefined) {
    annotations.readOnlyHint = tool.annotations.readOnlyHint;
  }
  if (tool.annotations?.destructiveHint !== undefined) {
    annotations.destructiveHint = tool.annotations.destructiveHint;
  }
  listings.push({
    name: tool.name,
    description: tool.description,
    inputSchema: tool.inputSchema,
    ...(tool.annotations === undefined ? {} : { annotations }),
  });
}

const routeMap = generateRouteMap(listings, TOOL_ANNOTATIONS);

const header = `/* eslint-disable unicorn/numeric-separators-style -- generated JSON literals */
// GENERATED by \`bun run codegen\` (spec 051 S5.2). Do not edit by hand.
//
// The committed route tree built from the MCP tool registry snapshot through
// \`generateRouteMap\`. Regenerate after any registry change; drift shows up here
// as a diff instead of a runtime surprise.

import type { RouteNode } from "../route-types.js";

export const generatedRouteMap: RouteNode = `;

await Bun.write(outputUrl, `${header}${JSON.stringify(routeMap, null, 2)};\n`);

process.stderr.write(`Wrote ${outputUrl.pathname}\n`);
