#!/usr/bin/env bun
import { panic, Result } from "better-result";
import {
  existsSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { parseEnv } from "node:util";
import ts from "typescript";
import * as v from "valibot";

import { resolveDatabaseUrl } from "../apps/api/src/db-url";
import {
  classifyNodeEnv,
  envBaseInvariantViolation,
  KNOWN_NODE_ENVS,
  NODE_ENV_KIND,
  resolveApiEnvironmentPlaceholders,
} from "../apps/api/src/env-base-schema";
import { documentProcessingEnvInvariantViolation } from "../apps/api/src/env-document-processing-worker-schema";
import {
  envApiInvariantViolation,
  resolveEmailProvider,
} from "../apps/api/src/env-schema";
import { EMPTY_VALUE_VARIABLES } from "../apps/api/src/lib/configuration-placeholders";
import { envWebInvariantViolation } from "../apps/web/src/env-schema";
import {
  AMBIENT_ENV_KEYS,
  API_ENV_SCHEMA,
  COLLAB_ENV_SCHEMA,
  DEPLOYMENT_ENV_KEYS,
  ENV_CATALOG,
  ENV_EXPOSURE,
  ENV_OWNER,
  type EnvCatalogEntry,
  type EnvOwner,
  isActiveExampleEntry,
  MANUAL_SCHEMA_KEYS,
  TOOLING_ENV_KEYS,
  WEB_ENV_SCHEMA,
} from "./env-catalog";

const REPO_ROOT = path.resolve(import.meta.dir, "..");
const API_EXAMPLE_PATH = path.join(REPO_ROOT, "apps/api/.env.example");
const COLLAB_EXAMPLE_PATH = path.join(REPO_ROOT, "apps/collab/.env.example");
const WEB_EXAMPLE_PATH = path.join(REPO_ROOT, "apps/web/.env.example");
const WEB_BUILD_CONTRACT_PATH = path.join(
  REPO_ROOT,
  "apps/web/build-env-contract.json",
);
const GENERATED_HEADER = [
  "# Generated by `bun run env:generate`; edit the Valibot schemas or env catalog.",
  "# Required entries are active. Optional entries are commented out unless",
  "# stella's local development stack intentionally enables them.",
  "",
].join("\n");

const quoteEnvValue = (value: string) =>
  `"${value.replaceAll("\\", "\\\\").replaceAll('"', '\\"')}"`;

// Catalog entries are typed as `v.GenericSchema`, for which `getDefault`
// resolves to `void` even though it returns the schema's real default at
// runtime. Reading it through this helper makes the value `unknown`, so the
// narrowing at the call site is honest rather than dead code.
const schemaDefault = (schema: v.GenericSchema): unknown =>
  v.getDefault(schema);

export const exampleValueForCatalogEntry = (entry: EnvCatalogEntry) => {
  if (entry.example !== undefined) {
    return entry.example;
  }
  const fallback = schemaDefault(entry.schema);
  if (typeof fallback === "string" || typeof fallback === "number") {
    return String(fallback);
  }
  if (typeof fallback === "boolean") {
    return fallback ? "true" : "false";
  }
  return "";
};

const requirementLabel = (entry: EnvCatalogEntry) => {
  if (entry.requirement === "required") {
    return "Required";
  }
  if (entry.requirement === "conditional") {
    if (!entry.requirementNote) {
      panic(`Conditional environment entry ${entry.name} requires a note.`);
    }
    return `Conditionally required when ${entry.requirementNote}`;
  }
  if (entry.requirement === "defaulted") {
    return "Optional with a default";
  }
  return "Optional";
};

const wrapComment = (text: string, width = 76) => {
  const lines: string[] = [];
  let current = "";
  for (const word of text.split(/\s+/u)) {
    if (current.length === 0) {
      current = word;
      continue;
    }
    if (current.length + word.length + 1 <= width) {
      current += ` ${word}`;
      continue;
    }
    lines.push(`# ${current}`);
    current = word;
  }
  if (current.length > 0) {
    lines.push(`# ${current}`);
  }
  return lines;
};

type RenderEnvironmentEntriesOptions = {
  header?: string;
  isActive?: (entry: EnvCatalogEntry) => boolean;
  valueFor?: (entry: EnvCatalogEntry) => string;
};

export const renderEnvironmentEntries = (
  entries: EnvCatalogEntry[],
  {
    header = GENERATED_HEADER,
    isActive = ({ name }) => isActiveExampleEntry(name),
    valueFor = exampleValueForCatalogEntry,
  }: RenderEnvironmentEntriesOptions = {},
) => {
  const sections = Map.groupBy(entries, ({ section }) => section);
  const lines: string[] = [header];
  for (const [section, sectionEntries] of sections) {
    lines.push(
      `# --- ${section} ${"-".repeat(Math.max(1, 66 - section.length))}`,
    );
    for (const entry of sectionEntries) {
      const active = entry.requirement === "required" || isActive(entry);
      const prefix = active ? "" : "# ";
      lines.push(
        ...wrapComment(
          `[${entry.exposure}] ${requirementLabel(entry)}. ${entry.description}`,
        ),
        `${prefix}${entry.name}=${quoteEnvValue(valueFor(entry))}`,
        "",
      );
    }
  }
  return `${lines.join("\n").trimEnd()}\n`;
};

export const renderApiEnvExample = () =>
  renderEnvironmentEntries(
    ENV_CATALOG.filter(
      ({ documented, owner }) =>
        documented && owner !== ENV_OWNER.web && owner !== ENV_OWNER.collab,
    ),
  );

export const renderWebEnvExample = () =>
  renderEnvironmentEntries(
    ENV_CATALOG.filter(
      ({ documented, owner }) => documented && owner === ENV_OWNER.web,
    ),
  );

export const renderCollabEnvExample = () =>
  renderEnvironmentEntries(
    ENV_CATALOG.filter(
      ({ documented, owner }) => documented && owner === ENV_OWNER.collab,
    ),
  );

const BUN_ENV_READER =
  'const names=JSON.parse(process.argv[1]??"[]");process.stdout.write(JSON.stringify(Object.fromEntries(names.map(name=>[name,process.env[name]??""]))));';
const BUN_ENV_LOAD_TIMEOUT_MS = 10_000;

const definedEnvironment = (environment: NodeJS.ProcessEnv) => {
  const defined: Record<string, string> = {};
  for (const [name, value] of Object.entries(environment)) {
    if (value !== undefined) {
      defined[name] = value;
    }
  }
  return defined;
};

export const parseEnvLayers = (
  texts: string[],
  ambientEnvironment: NodeJS.ProcessEnv = process.env,
) => {
  const text = texts.join("\n");
  const names = Object.keys(parseEnv(text));
  if (names.length === 0) {
    return {};
  }
  const temporaryDirectory = mkdtempSync(
    path.join(tmpdir(), "stella-env-tool-"),
  );
  const envPath = path.join(temporaryDirectory, "environment.env");
  const spawned = Result.try(() => {
    writeFileSync(envPath, text, { mode: 0o600 });
    return Bun.spawnSync({
      cmd: [
        process.execPath,
        "--no-env-file",
        `--env-file=${envPath}`,
        "-e",
        BUN_ENV_READER,
        JSON.stringify(names),
      ],
      cwd: temporaryDirectory,
      env: definedEnvironment(ambientEnvironment),
      killSignal: "SIGKILL",
      timeout: BUN_ENV_LOAD_TIMEOUT_MS,
    });
  });
  rmSync(temporaryDirectory, { recursive: true });
  if (Result.isError(spawned)) {
    panic("Bun failed to load environment layers.");
  }
  const result = spawned.value;
  if (result.exitCode !== 0) {
    panic("Bun failed to load environment layers.");
  }
  const decoded = Result.try(() => JSON.parse(result.stdout.toString()));
  if (Result.isError(decoded)) {
    panic("Bun returned invalid environment data.");
  }
  const validated = v.safeParse(
    v.record(v.string(), v.string()),
    decoded.value,
  );
  if (!validated.success) {
    panic("Bun returned invalid environment values.");
  }
  return validated.output;
};

export const parseEnvText = (
  text: string,
  ambientEnvironment: NodeJS.ProcessEnv = process.env,
) => parseEnvLayers([text], ambientEnvironment);

const generatedEnvironmentExamples = () => [
  { content: renderApiEnvExample(), path: API_EXAMPLE_PATH },
  { content: renderCollabEnvExample(), path: COLLAB_EXAMPLE_PATH },
  { content: renderWebEnvExample(), path: WEB_EXAMPLE_PATH },
];

const generatedEnvironmentArtifacts = () => [
  ...generatedEnvironmentExamples(),
  {
    content: renderWebBuildContract({
      clientKeys: Object.keys(WEB_ENV_SCHEMA),
      dockerfile: readFileSync(WEB_DOCKERFILE_PATH, "utf-8"),
    }),
    path: WEB_BUILD_CONTRACT_PATH,
  },
];

const generateEnvironmentArtifacts = () => {
  for (const artifact of generatedEnvironmentArtifacts()) {
    writeFileSync(artifact.path, artifact.content);
    console.log(`Generated ${path.relative(REPO_ROOT, artifact.path)}`);
  }
};

const checkEnvironmentArtifacts = () => {
  const stale = generatedEnvironmentArtifacts().filter(
    ({ content, path: artifactPath }) =>
      !existsSync(artifactPath) ||
      readFileSync(artifactPath, "utf-8") !== content,
  );
  if (stale.length === 0) {
    console.log("Environment artifacts match their schemas.");
    return true;
  }
  for (const { path: artifactPath } of stale) {
    console.error(`${path.relative(REPO_ROOT, artifactPath)} is stale.`);
  }
  console.error("Run `bun run env:generate` and commit the result.");
  return false;
};

// Vite inlines client variables at build time, so the web container build must
// carry every schema key into the build command: an ARG the image can receive,
// and an entry in the build command's environment prefix. A key missing from
// either section resolves to its schema default in every image, silently.
const WEB_DOCKERFILE_PATH = path.join(REPO_ROOT, "apps/web/Dockerfile");
const WEB_DOCKERFILE_LABEL = "apps/web/Dockerfile";
const WEB_SCHEMA_LABEL = "apps/web/src/env-schema.ts";
const WEB_BUILD_COMMAND = "bun --filter @stll/web build";
const WEB_CLIENT_PREFIX = "VITE_";

const DOCKER_NAME_PATTERN = /^[A-Z][A-Z0-9_]*$/u;
const DOCKER_ARG_PATTERN = /^ARG\s+(\S.*)$/iu;
const DOCKER_ASSIGNMENT_PATTERN = /\b([A-Z][A-Z0-9_]*)="([^"]*)"/gu;
const DOCKER_REFERENCE_PATTERN = /\$\{([A-Z][A-Z0-9_]*)\}/gu;

type WebBuildContract = {
  /**
   * Build arguments the builder stage declares before the build runs. Only
   * `ARG` counts: `ENV` also puts a name in scope for the build, but
   * `docker build --build-arg` cannot override it, so an `ENV`-only key is
   * exactly the frozen default this guard exists to catch.
   */
  args: Set<string>;
  /** Variables the build command exports, mapped to their exported value. */
  exported: Map<string, string>;
};

const dockerInstructions = (dockerfile: string) =>
  dockerfile
    .replaceAll(/\\\r?\n\s*/gu, " ")
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => line.length > 0 && !line.startsWith("#"));

export const parseWebBuildContract = (dockerfile: string): WebBuildContract => {
  const args = new Set<string>();
  for (const instruction of dockerInstructions(dockerfile)) {
    if (/^FROM\s/iu.test(instruction)) {
      args.clear();
      continue;
    }
    const declaration = DOCKER_ARG_PATTERN.exec(instruction)?.at(1);
    if (declaration !== undefined) {
      for (const token of declaration.split(/\s+/u)) {
        const name = token.split("=").at(0) ?? "";
        if (DOCKER_NAME_PATTERN.test(name)) {
          args.add(name);
        }
      }
      continue;
    }
    if (
      !instruction.startsWith("RUN ") ||
      !instruction.includes(WEB_BUILD_COMMAND)
    ) {
      continue;
    }
    const prefix = instruction.slice(0, instruction.indexOf(WEB_BUILD_COMMAND));
    const exported = new Map<string, string>();
    for (const match of prefix.matchAll(DOCKER_ASSIGNMENT_PATTERN)) {
      const name = match.at(1);
      const value = match.at(2);
      if (name !== undefined && value !== undefined) {
        exported.set(name, value);
      }
    }
    return { args, exported };
  }
  return panic(
    `${WEB_DOCKERFILE_LABEL} no longer runs \`${WEB_BUILD_COMMAND}\`; update the build-argument guard in scripts/env-tool.ts.`,
  );
};

type WebBuildArgGap =
  | { name: string; reference: string; type: "undeclared" }
  | { name: string; type: "missing" }
  | { name: string; type: "unknown" };

type FindWebBuildArgGapsOptions = {
  clientKeys: string[];
  dockerfile: string;
};

export const findWebBuildArgGaps = ({
  clientKeys,
  dockerfile,
}: FindWebBuildArgGapsOptions): WebBuildArgGap[] => {
  const { args, exported } = parseWebBuildContract(dockerfile);
  const schemaKeys = new Set(clientKeys);
  const gaps: WebBuildArgGap[] = [];
  for (const name of clientKeys) {
    if (!exported.has(name)) {
      gaps.push({ name, type: "missing" });
    }
  }
  for (const [name, value] of exported) {
    if (name.startsWith(WEB_CLIENT_PREFIX) && !schemaKeys.has(name)) {
      gaps.push({ name, type: "unknown" });
      continue;
    }
    for (const match of value.matchAll(DOCKER_REFERENCE_PATTERN)) {
      const reference = match.at(1);
      if (reference !== undefined && !args.has(reference)) {
        gaps.push({ name, reference, type: "undeclared" });
      }
    }
  }
  return gaps;
};

export const formatWebBuildArgGap = (gap: WebBuildArgGap) => {
  switch (gap.type) {
    case "missing":
      return `${WEB_DOCKERFILE_LABEL}: ${gap.name} is declared in ${WEB_SCHEMA_LABEL} but the web build command never exports it; every image inlines its schema default.`;
    case "undeclared":
      return `${WEB_DOCKERFILE_LABEL}: ${gap.name} is exported from \${${gap.reference}}, which the builder stage never declares as an ARG; the build always sees an empty value.`;
    case "unknown":
      return `${WEB_DOCKERFILE_LABEL}: ${gap.name} is exported to the web build but ${WEB_SCHEMA_LABEL} does not declare it.`;
    default: {
      const exhaustive: never = gap;
      return exhaustive;
    }
  }
};

type RenderWebBuildContractOptions = {
  clientKeys: string[];
  dockerfile: string;
};

export const renderWebBuildContract = ({
  clientKeys,
  dockerfile,
}: RenderWebBuildContractOptions) => {
  const gaps = findWebBuildArgGaps({ clientKeys, dockerfile });
  if (gaps.length > 0) {
    return panic("Cannot render an incomplete web build contract.");
  }
  const { exported } = parseWebBuildContract(dockerfile);
  const variables: Record<string, string> = {};
  for (const name of clientKeys.toSorted()) {
    const value = exported.get(name);
    const reference = value?.match(/^\$\{([A-Z][A-Z0-9_]*)\}$/u)?.at(1);
    if (reference === undefined) {
      return panic(
        `${WEB_DOCKERFILE_LABEL}: ${name} must map directly to one build argument before it can be published in the web build contract.`,
      );
    }
    variables[name] = reference;
  }
  return `${JSON.stringify({ version: 1, variables }, null, 2)}\n`;
};

const checkWebBuildArgs = () => {
  const gaps = findWebBuildArgGaps({
    clientKeys: Object.keys(WEB_ENV_SCHEMA),
    dockerfile: readFileSync(WEB_DOCKERFILE_PATH, "utf-8"),
  });
  if (gaps.length === 0) {
    console.log("Web container build arguments cover the client env schema.");
    return true;
  }
  for (const gap of gaps) {
    console.error(formatWebBuildArgGap(gap));
  }
  console.error(
    `Declare each key as an ARG and export it in the build-command environment prefix in ${WEB_DOCKERFILE_LABEL}.`,
  );
  return false;
};

const STATIC_ENV_PATTERNS = [
  /\b(?:process|Bun)\.env\.([A-Z][A-Z0-9_]*)/gu,
  /\b(?:process|Bun)\.env\[["']([A-Z][A-Z0-9_]*)["']\]/gu,
  /\bimport\.meta\.env\.([A-Z][A-Z0-9_]*)/gu,
  /\bimport\.meta\.env\[["']([A-Z][A-Z0-9_]*)["']\]/gu,
];
const STATIC_RUST_ENV_PATTERNS = [
  /\b(?:std::)?env::var(?:_os)?\(\s*"([A-Z][A-Z0-9_]*)"/gu,
  /\b(?:env|option_env)!\(\s*"([A-Z][A-Z0-9_]*)"/gu,
];

const DEPLOYMENT_ENV_PATTERN = /\$\{([A-Z][A-Z0-9_]*)(?=[:}?])/gu;
const BARE_DOCKER_ENV_PATTERN = /\$(?!\{)([A-Z][A-Z0-9_]*)\b/gu;

const AUDIT_GLOBS = [
  "apps/**/*.{ts,tsx,js,mjs,cjs,rs,yml,yaml}",
  "packages/**/*.{ts,tsx,js,mjs,cjs}",
  "scripts/**/*.{ts,js,sh}",
  "**/Dockerfile*",
  "**/docker-compose*.yml",
];

const AUDIT_IGNORE_FILES = new Set([
  // These tests contain environment syntax as source-text fixtures or use
  // test-process-only variables that are not repository configuration.
  "packages/property-testing/src/ci-gate-coverage.test.ts",
  "scripts/bun-ci-retry.test.sh",
  "scripts/detect-desktop-release-changes.test.sh",
  "scripts/env-tool.test.ts",
]);
const AUDIT_IGNORE_PATH_SEGMENTS = new Set([".cache", "node_modules"]);
/** Submodules: other repositories, with their own configuration surface. */
const AUDIT_IGNORE_PATH_PREFIXES = ["packages/template-packs/content/"];

export const isIgnoredAuditPath = (file: string) =>
  AUDIT_IGNORE_PATH_PREFIXES.some((prefix) => file.startsWith(prefix)) ||
  file.split("/").some((segment) => AUDIT_IGNORE_PATH_SEGMENTS.has(segment));

type EnvUsage = { file: string; line: number; name: string };

const ENV_NAME_PATTERN = /^[A-Z][A-Z0-9_]*$/u;
const SCRIPT_FILE_PATTERN = /\.[cm]?[jt]sx?$/u;

const findComputedEnvUsages = (file: string, text: string): EnvUsage[] => {
  if (!SCRIPT_FILE_PATTERN.test(file)) {
    return [];
  }

  const source = ts.createSourceFile(
    file,
    text,
    ts.ScriptTarget.Latest,
    true,
    file.endsWith("x") ? ts.ScriptKind.TSX : ts.ScriptKind.TS,
  );
  const constants = new Map<string, string>();
  type HelperReference =
    | { parameterIndex: number; type: "positional" }
    | {
        parameterIndex: number;
        propertyName: string;
        type: "object-property";
      };
  const helpers = new Map<string, HelperReference>();
  const usages: EnvUsage[] = [];

  const literalEnvName = (node: ts.Node | undefined) => {
    if (
      node &&
      (ts.isStringLiteral(node) || ts.isNoSubstitutionTemplateLiteral(node))
    ) {
      return ENV_NAME_PATTERN.test(node.text) ? node.text : undefined;
    }
    if (node && ts.isIdentifier(node)) {
      return constants.get(node.text);
    }
    return undefined;
  };

  const collectConstants = (node: ts.Node) => {
    if (ts.isVariableDeclaration(node) && ts.isIdentifier(node.name)) {
      const value = literalEnvName(node.initializer);
      if (value) {
        constants.set(node.name.text, value);
      }
    }
    ts.forEachChild(node, collectConstants);
  };
  collectConstants(source);

  const envArgument = (node: ts.Node) => {
    if (!ts.isElementAccessExpression(node)) {
      return undefined;
    }
    const envAccess = node.expression;
    if (
      !ts.isPropertyAccessExpression(envAccess) ||
      envAccess.name.text !== "env" ||
      !ts.isIdentifier(envAccess.expression) ||
      (envAccess.expression.text !== "process" &&
        envAccess.expression.text !== "Bun")
    ) {
      return undefined;
    }
    return node.argumentExpression;
  };

  type HelperDeclaration =
    | ts.ArrowFunction
    | ts.FunctionDeclaration
    | ts.FunctionExpression;

  const isHelperDeclaration = (node: ts.Node): node is HelperDeclaration =>
    ts.isArrowFunction(node) ||
    ts.isFunctionDeclaration(node) ||
    ts.isFunctionExpression(node);

  // `ts.Node.parent` is declared non-optional but is undefined once the walk
  // reaches the source file. Reading it through a nullable view keeps the
  // termination check meaningful instead of narrowing it away.
  const parentOf = (node: ts.Node): ts.Node | undefined => {
    const { parent }: { parent?: ts.Node } = node;
    return parent;
  };

  const helperName = (node: HelperDeclaration) => {
    if (ts.isFunctionDeclaration(node) && node.name) {
      return node.name.text;
    }
    if (
      (ts.isArrowFunction(node) || ts.isFunctionExpression(node)) &&
      ts.isVariableDeclaration(node.parent) &&
      ts.isIdentifier(node.parent.name)
    ) {
      return node.parent.name.text;
    }
    return undefined;
  };

  const bindingPropertyName = (element: ts.BindingElement) => {
    if (element.propertyName === undefined && ts.isIdentifier(element.name)) {
      return element.name.text;
    }
    if (
      element.propertyName &&
      (ts.isIdentifier(element.propertyName) ||
        ts.isStringLiteral(element.propertyName))
    ) {
      return element.propertyName.text;
    }
    return undefined;
  };

  const helperReference = (
    declaration: HelperDeclaration,
    argumentName: string,
  ): HelperReference | undefined => {
    for (const [
      parameterIndex,
      parameter,
    ] of declaration.parameters.entries()) {
      if (
        ts.isIdentifier(parameter.name) &&
        parameter.name.text === argumentName
      ) {
        return { parameterIndex, type: "positional" };
      }
      if (!ts.isObjectBindingPattern(parameter.name)) {
        continue;
      }
      const element = parameter.name.elements.find(
        ({ name }) => ts.isIdentifier(name) && name.text === argumentName,
      );
      if (!element) {
        continue;
      }
      const propertyName = bindingPropertyName(element);
      if (propertyName) {
        return { parameterIndex, propertyName, type: "object-property" };
      }
    }
    return undefined;
  };

  const collectReads = (node: ts.Node) => {
    const argument = envArgument(node);
    if (argument && ts.isIdentifier(argument)) {
      const constantName = constants.get(argument.text);
      if (constantName) {
        usages.push({
          file,
          line:
            source.getLineAndCharacterOfPosition(argument.getStart(source))
              .line + 1,
          name: constantName,
        });
      } else {
        let parent = parentOf(node);
        while (parent && !isHelperDeclaration(parent)) {
          parent = parentOf(parent);
        }
        if (parent && isHelperDeclaration(parent)) {
          const name = helperName(parent);
          const reference = helperReference(parent, argument.text);
          if (name && reference) {
            helpers.set(name, reference);
          }
        }
      }
    }
    ts.forEachChild(node, collectReads);
  };
  collectReads(source);

  const propertyName = (node: ts.PropertyName) =>
    ts.isIdentifier(node) || ts.isStringLiteral(node) ? node.text : undefined;

  const referencedCallArgument = (
    call: ts.CallExpression,
    reference: HelperReference,
  ) => {
    const argument = call.arguments.at(reference.parameterIndex);
    if (reference.type === "positional") {
      return argument;
    }
    if (!argument || !ts.isObjectLiteralExpression(argument)) {
      return undefined;
    }
    for (const property of argument.properties) {
      if (
        ts.isPropertyAssignment(property) &&
        propertyName(property.name) === reference.propertyName
      ) {
        return property.initializer;
      }
      if (
        ts.isShorthandPropertyAssignment(property) &&
        property.name.text === reference.propertyName
      ) {
        return property.name;
      }
    }
    return undefined;
  };

  const collectCalls = (node: ts.Node) => {
    if (ts.isCallExpression(node) && ts.isIdentifier(node.expression)) {
      const reference = helpers.get(node.expression.text);
      if (reference) {
        const argument = referencedCallArgument(node, reference);
        const name = literalEnvName(argument);
        if (name && argument) {
          usages.push({
            file,
            line:
              source.getLineAndCharacterOfPosition(argument.getStart(source))
                .line + 1,
            name,
          });
        }
      }
    }
    ts.forEachChild(node, collectCalls);
  };
  collectCalls(source);

  return usages;
};

export const findEnvUsages = (file: string, text: string): EnvUsage[] => {
  const usages = findComputedEnvUsages(file, text);
  let patterns = STATIC_ENV_PATTERNS;
  if (file.endsWith(".rs")) {
    patterns = STATIC_RUST_ENV_PATTERNS;
  } else if (file.includes("Dockerfile")) {
    patterns = [
      ...STATIC_ENV_PATTERNS,
      DEPLOYMENT_ENV_PATTERN,
      BARE_DOCKER_ENV_PATTERN,
    ];
  } else if (/\.(?:sh|ya?ml)$/u.test(file)) {
    patterns = [...STATIC_ENV_PATTERNS, DEPLOYMENT_ENV_PATTERN];
  }
  for (const pattern of patterns) {
    for (const match of text.matchAll(pattern)) {
      const name = match.at(1);
      if (!name) {
        continue;
      }
      usages.push({
        file,
        line: text.slice(0, match.index).split("\n").length,
        name,
      });
    }
  }
  return usages;
};

const isKnownEnvName = (name: string) =>
  ENV_CATALOG.some((entry) => entry.name === name) ||
  MANUAL_SCHEMA_KEYS.has(name) ||
  TOOLING_ENV_KEYS.has(name) ||
  DEPLOYMENT_ENV_KEYS.has(name) ||
  AMBIENT_ENV_KEYS.has(name) ||
  /^(?:ACTIONS_|BUN_|GITHUB_|INPUT_|npm_|RAILWAY_|RUNNER_)/u.test(name);

const auditEnvironment = async () => {
  const files = new Set<string>();
  for (const pattern of AUDIT_GLOBS) {
    const glob = new Bun.Glob(pattern);
    // eslint-disable-next-line no-await-in-loop -- each glob is a lazy async iterator
    for await (const file of glob.scan({ cwd: REPO_ROOT, onlyFiles: true })) {
      if (!isIgnoredAuditPath(file) && !AUDIT_IGNORE_FILES.has(file)) {
        files.add(file);
      }
    }
  }
  const unknown: EnvUsage[] = [];
  for (const file of files) {
    const text = readFileSync(path.join(REPO_ROOT, file), "utf-8");
    unknown.push(
      ...findEnvUsages(file, text).filter(({ name }) => !isKnownEnvName(name)),
    );
  }
  const unique = [
    ...new Map(
      unknown.map((usage) => [
        `${usage.file}:${usage.line}:${usage.name}`,
        usage,
      ]),
    ).values(),
  ];
  if (unique.length === 0) {
    console.log("All static environment-variable reads are cataloged.");
    return true;
  }
  for (const usage of unique) {
    console.error(`${usage.file}:${usage.line}: uncataloged env ${usage.name}`);
  }
  return false;
};

const sourceLabel = (name: string, fileValues: Record<string, string>) => {
  if (process.env[name] !== undefined) {
    return "process";
  }
  if (fileValues[name] !== undefined) {
    return "file";
  }
  return "default/unset";
};

export const formatEnvValue = (entry: EnvCatalogEntry, value: unknown) => {
  if (value === undefined) {
    return "<unset>";
  }
  if (entry.exposure === ENV_EXPOSURE.secret) {
    return "<redacted>";
  }
  return JSON.stringify(value);
};

export const formatEnvIssue = (issue: v.BaseIssue<unknown>) => {
  const key = issue.path
    ?.map((item) => item.key)
    .find((itemKey) => typeof itemKey === "string");
  if (typeof key !== "string") {
    return "Invalid environment configuration.";
  }
  const entry = ENV_CATALOG.find(({ name }) => name === key);
  if (entry?.exposure !== ENV_EXPOSURE.public) {
    return `${key}: invalid ${entry?.exposure ?? ENV_EXPOSURE.secret} value.`;
  }
  return `${key}: ${issue.message}`;
};

const ENV_APP = {
  api: "api",
  collab: "collab",
  web: "web",
} as const;

type EnvApp = (typeof ENV_APP)[keyof typeof ENV_APP];
type DoctorInput = Record<string, string | undefined>;
type DoctorValues = Record<string, unknown>;
type DoctorValidationResult =
  | { status: "invalid"; issues: string[]; values: DoctorValues }
  | { status: "valid"; values: DoctorValues };

const isEnvApp = (value: string): value is EnvApp =>
  Object.values(ENV_APP).some((app) => app === value);

export const normalizeEmptyEnvironment = (input: DoctorInput): DoctorInput => {
  const normalized: DoctorInput = {};
  for (const [name, value] of Object.entries(input)) {
    normalized[name] =
      value === "" && !EMPTY_VALUE_VARIABLES.has(name) ? undefined : value;
  }
  return normalized;
};

const validateSchema = (
  schema: Record<string, v.GenericSchema>,
  input: DoctorInput,
): DoctorValidationResult => {
  const result = v.safeParse(v.object(schema), input);
  if (!result.success) {
    return {
      status: "invalid",
      issues: result.issues.map(formatEnvIssue),
      values: input,
    };
  }
  return { status: "valid", values: { ...input, ...result.output } };
};

const validateApiEnvironment = (input: DoctorInput): DoctorValidationResult => {
  // Mirrors apps/api/src/env-base.ts: placeholders go first, so the doctor
  // and the runtime derive DATABASE_URL from the same values.
  const placeholders = resolveApiEnvironmentPlaceholders({
    schema: API_ENV_SCHEMA,
    values: input,
  });
  if (placeholders.violation !== null) {
    return {
      status: "invalid",
      issues: [placeholders.violation],
      values: input,
    };
  }
  const configured = placeholders.runtimeEnv;

  const databaseUrl = Result.try(() => resolveDatabaseUrl(configured));
  if (Result.isError(databaseUrl)) {
    return {
      status: "invalid",
      issues: ["DATABASE_URL: invalid database component settings."],
      values: configured,
    };
  }

  const nodeEnv = configured["NODE_ENV"];
  const nodeEnvKind = classifyNodeEnv(nodeEnv);
  if (nodeEnvKind === NODE_ENV_KIND.unknown) {
    return {
      status: "invalid",
      issues: [
        `NODE_ENV: "${nodeEnv}" is not one of ${KNOWN_NODE_ENVS.join(", ")}.`,
      ],
      values: configured,
    };
  }

  const runtimeInput = {
    ...configured,
    DATABASE_URL: databaseUrl.value,
    isDev: nodeEnvKind === NODE_ENV_KIND.local,
  };
  const parsed = v.safeParse(v.object(API_ENV_SCHEMA), runtimeInput);
  if (!parsed.success) {
    return {
      status: "invalid",
      issues: parsed.issues.map(formatEnvIssue),
      values: runtimeInput,
    };
  }

  const emailProvider = resolveEmailProvider(parsed.output);
  const output = { ...parsed.output, EMAIL_PROVIDER: emailProvider };
  const issues: string[] = [];
  const baseIssue = envBaseInvariantViolation(output);
  if (baseIssue !== null) {
    issues.push(baseIssue);
  }
  const documentProcessingIssue = documentProcessingEnvInvariantViolation({
    contentEncryptionKey: output.CONTENT_ENCRYPTION_KEY,
    nodeEnv,
    redisUrl: output.REDIS_URL,
  });
  if (documentProcessingIssue !== null) {
    issues.push(documentProcessingIssue);
  }
  const apiIssue = envApiInvariantViolation({ ...output, nodeEnv });
  if (apiIssue !== null) {
    issues.push(apiIssue);
  }
  const values = { ...runtimeInput, ...output };
  return issues.length === 0
    ? { status: "valid", values }
    : { status: "invalid", issues, values };
};

const validateWebEnvironment = (input: DoctorInput): DoctorValidationResult => {
  const result = v.safeParse(v.object(WEB_ENV_SCHEMA), input);
  if (!result.success) {
    return {
      status: "invalid",
      issues: result.issues.map(formatEnvIssue),
      values: input,
    };
  }
  const values = { ...input, ...result.output };
  const issue = envWebInvariantViolation(result.output);
  return issue === null
    ? { status: "valid", values }
    : { status: "invalid", issues: [issue], values };
};

type EnvAppConfig = {
  examplePath: string;
  owners: ReadonlySet<EnvOwner>;
  validate: (input: DoctorInput) => DoctorValidationResult;
};

const ENV_APP_CONFIG = {
  api: {
    examplePath: API_EXAMPLE_PATH,
    owners: new Set<EnvOwner>([
      ENV_OWNER.apiBase,
      ENV_OWNER.documentWorker,
      ENV_OWNER.apiServer,
    ]),
    validate: validateApiEnvironment,
  },
  collab: {
    examplePath: COLLAB_EXAMPLE_PATH,
    owners: new Set<EnvOwner>([ENV_OWNER.collab]),
    validate: (input: DoctorInput) => validateSchema(COLLAB_ENV_SCHEMA, input),
  },
  web: {
    examplePath: WEB_EXAMPLE_PATH,
    owners: new Set<EnvOwner>([ENV_OWNER.web]),
    validate: validateWebEnvironment,
  },
} as const satisfies Record<EnvApp, EnvAppConfig>;

const ENV_MODE = {
  development: "development",
  production: "production",
  test: "test",
} as const;
type EnvMode = (typeof ENV_MODE)[keyof typeof ENV_MODE];

const isEnvMode = (value: string): value is EnvMode =>
  Object.values(ENV_MODE).some((mode) => mode === value);

type ResolveDoctorModeOptions = {
  app: EnvApp;
  nodeEnv: string | undefined;
  requestedMode: EnvMode | undefined;
};

export const resolveDoctorMode = ({
  app,
  nodeEnv,
  requestedMode,
}: ResolveDoctorModeOptions): EnvMode | undefined => {
  if (requestedMode) {
    return requestedMode;
  }
  if (nodeEnv && isEnvMode(nodeEnv)) {
    return nodeEnv;
  }
  return app === ENV_APP.web ? ENV_MODE.development : undefined;
};

type ResolveDoctorProcessEnvironmentOptions = {
  environment: NodeJS.ProcessEnv;
  mode: EnvMode | undefined;
};

export const resolveDoctorProcessEnvironment = ({
  environment,
  mode,
}: ResolveDoctorProcessEnvironmentOptions): NodeJS.ProcessEnv =>
  mode ? { ...environment, NODE_ENV: mode } : environment;

type DoctorEnvFileNamesOptions = {
  app: EnvApp;
  mode: EnvMode | undefined;
};

export const doctorEnvFileNames = ({
  app,
  mode,
}: DoctorEnvFileNamesOptions) => {
  if (!mode) {
    return [".env", ".env.local"];
  }
  if (app === ENV_APP.web) {
    return [".env", ".env.local", `.env.${mode}`, `.env.${mode}.local`];
  }
  return [".env", `.env.${mode}`, ".env.local", `.env.${mode}.local`];
};

type ValidateDoctorEnvironmentOptions = {
  app: EnvApp;
  input: DoctorInput;
  mode?: EnvMode | undefined;
};

export const validateDoctorEnvironment = ({
  app,
  input,
  mode,
}: ValidateDoctorEnvironmentOptions): DoctorValidationResult => {
  const selectedInput =
    app === ENV_APP.api && mode ? { ...input, NODE_ENV: mode } : input;
  return ENV_APP_CONFIG[app].validate(normalizeEmptyEnvironment(selectedInput));
};

const runDoctor = (app: EnvApp, mode: EnvMode | undefined) => {
  const { examplePath, owners } = ENV_APP_CONFIG[app];
  const envDirectory = path.dirname(examplePath);
  const baseEnvPath = path.join(envDirectory, ".env");
  const envPaths = doctorEnvFileNames({ app, mode }).map((name) =>
    path.join(envDirectory, name),
  );
  const existingEnvPaths = envPaths.filter(existsSync);
  const doctorProcessEnvironment = resolveDoctorProcessEnvironment({
    environment: process.env,
    mode,
  });
  const fileValues = parseEnvLayers(
    existingEnvPaths.map((envPath) => readFileSync(envPath, "utf-8")),
    doctorProcessEnvironment,
  );
  const validation = validateDoctorEnvironment({
    app,
    input: { ...fileValues, ...doctorProcessEnvironment },
    mode,
  });
  const displayedEnvPaths = (
    existingEnvPaths.length > 0 ? existingEnvPaths : [baseEnvPath]
  ).map((envPath) => path.relative(REPO_ROOT, envPath));
  console.log(`Environment doctor: ${app} (${displayedEnvPaths.join(", ")})`);
  for (const entry of ENV_CATALOG.filter(
    ({ documented, owner }) => documented && owners.has(owner),
  )) {
    const value = validation.values[entry.name];
    console.log(
      `${entry.name}: ${formatEnvValue(entry, value)} [${sourceLabel(entry.name, fileValues)}; ${entry.exposure}]`,
    );
  }
  switch (validation.status) {
    case "valid":
      console.log(`${app}: valid`);
      return true;
    case "invalid":
      for (const issue of validation.issues) {
        console.error(issue);
      }
      return false;
    default: {
      const exhaustive: never = validation;
      return exhaustive;
    }
  }
};

const main = async () => {
  const command = process.argv.at(2);
  if (command === "generate") {
    generateEnvironmentArtifacts();
    return;
  }
  if (command === "check") {
    const buildArgsValid = checkWebBuildArgs();
    const artifactsValid = buildArgsValid && checkEnvironmentArtifacts();
    const auditValid = await auditEnvironment();
    if (!(artifactsValid && auditValid)) {
      process.exitCode = 1;
    }
    return;
  }
  if (command === "audit") {
    if (!(await auditEnvironment())) {
      process.exitCode = 1;
    }
    return;
  }
  if (command === "doctor") {
    const app = process.argv.at(3) ?? "api";
    const requestedMode = process.argv.at(4);
    if (
      !isEnvApp(app) ||
      (requestedMode !== undefined && !isEnvMode(requestedMode))
    ) {
      console.error(
        "Usage: bun run env:doctor [api|collab|web] [development|production|test]",
      );
      process.exitCode = 1;
      return;
    }
    const mode = resolveDoctorMode({
      app,
      nodeEnv: process.env.NODE_ENV,
      requestedMode,
    });
    if (!runDoctor(app, mode)) {
      process.exitCode = 1;
    }
    return;
  }
  console.error("Usage: env-tool.ts <generate|check|audit|doctor>");
  process.exitCode = 1;
};

if (import.meta.main) {
  await main();
}
