import { panic } from "better-result";
import { expect, test } from "bun:test";
import { existsSync, readFileSync } from "node:fs";
import { mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import nodePath from "node:path";
import { pathToFileURL } from "node:url";

import {
  GENERATORS,
  allowedOutputs,
  GUARD_A_EXCLUSIONS,
  generatorsForFiles,
  matchesGeneratedGlob,
  orderGenerators,
} from "./generated-files";
import {
  checkRouteGeneratorVersion,
  isGeneratedCandidate,
  isRegisteredGeneratedFile,
  isUnregisteredGeneratedFile,
  routeGeneratorVersionsMatch,
} from "./generated-files-guard";
import { isChangedLintPath } from "./lint-paths";

const generator = (id: string) => {
  const found = GENERATORS.find((entry) => entry.id === id);
  return found ?? panic(`Missing generator ${id}`);
};

test("Guard A rejects an unregistered generated source and ignores ordinary comments", () => {
  const unknown = "packages/example/src/unlisted.ts";
  expect(
    isGeneratedCandidate(unknown, "// Generated by a script\nexport {};"),
  ).toBe(true);
  expect(isRegisteredGeneratedFile(unknown)).toBe(false);
  expect(
    isUnregisteredGeneratedFile(
      unknown,
      "// Generated by a script\nexport {};",
    ),
  ).toBe(true);
  expect(isGeneratedCandidate("packages/example/src/unlisted.gen.ts", "")).toBe(
    true,
  );
  expect(
    isGeneratedCandidate(
      unknown,
      "// The generated output is consumed elsewhere.\nexport {};",
    ),
  ).toBe(false);
  for (const header of [
    "// @generated\nexport {};",
    "/* DO NOT EDIT. */\nexport {};",
    "# Generated by a script\nvalue: true",
  ]) {
    expect(isGeneratedCandidate(unknown, header)).toBe(true);
  }
  for (const header of [
    "// The generated output is consumed elsewhere.",
    "// This is generated test data.",
    "// Do not edit the input by hand.",
    `${"// ordinary\n".repeat(10)}// Generated by a script`,
  ]) {
    expect(isGeneratedCandidate(unknown, header)).toBe(false);
  }
  expect(isRegisteredGeneratedFile("apps/web/src/routeTree.gen.ts")).toBe(true);
  expect(isUnregisteredGeneratedFile("apps/web/src/routeTree.gen.ts", "")).toBe(
    false,
  );
  expect(isRegisteredGeneratedFile("apps/desktop/src-tauri/Cargo.lock")).toBe(
    true,
  );
});

test("CLI runtime outputs have one owner and stay ignored when regenerated", () => {
  const outputs = generator("cli-runtime").outputs;
  for (const output of outputs) {
    expect(
      GENERATORS.filter(({ outputs: ownerOutputs }) =>
        ownerOutputs.some((glob) => matchesGeneratedGlob(glob, output)),
      ).map(({ id }) => id),
    ).toEqual(["cli-runtime"]);
  }
  const ignored = Bun.spawnSync(
    ["git", "check-ignore", "--no-index", "--stdin"],
    {
      cwd: new URL("..", import.meta.url).pathname,
      stdin: new TextEncoder().encode(`${outputs.join("\n")}\n`),
      stdout: "pipe",
      stderr: "pipe",
    },
  );
  expect(ignored.exitCode).toBe(0);
  expect(
    new TextDecoder().decode(ignored.stdout).trim().split("\n").toSorted(),
  ).toEqual([...outputs].toSorted());
});

test("Guard A ignores hand-written certificate and error fixtures", async () => {
  for (const name of [
    "self-signed-certificate",
    "test-pki",
    "legacy-error-fields",
  ]) {
    const file = `apps/api/src/tests/helpers/${name}.ts`;
    const header = await Bun.file(file).slice(0, 4096).text();
    expect(isGeneratedCandidate(file, header), file).toBe(false);
  }
});

test("the route generator pin matches the plugin's resolved generator", () => {
  expect(
    routeGeneratorVersionsMatch(
      "1.167.38",
      "1.167.38",
      "@tanstack/router-generator@1.167.38",
    ),
  ).toBe(true);
  expect(
    routeGeneratorVersionsMatch(
      "1.167.39",
      "1.167.38",
      "@tanstack/router-generator@1.167.38",
    ),
  ).toBe(false);
  expect(
    routeGeneratorVersionsMatch(
      undefined,
      "1.167.38",
      "@tanstack/router-generator@1.167.38",
    ),
  ).toBe(false);
});

test("the route generator guard rejects missing script and direct pin", async () => {
  const directory = await mkdtemp(
    nodePath.join(tmpdir(), "route-generator-guard-"),
  );
  const web = nodePath.join(directory, "apps/web");
  const root = pathToFileURL(`${directory}/`);
  try {
    await mkdir(nodePath.join(web, "scripts"), { recursive: true });
    await writeFile(
      nodePath.join(web, "package.json"),
      '{"devDependencies":{}}',
    );
    await writeFile(
      nodePath.join(directory, "bun.lock"),
      JSON.stringify({
        packages: {
          "@tanstack/router-generator": ["@tanstack/router-generator@1.167.38"],
          "@tanstack/router-plugin": [
            "@tanstack/router-plugin@1.168.40",
            "",
            { dependencies: { "@tanstack/router-generator": "1.167.38" } },
          ],
        },
      }),
    );
    const missingScript = await checkRouteGeneratorVersion(root).catch(
      (error: unknown) => error,
    );
    expect(missingScript).toHaveProperty(
      "message",
      "The route-tree generator script is missing",
    );
    await writeFile(
      nodePath.join(web, "scripts/generate-route-tree.ts"),
      "export {};\n",
    );
    const missingPin = await checkRouteGeneratorVersion(root).catch(
      (error: unknown) => error,
    );
    expect(missingPin).toHaveProperty(
      "message",
      "The direct router-generator pin is missing",
    );
  } finally {
    await rm(directory, { recursive: true, force: true });
  }
});

test("autofix selects only owners of changed inputs and preserves dependencies", () => {
  const requiredIds = [
    "capability-catalog",
    "cli-registry",
    "cli-runtime",
    "mcp-surface",
  ] satisfies readonly (typeof GENERATORS)[number]["id"][];
  expect(
    generatorsForFiles(["apps/web/src/routes/law/index.tsx"]).map(
      ({ id }) => id,
    ),
  ).toEqual(["ratchet-improvements", "module-ownership", "route-tree"]);
  expect(generatorsForFiles(["docs/unrelated.md"]).map(({ id }) => id)).toEqual(
    ["ratchet-improvements"],
  );
  for (const file of [
    "apps/api/src/lib/format.ts",
    "packages/time/src/format.ts",
  ]) {
    const selected = new Set(generatorsForFiles([file]).map(({ id }) => id));
    for (const id of requiredIds) {
      expect(selected.has(id), `${file} selects ${id}`).toBe(true);
    }
  }
  const ordered = orderGenerators(
    generatorsForFiles(["apps/api/src/handlers/example.ts"]),
  );
  expect(
    ordered.findIndex(({ id }) => id === "capability-catalog"),
  ).toBeLessThan(ordered.findIndex(({ id }) => id === "cli-registry"));
  expect(ordered.findIndex(({ id }) => id === "cli-registry")).toBeLessThan(
    ordered.findIndex(({ id }) => id === "cli-runtime"),
  );
});

test("autofix selection closes over generated outputs and ordering dependencies", () => {
  const tracked = new TextDecoder()
    .decode(Bun.spawnSync(["git", "ls-files", "-z"], { stdout: "pipe" }).stdout)
    .split("\0")
    .filter(Boolean);
  const changedPaths = [
    [".oxfmtrc.json", "capability-catalog", "cli-registry", "cli-runtime"],
    [
      "packages/api-contract/src/mcp-tool.ts",
      "mcp-app-bundles",
      "capability-catalog",
    ],
  ] as const;
  for (const [file, ...required] of changedPaths) {
    const selected = generatorsForFiles([file]);
    const ids = new Set(selected.map(({ id }) => id));
    for (const id of required) {
      expect(ids.has(id), `${file} selects ${id}`).toBe(true);
    }
    for (const upstream of selected) {
      for (const downstream of GENERATORS.filter(({ autofix }) => autofix)) {
        if (downstream.after.some((id) => id === upstream.id)) {
          expect(
            ids.has(downstream.id),
            `${upstream.id} feeds ${downstream.id}`,
          ).toBe(true);
        }
        for (const output of upstream.outputs) {
          const feedsDownstream = tracked.some(
            (outputFile) =>
              matchesGeneratedGlob(output, outputFile) &&
              downstream.inputs.some((input) =>
                matchesGeneratedGlob(input, outputFile),
              ),
          );
          if (feedsDownstream) {
            expect(
              ids.has(downstream.id),
              `${output} feeds ${downstream.id}`,
            ).toBe(true);
          }
        }
      }
    }
  }
});

test("the planned allowlist is exactly the selected committed output union", () => {
  for (const paths of [
    ".oxfmtrc.json\n",
    "packages/api-contract/src/mcp-tool.ts\n",
    "docs/unrelated.md\n",
  ]) {
    const plan = Bun.spawnSync(["bun", "scripts/autofix-plan.ts", "plan"], {
      stdin: new TextEncoder().encode(paths),
      stdout: "pipe",
      stderr: "pipe",
    });
    expect(plan.exitCode).toBe(0);
    const values = Object.fromEntries(
      new TextDecoder()
        .decode(plan.stdout)
        .trim()
        .split("\n")
        .map((line) => line.split("=", 2)),
    );
    const selected = generatorsForFiles(paths.trim().split("\n"));
    expect(values["ids"]?.split(",").filter(Boolean).toSorted()).toEqual(
      selected.map(({ id }) => id).toSorted(),
    );
    expect(values["allowed"]?.split("|").filter(Boolean).toSorted()).toEqual(
      allowedOutputs(selected).toSorted(),
    );
  }
});

test("manifest paths and named guards resolve against tracked files and CI", async () => {
  const tracked = new TextDecoder()
    .decode(Bun.spawnSync(["git", "ls-files", "-z"], { stdout: "pipe" }).stdout)
    .split("\0")
    .filter(Boolean);
  const steps = new Set(
    [...ci.matchAll(/^\s+- name: (.+)$/gmu)].map((match) => match[1]),
  );
  for (const entry of GENERATORS) {
    for (const glob of entry.inputs) {
      expect(
        tracked.some((file) => matchesGeneratedGlob(glob, file)),
        `${entry.id}: ${glob}`,
      ).toBe(true);
    }
    for (const glob of entry.outputs) {
      const isTracked = tracked.some((file) =>
        matchesGeneratedGlob(glob, file),
      );
      switch (entry.outputKind) {
        case "committed":
          expect(isTracked, `${entry.id}: ${glob}`).toBe(true);
          break;
        case "derived": {
          expect(isTracked, `${entry.id}: ${glob} must stay untracked`).toBe(
            false,
          );
          const ignored = Bun.spawnSync(
            ["git", "check-ignore", "--no-index", "--", glob],
            { stdout: "pipe", stderr: "pipe" },
          );
          expect(ignored.exitCode, `${entry.id}: ${glob} must be ignored`).toBe(
            0,
          );
          expect(allowedOutputs([entry])).not.toContain(glob);
          break;
        }
        default:
          entry satisfies never;
      }
    }
    if ("checkedBy" in entry) {
      expect(
        steps.has(entry.checkedBy),
        `${entry.id}: ${entry.checkedBy}`,
      ).toBe(true);
    }
    expect(entry.outputs.every((glob) => !/[|\n]/u.test(glob))).toBe(true);
    const scriptFile = entry.write.find((part) => /\.(?:ts|sh)$/u.test(part));
    if (scriptFile) {
      expect(existsSync(scriptFile), `${entry.id}: ${scriptFile}`).toBe(true);
      continue;
    }
    const write: readonly string[] = entry.write;
    const filter = write.indexOf("--filter");
    const cwd = write.find((part) => part.startsWith("--cwd="));
    let packagePath = cwd?.replace("--cwd=", "") ?? ".";
    if (filter !== -1) {
      packagePath = (write[filter + 1] ?? "").replace("@stll/", "");
    }
    let root = packagePath;
    if (packagePath !== "." && !packagePath.includes("/")) {
      root =
        ["apps", "packages"]
          .map((dir) => `${dir}/${packagePath}`)
          .find((path) => existsSync(`${path}/package.json`)) ?? packagePath;
    }
    const packageJson = await Bun.file(`${root}/package.json`).json();
    const run = write.indexOf("run");
    const script = run !== -1 ? write[run + 1] : write[filter + 2];
    expect(script, `${entry.id} has a script`).toBeDefined();
    if (script === undefined) {
      continue;
    }
    expect(
      packageJson.scripts?.[script],
      `${entry.id}: ${script}`,
    ).toBeDefined();
  }
  for (const { glob } of GUARD_A_EXCLUSIONS) {
    expect(
      tracked.some((file) => matchesGeneratedGlob(glob, file)),
      glob,
    ).toBe(true);
  }
});

test("the plan alone never authorizes the ratchet baseline", () => {
  const selected = generatorsForFiles(["apps/web/src/example.ts"]);
  expect(selected.some(({ id }) => id === "ratchet-improvements")).toBe(true);
  expect(allowedOutputs(selected)).not.toContain(
    "scripts/ratchet-baseline.json",
  );
  expect(
    allowedOutputs([
      {
        ...generator("ratchet-improvements"),
        outputs: ["scripts/**", "scripts/ratchet-baseline.json"],
      },
    ]),
  ).not.toContain("scripts/ratchet-baseline.json");
});

test("autofix refuses an empty selected-generator handoff", () => {
  const run = Bun.spawnSync(["bun", "scripts/autofix-plan.ts", "allowed", ""], {
    stdout: "pipe",
    stderr: "pipe",
  });
  expect(run.exitCode).toBe(1);
  expect(new TextDecoder().decode(run.stderr)).toContain(
    "Autofix plan has no selected generators",
  );
});

test("lint selection derives generated outputs from the manifest", () => {
  expect(isChangedLintPath("apps/web/src/routeTree.gen.ts")).toBe(false);
  expect(isChangedLintPath("packages/skills/src/blueprints.gen.ts")).toBe(
    false,
  );
  expect(isChangedLintPath("apps/web/src/routes/new.gen.ts")).toBe(true);
  expect(isChangedLintPath("apps/web/public/prepaint-init.js")).toBe(true);
  expect(
    isChangedLintPath(
      "apps/api/src/lib/legal-search/morphology/snowball/__fixtures__/vocabulary.ts",
    ),
  ).toBe(true);
});

const ci = readFileSync(
  new URL("../.github/workflows/ci.yml", import.meta.url),
  "utf-8",
);

const casePatternsAfter = (marker: string) => {
  const section = ci.slice(ci.indexOf(marker));
  const match = /case "\$file" in\n\s+([^\n]+)\)/u.exec(section);
  expect(match, marker).not.toBeNull();
  return (match?.[1] ?? "").split("|");
};

test("CI path cases stay pinned to the manifest", () => {
  for (const [id, marker] of [
    ["web-api-types", "# The web API types drift guard"],
    ["model-rates", "# The committed rate and capability snapshots"],
  ] as const) {
    const inputs = generator(id).inputs.map((glob) =>
      glob.replace(/\/\*\*$/u, "/*"),
    );
    expect(casePatternsAfter(marker).toSorted(), id).toEqual(inputs.toSorted());
  }
});

test("route-tree CI scope covers every manifest input and output", () => {
  const routeTree = generator("route-tree");
  const paths = [...routeTree.inputs, ...routeTree.outputs].map((glob) =>
    glob.replace(/\/\*\*$/u, "/*"),
  );
  expect(
    casePatternsAfter(
      "# The route-tree generator reads the web package script",
    ).toSorted(),
  ).toEqual(paths.toSorted());
});

test("CI diff path guards stay pinned to manifest outputs", () => {
  const cli = ci.slice(
    ci.indexOf("- name: CLI committed registry and derived runtime guard"),
    ci.indexOf("- name: MCP App bundle guard"),
  );
  const diff = cli.split("git diff --exit-code -- \\\n")[1];
  expect(diff).toBeDefined();
  const paths: string[] = [];
  for (const line of (diff ?? "").split("\n")) {
    const argument = line.trim();
    paths.push(argument.replace(/ \\$/u, ""));
    if (!argument.endsWith("\\")) {
      break;
    }
  }
  expect(paths.toSorted()).toEqual(
    generator("cli-registry")
      .outputs.map((glob) => glob.replace(/\/\*\*$/u, ""))
      .toSorted(),
  );
  const bundle = ci.slice(ci.indexOf("- name: MCP App bundle guard"));
  expect(bundle).toContain(
    `git diff --exit-code -- "${generator("mcp-app-bundles").outputs[0]}"`,
  );
});
