import { panic } from "better-result";
import { expect, test } from "bun:test";
import { existsSync, readFileSync } from "node:fs";
import { mkdir, mkdtemp, readdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import nodePath from "node:path";
import { pathToFileURL } from "node:url";
import * as v from "valibot";

import { generateCapabilityRuntime } from "../apps/api/scripts/generate-capability-runtime";
import {
  GENERATORS,
  CI_GENERATED_FILES,
  allowedOutputs,
  GUARD_A_EXCLUSIONS,
  generatorsForFiles,
  matchesGeneratedGlob,
  orderGenerators,
} from "./generated-files";
import {
  checkRouteGeneratorVersion,
  isGeneratedCandidate,
  isRegisteredGeneratedFile,
  isUnregisteredGeneratedFile,
  routeGeneratorVersionsMatch,
} from "./generated-files-guard";
import { isChangedLintPath } from "./lint-paths";
import { workflowJobSteps, workflowStepByName } from "./workflow-steps";

const generator = (id: string) => {
  const found = GENERATORS.find((entry) => entry.id === id);
  return found ?? panic(`Missing generator ${id}`);
};

test("generation owners have unique identifiers", () => {
  const ids = GENERATORS.map(({ id }) => id);
  expect(new Set(ids).size).toBe(ids.length);
});

test("visual source changes select the frame bundle before API catalog generation", () => {
  const selected = orderGenerators(
    generatorsForFiles([
      "apps/api/src/handlers/visual-sandbox/browser/runtime.ts",
    ]),
  );
  const ids = selected.map(({ id }) => id);
  expect(ids).toContain("visual-sandbox-bundle");
  expect(ids.indexOf("visual-sandbox-bundle")).toBeLessThan(
    ids.indexOf("capability-catalog"),
  );
  expect(generator("visual-sandbox-bundle").outputs).toEqual([
    "apps/api/src/handlers/visual-sandbox/generated/runtime.js.txt",
  ]);
});

test("generation metadata loads without dependencies in a reduced checkout", async () => {
  const directory = await mkdtemp(
    nodePath.join(tmpdir(), "generation-metadata-"),
  );
  try {
    const registry = nodePath.join(directory, "scripts/generated-files.ts");
    await mkdir(nodePath.dirname(registry), { recursive: true });
    const inventory = nodePath.join(
      directory,
      "packages/scripts/src/generated-files.ts",
    );
    await mkdir(nodePath.dirname(inventory), { recursive: true });
    await writeFile(
      inventory,
      readFileSync(
        new URL("../packages/scripts/src/generated-files.ts", import.meta.url),
        "utf-8",
      ),
    );
    const source = readFileSync(
      new URL("generated-files.ts", import.meta.url),
      "utf-8",
    );
    await writeFile(registry, source);
    const load = () =>
      Bun.spawnSync(
        [
          process.execPath,
          "-e",
          "const metadata = await import(process.argv[1]); console.log(metadata.CI_GENERATED_FILES.length);",
          registry,
        ],
        { cwd: directory },
      );
    const ordinary = load();
    expect(ordinary.exitCode, ordinary.stderr.toString()).toBe(0);
    expect(ordinary.stdout.toString().trim()).toBe(
      String(CI_GENERATED_FILES.length),
    );
    await writeFile(
      registry,
      `import "../packages/scripts/src/prepared-generated-sources";\n${source}`,
    );
    const misplaced = load();
    expect(misplaced.exitCode).not.toBe(0);
    expect(misplaced.stderr.toString()).toContain("prepared-generated-sources");
  } finally {
    await rm(directory, { recursive: true, force: true });
  }
});

test("Guard A rejects an unregistered generated source and ignores ordinary comments", () => {
  const unknown = "packages/example/src/unlisted.ts";
  expect(
    isGeneratedCandidate(unknown, "// Generated by a script\nexport {};"),
  ).toBe(true);
  expect(isRegisteredGeneratedFile(unknown)).toBe(false);
  expect(
    isUnregisteredGeneratedFile(
      unknown,
      "// Generated by a script\nexport {};",
    ),
  ).toBe(true);
  expect(isGeneratedCandidate("packages/example/src/unlisted.gen.ts", "")).toBe(
    true,
  );
  expect(
    isGeneratedCandidate(
      unknown,
      "// The generated output is consumed elsewhere.\nexport {};",
    ),
  ).toBe(false);
  for (const header of [
    "// @generated\nexport {};",
    "/* DO NOT EDIT. */\nexport {};",
    "# Generated by a script\nvalue: true",
  ]) {
    expect(isGeneratedCandidate(unknown, header)).toBe(true);
  }
  for (const header of [
    "// The generated output is consumed elsewhere.",
    "// This is generated test data.",
    "// Do not edit the input by hand.",
    `${"// ordinary\n".repeat(10)}// Generated by a script`,
  ]) {
    expect(isGeneratedCandidate(unknown, header)).toBe(false);
  }
  expect(isRegisteredGeneratedFile("apps/web/src/routeTree.gen.ts")).toBe(true);
  expect(isUnregisteredGeneratedFile("apps/web/src/routeTree.gen.ts", "")).toBe(
    false,
  );
  expect(isRegisteredGeneratedFile("apps/desktop/src-tauri/Cargo.lock")).toBe(
    true,
  );
});

test("capability shard additions are registered and feed CLI generation", () => {
  const catalogShard = "packages/cli/capabilities/matters.list.json";
  const dispatchShard =
    "apps/api/src/mcp/generated/capability-dispatch/matters.list.ts";
  expect(isRegisteredGeneratedFile(catalogShard)).toBe(true);
  expect(isRegisteredGeneratedFile(dispatchShard)).toBe(true);
  expect(generatorsForFiles([catalogShard]).map(({ id }) => id)).toContain(
    "cli-registry",
  );
  expect(generatorsForFiles([catalogShard]).map(({ id }) => id)).toContain(
    "cli-runtime",
  );
  expect(generator("capability-catalog").outputs).not.toContain(
    "apps/api/src/mcp/generated/capability-dispatch.ts",
  );
});

test("derived runtime outputs have one owner and stay ignored when regenerated", () => {
  for (const id of ["capability-runtime", "cli-runtime"] as const) {
    const outputs = generator(id).outputs;
    for (const output of outputs) {
      expect(
        GENERATORS.filter(({ outputs: ownerOutputs }) =>
          ownerOutputs.some((glob) => matchesGeneratedGlob(glob, output)),
        ).map((owner) => owner.id),
        output,
      ).toEqual([id]);
    }
    const ignored = Bun.spawnSync(
      ["git", "check-ignore", "--no-index", "--stdin"],
      {
        cwd: new URL("..", import.meta.url).pathname,
        stdin: new TextEncoder().encode(`${outputs.join("\n")}\n`),
        stdout: "pipe",
        stderr: "pipe",
      },
    );
    expect(ignored.exitCode, id).toBe(0);
    expect(
      new TextDecoder().decode(ignored.stdout).trim().split("\n").toSorted(),
      id,
    ).toEqual([...outputs].toSorted());
  }
});

test("capability runtime cache manifests cover every file the producer writes", async () => {
  const fixture = await mkdtemp(nodePath.join(tmpdir(), "capability-outputs-"));
  try {
    const generated = nodePath.join(fixture, "apps/api/src/mcp/generated");
    const catalog = nodePath.join(fixture, "packages/cli/capabilities");
    await mkdir(nodePath.join(generated, "capability-dispatch"), {
      recursive: true,
    });
    await mkdir(catalog, { recursive: true });
    await writeFile(
      nodePath.join(catalog, "matters.list.json"),
      JSON.stringify({ id: "matters.list", featureId: "matters" }),
    );
    await writeFile(
      nodePath.join(generated, "capability-dispatch/matters.list.ts"),
      "export const CAPABILITY_DISPATCH = {};\n",
    );
    await generateCapabilityRuntime(pathToFileURL(`${fixture}/`));
    const outputs = (await readdir(generated))
      .filter((file) => file.endsWith(".ts"))
      .map((file) => `src/mcp/generated/${file}`)
      .toSorted();
    expect(outputs.length).toBeGreaterThan(0);
    expect(outputs.map((file) => `apps/api/${file}`)).toEqual(
      generator("capability-runtime").outputs.toSorted(),
    );
    const config = v.parse(
      v.object({
        tasks: v.record(
          v.string(),
          v.looseObject({
            outputs: v.optional(v.array(v.string())),
            inputs: v.optional(v.array(v.string())),
            dependsOn: v.optional(v.array(v.string())),
          }),
        ),
      }),
      Bun.JSONC.parse(
        readFileSync(new URL("../turbo.json", import.meta.url), "utf-8"),
      ),
    );
    const assertOutputs = (tasks: typeof config.tasks) => {
      expect(
        tasks["@stll/api#generate:capability-runtime"]?.outputs?.toSorted(),
      ).toEqual(outputs);
      for (const output of outputs) {
        expect(tasks["@stll/api#typecheck"]?.outputs).toContain(output);
        expect(tasks["@stll/web#generate:api-types"]?.inputs).toContain(
          `!$TURBO_ROOT$/apps/api/${output}`,
        );
      }
    };
    assertOutputs(config.tasks);
    for (const output of outputs) {
      const mutated = structuredClone(config.tasks);
      const web = mutated["@stll/web#generate:api-types"];
      if (web?.inputs === undefined) {
        panic("Missing web API generation inputs");
      }
      const originalLength = web.inputs.length;
      web.inputs = web.inputs.filter(
        (input) => input !== `!$TURBO_ROOT$/apps/api/${output}`,
      );
      expect(web.inputs.length).toBe(originalLength - 1);
      expect(() => assertOutputs(mutated)).toThrow("toContain");
    }
    for (const task of [
      "@stll/api#generate:capability-runtime",
      "@stll/api#typecheck",
    ]) {
      for (const output of outputs) {
        const mutated = structuredClone(config.tasks);
        const body = mutated[task];
        if (!body?.outputs) {
          panic(`Missing capability cache output fixture: ${task}`);
        }
        body.outputs = body.outputs.filter((file) => file !== output);
        expect(() => assertOutputs(mutated)).toThrow("expect(received)");
      }
    }
  } finally {
    await rm(fixture, { recursive: true, force: true });
  }
});

test("Guard A ignores hand-written certificate and error fixtures", async () => {
  for (const name of [
    "self-signed-certificate",
    "test-pki",
    "legacy-error-fields",
  ]) {
    const file = `apps/api/src/tests/helpers/${name}.ts`;
    const header = await Bun.file(file).slice(0, 4096).text();
    expect(isGeneratedCandidate(file, header), file).toBe(false);
  }
});

test("the route generator pin matches the plugin's resolved generator", () => {
  expect(
    routeGeneratorVersionsMatch(
      "1.167.38",
      "1.167.38",
      "@tanstack/router-generator@1.167.38",
    ),
  ).toBe(true);
  expect(
    routeGeneratorVersionsMatch(
      "1.167.39",
      "1.167.38",
      "@tanstack/router-generator@1.167.38",
    ),
  ).toBe(false);
  expect(
    routeGeneratorVersionsMatch(
      undefined,
      "1.167.38",
      "@tanstack/router-generator@1.167.38",
    ),
  ).toBe(false);
});

test("the route generator guard rejects missing script and direct pin", async () => {
  const directory = await mkdtemp(
    nodePath.join(tmpdir(), "route-generator-guard-"),
  );
  const web = nodePath.join(directory, "apps/web");
  const root = pathToFileURL(`${directory}/`);
  try {
    await mkdir(nodePath.join(web, "scripts"), { recursive: true });
    await writeFile(
      nodePath.join(web, "package.json"),
      '{"devDependencies":{}}',
    );
    await writeFile(
      nodePath.join(directory, "bun.lock"),
      JSON.stringify({
        packages: {
          "@tanstack/router-generator": ["@tanstack/router-generator@1.167.38"],
          "@tanstack/router-plugin": [
            "@tanstack/router-plugin@1.168.40",
            "",
            { dependencies: { "@tanstack/router-generator": "1.167.38" } },
          ],
        },
      }),
    );
    const missingScript = await checkRouteGeneratorVersion(root).catch(
      (error: unknown) => error,
    );
    expect(missingScript).toHaveProperty(
      "message",
      "The route-tree generator script is missing",
    );
    await writeFile(
      nodePath.join(web, "scripts/generate-route-tree.ts"),
      "export {};\n",
    );
    const missingPin = await checkRouteGeneratorVersion(root).catch(
      (error: unknown) => error,
    );
    expect(missingPin).toHaveProperty(
      "message",
      "The direct router-generator pin is missing",
    );
  } finally {
    await rm(directory, { recursive: true, force: true });
  }
});

test("autofix selects only owners of changed inputs and preserves dependencies", () => {
  const requiredIds = [
    "capability-catalog",
    "capability-runtime",
    "cli-registry",
    "cli-runtime",
    "mcp-surface",
  ] satisfies readonly (typeof GENERATORS)[number]["id"][];
  expect(
    generatorsForFiles(["apps/web/src/routes/law/index.tsx"]).map(
      ({ id }) => id,
    ),
  ).toEqual(["module-ownership", "route-tree"]);
  expect(
    generatorsForFiles(["scripts/ownership/new-capability.ts"]).map(
      ({ id }) => id,
    ),
  ).toEqual(["module-ownership"]);
  expect(generatorsForFiles(["docs/unrelated.md"]).map(({ id }) => id)).toEqual(
    [],
  );
  for (const file of [
    "apps/api/src/lib/format.ts",
    "packages/time/src/format.ts",
  ]) {
    const selected = new Set(generatorsForFiles([file]).map(({ id }) => id));
    for (const id of requiredIds) {
      expect(selected.has(id), `${file} selects ${id}`).toBe(true);
    }
  }
  const ordered = orderGenerators(
    generatorsForFiles(["apps/api/src/handlers/example.ts"]),
  );
  expect(
    ordered.findIndex(({ id }) => id === "capability-catalog"),
  ).toBeLessThan(ordered.findIndex(({ id }) => id === "capability-runtime"));
  expect(
    ordered.findIndex(({ id }) => id === "capability-runtime"),
  ).toBeLessThan(ordered.findIndex(({ id }) => id === "cli-registry"));
  expect(ordered.findIndex(({ id }) => id === "cli-registry")).toBeLessThan(
    ordered.findIndex(({ id }) => id === "cli-runtime"),
  );
});

test("autofix selection closes over generated outputs and ordering dependencies", () => {
  const tracked = new TextDecoder()
    .decode(Bun.spawnSync(["git", "ls-files", "-z"], { stdout: "pipe" }).stdout)
    .split("\0")
    .filter(Boolean);
  const changedPaths = [
    [
      ".oxfmtrc.json",
      "capability-catalog",
      "capability-runtime",
      "cli-registry",
      "cli-runtime",
    ],
    [
      "packages/api-contract/src/mcp-tool.ts",
      "mcp-app-bundles",
      "capability-catalog",
    ],
  ] as const;
  for (const [file, ...required] of changedPaths) {
    const selected = generatorsForFiles([file]);
    const ids = new Set(selected.map(({ id }) => id));
    for (const id of required) {
      expect(ids.has(id), `${file} selects ${id}`).toBe(true);
    }
    for (const upstream of selected) {
      for (const downstream of GENERATORS.filter(({ autofix }) => autofix)) {
        if (downstream.after.some((id) => id === upstream.id)) {
          expect(
            ids.has(downstream.id),
            `${upstream.id} feeds ${downstream.id}`,
          ).toBe(true);
        }
        for (const output of upstream.outputs) {
          const feedsDownstream = tracked.some(
            (outputFile) =>
              matchesGeneratedGlob(output, outputFile) &&
              downstream.inputs.some((input) =>
                matchesGeneratedGlob(input, outputFile),
              ),
          );
          if (feedsDownstream) {
            expect(
              ids.has(downstream.id),
              `${output} feeds ${downstream.id}`,
            ).toBe(true);
          }
        }
      }
    }
  }
});

test("the planned allowlist is exactly the selected committed output union", () => {
  for (const paths of [
    ".oxfmtrc.json\n",
    "packages/api-contract/src/mcp-tool.ts\n",
    "docs/unrelated.md\n",
  ]) {
    const plan = Bun.spawnSync(["bun", "scripts/autofix-plan.ts", "plan"], {
      stdin: new TextEncoder().encode(paths),
      stdout: "pipe",
      stderr: "pipe",
    });
    expect(plan.exitCode).toBe(0);
    const values = Object.fromEntries(
      new TextDecoder()
        .decode(plan.stdout)
        .trim()
        .split("\n")
        .map((line) => line.split("=", 2)),
    );
    const selected = generatorsForFiles(paths.trim().split("\n"));
    expect(values["ids"]?.split(",").filter(Boolean).toSorted()).toEqual(
      selected.map(({ id }) => id).toSorted(),
    );
    expect(values["allowed"]?.split("|").filter(Boolean).toSorted()).toEqual(
      allowedOutputs(selected).toSorted(),
    );
  }
});

test("manifest paths and named guards resolve against tracked files and CI", async () => {
  const tracked = new TextDecoder()
    .decode(Bun.spawnSync(["git", "ls-files", "-z"], { stdout: "pipe" }).stdout)
    .split("\0")
    .filter(Boolean);
  const steps = new Set(
    [...ci.matchAll(/^\s+- name: (.+)$/gmu)].map((match) => match[1]),
  );
  for (const entry of GENERATORS) {
    for (const glob of entry.inputs) {
      expect(
        tracked.some((file) => matchesGeneratedGlob(glob, file)),
        `${entry.id}: ${glob}`,
      ).toBe(true);
    }
    for (const glob of entry.outputs) {
      const isTracked = tracked.some((file) =>
        matchesGeneratedGlob(glob, file),
      );
      switch (entry.outputKind) {
        case "committed":
          expect(isTracked, `${entry.id}: ${glob}`).toBe(true);
          break;
        case "derived": {
          expect(isTracked, `${entry.id}: ${glob} must stay untracked`).toBe(
            false,
          );
          const ignored = Bun.spawnSync(
            ["git", "check-ignore", "--no-index", "--", glob],
            { stdout: "pipe", stderr: "pipe" },
          );
          expect(ignored.exitCode, `${entry.id}: ${glob} must be ignored`).toBe(
            0,
          );
          expect(allowedOutputs([entry])).not.toContain(glob);
          break;
        }
        default:
          entry satisfies never;
      }
    }
    if ("checkedBy" in entry) {
      expect(
        steps.has(entry.checkedBy),
        `${entry.id}: ${entry.checkedBy}`,
      ).toBe(true);
    }
    expect(entry.outputs.every((glob) => !/[|\n]/u.test(glob))).toBe(true);
    const scriptFile = entry.write.find((part) => /\.(?:ts|sh)$/u.test(part));
    if (scriptFile) {
      expect(existsSync(scriptFile), `${entry.id}: ${scriptFile}`).toBe(true);
      continue;
    }
    const write: readonly string[] = entry.write;
    const filter = write.indexOf("--filter");
    const cwd = write.find((part) => part.startsWith("--cwd="));
    let packagePath = cwd?.replace("--cwd=", "") ?? ".";
    if (filter !== -1) {
      packagePath = (write[filter + 1] ?? "").replace("@stll/", "");
    }
    let root = packagePath;
    if (packagePath !== "." && !packagePath.includes("/")) {
      root =
        ["apps", "packages"]
          .map((dir) => `${dir}/${packagePath}`)
          .find((path) => existsSync(`${path}/package.json`)) ?? packagePath;
    }
    const packageJson = await Bun.file(`${root}/package.json`).json();
    const run = write.indexOf("run");
    const script = run !== -1 ? write[run + 1] : write[filter + 2];
    expect(script, `${entry.id} has a script`).toBeDefined();
    if (script === undefined) {
      continue;
    }
    expect(
      packageJson.scripts?.[script],
      `${entry.id}: ${script}`,
    ).toBeDefined();
  }
  for (const { glob } of GUARD_A_EXCLUSIONS) {
    expect(
      tracked.some((file) => matchesGeneratedGlob(glob, file)),
      glob,
    ).toBe(true);
  }
});

test("the plan alone never authorizes the ratchet baseline", () => {
  const selected = generatorsForFiles(["apps/web/src/example.ts"]);
  expect(allowedOutputs(selected)).not.toContain(
    "scripts/ratchet-baseline.json",
  );
});

test("autofix refuses an empty selected-generator handoff", () => {
  const run = Bun.spawnSync(["bun", "scripts/autofix-plan.ts", "allowed", ""], {
    stdout: "pipe",
    stderr: "pipe",
  });
  expect(run.exitCode).toBe(1);
  expect(new TextDecoder().decode(run.stderr)).toContain(
    "Autofix plan has no selected generators",
  );
});

test("lint selection derives committed generated outputs from the manifest", () => {
  expect(isChangedLintPath("apps/web/src/routeTree.gen.ts")).toBe(false);
  expect(isChangedLintPath("packages/skills/src/blueprints.gen.ts")).toBe(
    false,
  );
  expect(isChangedLintPath("apps/web/src/routes/new.gen.ts")).toBe(true);
  expect(isChangedLintPath("apps/web/public/prepaint-init.js")).toBe(true);
  expect(
    isChangedLintPath(
      "apps/api/src/lib/legal-search/morphology/snowball/__fixtures__/vocabulary.ts",
    ),
  ).toBe(true);
});

const ci = readFileSync(
  new URL("../.github/workflows/ci.yml", import.meta.url),
  "utf-8",
);
const ciGeneratedSteps = workflowJobSteps(
  Bun.YAML.parse(ci),
  "ci-checks-generated",
);
const ciGeneratedStepRun = (name: string): string => {
  const run = workflowStepByName(ciGeneratedSteps, name)["run"];
  if (typeof run !== "string") {
    panic(`CI step ${name} has no run command`);
  }
  return run;
};

const casePatternsAfter = (marker: string) => {
  const section = ci.slice(ci.indexOf(marker));
  const match = /case "\$file" in\n\s+([^\n]+)\)/u.exec(section);
  expect(match, marker).not.toBeNull();
  return (match?.[1] ?? "").split("|");
};

test("route-tree CI scope covers every manifest input and output", () => {
  const routeTree = generator("route-tree");
  const paths = [...routeTree.inputs, ...routeTree.outputs].map((glob) =>
    glob.replace(/\/\*\*$/u, "/*"),
  );
  expect(
    casePatternsAfter(
      "# The route-tree generator reads the web package script",
    ).toSorted(),
  ).toEqual(paths.toSorted());
});

test("CI rate snapshot scope stays pinned to the manifest", () => {
  const inputs = generator("model-rates").inputs.map((glob) =>
    glob.replace(/\/\*\*$/u, "/*"),
  );
  expect(
    casePatternsAfter(
      "# The committed rate and capability snapshots",
    ).toSorted(),
  ).toEqual(inputs.toSorted());
});

const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === "object" && value !== null && !Array.isArray(value);

const generationInputs = (name: string) => {
  const config: unknown = Bun.JSONC.parse(
    readFileSync(new URL("../turbo.json", import.meta.url), "utf-8"),
  );
  if (!isRecord(config) || !isRecord(config["tasks"])) {
    panic("Turbo configuration has no tasks");
  }
  const task = config["tasks"][`@stll/web#${name}`];
  if (!isRecord(task) || !Array.isArray(task["inputs"])) {
    panic(`Missing generation task inputs for ${name}`);
  }
  return task["inputs"]
    .map((input: unknown) => {
      if (typeof input !== "string") {
        panic("Generation task input must be a glob");
      }
      return input;
    })
    .filter((input) => !input.startsWith("!"));
};

test("CI determinism selectors cover the cached generators' input contracts", () => {
  for (const [name, marker] of [
    ["generate:api-types", "# The web API types"],
    ["generate:route-tree", "# The route-tree generator"],
  ] as const) {
    const selectors = casePatternsAfter(marker);
    for (const glob of generationInputs(name)) {
      const rooted = glob.startsWith("$TURBO_ROOT$/")
        ? glob.replace("$TURBO_ROOT$/", "")
        : `apps/web/${glob}`;
      // Shell case * crosses directory separators, unlike Bun.Glob's *.
      const sample = rooted
        .replace(/\*\*/gu, "nested")
        .replace(/\*/gu, "fixture")
        .replace(/\?/gu, "x");
      expect(
        selectors.some((selector) =>
          new Bun.Glob(selector.replace(/\*+/gu, "**")).match(sample),
        ),
        `${name} CI selector covers ${rooted}`,
      ).toBe(true);
    }
  }
});

test("CI diff path guards stay pinned to manifest outputs", () => {
  const cli = ciGeneratedStepRun(
    "CLI sharded registry and derived runtime guard",
  );
  const diff = cli.split("git diff --exit-code -- \\\n")[1];
  expect(diff).toBeDefined();
  const paths: string[] = [];
  for (const line of (diff ?? "").split("\n")) {
    const argument = line.trim();
    paths.push(argument.replace(/ \\$/u, ""));
    if (!argument.endsWith("\\")) {
      break;
    }
  }
  expect(paths.toSorted()).toEqual(
    generator("cli-registry")
      .outputs.map((glob) => glob.replace(/\/\*\*$/u, ""))
      .toSorted(),
  );
  const bundle = ciGeneratedStepRun(
    "MCP app package bundles and shared assets guard",
  );
  const bundleOutputs = generator("mcp-app-bundles")
    .outputs.map((glob) => `"${glob}"`)
    .join(" ");
  expect(bundle).toContain(`git diff --exit-code -- ${bundleOutputs}`);
});

test("route tree has one derived owner and a cache producer for every consumer", () => {
  const owner = generator("route-tree");
  expect(owner.outputKind).toBe("derived");
  const config = v.parse(
    v.object({
      tasks: v.record(
        v.string(),
        v.looseObject({
          dependsOn: v.optional(v.array(v.string())),
          outputs: v.optional(v.array(v.string())),
        }),
      ),
    }),
    Bun.JSONC.parse(
      readFileSync(new URL("../turbo.json", import.meta.url), "utf-8"),
    ),
  );
  const output = "apps/web/src/routeTree.gen.ts";
  expect(
    GENERATORS.filter(({ outputs }) =>
      outputs.some((file) => file === output),
    ).map(({ id }) => id),
  ).toEqual([owner.id]);
  const ignored = Bun.spawnSync(["git", "check-ignore", "--no-index", output]);
  expect(ignored.exitCode).toBe(0);
  const producer = config.tasks["@stll/web#generate:route-tree"];
  expect(producer?.outputs).toEqual(["src/routeTree.gen.ts"]);
  expect(
    generationInputs("generate:route-tree")
      .map((input) =>
        input.startsWith("$TURBO_ROOT$/")
          ? input.replace("$TURBO_ROOT$/", "")
          : `apps/web/${input}`,
      )
      .toSorted(),
  ).toEqual([...owner.inputs].toSorted());
  for (const name of [
    "typecheck",
    "lint",
    "lint:fix",
    "test",
    "test:property",
    "build",
    "dev",
  ]) {
    expect(config.tasks[`@stll/web#${name}`]?.dependsOn, name).toContain(
      "generate:route-tree",
    );
  }
});

test("the fresh-export proof runs nightly and alone on dispatch", () => {
  const workflow = v.parse(
    v.object({ jobs: v.record(v.string(), v.looseObject({ if: v.string() })) }),
    Bun.YAML.parse(
      readFileSync(
        new URL("../.github/workflows/nightly-typecheck.yml", import.meta.url),
        "utf-8",
      ),
    ),
  );
  expect(workflow.jobs["fresh-web-sources"]?.if).toBe(
    `\${{ github.event_name == 'schedule' || inputs.fresh-web }}`,
  );
  for (const [name, job] of Object.entries(workflow.jobs)) {
    if (name === "fresh-web-sources") {
      continue;
    }
    expect(job.if, name).toBe(`\${{ !inputs.fresh-web }}`);
  }
});

test("catalog upstream inputs have one scheduled producer and an offline check", () => {
  const owner = generator("model-catalog-inputs");
  expect(owner.write).toEqual([
    "bun",
    "--filter",
    "@stll/ai-catalog",
    "gen:rates",
    "--refresh",
  ]);
  expect(owner.check).toEqual([
    "bun",
    "--filter",
    "@stll/ai-catalog",
    "gen:rates",
    "--check",
  ]);
  expect(owner.autofix).toBe(false);
  for (const file of [
    "packages/ai-catalog/upstream/models.dev.gen.json",
    "packages/ai-catalog/upstream/openrouter.gen.json",
  ]) {
    expect(isRegisteredGeneratedFile(file)).toBe(true);
    expect(
      GENERATORS.filter(({ outputs }) =>
        outputs.some((glob) => matchesGeneratedGlob(glob, file)),
      ).map(({ id }) => id),
    ).toEqual([owner.id]);
  }
});
