import { panic } from "better-result";
import { expect, test } from "bun:test";
import { readFileSync } from "node:fs";

import {
  GENERATORS,
  generatorsForFiles,
  orderGenerators,
} from "./generated-files";
import {
  isGeneratedCandidate,
  isRegisteredGeneratedFile,
  isUnregisteredGeneratedFile,
  routeGeneratorVersionsMatch,
} from "./generated-files-guard";
import { isChangedLintPath } from "./lint-paths";

const generator = (id: string) => {
  const found = GENERATORS.find((entry) => entry.id === id);
  return found ?? panic(`Missing generator ${id}`);
};

test("Guard A rejects an unregistered generated source and ignores ordinary comments", () => {
  const unknown = "packages/example/src/unlisted.ts";
  expect(
    isGeneratedCandidate(unknown, "// Generated by a script\nexport {};"),
  ).toBe(true);
  expect(isRegisteredGeneratedFile(unknown)).toBe(false);
  expect(
    isUnregisteredGeneratedFile(
      unknown,
      "// Generated by a script\nexport {};",
    ),
  ).toBe(true);
  expect(isGeneratedCandidate("packages/example/src/unlisted.gen.ts", "")).toBe(
    true,
  );
  expect(
    isGeneratedCandidate(
      unknown,
      "// The generated output is consumed elsewhere.\nexport {};",
    ),
  ).toBe(false);
  expect(isRegisteredGeneratedFile("apps/web/src/routeTree.gen.ts")).toBe(true);
  expect(isUnregisteredGeneratedFile("apps/web/src/routeTree.gen.ts", "")).toBe(
    false,
  );
  expect(isRegisteredGeneratedFile("apps/desktop/src-tauri/Cargo.lock")).toBe(
    true,
  );
});

test("the route generator pin matches the plugin's resolved generator", () => {
  expect(
    routeGeneratorVersionsMatch(
      "1.167.38",
      "1.167.38",
      "@tanstack/router-generator@1.167.38",
    ),
  ).toBe(true);
  expect(
    routeGeneratorVersionsMatch(
      "1.167.39",
      "1.167.38",
      "@tanstack/router-generator@1.167.38",
    ),
  ).toBe(false);
});

test("autofix selects only owners of changed inputs and preserves dependencies", () => {
  expect(
    generatorsForFiles(["apps/web/src/routes/law/index.tsx"]).map(
      ({ id }) => id,
    ),
  ).toEqual(["module-ownership", "route-tree"]);
  expect(generatorsForFiles(["docs/unrelated.md"])).toEqual([]);
  const ordered = orderGenerators(
    generatorsForFiles(["apps/api/src/handlers/example.ts"]),
  );
  expect(
    ordered.findIndex(({ id }) => id === "capability-catalog"),
  ).toBeLessThan(ordered.findIndex(({ id }) => id === "cli-registry"));
});

test("autofix refuses an empty selected-generator handoff", () => {
  const run = Bun.spawnSync(["bun", "scripts/autofix-plan.ts", "allowed", ""], {
    stdout: "pipe",
    stderr: "pipe",
  });
  expect(run.exitCode).toBe(1);
  expect(new TextDecoder().decode(run.stderr)).toContain(
    "Autofix plan has no selected generators",
  );
});

test("lint selection derives generated outputs from the manifest", () => {
  expect(isChangedLintPath("apps/web/src/routeTree.gen.ts")).toBe(false);
  expect(isChangedLintPath("packages/skills/src/blueprints.gen.ts")).toBe(
    false,
  );
  expect(isChangedLintPath("apps/web/src/routes/new.gen.ts")).toBe(true);
});

const ci = readFileSync(
  new URL("../.github/workflows/ci.yml", import.meta.url),
  "utf-8",
);

const casePatternsAfter = (marker: string) => {
  const section = ci.slice(ci.indexOf(marker));
  const match = /case "\$file" in\n\s+([^\n]+)\)/u.exec(section);
  expect(match, marker).not.toBeNull();
  return (match?.[1] ?? "").split("|");
};

test("CI path cases stay pinned to the manifest", () => {
  for (const [id, marker] of [
    ["web-api-types", "# The web API types drift guard"],
    ["model-rates", "# The committed rate and capability snapshots"],
  ] as const) {
    const inputs = generator(id).inputs.map((glob) =>
      glob.replace(/\/\*\*$/u, "/*"),
    );
    expect(casePatternsAfter(marker).toSorted(), id).toEqual(inputs.toSorted());
  }
});

test("CI diff path guards stay pinned to manifest outputs", () => {
  const cli = ci.slice(
    ci.indexOf("- name: CLI registry snapshot guard"),
    ci.indexOf("- name: MCP App bundle guard"),
  );
  const diff = cli.split("git diff --exit-code -- \\\n")[1];
  expect(diff).toBeDefined();
  const paths = (diff ?? "")
    .split("\n")
    .slice(0, 4)
    .map((line) => line.trim().replace(/ \\$/u, ""));
  expect(paths.toSorted()).toEqual(
    generator("cli-registry")
      .outputs.map((glob) => glob.replace(/\/\*\*$/u, ""))
      .toSorted(),
  );
  const bundle = ci.slice(ci.indexOf("- name: MCP App bundle guard"));
  expect(bundle).toContain(
    `git diff --exit-code -- "${generator("mcp-app-bundles").outputs[0]}"`,
  );
});
