// Hold every BullMQ queue to a declared authority and every member-run queue
// to the run actor, with a shrink-only, reasoned baseline
// (scripts/queue-authority-baseline.json).
//
// The registry is `QUEUE_AUTHORITY` in apps/api/src/lib/member-run-queues.ts.
// Its type requires a row per queue in the BullMQ host table; this script
// checks what the type cannot:
//
//   errors   (never baselined) a queue the host table and the registry
//            disagree on; a row without a reason; a BullMQ `Worker` whose
//            queue name does not resolve statically to string literals; a
//            row whose worker module consumes no `Worker` on that queue; a
//            `Worker` on a queue the registry assigns to another module (or
//            to none); a `MEMBER_RUN_QUEUES` entry the registry does not
//            classify as a member run of that module; a raw BullMQ worker
//            import outside the constructor owner.
//   members  (baselined, keyed without line numbers) a member-run queue whose
//            worker module never calls the imported `createRootRunActor`
//            (`<queue>::run-actor`); a member-run module the pinned-handle
//            allowlist still admits (`<queue>::pinned-handles::<file>`); a
//            member-run queue without an `*.integration.test.ts` that declares
//            an active bun:test case per revocation title
//            (`<queue>::revocation-test`).
//
// Scheduler tasks are held the same way. `SCHEDULER_TASK_AUTHORITY`
// (apps/api/src/lib/scheduler/task-authority.ts) is typed against the
// scheduler registry; this script reads the registry source and checks the
// following, with its own baseline (scripts/scheduler-task-authority-baseline.json):
//
//   errors   a registered task without a row, or a row for a task the
//            registry does not run; a row without a reason; a declared module
//            that is not the one the registry runs for the task; a declared
//            run actor whose module does not call its resolver.
//   members  a member-run task that does not settle its member's access when
//            it runs (`task:<name>::run-actor`); a member-run task module the
//            pinned-handle allowlist still admits
//            (`task:<name>::pinned-handles::<file>`); a task whose code does
//            not settle who it acts for (`task:<name>::unclassified`).
//
// Modes:
//   bun scripts/queue-authority.ts --check [--base <ref>]   (default base:
//     $BASE_SHA, then origin/main)
//   bun scripts/queue-authority.ts --write
//   bun scripts/queue-authority.ts --self-test

import { panic } from "better-result";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import ts from "typescript";
import * as v from "valibot";

import { compareCodeUnit } from "@stll/collation";

import {
  MEMBER_RUN_QUEUES,
  MEMBER_RUN_REVOCATION_CASES,
  QUEUE_AUTHORITY,
} from "../apps/api/src/lib/member-run-queues.ts";
import type { QueueAuthorityEntry } from "../apps/api/src/lib/member-run-queues.ts";
import {
  MEMBER_RUN_ACTOR_RESOLVERS,
  SCHEDULER_TASK_AUTHORITY,
} from "../apps/api/src/lib/scheduler/task-authority.ts";
import type { SchedulerTaskAuthorityEntry } from "../apps/api/src/lib/scheduler/task-authority.ts";
import { BASELINE_PATHS } from "./baseline-paths.ts";
import { addedEntries, runLedgerMembershipGuard } from "./ledger-membership.ts";
import { OWNERSHIP } from "./ownership.ts";

const ROOT = path.resolve(import.meta.dir, "..");
const BASELINE = BASELINE_PATHS.queueAuthority;
const TASK_BASELINE = BASELINE_PATHS.schedulerTaskAuthority;
const TASK_BASELINE_COMMENT =
  "Scheduler tasks whose authority is not yet settled in code. Generated by bun scripts/queue-authority.ts --write; shrink-only. Keys: task:<name>::run-actor (a member-run task that does not settle its member's access when it runs), task:<name>::pinned-handles::<file> (a member-run task module the pinned-workspace-handles allowlist admits), task:<name>::unclassified (the code does not settle who the task acts for).";
const API_SOURCE = "apps/api/src/";
const HOST_TABLE_FILE = "apps/api/src/lib/bullmq-queue.ts";
const HOST_TABLE_NAME = "BULLMQ_QUEUE_HOSTS";
const WORKER_CONSTRUCTOR = "BullMqWorker";
const PINNED_HANDLES_ROW = "pinned-workspace-handles";
const RUN_ACTOR = "createRootRunActor";
const RUN_ACTOR_MODULE = "@/api/lib/root-scoped-db";
const REVOCATION_TEST_SUFFIX = ".integration.test.ts";
const SCHEDULER_REGISTRY_FILE = "apps/api/src/lib/scheduler/registry.ts";
/** The registry's task tables: the static one and the one that adds the
 *  tasks built at boot. */
const SCHEDULER_REGISTRY_TABLES = ["SCHEDULER_TASKS", "schedulerTasks"];
/** Where the process builds the scheduler registry and supplies the tasks
 *  built at boot. */
const SCHEDULER_BOOT_FILE = "apps/api/src/server.ts";

const BASELINE_SCHEMA = v.object({
  comment: v.string(),
  members: v.record(v.string(), v.pipe(v.string(), v.nonEmpty())),
});
type Baseline = v.InferOutput<typeof BASELINE_SCHEMA>;

const REASONS = {
  runActor:
    "Member run on pinned handles; build them with createRootRunActor, read inputs through inputDb, and list the queue in MEMBER_RUN_QUEUES.",
  pinnedHandles:
    "Member-run module still allowed pinned workspace handles; move its reads to the run actor and drop it from the pinned-workspace-handles allowlist.",
  revocationTest:
    "No integration test removes the requester's access after the run is queued; add one per revocation case and name it in revocationTest.",
  taskRunActor:
    "Member-run task that does not settle its member's access when it runs; resolve it each run (a run actor or a membership check) and declare runActor.",
  taskPinnedHandles:
    "Member-run task module still allowed pinned workspace handles; read through the run actor and drop it from the pinned-workspace-handles allowlist.",
} as const;

type AuditInput = {
  hostQueues: readonly string[];
  registry: Readonly<Record<string, QueueAuthorityEntry>>;
  memberRunQueues: readonly { queue: string; module: string }[];
  /**
   * Modules that construct a BullMQ `Worker`, with the queue names those
   * workers consume; `null` when a queue name does not resolve statically.
   */
  workerQueues: ReadonlyMap<string, readonly string[] | null>;
  pinnedAllowed: ReadonlySet<string>;
  /** Repository-relative read; `null` when the file does not exist. */
  readFile: (relativePath: string) => string | null;
};

type Member = { key: string; reason: string };
type Audit = { errors: string[]; members: Member[] };

const auditRegistry = (input: AuditInput, errors: string[]) => {
  const hosted = new Set(input.hostQueues);
  for (const queue of input.hostQueues) {
    if (!(queue in input.registry)) {
      errors.push(`Queue without an authority row: ${queue}`);
    }
  }
  for (const [queue, entry] of Object.entries(input.registry)) {
    if (!hosted.has(queue)) {
      errors.push(`Authority row for a queue the host table lacks: ${queue}`);
    }
    if (entry.reason.trim() === "") {
      errors.push(`Authority row without a reason: ${queue}`);
    }
    const consumed = input.workerQueues.get(entry.worker);
    if (consumed === undefined) {
      errors.push(
        `Declared worker module constructs no BullMQ Worker: ${queue} -> ${entry.worker}`,
      );
    } else if (consumed !== null && !consumed.includes(queue)) {
      errors.push(
        `Declared worker module has no Worker on its queue: ${queue} -> ${entry.worker}`,
      );
    }
    for (const executor of entry.executors ?? []) {
      if (input.readFile(executor) === null) {
        errors.push(
          `Declared executor does not exist: ${queue} -> ${executor}`,
        );
      }
    }
  }
  for (const [module, queues] of input.workerQueues) {
    if (queues === null) {
      errors.push(
        `BullMQ Worker queue name does not resolve to string literals: ${module}`,
      );
      continue;
    }
    for (const queue of queues) {
      const owner = input.registry[queue]?.worker;
      if (owner !== module) {
        errors.push(
          owner === undefined
            ? `BullMQ Worker outside the queue authority registry: ${module} (${queue})`
            : `BullMQ Worker on ${queue} in ${module}, but the registry assigns it to ${owner}`,
        );
      }
    }
  }
  for (const { queue, module } of input.memberRunQueues) {
    const entry = input.registry[queue];
    if (entry?.authority !== "member-run" || entry.worker !== module) {
      errors.push(
        `MEMBER_RUN_QUEUES lists ${queue} (${module}), but the registry does not classify it as a member run of that module`,
      );
    }
  }
};

const unwrap = (node: ts.Expression): ts.Expression =>
  ts.isSatisfiesExpression(node) ||
  ts.isAsExpression(node) ||
  ts.isParenthesizedExpression(node)
    ? unwrap(node.expression)
    : node;

const propertyName = (name: ts.PropertyName): string | null =>
  ts.isIdentifier(name) || ts.isStringLiteral(name) ? name.text : null;

const parseSource = (name: string, source: string): ts.SourceFile =>
  ts.createSourceFile(name, source, ts.ScriptTarget.Latest, true);

const findNodes = <T extends ts.Node>(
  root: ts.Node,
  guard: (node: ts.Node) => node is T,
): T[] => {
  const found: T[] = [];
  const visit = (node: ts.Node) => {
    if (guard(node)) {
      found.push(node);
    }
    ts.forEachChild(node, visit);
  };
  visit(root);
  return found;
};

type ImportBinding = { module: string; imported: string };

/** Value (not type-only) named imports, keyed by local name. */
const importBindings = (file: ts.SourceFile): Map<string, ImportBinding> => {
  const bindings = new Map<string, ImportBinding>();
  for (const statement of file.statements) {
    if (
      !ts.isImportDeclaration(statement) ||
      !ts.isStringLiteral(statement.moduleSpecifier) ||
      statement.importClause?.phaseModifier === ts.SyntaxKind.TypeKeyword
    ) {
      continue;
    }
    const named = statement.importClause?.namedBindings;
    if (named === undefined || !ts.isNamedImports(named)) {
      continue;
    }
    for (const element of named.elements) {
      if (!element.isTypeOnly) {
        bindings.set(element.name.text, {
          module: statement.moduleSpecifier.text,
          imported: (element.propertyName ?? element.name).text,
        });
      }
    }
  }
  return bindings;
};

/** Local names bound to `imported` from `module`. */
const importedAs = (
  file: ts.SourceFile,
  module: string,
  imported: string,
): Set<string> =>
  new Set(
    [...importBindings(file)]
      .filter(
        ([, binding]) =>
          binding.module === module && binding.imported === imported,
      )
      .map(([local]) => local),
  );

/** Whether the module calls the `createRootRunActor` it imports. */
const callsRunActor = (source: string): boolean => {
  const file = parseSource("worker.ts", source);
  const locals = importedAs(file, RUN_ACTOR_MODULE, RUN_ACTOR);
  return findNodes(file, ts.isCallExpression).some(
    (call) =>
      ts.isIdentifier(call.expression) && locals.has(call.expression.text),
  );
};

const INACTIVE_MODIFIERS = new Set([
  "if",
  "skip",
  "skipIf",
  "todo",
  "todoIf",
  "failing",
]);

/** Whether `node` sits inside a skipped, conditional or todo suite or test. */
const insideInactiveBlock = (node: ts.Node): boolean => {
  let current = node.parent;
  while (!ts.isSourceFile(current)) {
    if (ts.isCallExpression(current)) {
      const callee = ts.isCallExpression(current.expression)
        ? current.expression.expression
        : current.expression;
      if (
        ts.isPropertyAccessExpression(callee) &&
        INACTIVE_MODIFIERS.has(callee.name.text)
      ) {
        return true;
      }
    }
    current = current.parent;
  }
  return false;
};

/**
 * Titles of the active bun:test cases in `source`: a plain `test`/`it` call
 * imported from bun:test with a literal title and a function body, outside
 * any skipped or conditional block. Comments and constants do not count.
 */
const activeTestTitles = (source: string): Set<string> => {
  const file = parseSource("revocation.test.ts", source);
  const runners = new Set([
    ...importedAs(file, "bun:test", "test"),
    ...importedAs(file, "bun:test", "it"),
  ]);
  const titles = new Set<string>();
  for (const call of findNodes(file, ts.isCallExpression)) {
    const [title, body] = call.arguments;
    if (
      ts.isIdentifier(call.expression) &&
      runners.has(call.expression.text) &&
      title !== undefined &&
      ts.isStringLiteralLike(title) &&
      body !== undefined &&
      (ts.isArrowFunction(body) || ts.isFunctionExpression(body)) &&
      !insideInactiveBlock(call)
    ) {
      titles.add(title.text);
    }
  }
  return titles;
};

const API_ALIAS = "@/api/";
const MAX_RESOLVE_DEPTH = 6;

const resolveModulePath = (from: string, specifier: string): string | null => {
  let base: string;
  if (specifier.startsWith(API_ALIAS)) {
    base = path.posix.join(API_SOURCE, specifier.slice(API_ALIAS.length));
  } else if (specifier.startsWith(".")) {
    base = path.posix.join(path.posix.dirname(from), specifier);
  } else {
    return null;
  }
  return `${base.replace(/\.ts$/u, "")}.ts`;
};

const declarationInitializer = (
  file: ts.SourceFile,
  name: string,
): ts.Expression | undefined =>
  findNodes(file, ts.isVariableDeclaration).find(
    (declaration) =>
      ts.isIdentifier(declaration.name) && declaration.name.text === name,
  )?.initializer;

type ResolveContext = {
  relativePath: string;
  file: ts.SourceFile;
  readFile: AuditInput["readFile"];
  depth: number;
};

/**
 * The string literals an expression can evaluate to, following local
 * constants, named imports (relative or `@/api/`), element access into an
 * object literal and its values. `null` when any step is not a literal.
 */
const resolveStrings = (
  expression: ts.Expression,
  context: ResolveContext,
): string[] | null => {
  const node = unwrap(expression);
  if (ts.isStringLiteralLike(node)) {
    return [node.text];
  }
  if (context.depth > MAX_RESOLVE_DEPTH) {
    return null;
  }
  const deeper = { ...context, depth: context.depth + 1 };
  if (ts.isElementAccessExpression(node)) {
    return resolveStrings(node.expression, deeper);
  }
  if (ts.isObjectLiteralExpression(node)) {
    const values: string[] = [];
    for (const property of node.properties) {
      const resolved = ts.isPropertyAssignment(property)
        ? resolveStrings(property.initializer, deeper)
        : null;
      if (resolved === null) {
        return null;
      }
      values.push(...resolved);
    }
    return values;
  }
  if (!ts.isIdentifier(node)) {
    return null;
  }
  const local = declarationInitializer(context.file, node.text);
  if (local !== undefined) {
    return resolveStrings(local, deeper);
  }
  const binding = importBindings(context.file).get(node.text);
  const target =
    binding === undefined
      ? null
      : resolveModulePath(context.relativePath, binding.module);
  const source = target === null ? null : context.readFile(target);
  if (binding === undefined || target === null || source === null) {
    return null;
  }
  const file = parseSource(target, source);
  const exported = declarationInitializer(file, binding.imported);
  return exported === undefined
    ? null
    : resolveStrings(exported, { ...deeper, relativePath: target, file });
};

const accessedMemberName = (node: ts.Node): string | null => {
  if (ts.isPropertyAccessExpression(node)) {
    return node.name.text;
  }
  if (
    ts.isElementAccessExpression(node) &&
    ts.isStringLiteralLike(node.argumentExpression)
  ) {
    return node.argumentExpression.text;
  }
  return null;
};

/**
 * Queue names consumed by the owned BullMQ workers a module constructs:
 * `undefined` when it constructs none, `null` when a queue name does not
 * resolve statically.
 */
const workerQueueNames = (
  relativePath: string,
  source: string,
  readFile: AuditInput["readFile"],
): readonly string[] | null | undefined => {
  if (!source.includes("bullmq-queue")) {
    return undefined;
  }
  const file = parseSource(relativePath, source);
  const bindings = importBindings(file);
  const namespaces = new Map<string, string>();
  for (const statement of file.statements) {
    if (
      ts.isImportDeclaration(statement) &&
      ts.isStringLiteral(statement.moduleSpecifier) &&
      statement.importClause?.phaseModifier !== ts.SyntaxKind.TypeKeyword &&
      statement.importClause?.namedBindings !== undefined &&
      ts.isNamespaceImport(statement.importClause.namedBindings)
    ) {
      namespaces.set(
        statement.importClause.namedBindings.name.text,
        statement.moduleSpecifier.text,
      );
    }
  }
  const isOwnedConstructor = (
    expression: ts.Expression,
    depth = 0,
  ): boolean => {
    if (depth > MAX_RESOLVE_DEPTH) {
      return false;
    }
    const node = unwrap(expression);
    if (ts.isIdentifier(node)) {
      const binding = bindings.get(node.text);
      if (binding !== undefined) {
        return (
          binding.imported === WORKER_CONSTRUCTOR &&
          resolveModulePath(relativePath, binding.module) === HOST_TABLE_FILE
        );
      }
      const initializer = declarationInitializer(file, node.text);
      return (
        initializer !== undefined && isOwnedConstructor(initializer, depth + 1)
      );
    }
    const namespace =
      (ts.isPropertyAccessExpression(node) ||
        ts.isElementAccessExpression(node)) &&
      ts.isIdentifier(node.expression)
        ? namespaces.get(node.expression.text)
        : undefined;
    const member = accessedMemberName(node);
    return (
      namespace !== undefined &&
      member === WORKER_CONSTRUCTOR &&
      resolveModulePath(relativePath, namespace) === HOST_TABLE_FILE
    );
  };
  const constructions = findNodes(file, ts.isNewExpression).filter((node) =>
    isOwnedConstructor(node.expression),
  );
  if (constructions.length === 0) {
    return undefined;
  }
  const queues = new Set<string>();
  for (const construction of constructions) {
    const first = construction.arguments?.at(0);
    const names =
      first === undefined
        ? null
        : resolveStrings(first, { relativePath, file, readFile, depth: 0 });
    if (names === null) {
      return null;
    }
    for (const name of names) {
      queues.add(name);
    }
  }
  return [...queues].toSorted();
};

const bindingLeavesWorkerUnavailable = (
  element: ts.BindingElement,
): boolean => {
  if (element.dotDotDotToken !== undefined) {
    return false;
  }
  if (element.propertyName !== undefined) {
    const name = propertyName(element.propertyName);
    return name !== null && name !== "Worker";
  }
  return ts.isIdentifier(element.name) && element.name.text !== "Worker";
};

const dynamicBullMqImportReachesWorker = (call: ts.CallExpression): boolean => {
  const specifier = call.arguments.at(0);
  if (
    (call.expression.kind !== ts.SyntaxKind.ImportKeyword &&
      !(
        ts.isIdentifier(call.expression) && call.expression.text === "require"
      )) ||
    specifier === undefined ||
    !ts.isStringLiteral(specifier) ||
    !(specifier.text === "bullmq" || specifier.text.startsWith("bullmq/"))
  ) {
    return false;
  }
  let parent = call.parent;
  while (
    ts.isAwaitExpression(parent) ||
    ts.isParenthesizedExpression(parent) ||
    ts.isAsExpression(parent) ||
    ts.isSatisfiesExpression(parent)
  ) {
    parent = parent.parent;
  }
  const member = accessedMemberName(parent);
  if (member !== null && member !== "Worker") {
    return false;
  }
  if (
    ts.isVariableDeclaration(parent) &&
    ts.isObjectBindingPattern(parent.name)
  ) {
    return !parent.name.elements.every(bindingLeavesWorkerUnavailable);
  }
  return true;
};

const rawWorkerImports = (relativePath: string, source: string): string[] => {
  if (relativePath === HOST_TABLE_FILE || !source.includes("bullmq")) {
    return [];
  }
  const file = parseSource(relativePath, source);
  const violations: string[] = [];
  for (const statement of file.statements) {
    if (
      !ts.isImportDeclaration(statement) &&
      !ts.isExportDeclaration(statement)
    ) {
      continue;
    }
    const specifier = statement.moduleSpecifier;
    if (
      specifier === undefined ||
      !ts.isStringLiteral(specifier) ||
      !(specifier.text === "bullmq" || specifier.text.startsWith("bullmq/"))
    ) {
      continue;
    }
    const names = ts.isImportDeclaration(statement)
      ? statement.importClause?.namedBindings
      : statement.exportClause;
    const reachesWorker =
      names === undefined
        ? ts.isExportDeclaration(statement)
        : ts.isNamespaceImport(names) ||
          ts.isNamespaceExport(names) ||
          names.elements.some(
            (element) =>
              (element.propertyName ?? element.name).text === "Worker",
          );
    if (reachesWorker) {
      violations.push(
        `BullMQ Worker imports use ${HOST_TABLE_FILE}: ${relativePath}`,
      );
    }
  }
  for (const call of findNodes(file, ts.isCallExpression)) {
    if (!dynamicBullMqImportReachesWorker(call)) {
      continue;
    }
    violations.push(
      `BullMQ Worker imports use ${HOST_TABLE_FILE}: ${relativePath}`,
    );
  }
  return violations;
};

const revocationGap = (
  entry: QueueAuthorityEntry,
  readFile: AuditInput["readFile"],
): string | null => {
  if (entry.revocationTest === undefined) {
    return REASONS.revocationTest;
  }
  if (!entry.revocationTest.endsWith(REVOCATION_TEST_SUFFIX)) {
    return `revocationTest ${entry.revocationTest} is not an integration test (*${REVOCATION_TEST_SUFFIX}).`;
  }
  const source = readFile(entry.revocationTest);
  if (source === null) {
    return `revocationTest ${entry.revocationTest} does not exist.`;
  }
  const active = activeTestTitles(source);
  const missing = MEMBER_RUN_REVOCATION_CASES.filter(
    (title) => !active.has(title),
  );
  return missing.length === 0
    ? null
    : `${entry.revocationTest} lacks: ${missing.join("; ")}.`;
};

const auditQueueAuthority = (input: AuditInput): Audit => {
  const errors: string[] = [];
  auditRegistry(input, errors);
  const onActor = new Set(input.memberRunQueues.map(({ queue }) => queue));
  const members: Member[] = [];
  for (const [queue, entry] of Object.entries(input.registry)) {
    if (entry.authority !== "member-run") {
      continue;
    }
    const usesActor =
      onActor.has(queue) && callsRunActor(input.readFile(entry.worker) ?? "");
    if (!usesActor) {
      members.push({ key: `${queue}::run-actor`, reason: REASONS.runActor });
    }
    for (const file of [entry.worker, ...(entry.executors ?? [])]) {
      if (input.pinnedAllowed.has(file)) {
        members.push({
          key: `${queue}::pinned-handles::${file}`,
          reason: REASONS.pinnedHandles,
        });
      }
    }
    const gap = revocationGap(entry, input.readFile);
    if (gap !== null) {
      members.push({ key: `${queue}::revocation-test`, reason: gap });
    }
  }
  members.sort((left, right) => compareCodeUnit(left.key, right.key));
  return { errors, members };
};

/** Keys of the object literal assigned to `name` in `source`. */
const objectKeys = (source: string, name: string): string[] | null => {
  const file = ts.createSourceFile("host.ts", source, ts.ScriptTarget.Latest);
  for (const statement of file.statements) {
    if (!ts.isVariableStatement(statement)) {
      continue;
    }
    for (const declaration of statement.declarationList.declarations) {
      if (
        ts.isIdentifier(declaration.name) &&
        declaration.name.text === name &&
        declaration.initializer !== undefined
      ) {
        const value = unwrap(declaration.initializer);
        if (!ts.isObjectLiteralExpression(value)) {
          return null;
        }
        return value.properties.flatMap((property) => {
          const key =
            ts.isPropertyAssignment(property) && propertyName(property.name);
          return typeof key === "string" ? [key] : [];
        });
      }
    }
  }
  return null;
};

type RegisteredTask = { name: string; module: string };

/** Value imports of `file` resolved to repository-relative modules. */
const namedImports = (
  file: ts.SourceFile,
  relativePath: string,
): Map<string, string> => {
  const imports = new Map<string, string>();
  for (const [local, binding] of importBindings(file)) {
    const module = resolveModulePath(relativePath, binding.module);
    if (module !== null) {
      imports.set(local, module);
    }
  }
  return imports;
};

/** The string literal `source` assigns to the constant `name`. */
const constantString = (source: string, name: string): string | null => {
  const initializer = declarationInitializer(
    parseSource("task.ts", source),
    name,
  );
  const value = initializer === undefined ? undefined : unwrap(initializer);
  return value !== undefined && ts.isStringLiteralLike(value)
    ? value.text
    : null;
};

/** Whether `source` calls the `resolver` it imports. */
const callsImported = (source: string, resolver: string): boolean => {
  const file = parseSource("run-actor.ts", source);
  const locals = new Set(
    [...importBindings(file)]
      .filter(([, binding]) => binding.imported === resolver)
      .map(([local]) => local),
  );
  return findNodes(file, ts.isCallExpression).some(
    (call) =>
      ts.isIdentifier(call.expression) && locals.has(call.expression.text),
  );
};

/** Whether the module at `from` calls a function it imports from `target`. */
const callsInto = (from: string, source: string, target: string): boolean => {
  const file = parseSource(from, source);
  const imports = namedImports(file, from);
  return findNodes(file, ts.isCallExpression).some(
    (call) =>
      ts.isIdentifier(call.expression) &&
      imports.get(call.expression.text) === target,
  );
};

/** Object literals of the registry's task tables. */
const registryTables = (file: ts.SourceFile): ts.ObjectLiteralExpression[] => {
  const tables: ts.ObjectLiteralExpression[] = [];
  const collect = (node: ts.Node) => {
    if (ts.isObjectLiteralExpression(node)) {
      tables.push(node);
      return;
    }
    ts.forEachChild(node, collect);
  };
  for (const statement of file.statements) {
    if (!ts.isVariableStatement(statement)) {
      continue;
    }
    for (const declaration of statement.declarationList.declarations) {
      if (
        ts.isIdentifier(declaration.name) &&
        SCHEDULER_REGISTRY_TABLES.includes(declaration.name.text) &&
        declaration.initializer !== undefined
      ) {
        collect(declaration.initializer);
      }
    }
  }
  return tables;
};

/** The identifier a registry value names: `task` or `createTask()`. */
const valueIdentifier = (value: ts.Expression): string | null => {
  const inner = unwrap(value);
  if (ts.isIdentifier(inner)) {
    return inner.text;
  }
  return ts.isCallExpression(inner) && ts.isIdentifier(inner.expression)
    ? inner.expression.text
    : null;
};

type FunctionLike =
  | ts.ArrowFunction
  | ts.FunctionExpression
  | ts.FunctionDeclaration;

const isFunctionLike = (node: ts.Node): node is FunctionLike =>
  ts.isArrowFunction(node) ||
  ts.isFunctionExpression(node) ||
  ts.isFunctionDeclaration(node);

const enclosingFunction = (node: ts.Node): FunctionLike | undefined =>
  ts.findAncestor(node.parent, isFunctionLike);

/** The name a function is declared under, `const f = () => …` included. */
const functionName = (fn: FunctionLike): string | null => {
  if (ts.isFunctionDeclaration(fn)) {
    return fn.name?.text ?? null;
  }
  return ts.isVariableDeclaration(fn.parent) && ts.isIdentifier(fn.parent.name)
    ? fn.parent.name.text
    : null;
};

const parameterIndex = (fn: FunctionLike | undefined, name: string): number =>
  fn === undefined
    ? -1
    : fn.parameters.findIndex(
        (parameter) =>
          ts.isIdentifier(parameter.name) && parameter.name.text === name,
      );

/**
 * The module implementing a task the registry receives as the parameter
 * `value` of the table function around `property`: follow the registry
 * factory that forwards that parameter to the boot file's call of it, and
 * take the module the boot file imports the argument from. `null` unless
 * every boot call resolves to the same single module.
 */
const injectedTaskModule = (
  property: ts.PropertyAssignment,
  value: string,
  registry: { file: ts.SourceFile; path: string },
  readFile: AuditInput["readFile"],
): string | null => {
  const table = enclosingFunction(property);
  const tableName = table === undefined ? null : functionName(table);
  const position = parameterIndex(table, value);
  if (tableName === null || position < 0) {
    return null;
  }
  const factories: { name: string; position: number }[] = [];
  for (const call of findNodes(registry.file, ts.isCallExpression)) {
    const argument = call.arguments[position];
    if (
      !ts.isIdentifier(call.expression) ||
      call.expression.text !== tableName ||
      argument === undefined ||
      !ts.isIdentifier(argument)
    ) {
      continue;
    }
    const caller = enclosingFunction(call);
    const callerName = caller === undefined ? null : functionName(caller);
    const forwarded = parameterIndex(caller, argument.text);
    if (callerName !== null && forwarded >= 0) {
      factories.push({ name: callerName, position: forwarded });
    }
  }
  const bootSource = readFile(SCHEDULER_BOOT_FILE);
  if (bootSource === null || factories.length === 0) {
    return null;
  }
  const boot = parseSource(SCHEDULER_BOOT_FILE, bootSource);
  const bootImports = namedImports(boot, SCHEDULER_BOOT_FILE);
  const bindings = importBindings(boot);
  const modules = new Set<string>();
  for (const call of findNodes(boot, ts.isCallExpression)) {
    if (
      !ts.isIdentifier(call.expression) ||
      bootImports.get(call.expression.text) !== registry.path
    ) {
      continue;
    }
    const imported = bindings.get(call.expression.text)?.imported;
    const factory = factories.find(({ name }) => name === imported);
    if (factory === undefined) {
      continue;
    }
    const argument = call.arguments[factory.position];
    const supplied = argument === undefined ? null : valueIdentifier(argument);
    modules.add(
      (supplied === null ? undefined : bootImports.get(supplied)) ??
        SCHEDULER_BOOT_FILE,
    );
  }
  const [only, ...rest] = modules;
  return rest.length === 0 ? (only ?? null) : null;
};

/**
 * Every task the scheduler registry runs, with the module that implements it:
 * the module the task's value is imported from; for a task the registry
 * receives at boot, the module the boot file imports it from; else the
 * registry itself.
 */
const registeredTasks = (
  registryFile: string,
  readFile: AuditInput["readFile"],
): { tasks: RegisteredTask[]; errors: string[] } => {
  const source = readFile(registryFile);
  if (source === null) {
    return {
      tasks: [],
      errors: [`Scheduler registry missing: ${registryFile}`],
    };
  }
  const file = parseSource(registryFile, source);
  const imports = namedImports(file, registryFile);
  const tasks: RegisteredTask[] = [];
  const errors: string[] = [];
  for (const table of registryTables(file)) {
    for (const property of table.properties) {
      if (!ts.isPropertyAssignment(property)) {
        continue;
      }
      const literal = propertyName(property.name);
      const keyConstant =
        ts.isComputedPropertyName(property.name) &&
        ts.isIdentifier(property.name.expression)
          ? property.name.expression.text
          : null;
      const keyModule =
        keyConstant === null ? registryFile : imports.get(keyConstant);
      const name =
        literal ??
        (keyConstant === null || keyModule === undefined
          ? null
          : constantString(readFile(keyModule) ?? "", keyConstant));
      if (name === null || keyModule === undefined) {
        errors.push(
          `Scheduler registry key not resolvable to a task name: ${property.name.getText(file)}`,
        );
        continue;
      }
      const initializer = unwrap(property.initializer);
      const typedEntry = ts.isObjectLiteralExpression(initializer);
      let value = valueIdentifier(property.initializer);
      if (typedEntry) {
        const taskProperty = initializer.properties.find(
          (entry) =>
            (ts.isPropertyAssignment(entry) ||
              ts.isShorthandPropertyAssignment(entry)) &&
            propertyName(entry.name) === "task",
        );
        value = null;
        if (
          taskProperty !== undefined &&
          ts.isPropertyAssignment(taskProperty)
        ) {
          value = valueIdentifier(taskProperty.initializer);
        }
        if (
          taskProperty !== undefined &&
          ts.isShorthandPropertyAssignment(taskProperty)
        ) {
          value = valueIdentifier(taskProperty.name);
        }
      }
      const imported = value === null ? undefined : imports.get(value);
      if (
        typedEntry &&
        (value === null ||
          (imported === undefined &&
            parameterIndex(enclosingFunction(property), value) < 0))
      ) {
        errors.push(
          `Scheduler typed registry task not resolvable to one module: ${name}`,
        );
        continue;
      }
      if (
        value === null ||
        imported !== undefined ||
        parameterIndex(enclosingFunction(property), value) < 0
      ) {
        tasks.push({ name, module: imported ?? registryFile });
        continue;
      }
      const injected = injectedTaskModule(
        property,
        value,
        { file, path: registryFile },
        readFile,
      );
      if (injected === null) {
        errors.push(
          `Scheduler task supplied at boot not traceable to one module: ${name} (${value} from ${SCHEDULER_BOOT_FILE})`,
        );
        continue;
      }
      tasks.push({ name, module: injected });
    }
  }
  return { tasks, errors };
};

type TaskAuditInput = {
  tasks: readonly RegisteredTask[];
  registry: Readonly<Record<string, SchedulerTaskAuthorityEntry>>;
  pinnedAllowed: ReadonlySet<string>;
  readFile: AuditInput["readFile"];
};

const auditSchedulerTaskAuthority = (input: TaskAuditInput): Audit => {
  const errors: string[] = [];
  const members: Member[] = [];
  const registered = new Map(
    input.tasks.map(({ name, module }) => [name, module]),
  );
  for (const { name } of input.tasks) {
    if (!(name in input.registry)) {
      errors.push(`Scheduler task without an authority row: ${name}`);
    }
  }
  for (const [name, entry] of Object.entries(input.registry)) {
    const runs = registered.get(name);
    if (runs === undefined) {
      errors.push(
        `Authority row for a task the scheduler registry lacks: ${name}`,
      );
    } else if (runs !== entry.module) {
      errors.push(
        `Declared module is not the one the registry runs: ${name} -> ${entry.module} (registry runs ${runs})`,
      );
    }
    if (entry.reason.trim() === "") {
      errors.push(`Authority row without a reason: ${name}`);
    }
    if (entry.authority === "unclassified") {
      members.push({ key: `task:${name}::unclassified`, reason: entry.reason });
      continue;
    }
    if (entry.authority !== "member-run") {
      continue;
    }
    if (entry.runActor === null) {
      members.push({
        key: `task:${name}::run-actor`,
        reason: REASONS.taskRunActor,
      });
    } else if (
      entry.runActor.module !== entry.module &&
      !callsInto(
        entry.module,
        input.readFile(entry.module) ?? "",
        entry.runActor.module,
      )
    ) {
      errors.push(
        `Declared run actor is off the task's call path: ${name} -> ${entry.module} calls nothing from ${entry.runActor.module}`,
      );
    } else if (
      !callsImported(
        input.readFile(entry.runActor.module) ?? "",
        entry.runActor.resolver,
      )
    ) {
      errors.push(
        `Declared run actor not found: ${name} -> ${entry.runActor.module} does not call ${entry.runActor.resolver}`,
      );
    }
    if (input.pinnedAllowed.has(entry.module)) {
      members.push({
        key: `task:${name}::pinned-handles::${entry.module}`,
        reason: REASONS.taskPinnedHandles,
      });
    }
  }
  return { errors, members };
};

const isProductionSource = (relativePath: string): boolean =>
  !/\.(test|type-test)\.[cm]?[jt]sx?$/u.test(relativePath) &&
  !/(^|\/)(__fixtures__|__tests__|test-fixtures|tests|node_modules|dist)\//u.test(
    relativePath,
  );

const readRepoFile = (relativePath: string): string | null => {
  const absolute = path.join(ROOT, relativePath);
  return existsSync(absolute) ? readFileSync(absolute, "utf-8") : null;
};

const treeInput = () => {
  const hostQueues = objectKeys(
    readRepoFile(HOST_TABLE_FILE) ?? "",
    HOST_TABLE_NAME,
  );
  if (hostQueues === null) {
    return panic(`${HOST_TABLE_NAME} not found in ${HOST_TABLE_FILE}`);
  }
  const workerQueues = new Map<string, readonly string[] | null>();
  const workerOwnershipErrors: string[] = [];
  const sources = Bun.spawnSync(
    [
      "git",
      "ls-files",
      "--cached",
      "--others",
      "--exclude-standard",
      "-z",
      "--",
      "apps",
      "packages",
      "scripts",
    ],
    { cwd: ROOT },
  );
  if (sources.exitCode !== 0) {
    return panic("Cannot enumerate BullMQ worker source files");
  }
  for (const file of sources.stdout
    .toString()
    .split("\0")
    .filter((filename) => /\.[cm]?[jt]sx?$/u.test(filename))
    .filter(isProductionSource)
    .toSorted()) {
    const source = readRepoFile(file) ?? "";
    workerOwnershipErrors.push(...rawWorkerImports(file, source));
    const queues = workerQueueNames(file, source, readRepoFile);
    if (queues !== undefined) {
      workerQueues.set(file, queues);
    }
  }
  const pinnedRow = OWNERSHIP.find(({ id }) => id === PINNED_HANDLES_ROW);
  if (pinnedRow?.enforcement.kind !== "import") {
    return panic(`ownership row ${PINNED_HANDLES_ROW} is not an import row`);
  }
  return {
    hostQueues,
    registry: QUEUE_AUTHORITY,
    memberRunQueues: MEMBER_RUN_QUEUES,
    workerQueues,
    workerOwnershipErrors,
    pinnedAllowed: new Set(
      pinnedRow.enforcement.allowed.map(({ path: file }) => file),
    ),
    readFile: readRepoFile,
  } satisfies AuditInput & { workerOwnershipErrors: string[] };
};

type Ledger = {
  path: string;
  label: string;
  /** Kept when the baseline file does not exist yet. */
  comment: string;
  newGap: string;
  closedGap: string;
  remediation: string;
  audit: Audit;
};

/** Queues and scheduler tasks of the working tree, each held to its own
 *  baseline. */
const treeLedgers = (): Ledger[] => {
  const queueInput = treeInput();
  const registry = registeredTasks(SCHEDULER_REGISTRY_FILE, readRepoFile);
  const tasks = auditSchedulerTaskAuthority({
    tasks: registry.tasks,
    registry: SCHEDULER_TASK_AUTHORITY,
    pinnedAllowed: queueInput.pinnedAllowed,
    readFile: readRepoFile,
  });
  const queueAudit = auditQueueAuthority(queueInput);
  return [
    {
      path: BASELINE,
      label: "queue-authority",
      comment: "",
      newGap:
        "New member-run gap (build the run with createRootRunActor and test revocation)",
      closedGap: "Closed member-run gap still listed (run --write)",
      remediation:
        "build a new member run with createRootRunActor and a revocation test instead of listing it",
      audit: {
        members: queueAudit.members,
        errors: [...queueInput.workerOwnershipErrors, ...queueAudit.errors],
      },
    },
    {
      path: TASK_BASELINE,
      label: "scheduler-task-authority",
      comment: TASK_BASELINE_COMMENT,
      newGap:
        "New scheduler task gap (classify the task; a member-run task settles its member's access each run)",
      closedGap: "Closed scheduler task gap still listed (run --write)",
      remediation:
        "classify a new scheduler task and settle a member-run task's access each run instead of listing it",
      audit: {
        errors: [...registry.errors, ...tasks.errors],
        members: tasks.members.toSorted((left, right) =>
          compareCodeUnit(left.key, right.key),
        ),
      },
    },
  ];
};

const parseBaseline = (text: string, label: string): Baseline => {
  const parsed = v.safeParse(BASELINE_SCHEMA, JSON.parse(text));
  if (!parsed.success) {
    return panic(`${label}: ${v.summarize(parsed.issues)}`);
  }
  return parsed.output;
};

const readBaseline = (ledger: Ledger): Baseline => {
  const text = readRepoFile(ledger.path);
  return text === null
    ? { comment: ledger.comment, members: {} }
    : parseBaseline(text, ledger.path);
};

const reportErrors = (errors: readonly string[]): boolean => {
  for (const error of errors) {
    console.error(error);
  }
  return errors.length > 0;
};

const write = (): number => {
  const ledgers = treeLedgers();
  if (reportErrors(ledgers.flatMap(({ audit }) => audit.errors))) {
    return 1;
  }
  for (const ledger of ledgers) {
    const previous = readBaseline(ledger);
    const next: Baseline = {
      comment: previous.comment,
      members: Object.fromEntries(
        ledger.audit.members.map(({ key, reason }) => [
          key,
          previous.members[key] ?? reason,
        ]),
      ),
    };
    writeFileSync(
      path.join(ROOT, ledger.path),
      `${JSON.stringify(next, null, 2)}\n`,
    );
    console.log(
      `${ledger.path} written: ${String(ledger.audit.members.length)} members.`,
    );
  }
  return 0;
};

/** Members found but not listed, and listed members no longer found. */
const baselineDifference = (
  found: readonly string[],
  listed: readonly string[],
) => ({
  added: found.filter((key) => !listed.includes(key)),
  stale: listed.filter((key) => !found.includes(key)),
});

const check = (args: readonly string[]): number => {
  const baseIndex = args.indexOf("--base");
  const base =
    (baseIndex === -1 ? undefined : args[baseIndex + 1]) ??
    process.env["BASE_SHA"] ??
    "origin/main";
  let failed = false;
  let baselined = 0;
  for (const ledger of treeLedgers()) {
    const { errors, members } = ledger.audit;
    const { added, stale } = baselineDifference(
      members.map(({ key }) => key),
      Object.keys(readBaseline(ledger).members),
    );
    const failures = [
      ...errors,
      ...added.map((key) => `${ledger.newGap}: ${key}`),
      ...stale.map((key) => `${ledger.closedGap}: ${key}`),
    ];
    reportErrors(failures);
    const membership =
      readRepoFile(ledger.path) === null
        ? 0
        : runLedgerMembershipGuard({
            ledgerRel: ledger.path,
            repoRoot: ROOT,
            parseLedger: (text, label) =>
              Object.keys(parseBaseline(text, label).members),
            label: ledger.label,
            remediation: ledger.remediation,
            args: ["--base", base === "" ? "origin/main" : base],
          });
    failed ||= failures.length > 0 || membership !== 0;
    baselined += members.length;
  }
  if (failed) {
    return 1;
  }
  console.log(
    `Queue authority: ${String(Object.keys(QUEUE_AUTHORITY).length)} queues and ${String(Object.keys(SCHEDULER_TASK_AUTHORITY).length)} scheduler tasks classified, ${String(baselined)} baselined members, exact sets verified.`,
  );
  return 0;
};

const SELF_TEST_WORKER = `
  import { BullMqWorker as BullWorker } from "@/api/lib/bullmq-queue";
  import { NAMES } from "@/api/lib/names";
  const LOCAL = "local";
  const name = NAMES[kind];
  export const start = () => [
    new BullWorker<Job>(LOCAL, async () => {}),
    new BullWorker<Job>(name, async () => {}),
  ];
`;
const SELF_TEST_NAMES = `
  export const NAMES = { [K.a]: "imported-a", b: "imported-b" } as const;
`;
const SELF_TEST_WEB_WORKER = `
  export const start = () => new Worker(new URL("./w.ts", import.meta.url));
`;
const SELF_TEST_DYNAMIC_WORKER = `
  import { BullMqWorker } from "@/api/lib/bullmq-queue";
  export const start = (queue: string) => new BullMqWorker(queue, async () => {});
`;
const workerOn = (queue: string) =>
  `import { BullMqWorker } from "@/api/lib/bullmq-queue"; new BullMqWorker("${queue}", async () => {});`;
const SELF_TEST_ACTOR = `
  import { ${RUN_ACTOR} as actorFor } from "${RUN_ACTOR_MODULE}";
  const actor = actorFor(data);
`;
const SELF_TEST_ACTOR_TEXT_ONLY = `
  // ${RUN_ACTOR}(data) is planned
  const note = "${RUN_ACTOR}(data)";
  const ${RUN_ACTOR} = (value: unknown) => value;
  ${RUN_ACTOR}(data);
`;
const SELF_TEST_BUN_TEST = 'import { describe, test } from "bun:test";\n';
const revocationCase = (title: string, call = "test") =>
  `${call}("${title}", async () => {});`;
const SELF_TEST_REVOCATION =
  SELF_TEST_BUN_TEST +
  MEMBER_RUN_REVOCATION_CASES.map((title) => revocationCase(title)).join("\n");
const SELF_TEST_INACTIVE_REVOCATIONS = [
  // Titles only in comments and constants.
  `${SELF_TEST_BUN_TEST}// ${MEMBER_RUN_REVOCATION_CASES.join(" ")}\nconst titles = ${JSON.stringify(MEMBER_RUN_REVOCATION_CASES)};`,
  // A skipped case.
  `${SELF_TEST_BUN_TEST}${revocationCase(MEMBER_RUN_REVOCATION_CASES[0])}\n${revocationCase(MEMBER_RUN_REVOCATION_CASES[1], "test.skip")}`,
  // Both cases inside a skipped suite.
  `${SELF_TEST_BUN_TEST}describe.skipIf(true)("s", () => {\n${MEMBER_RUN_REVOCATION_CASES.map((title) => revocationCase(title)).join("\n")}\n});`,
  // A local function named test, not bun:test.
  `const test = (..._args: unknown[]) => undefined;\n${MEMBER_RUN_REVOCATION_CASES.map((title) => revocationCase(title)).join("\n")}`,
];

const SELF_TEST_TASKS = "apps/api/src/lib/scheduler/tasks";
const SELF_TEST_REGISTRY = `
  import { A_TASK, runA } from "@/api/lib/scheduler/tasks/a";
  import { createDispatch } from "@/api/lib/scheduler/dispatch";
  import { REAP_TASK } from "@/api/lib/scheduler/tasks/reap";
  const local = () => {};
  const SCHEDULER_TASKS = {
    [A_TASK]: runA,
    "x.dispatch": createDispatch(),
    "x.noop": local,
  } as const satisfies Record<string, unknown>;
  const schedulerTasks = (reap: unknown) => ({
    ...SCHEDULER_TASKS,
    [REAP_TASK]: reap,
  });
  const NAMES = Object.keys(schedulerTasks(local));
  export const createRegistry = (reaper: unknown) =>
    new Map(Object.entries(schedulerTasks(reaper)));
`;
/** The boot file supplies the reap task from a module other than the one
 *  that names it. */
const SELF_TEST_BOOT = `
  import { createRegistry } from "@/api/lib/scheduler/registry";
  import { createReap } from "@/api/lib/scheduler/tasks/reaper";
  startLoop({ registry: createRegistry(createReap(db)) });
`;

const selfTestTypedSchedulerTasks = (
  readFile: AuditInput["readFile"],
  expectedTasks: readonly RegisteredTask[],
): string[] => {
  const failures: string[] = [];
  const typedSource = SELF_TEST_REGISTRY.replace(
    "[A_TASK]: runA,",
    '[A_TASK]: { featureId: "fixture", task: runA },',
  ).replace(
    "[REAP_TASK]: reap,",
    '[REAP_TASK]: { featureId: "fixture", task: reap },',
  );
  const typedReadFile = (file: string) =>
    file === SCHEDULER_REGISTRY_FILE ? typedSource : readFile(file);
  const typed = registeredTasks(SCHEDULER_REGISTRY_FILE, typedReadFile);
  if (
    JSON.stringify(typed) !==
    JSON.stringify({ tasks: expectedTasks, errors: [] })
  ) {
    failures.push(
      `typed task entries must resolve imported and boot tasks: ${JSON.stringify(typed)}`,
    );
  }
  for (const [module, expectedErrors] of [
    [`${SELF_TEST_TASKS}/a.ts`, []],
    [
      "stale.ts",
      [
        `Declared module is not the one the registry runs: a.run -> stale.ts (registry runs ${SELF_TEST_TASKS}/a.ts)`,
      ],
    ],
  ] as const) {
    const audited = auditSchedulerTaskAuthority({
      tasks: typed.tasks.filter(({ name }) => name === "a.run"),
      registry: {
        "a.run": { authority: "org-automation", module, reason: "r" },
      },
      pinnedAllowed: new Set(),
      readFile: typedReadFile,
    });
    if (JSON.stringify(audited.errors) !== JSON.stringify(expectedErrors)) {
      failures.push(
        `typed task authority must match ${module}: ${JSON.stringify(audited.errors)}`,
      );
    }
  }
  for (const initializer of [
    '{ featureId: "fixture" }',
    '{ featureId: "fixture", task: runA.missing }',
    '{ featureId: "fixture", task: missingTask }',
  ]) {
    const invalid = registeredTasks(SCHEDULER_REGISTRY_FILE, (file) =>
      file === SCHEDULER_REGISTRY_FILE
        ? SELF_TEST_REGISTRY.replace(
            "[A_TASK]: runA,",
            () => `[A_TASK]: ${initializer},`,
          )
        : readFile(file),
    );
    if (
      JSON.stringify(invalid.errors) !==
        JSON.stringify([
          "Scheduler typed registry task not resolvable to one module: a.run",
        ]) ||
      invalid.tasks.some(({ name }) => name === "a.run")
    ) {
      failures.push(
        `typed entry with a missing or unresolvable task must error: ${initializer}: ${JSON.stringify(invalid)}`,
      );
    }
  }
  return failures;
};

const selfTestSchedulerTasks = (): string[] => {
  const failures: string[] = [];
  const files: Record<string, string> = {
    [SCHEDULER_REGISTRY_FILE]: SELF_TEST_REGISTRY,
    [`${SELF_TEST_TASKS}/a.ts`]: 'export const A_TASK =\n  "a.run" as const;',
    [`${SELF_TEST_TASKS}/reap.ts`]:
      'export const REAP_TASK = "a.reap" as const;',
    [SCHEDULER_BOOT_FILE]: SELF_TEST_BOOT,
    // The task module calls into the module that settles its member.
    "m.ts":
      'import { settleRun } from "./actor";\nimport { decoyRun } from "./decoy";\nawait settleRun();\ndecoyRun();',
    "detached.ts": "export const run = () => undefined;",
    // Importing without calling is not a call path.
    "imported-only.ts":
      'import { settleRun } from "./actor";\nexport const keep = settleRun;',
    "actor.ts": `import { ${MEMBER_RUN_ACTOR_RESOLVERS[1]} as settle } from "@/api/lib/auth";\nawait settle(data);`,
    // Mentions in a comment or a string, and a local function of the same
    // name, are not a call to the imported resolver.
    "decoy.ts": `// ${MEMBER_RUN_ACTOR_RESOLVERS[1]}(data)\nconst note = "${MEMBER_RUN_ACTOR_RESOLVERS[1]}(data)";\nconst ${MEMBER_RUN_ACTOR_RESOLVERS[1]} = (value: unknown) => value;\n${MEMBER_RUN_ACTOR_RESOLVERS[1]}(data);`,
  };
  const readFile = (file: string) => files[file] ?? null;
  const resolved = registeredTasks(SCHEDULER_REGISTRY_FILE, readFile);
  const expectedTasks = [
    { name: "a.run", module: `${SELF_TEST_TASKS}/a.ts` },
    { name: "x.dispatch", module: "apps/api/src/lib/scheduler/dispatch.ts" },
    { name: "x.noop", module: SCHEDULER_REGISTRY_FILE },
    { name: "a.reap", module: `${SELF_TEST_TASKS}/reaper.ts` },
  ];
  if (
    JSON.stringify(resolved) !==
    JSON.stringify({ tasks: expectedTasks, errors: [] })
  ) {
    failures.push(
      `registry tasks must resolve to ${JSON.stringify(expectedTasks)}; got ${JSON.stringify(resolved)}`,
    );
  }
  // A boot task whose supply cannot be traced, or is supplied from two
  // modules, fails instead of falling back to the module naming it.
  const untraced =
    "Scheduler task supplied at boot not traceable to one module: a.reap (reap from apps/api/src/server.ts)";
  for (const [label, boot] of [
    ["no boot file", null],
    ["no boot call", "export {};"],
    [
      "two supplying modules",
      `${SELF_TEST_BOOT}\nimport { otherReap } from "@/api/lib/scheduler/tasks/other";\ncreateRegistry(otherReap);`,
    ],
  ] as const) {
    const errors = registeredTasks(SCHEDULER_REGISTRY_FILE, (file) =>
      file === SCHEDULER_BOOT_FILE ? boot : readFile(file),
    ).errors;
    if (JSON.stringify(errors) !== JSON.stringify([untraced])) {
      failures.push(
        `${label}: boot task must fail as untraceable; got ${JSON.stringify(errors)}`,
      );
    }
  }
  failures.push(...selfTestTypedSchedulerTasks(readFile, expectedTasks));
  const task = (name: string, module = "m.ts") => ({ name, module });
  const automation = (module = "m.ts", reason = "r") =>
    ({ authority: "org-automation", module, reason }) as const;
  const audit = auditSchedulerTaskAuthority({
    tasks: [
      task("on-actor"),
      task("no-actor", "pinned.ts"),
      task("lost-actor"),
      task("decoy-actor"),
      task("detached-actor", "detached.ts"),
      task("imported-actor", "imported-only.ts"),
      task("org"),
      task("open"),
      task("moved", "real.ts"),
      task("missing"),
      task("blank"),
    ],
    registry: {
      "on-actor": {
        authority: "member-run",
        module: "m.ts",
        reason: "r",
        runActor: {
          module: "actor.ts",
          resolver: MEMBER_RUN_ACTOR_RESOLVERS[1],
        },
      },
      "no-actor": {
        authority: "member-run",
        module: "pinned.ts",
        reason: "r",
        runActor: null,
      },
      "lost-actor": {
        authority: "member-run",
        module: "m.ts",
        reason: "r",
        runActor: { module: "m.ts", resolver: MEMBER_RUN_ACTOR_RESOLVERS[0] },
      },
      "decoy-actor": {
        authority: "member-run",
        module: "m.ts",
        reason: "r",
        runActor: {
          module: "decoy.ts",
          resolver: MEMBER_RUN_ACTOR_RESOLVERS[1],
        },
      },
      "detached-actor": {
        authority: "member-run",
        module: "detached.ts",
        reason: "r",
        runActor: {
          module: "actor.ts",
          resolver: MEMBER_RUN_ACTOR_RESOLVERS[1],
        },
      },
      "imported-actor": {
        authority: "member-run",
        module: "imported-only.ts",
        reason: "r",
        runActor: {
          module: "actor.ts",
          resolver: MEMBER_RUN_ACTOR_RESOLVERS[1],
        },
      },
      org: automation(),
      open: { authority: "unclassified", module: "m.ts", reason: "why" },
      moved: automation("stale.ts"),
      blank: automation("m.ts", " "),
      ghost: automation(),
    },
    pinnedAllowed: new Set(["pinned.ts"]),
    readFile,
  });
  const expectedErrors = [
    "Scheduler task without an authority row: missing",
    `Declared run actor not found: lost-actor -> m.ts does not call ${MEMBER_RUN_ACTOR_RESOLVERS[0]}`,
    `Declared run actor not found: decoy-actor -> decoy.ts does not call ${MEMBER_RUN_ACTOR_RESOLVERS[1]}`,
    "Declared run actor is off the task's call path: detached-actor -> detached.ts calls nothing from actor.ts",
    "Declared run actor is off the task's call path: imported-actor -> imported-only.ts calls nothing from actor.ts",
    "Declared module is not the one the registry runs: moved -> stale.ts (registry runs real.ts)",
    "Authority row without a reason: blank",
    "Authority row for a task the scheduler registry lacks: ghost",
  ];
  const expectedMembers = [
    "task:no-actor::run-actor",
    "task:no-actor::pinned-handles::pinned.ts",
    "task:open::unclassified",
  ];
  if (JSON.stringify(audit.errors) !== JSON.stringify(expectedErrors)) {
    failures.push(
      `task errors must be exactly ${JSON.stringify(expectedErrors)}; got ${JSON.stringify(audit.errors)}`,
    );
  }
  const memberKeys = audit.members.map(({ key }) => key);
  if (JSON.stringify(memberKeys) !== JSON.stringify(expectedMembers)) {
    failures.push(
      `task members must be exactly ${JSON.stringify(expectedMembers)}; got ${JSON.stringify(memberKeys)}`,
    );
  }
  if (
    audit.members.find(({ key }) => key === "task:open::unclassified")
      ?.reason !== "why"
  ) {
    failures.push("an unclassified task must carry its row's reason");
  }
  return failures;
};

const selfTestWorkerConstructors = (): string[] => {
  const failures: string[] = [];
  const resolved = workerQueueNames(
    "apps/api/src/lib/w.ts",
    SELF_TEST_WORKER,
    (file) => (file === "apps/api/src/lib/names.ts" ? SELF_TEST_NAMES : null),
  );
  if (
    JSON.stringify(resolved) !==
    JSON.stringify(["imported-a", "imported-b", "local"])
  ) {
    failures.push(
      `aliased Worker queue names must resolve through constants and imports; got ${JSON.stringify(resolved)}`,
    );
  }
  if (
    workerQueueNames("w.ts", SELF_TEST_WEB_WORKER, () => null) !== undefined
  ) {
    failures.push("a web Worker must not count as a BullMQ worker");
  }
  if (workerQueueNames("w.ts", SELF_TEST_DYNAMIC_WORKER, () => null) !== null) {
    failures.push("a Worker on a runtime queue name must not resolve");
  }
  for (const source of [
    'import * as queues from "@/api/lib/bullmq-queue"; new queues.BullMqWorker("q", async () => {});',
    'import * as queues from "./bullmq-queue.ts"; new queues["BullMqWorker"]("q", async () => {});',
    'import { BullMqWorker as OwnedWorker } from "./bullmq-queue"; const Alias = OwnedWorker; new Alias("q", async () => {});',
  ]) {
    const names = workerQueueNames("apps/api/src/lib/w.ts", source, () => null);
    if (JSON.stringify(names) !== JSON.stringify(["q"])) {
      failures.push(
        `owned constructor aliases and namespaces must be enumerated; got ${JSON.stringify(names)}`,
      );
    }
  }
  for (const source of [
    'import { Worker } from "bullmq"; new Worker("q", async () => {});',
    'import { Worker as RawWorker } from "bullmq"; const Alias = RawWorker; new Alias("q", async () => {});',
    'import * as queues from "bullmq"; new queues.Worker("q", async () => {});',
    'import type { Worker } from "bullmq";',
    'export { Worker as RawWorker } from "bullmq";',
    'export * from "bullmq";',
    'const { Worker: RawWorker } = await import("bullmq"); new RawWorker("q", async () => {});',
    'const queues = await import("bullmq"); new queues.Worker("q", async () => {});',
    'const { Worker: RawWorker } = require("bullmq"); new RawWorker("q", async () => {});',
  ]) {
    const errors = rawWorkerImports("apps/api/src/lib/w.ts", source);
    if (errors.length !== 1) {
      failures.push(
        `raw worker imports must be confined to the constructor owner; got ${JSON.stringify(errors)}`,
      );
    }
    if (rawWorkerImports(HOST_TABLE_FILE, source).length !== 0) {
      failures.push("the constructor owner must be admitted");
    }
  }
  for (const source of [
    'import { Queue, type Job } from "bullmq";',
    'const { Queue } = await import("bullmq");',
    'const Queue = (await import("bullmq")).Queue;',
    'const { Queue } = require("bullmq");',
  ]) {
    if (rawWorkerImports("apps/api/src/lib/w.ts", source).length !== 0) {
      failures.push("other BullMQ exports must remain available");
    }
  }
  const straySource =
    'import * as queues from "@/api/lib/bullmq-queue"; new queues.BullMqWorker("stray", async () => {});';
  const strayQueues = workerQueueNames(
    "apps/api/src/lib/stray.ts",
    straySource,
    () => null,
  );
  const strayAudit = auditQueueAuthority({
    hostQueues: ["q"],
    registry: {
      q: {
        authority: "org-automation",
        worker: "apps/api/src/lib/w.ts",
        reason: "r",
      },
    },
    memberRunQueues: [],
    workerQueues: new Map([
      ["apps/api/src/lib/w.ts", ["q"]],
      ["apps/api/src/lib/stray.ts", strayQueues ?? null],
    ]),
    pinnedAllowed: new Set(),
    readFile: () => null,
  });
  if (
    JSON.stringify(strayQueues) !== JSON.stringify(["stray"]) ||
    JSON.stringify(strayAudit.errors) !==
      JSON.stringify([
        "BullMQ Worker outside the queue authority registry: apps/api/src/lib/stray.ts (stray)",
      ])
  ) {
    failures.push(
      "an enumerated owned worker on an unregistered queue must fail",
    );
  }
  return failures;
};

const selfTest = (): number => {
  const failures: string[] = [];
  const files: Record<string, string> = {
    "on-actor.ts": SELF_TEST_ACTOR,
    "pinned.ts": "createRootScopedDb({});",
    "executor.ts": "createRootSafeDb({});",
    "org.ts": "",
    "stray.ts": "",
    "on-actor.integration.test.ts": SELF_TEST_REVOCATION,
    "half.integration.test.ts": `${SELF_TEST_BUN_TEST}${revocationCase(MEMBER_RUN_REVOCATION_CASES[0])}`,
  };
  const entry = (
    authority: QueueAuthorityEntry["authority"],
    worker: string,
    extra: Partial<QueueAuthorityEntry> = {},
  ): QueueAuthorityEntry => ({ authority, worker, reason: "r", ...extra });
  const audit = auditQueueAuthority({
    hostQueues: ["actor", "pinned", "org", "half", "unclassified"],
    registry: {
      actor: entry("member-run", "on-actor.ts", {
        revocationTest: "on-actor.integration.test.ts",
      }),
      pinned: entry("member-run", "pinned.ts", { executors: ["executor.ts"] }),
      org: entry("org-automation", "org.ts"),
      half: entry("member-run", "on-actor.ts", {
        revocationTest: "half.integration.test.ts",
      }),
      ghost: entry("org-automation", "org.ts", { reason: " " }),
    },
    memberRunQueues: [
      { queue: "actor", module: "on-actor.ts" },
      { queue: "half", module: "on-actor.ts" },
      { queue: "org", module: "org.ts" },
    ],
    workerQueues: new Map([
      ["on-actor.ts", ["actor", "half"]],
      ["pinned.ts", ["pinned"]],
      ["org.ts", ["ghost", "org"]],
      ["stray.ts", ["stray"]],
    ]),
    pinnedAllowed: new Set(["executor.ts", "pinned.ts"]),
    readFile: (file) => files[file] ?? null,
  });
  const expectedErrors = [
    "Queue without an authority row: unclassified",
    "Authority row for a queue the host table lacks: ghost",
    "Authority row without a reason: ghost",
    "BullMQ Worker outside the queue authority registry: stray.ts (stray)",
    "MEMBER_RUN_QUEUES lists org (org.ts), but the registry does not classify it as a member run of that module",
  ];
  const expectedMembers = [
    "half::revocation-test",
    "pinned::pinned-handles::executor.ts",
    "pinned::pinned-handles::pinned.ts",
    "pinned::revocation-test",
    "pinned::run-actor",
  ];
  if (JSON.stringify(audit.errors) !== JSON.stringify(expectedErrors)) {
    failures.push(
      `errors must be exactly ${JSON.stringify(expectedErrors)}; got ${JSON.stringify(audit.errors)}`,
    );
  }
  const memberKeys = audit.members.map(({ key }) => key);
  if (JSON.stringify(memberKeys) !== JSON.stringify(expectedMembers)) {
    failures.push(
      `members must be exactly ${JSON.stringify(expectedMembers)}; got ${JSON.stringify(memberKeys)}`,
    );
  }
  const declaredMissing = auditQueueAuthority({
    hostQueues: ["q"],
    registry: { q: entry("org-automation", "missing.ts") },
    memberRunQueues: [],
    workerQueues: new Map(),
    pinnedAllowed: new Set(),
    readFile: () => null,
  });
  if (declaredMissing.errors.length !== 1) {
    failures.push("a declared worker that constructs no Worker must fail");
  }
  // Two rows pointing at each other's modules: module membership is
  // unchanged, so only the queue-to-worker pairs reveal the swap.
  const swapped = auditQueueAuthority({
    hostQueues: ["member", "org"],
    registry: {
      member: entry("member-run", "org.ts"),
      org: entry("org-automation", "member.ts"),
    },
    memberRunQueues: [],
    workerQueues: new Map([
      [
        "member.ts",
        workerQueueNames("member.ts", workerOn("member"), () => null) ?? null,
      ],
      [
        "org.ts",
        workerQueueNames("org.ts", workerOn("org"), () => null) ?? null,
      ],
    ]),
    pinnedAllowed: new Set(),
    readFile: () => null,
  });
  const expectedSwap = [
    "Declared worker module has no Worker on its queue: member -> org.ts",
    "Declared worker module has no Worker on its queue: org -> member.ts",
    "BullMQ Worker on member in member.ts, but the registry assigns it to org.ts",
    "BullMQ Worker on org in org.ts, but the registry assigns it to member.ts",
  ];
  if (JSON.stringify(swapped.errors) !== JSON.stringify(expectedSwap)) {
    failures.push(
      `swapped worker rows must fail as ${JSON.stringify(expectedSwap)}; got ${JSON.stringify(swapped.errors)}`,
    );
  }
  failures.push(...selfTestWorkerConstructors());
  const unresolved = auditQueueAuthority({
    hostQueues: [],
    registry: {},
    memberRunQueues: [],
    workerQueues: new Map([["dynamic.ts", null]]),
    pinnedAllowed: new Set(),
    readFile: () => null,
  });
  if (unresolved.errors.length !== 1) {
    failures.push("an unresolved Worker queue name must fail");
  }
  if (!callsRunActor(SELF_TEST_ACTOR)) {
    failures.push("an aliased run actor call must count");
  }
  if (callsRunActor(SELF_TEST_ACTOR_TEXT_ONLY)) {
    failures.push(
      "run actor text in comments, strings or a local function must not count",
    );
  }
  for (const [index, source] of SELF_TEST_INACTIVE_REVOCATIONS.entries()) {
    const gap = revocationGap(
      entry("member-run", "w.ts", { revocationTest: "r.integration.test.ts" }),
      () => source,
    );
    if (gap === null) {
      failures.push(`inactive revocation case ${String(index)} must not count`);
    }
  }
  if (
    revocationGap(
      entry("member-run", "w.ts", { revocationTest: "r.test.ts" }),
      () => SELF_TEST_REVOCATION,
    ) === null
  ) {
    failures.push(
      "a revocation test outside *.integration.test.ts must not count",
    );
  }
  const keys = objectKeys(
    `const T = { "a-b": "api", c: "x" } as const satisfies Record<string, string>;`,
    "T",
  );
  if (JSON.stringify(keys) !== JSON.stringify(["a-b", "c"])) {
    failures.push(`host table keys must be read; got ${JSON.stringify(keys)}`);
  }
  const difference = baselineDifference(["a", "b"], ["b", "c"]);
  if (
    JSON.stringify(difference) !==
    JSON.stringify({ added: ["a"], stale: ["c"] })
  ) {
    failures.push("a new and a stale baseline row must both be reported");
  }
  if (addedEntries(["x::run-actor"], ["y::run-actor"]).length !== 1) {
    failures.push("a row the base does not list must count as new");
  }
  failures.push(...selfTestSchedulerTasks());
  for (const failure of failures) {
    console.error(`queue-authority --self-test: ${failure}`);
  }
  if (failures.length === 0) {
    console.log("queue-authority --self-test: PASS");
  }
  return failures.length === 0 ? 0 : 1;
};

if (import.meta.main) {
  const args = process.argv.slice(2);
  if (args.includes("--self-test")) {
    process.exit(selfTest());
  }
  if (args.includes("--write")) {
    process.exit(write());
  }
  process.exit(check(args.filter((arg) => arg !== "--check")));
}
