import * as v from "valibot";

export const SELFHOST_COMPOSE_PATH = "docker-compose.selfhost.yml";
export const SELFHOST_ENV_EXAMPLE_PATH = "deploy/selfhost/.env.example";
export const SELFHOST_ENV_PATH = "deploy/selfhost/.env";

export const SELFHOST_COMPOSE_ENV = {
  apiEnvFile: "STELLA_API_ENV_FILE",
  applicationImage: "STELLA_API_IMAGE",
  gotenbergPassword: "GOTENBERG_PASSWORD",
  gotenbergUsername: "GOTENBERG_USERNAME",
  signupRateLimitIpSource: "STELLA_SIGNUP_RATE_LIMIT_IP_SOURCE",
} as const;

export const SELFHOST_APPLICATION_IMAGE_EXPRESSION = `\${${SELFHOST_COMPOSE_ENV.applicationImage}:?set ${SELFHOST_COMPOSE_ENV.applicationImage} to a digest-qualified image}`;
export const SELFHOST_GOTENBERG_IMAGE =
  "gotenberg/gotenberg:8.36.0@sha256:87c16b9f364279d321bc9772d31fa58aa6abe036423c270698bd636c3a8e9466";

export const SELFHOST_SERVICE = {
  api: "api",
  documentProcessingWorker: "document-processing-worker",
  gotenberg: "gotenberg",
} as const;

export type SelfhostService =
  (typeof SELFHOST_SERVICE)[keyof typeof SELFHOST_SERVICE];

type SelfhostServiceContract =
  | {
      type: "http-api";
      description: string;
      image: "application";
      readiness: "/ready";
    }
  | {
      type: "queue-worker";
      command: readonly ["bun", "/app/document-processing-worker.js"];
      description: string;
      image: "application";
      readiness: "api-ready";
    }
  | {
      type: "document-converter";
      description: string;
      image: "gotenberg";
      readiness: "/health";
    };

export const SELFHOST_SERVICE_CONTRACT = {
  [SELFHOST_SERVICE.api]: {
    type: "http-api",
    description: "HTTP API and the authoritative scheduled-job loop",
    image: "application",
    readiness: "/ready",
  },
  [SELFHOST_SERVICE.documentProcessingWorker]: {
    type: "queue-worker",
    command: ["bun", "/app/document-processing-worker.js"],
    description: "Durable document-processing queue consumer",
    image: "application",
    readiness: "api-ready",
  },
  [SELFHOST_SERVICE.gotenberg]: {
    type: "document-converter",
    description: "Private authenticated document-conversion sidecar",
    image: "gotenberg",
    readiness: "/health",
  },
} as const satisfies Record<SelfhostService, SelfhostServiceContract>;

const API_READINESS_COMMAND =
  "const response = await fetch('http://127.0.0.1:3001/ready', { signal: AbortSignal.timeout(4000) }); if (!response.ok) process.exit(1);";
const WORKER_READINESS_COMMAND =
  "const response = await fetch('http://api:3001/ready', { signal: AbortSignal.timeout(4000) }); if (!response.ok) process.exit(1);";

const generatedHeader = (command: string) =>
  `# Generated by \`${command}\`; edit scripts/selfhost-contract.ts instead.\n`;

export const renderSelfhostCompose = () => `${generatedHeader(
  "bun run selfhost:generate",
)}services:
  ${SELFHOST_SERVICE.api}:
    image: ${SELFHOST_APPLICATION_IMAGE_EXPRESSION}
    env_file:
      - \${${SELFHOST_COMPOSE_ENV.apiEnvFile}:-${SELFHOST_ENV_PATH}}
    environment:
      NODE_ENV: production
      STELLA_SIGNUP_RATE_LIMIT_IP_SOURCE: \${${SELFHOST_COMPOSE_ENV.signupRateLimitIpSource}:-direct}
    ports:
      - "\${STELLA_API_HOST_PORT:-3001}:3001"
    depends_on:
      ${SELFHOST_SERVICE.gotenberg}:
        condition: service_healthy
    healthcheck:
      test:
        - CMD
        - bun
        - -e
        - "${API_READINESS_COMMAND}"
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    pids_limit: \${STELLA_API_PIDS_LIMIT:-512}
    mem_limit: \${STELLA_API_MEM_LIMIT:-2g}
    cpus: \${STELLA_API_CPUS:-2.0}

  ${SELFHOST_SERVICE.documentProcessingWorker}:
    image: ${SELFHOST_APPLICATION_IMAGE_EXPRESSION}
    env_file:
      - \${${SELFHOST_COMPOSE_ENV.apiEnvFile}:-${SELFHOST_ENV_PATH}}
    environment:
      NODE_ENV: production
    command:
      - bun
      - /app/document-processing-worker.js
    depends_on:
      ${SELFHOST_SERVICE.api}:
        condition: service_healthy
    healthcheck:
      test:
        - CMD
        - bun
        - -e
        - "${WORKER_READINESS_COMMAND}"
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    pids_limit: \${STELLA_DOCUMENT_PROCESSING_WORKER_PIDS_LIMIT:-256}
    mem_limit: \${STELLA_DOCUMENT_PROCESSING_WORKER_MEM_LIMIT:-1g}
    cpus: \${STELLA_DOCUMENT_PROCESSING_WORKER_CPUS:-1.0}

  ${SELFHOST_SERVICE.gotenberg}:
    image: ${SELFHOST_GOTENBERG_IMAGE}
    environment:
      API_ENABLE_BASIC_AUTH: "true"
      GOTENBERG_API_BASIC_AUTH_USERNAME: \${${SELFHOST_COMPOSE_ENV.gotenbergUsername}:?set ${SELFHOST_COMPOSE_ENV.gotenbergUsername} in ${SELFHOST_ENV_PATH}}
      GOTENBERG_API_BASIC_AUTH_PASSWORD: \${${SELFHOST_COMPOSE_ENV.gotenbergPassword}:?set ${SELFHOST_COMPOSE_ENV.gotenbergPassword} in ${SELFHOST_ENV_PATH}}
    healthcheck:
      test:
        - CMD-SHELL
        - 'curl -fsS -H "Authorization: Basic $$(printf "%s" "$\${GOTENBERG_API_BASIC_AUTH_USERNAME}:$\${GOTENBERG_API_BASIC_AUTH_PASSWORD}" | base64 | tr -d "\\n")" http://localhost:3000/health'
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    pids_limit: \${STELLA_GOTENBERG_PIDS_LIMIT:-1024}
    mem_limit: \${STELLA_GOTENBERG_MEM_LIMIT:-1g}
    cpus: \${STELLA_GOTENBERG_CPUS:-1.0}
`;

const commandSchema = v.array(v.string());
const composeServiceSchema = v.looseObject({
  image: v.string(),
  command: v.optional(commandSchema),
  depends_on: v.optional(v.record(v.string(), v.unknown())),
  healthcheck: v.optional(
    v.looseObject({
      test: v.union([v.string(), commandSchema]),
    }),
  ),
});
const composeSchema = v.object({
  services: v.record(v.string(), composeServiceSchema),
});

const sameCommand = (
  actual: readonly string[] | undefined,
  expected: readonly string[],
) => JSON.stringify(actual) === JSON.stringify(expected);

const healthcheckCommand = (
  services: v.InferOutput<typeof composeSchema>["services"],
  service: SelfhostService,
) => {
  const test = services[service]?.healthcheck?.test;
  return Array.isArray(test) ? test : undefined;
};

export const selfhostComposeViolations = (text: string): string[] => {
  const decoded = v.safeParse(composeSchema, Bun.YAML.parse(text));
  if (!decoded.success) {
    return ["Compose does not match the typed self-host schema."];
  }

  const { services } = decoded.output;
  const declaredServices = Object.keys(services).toSorted();
  const expectedServices = Object.keys(SELFHOST_SERVICE_CONTRACT).toSorted();
  const violations: string[] = [];
  if (JSON.stringify(declaredServices) !== JSON.stringify(expectedServices)) {
    violations.push(
      `Compose services must be exactly: ${expectedServices.join(", ")}.`,
    );
  }

  for (const service of [
    SELFHOST_SERVICE.api,
    SELFHOST_SERVICE.documentProcessingWorker,
  ] as const) {
    if (services[service]?.image !== SELFHOST_APPLICATION_IMAGE_EXPRESSION) {
      violations.push(`${service} must use the required application image.`);
    }
  }
  if (
    services[SELFHOST_SERVICE.gotenberg]?.image !== SELFHOST_GOTENBERG_IMAGE
  ) {
    violations.push("gotenberg must use the contract's digest-pinned image.");
  }

  const worker = services[SELFHOST_SERVICE.documentProcessingWorker];
  if (
    !sameCommand(
      worker?.command,
      SELFHOST_SERVICE_CONTRACT[SELFHOST_SERVICE.documentProcessingWorker]
        .command,
    )
  ) {
    violations.push("document-processing-worker has the wrong command.");
  }
  if (
    !sameCommand(healthcheckCommand(services, SELFHOST_SERVICE.api), [
      "CMD",
      "bun",
      "-e",
      API_READINESS_COMMAND,
    ])
  ) {
    violations.push("api healthcheck must probe /ready.");
  }
  if (
    !sameCommand(
      healthcheckCommand(services, SELFHOST_SERVICE.documentProcessingWorker),
      ["CMD", "bun", "-e", WORKER_READINESS_COMMAND],
    )
  ) {
    violations.push("document-processing-worker must depend on API readiness.");
  }
  if (services[SELFHOST_SERVICE.gotenberg]?.healthcheck === undefined) {
    violations.push("gotenberg must declare a healthcheck.");
  }
  return violations;
};

export const RELEASE_ARTIFACT = {
  apiImage: {
    name: "API image",
    portability: "portable",
    manifestKey: "image",
  },
  webImage: {
    name: "Web image",
    portability: "target-bound",
    manifestKey: "webImage",
  },
} as const;

export const SELFHOST_DOC_MARKERS = {
  begin: "<!-- BEGIN GENERATED SELF-HOST CONTRACT -->",
  end: "<!-- END GENERATED SELF-HOST CONTRACT -->",
} as const;

export const SELFHOST_RUN_DOC_MARKERS = {
  begin: "<!-- BEGIN GENERATED SELF-HOST RUN COMMANDS -->",
  end: "<!-- END GENERATED SELF-HOST RUN COMMANDS -->",
} as const;

export const RELEASE_DOC_MARKERS = {
  begin: "<!-- BEGIN GENERATED RELEASE ARTIFACT CONTRACT -->",
  end: "<!-- END GENERATED RELEASE ARTIFACT CONTRACT -->",
} as const;

export const renderSelfhostDocsContract = () => {
  const rows = Object.entries(SELFHOST_SERVICE_CONTRACT).map(
    ([name, contract]) =>
      `- \`${name}\`: ${contract.description}; readiness \`${contract.readiness}\`.`,
  );
  return [
    SELFHOST_DOC_MARKERS.begin,
    "",
    "The production Compose contract contains exactly these services:",
    "",
    ...rows,
    "",
    `Its generated environment template is \`${SELFHOST_ENV_EXAMPLE_PATH}\`.`,
    SELFHOST_DOC_MARKERS.end,
  ].join("\n");
};

export const renderSelfhostRunDocsContract = () =>
  [
    SELFHOST_RUN_DOC_MARKERS.begin,
    "```bash",
    "bun run selfhost:doctor",
    "docker compose --env-file deploy/selfhost/.env \\",
    "  -f docker-compose.selfhost.yml config --quiet",
    "docker compose --env-file deploy/selfhost/.env \\",
    "  -f docker-compose.selfhost.yml run --rm --no-deps api \\",
    "  bun /app/apps/api/src/db/migrate.js",
    "docker compose --env-file deploy/selfhost/.env \\",
    "  -f docker-compose.selfhost.yml up -d",
    "```",
    SELFHOST_RUN_DOC_MARKERS.end,
  ].join("\n");

export const renderReleaseDocsContract = () =>
  [
    RELEASE_DOC_MARKERS.begin,
    "",
    "Each release publishes two container artifacts:",
    "",
    `- The ${RELEASE_ARTIFACT.apiImage.name} is portable and is the image used by the self-host`,
    "  Compose contract.",
    `- The ${RELEASE_ARTIFACT.webImage.name} is built for the release workflow's selected hosted`,
    "  target environment; self-hosted operators must build the web image with",
    "  their own public URLs.",
    `- \`release-manifest.json\` records both \`${RELEASE_ARTIFACT.apiImage.manifestKey}\` and \`${RELEASE_ARTIFACT.webImage.manifestKey}\` with`,
    "  digest-qualified references.",
    "",
    RELEASE_DOC_MARKERS.end,
  ].join("\n");
