import { panic } from "better-result";
import { expect, test } from "bun:test";
import {
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";

const root = path.resolve(import.meta.dir, "../../..");
const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === "object" && value !== null && !Array.isArray(value);

test("ignored API types restore from Turbo cache and API source edits invalidate it", () => {
  const parsed: unknown = Bun.JSONC.parse(
    readFileSync(path.join(root, "turbo.json"), "utf-8"),
  );
  if (!isRecord(parsed) || !isRecord(parsed["tasks"])) {
    panic("Turbo configuration has no tasks");
  }
  const tasks = parsed["tasks"];
  const directory = mkdtempSync(
    path.join(tmpdir(), "stella-web-generation-cache-"),
  );
  const write = (filename: string, content: string) => {
    const filenamePath = path.join(directory, filename);
    mkdirSync(path.dirname(filenamePath), { recursive: true });
    writeFileSync(filenamePath, content);
  };
  const run = (command: string[]) => {
    const child = Bun.spawnSync(command, {
      cwd: directory,
      env: { ...process.env, TURBO_TELEMETRY_DISABLED: "1" },
      stdout: "pipe",
      stderr: "pipe",
    });
    expect(child.exitCode, child.stderr.toString()).toBe(0);
  };
  try {
    write(
      "package.json",
      JSON.stringify({
        name: "cache-fixture",
        private: true,
        packageManager: "bun@1.4.2",
        workspaces: ["apps/*"],
      }),
    );
    write(
      "apps/web/package.json",
      JSON.stringify({
        name: "@stll/web",
        scripts: {
          "generate:api-types": "bun ../api/scripts/generate-web-api-types.ts",
        },
      }),
    );
    write("apps/api/package.json", JSON.stringify({ name: "@stll/api" }));
    write(
      ".gitignore",
      ".turbo/\napps/web/src/generated/api-routes.gen.ts\nruns.log\n",
    );
    write("apps/api/src/contract.ts", "export type Contract = string;\n");
    const generator = (output: string) =>
      `import { appendFileSync, mkdirSync, writeFileSync } from 'node:fs';\nmkdirSync('src/generated', { recursive: true });\nwriteFileSync(${JSON.stringify(output)}, 'generated bytes\\n');\nappendFileSync('../../runs.log', ${JSON.stringify(`${output}\n`)});\n`;
    write(
      "apps/api/scripts/generate-web-api-types.ts",
      generator("src/generated/api-routes.gen.ts"),
    );
    write(
      "turbo.json",
      JSON.stringify({
        tasks: {
          "@stll/web#generate:api-types": tasks["@stll/web#generate:api-types"],
        },
      }),
    );
    run(["git", "init", "--quiet"]);
    write(
      "bun.lock",
      JSON.stringify({
        lockfileVersion: 3,
        configVersion: 1,
        workspaces: {
          "": { name: "cache-fixture" },
          "apps/api": { name: "@stll/api" },
          "apps/web": { name: "@stll/web" },
        },
        packages: {},
      }),
    );
    const command = [
      path.join(root, "node_modules/.bin/turbo"),
      "run",
      "generate:api-types",
      "--filter=@stll/web",
      "--cache=local:rw",
    ];
    run(command);
    const executions = readFileSync(path.join(directory, "runs.log"), "utf-8");
    const output = path.join(
      directory,
      "apps/web/src/generated/api-routes.gen.ts",
    );
    run(["git", "check-ignore", "apps/web/src/generated/api-routes.gen.ts"]);
    rmSync(output);
    run(command);
    expect(readFileSync(path.join(directory, "runs.log"), "utf-8")).toBe(
      executions,
    );
    expect(readFileSync(output, "utf-8")).toBe("generated bytes\n");
    write("apps/api/src/contract.ts", "export type Contract = number;\n");
    run(command);
    expect(
      readFileSync(path.join(directory, "runs.log"), "utf-8")
        .split("\n")
        .filter(Boolean),
    ).toHaveLength(2);
  } finally {
    rmSync(directory, { recursive: true, force: true });
  }
}, 30_000);
