import { Result, TaggedError } from "better-result";

import type { Transaction } from "@/api/db/root";
import type { SafeDb } from "@/api/db/safe-db";
import { computeVersionDiffStats } from "@/api/handlers/entities/compute-version-diff";
import { writeFileVersion } from "@/api/handlers/entities/write-file-version";
import type { WriteFileVersionResult } from "@/api/handlers/entities/write-file-version";
import { allocateFileObject } from "@/api/handlers/files/file-object-ids";
import { createFileKey } from "@/api/handlers/files/utils";
import { captureError } from "@/api/lib/analytics/capture";
import type { AuditRecorder } from "@/api/lib/audit-log";
import { createSafeId } from "@/api/lib/branded-types";
import type { SafeId } from "@/api/lib/branded-types";
import type { DocumentSource } from "@/api/lib/document-source";
import {
  enqueueImageThumbnailOrMarkFailed,
  enqueuePdfDerivativeOrMarkFailed,
} from "@/api/lib/file-derivative-queue";
import { FILE_SIZE_LIMIT_BYTES } from "@/api/lib/limits";
import { createRootScopedDb } from "@/api/lib/root-scoped-db";
import { getS3 } from "@/api/lib/s3";
import { sanitizeFilenamePreservingExtension } from "@/api/lib/sanitize-filename";
import { processExtraction } from "@/api/lib/search/process-extraction";
import { broadcast } from "@/api/lib/sse";

class EntityVersionTargetError extends TaggedError("EntityVersionTargetError")<{
  code:
    | "current-version-not-found"
    | "document-too-large"
    | "entity-not-found"
    | "entity-read-only"
    | "missing-file-field";
  message: string;
}>() {}

type EntityVersionTargetErrorCode = EntityVersionTargetError["code"];

type CreateEntityVersionFromBufferInput = {
  safeDb: SafeDb;
  organizationId: SafeId<"organization">;
  workspaceId: SafeId<"workspace">;
  entityId: SafeId<"entity">;
  userId: SafeId<"user">;
  recordAuditEvent: AuditRecorder;
  buffer: Uint8Array | ArrayBuffer;
  fileName: string;
  mimeType: string;
  source: DocumentSource | null;
  scanWarnings?: string[] | undefined;
  afterWrite?:
    | ((
        tx: Transaction,
        result: Extract<WriteFileVersionResult, { status: "ok" }>,
      ) => Promise<void>)
    | undefined;
};

export type CreateEntityVersionFromBufferResult = Result<
  {
    entityId: SafeId<"entity">;
    entityVersionId: SafeId<"entityVersion">;
    fieldId: SafeId<"field">;
    fileName: string;
    versionNumber: number;
  },
  EntityVersionTargetError
>;

const ENTITY_VERSION_TARGET_MESSAGES = {
  "entity-not-found": "Entity not found",
  "entity-read-only": "Entity is read-only",
  "current-version-not-found": "Current version not found",
  "document-too-large": `Document exceeds the ${FILE_SIZE_LIMIT_BYTES.document}-byte size limit`,
  "missing-file-field": "Entity has no file field",
} satisfies Record<EntityVersionTargetErrorCode, string>;

const messageForStatus = (status: EntityVersionTargetErrorCode): string =>
  ENTITY_VERSION_TARGET_MESSAGES[status];

/** Persist trusted server-generated bytes as a new version of an entity. */
export const createEntityVersionFromBuffer = async ({
  safeDb,
  organizationId,
  workspaceId,
  entityId,
  userId,
  recordAuditEvent,
  buffer,
  fileName: rawFileName,
  mimeType,
  source,
  scanWarnings,
  afterWrite,
}: CreateEntityVersionFromBufferInput): Promise<CreateEntityVersionFromBufferResult> => {
  const bytes = buffer instanceof Uint8Array ? buffer : new Uint8Array(buffer);
  if (bytes.byteLength > FILE_SIZE_LIMIT_BYTES.document) {
    return Result.err(
      new EntityVersionTargetError({
        code: "document-too-large",
        message: messageForStatus("document-too-large"),
      }),
    );
  }

  const fileName = sanitizeFilenamePreservingExtension(rawFileName);
  const fileId = allocateFileObject();
  const entityVersionId = createSafeId<"entityVersion">();
  const fieldId = createSafeId<"field">();
  const sha256Hex = new Bun.CryptoHasher("sha256").update(bytes).digest("hex");
  const objectKey = createFileKey({
    organizationId,
    workspaceId,
    fileId,
    mimeType,
  });

  const cleanupObject = async (): Promise<void> => {
    await getS3()
      .delete(objectKey)
      .catch((cleanupError: unknown) => {
        captureError(cleanupError, { entityId, objectKey });
      });
  };

  try {
    await getS3().write(objectKey, bytes);
  } catch (error) {
    // A timeout or connection failure can be ambiguous: object storage may
    // have accepted the complete object even though the client saw an error.
    // Best-effort deletion prevents an unreferenced final-key object.
    await cleanupObject();
    throw error;
  }

  const writeResult = await safeDb(
    async (tx) =>
      await writeFileVersion({
        tx,
        workspaceId,
        entityId,
        userId,
        recordAuditEvent,
        entityVersionId,
        fieldId,
        fileId,
        fileName,
        mimeType,
        sizeBytes: bytes.byteLength,
        sha256Hex,
        source,
        scanWarnings,
        ...(afterWrite !== undefined && {
          afterWrite: async (result) => await afterWrite(tx, result),
        }),
      }),
  );
  if (Result.isError(writeResult)) {
    await cleanupObject();
    throw writeResult.error;
  }
  const written = writeResult.value;

  if (written.status !== "ok") {
    await cleanupObject();
    return Result.err(
      new EntityVersionTargetError({
        code: written.status,
        message: messageForStatus(written.status),
      }),
    );
  }

  processExtraction(entityId).catch((error: unknown) => {
    captureError(error, { entityId });
  });
  enqueuePdfDerivativeOrMarkFailed({
    encrypted: false,
    entityId,
    fieldId,
    mimeType,
    organizationId,
    userId,
    workspaceId,
  }).catch((error: unknown) => {
    captureError(error, { entityId, fieldId, mimeType });
  });
  enqueueImageThumbnailOrMarkFailed({
    encrypted: false,
    entityId,
    fieldId,
    mimeType,
    organizationId,
    userId,
    workspaceId,
  }).catch((error: unknown) => {
    captureError(error, { entityId, fieldId, mimeType });
  });
  computeVersionDiffStats({
    versionId: entityVersionId,
    entityId,
    scopedDb: createRootScopedDb({
      organizationId,
      userId,
      workspaceIds: [workspaceId],
    }),
    workspaceId,
    organizationId,
  }).catch((error: unknown) => {
    captureError(error, { versionId: entityVersionId });
  });
  broadcast(workspaceId, {
    type: "invalidate-query",
    data: ["entities", workspaceId],
  });

  return Result.ok({
    entityId,
    entityVersionId,
    fieldId,
    fileName,
    versionNumber: written.versionNumber,
  });
};
