// Dev-only exporter: projects the MCP tool registry
// (`DEFAULT_MCP_TOOL_DEFINITIONS`) down to the four `tools/list` wire fields and
// writes a JSON snapshot that `@stll/cli`'s codegen consumes.
//
// Why a snapshot instead of importing the registry from `@stll/cli` directly:
// `static-tool-definitions.ts` transitively imports `@/api/env`, which eagerly
// validates the full API environment (REDIS_URL, BETTER_AUTH_*, GOTENBERG_*,
// ...) at module load. Running that inside `apps/api` (where the env resolves)
// and emitting a plain JSON file keeps the published `@stll/cli` package free of
// any import — type or value — reachable from `apps/api`. Regenerate with
// `bun run codegen` from `packages/cli` (which runs this first, then the pure
// generator). The snapshot is committed, so registry drift shows up as a diff.

import {
  MCP_DEFAULT_RESOURCE_SCOPES,
  MCP_DISCOVERY_PATH,
  MCP_HTTP_PATH,
  MCP_OAUTH_PROTOCOL_SCOPES,
  STELLA_API_CONTRACT,
} from "@/api/mcp/constants";
import { MCP_ERROR_CODES } from "@/api/mcp/error-codes";
import { listMcpResources } from "@/api/mcp/resources";
import { DEFAULT_MCP_CLI_ANNOTATIONS } from "@/api/mcp/static-cli-metadata";
import { DEFAULT_MCP_TOOL_DEFINITIONS } from "@/api/mcp/static-tool-definitions";
import {
  MCP_CLI_TOOL_SCOPES,
  type McpCliToolAnnotation,
} from "@/api/mcp/tool-types";

// The four wire fields exposed by `tools/list` (scope/feature/access/anonymized
// are server-internal and never leave the server).
type RegistryToolListing = {
  cli: McpCliToolAnnotation;
  name: string;
  description: string;
  inputSchema: unknown;
  annotations?: unknown;
};

const listings: RegistryToolListing[] = [];
for (const tool of DEFAULT_MCP_TOOL_DEFINITIONS) {
  listings.push({
    cli: DEFAULT_MCP_CLI_ANNOTATIONS[tool.name],
    name: tool.name,
    description: tool.description,
    inputSchema: tool.inputSchema,
    annotations: tool.annotations,
  });
}

const snapshotPath = new URL(
  "../../../packages/cli/src/generated/registry-snapshot.json",
  import.meta.url,
);

await Bun.write(snapshotPath, `${JSON.stringify(listings, null, 2)}\n`);

process.stderr.write(
  `Wrote ${listings.length} tool listings to ${snapshotPath.pathname}\n`,
);

// The resource surface (spec 051 S5.4) is generated the same way: project
// `resources/list` to its wire fields so the CLI's `reference` tree never drifts
// from the server's static resources. The set is mode-independent; export the
// default-mode projection.
type ResourceListing = {
  uri: string;
  name: string;
  title?: string;
  description?: string;
  mimeType?: string;
};

const resourceListings: ResourceListing[] = [];
for (const resource of listMcpResources("default")) {
  const listing: ResourceListing = { uri: resource.uri, name: resource.name };
  if (resource.title !== undefined) {
    listing.title = resource.title;
  }
  if (resource.description !== undefined) {
    listing.description = resource.description;
  }
  if (resource.mimeType !== undefined) {
    listing.mimeType = resource.mimeType;
  }
  resourceListings.push(listing);
}

const resourceSnapshotPath = new URL(
  "../../../packages/cli/src/generated/resources-snapshot.json",
  import.meta.url,
);

await Bun.write(
  resourceSnapshotPath,
  `${JSON.stringify(resourceListings, null, 2)}\n`,
);

process.stderr.write(
  `Wrote ${resourceListings.length} resource listings to ${resourceSnapshotPath.pathname}\n`,
);

// The published CLI cannot depend on the private workspace API-contract
// package. Copy this dependency-free transport contract verbatim into its
// committed generated tree instead. API, MCP App and CLI therefore compile
// from one source file, while the existing codegen-diff guard catches a stale
// CLI projection.
const uploadTransportSourcePath = new URL(
  "../../../packages/api-contract/src/document-version-upload.ts",
  import.meta.url,
);
const uploadTransportOutputPath = new URL(
  "../../../packages/cli/src/generated/document-version-upload-transport.ts",
  import.meta.url,
);
const uploadTransportSource = await Bun.file(uploadTransportSourcePath).text();
await Bun.write(
  uploadTransportOutputPath,
  `// GENERATED by \`bun run codegen\`. Do not edit by hand.\n${uploadTransportSource}`,
);
process.stderr.write(`Wrote ${uploadTransportOutputPath.pathname}\n`);

// Bake the API-owned compatibility contract into the CLI. Published CLIs keep
// their generated minimum revision while the server can advance independently;
// Changesets package-version bumps never touch this contract.
const apiContractOutputPath = new URL(
  "../../../packages/cli/src/generated/api-contract.ts",
  import.meta.url,
);
await Bun.write(
  apiContractOutputPath,
  `// GENERATED by \`bun run codegen\`. Do not edit by hand.

export const CLI_SUPPORTED_API_PROTOCOLS = [${STELLA_API_CONTRACT.protocol}] as const;
export const CLI_MINIMUM_SERVER_REVISION = ${STELLA_API_CONTRACT.revision};
export const CLI_REQUIRED_CAPABILITIES = ${JSON.stringify(STELLA_API_CONTRACT.capabilities, null, 2)} as const;
`,
);
process.stderr.write(`Wrote ${apiContractOutputPath.pathname}\n`);

// The CLI is published independently and cannot import the private API
// workspace. Generate its stable MCP wire constants from the API-owned values
// instead of maintaining handwritten mirrors guarded by source-text tests.
const mcpContractOutputPath = new URL(
  "../../../packages/cli/src/generated/mcp-contract.ts",
  import.meta.url,
);
const cliKnownScopes = [
  ...MCP_OAUTH_PROTOCOL_SCOPES,
  ...MCP_DEFAULT_RESOURCE_SCOPES,
];
await Bun.write(
  mcpContractOutputPath,
  `// GENERATED by \`bun run codegen\`. Do not edit by hand.

export const MCP_HTTP_PATH = ${JSON.stringify(MCP_HTTP_PATH)} as const;
export const MCP_DISCOVERY_PATH = ${JSON.stringify(MCP_DISCOVERY_PATH)} as const;
export const CLI_KNOWN_SCOPES = ${JSON.stringify(cliKnownScopes, null, 2)} as const;
export const CLI_REQUIRED_RESOURCE_SCOPES = ${JSON.stringify(MCP_DEFAULT_RESOURCE_SCOPES, null, 2)} as const;
export const MCP_ERROR_CODES = ${JSON.stringify(MCP_ERROR_CODES, null, 2)} as const;
export type McpErrorCode = (typeof MCP_ERROR_CODES)[number];
export const MCP_CLI_TOOL_SCOPES = ${JSON.stringify(MCP_CLI_TOOL_SCOPES, null, 2)} as const;
export type McpCliToolScope = (typeof MCP_CLI_TOOL_SCOPES)[number];
`,
);
process.stderr.write(`Wrote ${mcpContractOutputPath.pathname}\n`);

// The registry transitively pulls in `@/api/lib/sse.ts`, which opens a
// Redis subscriber connection at import time (for cross-instance SSE
// broadcast) and never unrefs it. That's correct for the long-running API
// process but leaves this one-off script's event loop open indefinitely.
// The export is done at this point, so exit explicitly instead of waiting
// on a handle this script never needed.
process.exit(0);
