// Dev-only exporter: projects the MCP tool registry
// (`DEFAULT_MCP_TOOL_DEFINITIONS`) down to the four `tools/list` wire fields and
// writes a JSON snapshot that `@stll/cli`'s codegen consumes.
//
// Why a snapshot instead of importing the registry from `@stll/cli` directly:
// `static-tool-definitions.ts` transitively imports `@/api/env`, which eagerly
// validates the full API environment (REDIS_URL, BETTER_AUTH_*, GOTENBERG_*,
// ...) at module load. Running that inside `apps/api` (where the env resolves)
// and emitting a plain JSON file keeps the published `@stll/cli` package free of
// any import — type or value — reachable from `apps/api`. Regenerate with
// `bun run codegen` from `packages/cli` (which runs this first, then the pure
// generator). The snapshot is committed, so registry drift shows up as a diff.

import { panic } from "better-result";

import { WRITE_TOOL_REF_FIELD_MAP } from "@/api/handlers/chat/tools/registry-adapter/ref-field-map";
import {
  dynamicToolNamespacePrefix,
  isDynamicToolNamespace,
} from "@/api/lib/mcp-upstream/namespace";
import { CHATGPT_APP_SUBMISSION_PROFILE } from "@/api/mcp/chatgpt-app-submission-profile";
import {
  MCP_DEFAULT_RESOURCE_SCOPES,
  MCP_DISCOVERY_PATH,
  MCP_HTTP_PATH,
  MCP_OAUTH_PROTOCOL_SCOPES,
  STELLA_API_CONTRACT,
} from "@/api/mcp/constants";
import { MCP_ERROR_CODES } from "@/api/mcp/error-codes";
import {
  DYNAMIC_TOOL_FAMILY_POLICIES,
  isStellaOwnedDynamicToolNamespace,
  type StellaOwnedDynamicToolNamespace,
} from "@/api/mcp/gateway/dynamic-tool-policy";
import { listMcpResources } from "@/api/mcp/resources";
import { DEFAULT_MCP_CLI_ANNOTATIONS } from "@/api/mcp/static-cli-metadata";
import { DEFAULT_MCP_TOOL_DEFINITIONS } from "@/api/mcp/static-tool-definitions";
import {
  MCP_CLI_TOOL_SCOPES,
  type McpCliToolAnnotation,
} from "@/api/mcp/tool-types";

type StaticMcpToolDefinition = (typeof DEFAULT_MCP_TOOL_DEFINITIONS)[number];

const deriveCliAnnotation = (
  tool: StaticMcpToolDefinition,
): McpCliToolAnnotation => {
  const annotation: McpCliToolAnnotation =
    DEFAULT_MCP_CLI_ANNOTATIONS[tool.name];
  const behavior =
    "destructiveBehavior" in tool ? tool.destructiveBehavior : undefined;
  if (behavior === undefined || behavior.type === "always") {
    return annotation;
  }

  if (behavior.type === "capability-catalog") {
    return { ...annotation, confirmPassthrough: true };
  }

  const discriminator = annotation.discriminator;
  if (discriminator === undefined || discriminator.prop !== behavior.property) {
    return panic(
      `${tool.name} CLI metadata must discriminate on ${behavior.property}`,
    );
  }

  return {
    ...annotation,
    discriminator: {
      ...discriminator,
      subcommands: Object.fromEntries(
        Object.entries(discriminator.subcommands).map(([value, subcommand]) => [
          value,
          {
            ...subcommand,
            destructive: behavior.destructiveValues.some(
              (destructiveValue) => destructiveValue === value,
            ),
          },
        ]),
      ),
    },
  };
};

// The four wire fields exposed by `tools/list` (scope/feature/access/anonymized
// are server-internal and never leave the server).
type RegistryToolListing = {
  cli: McpCliToolAnnotation;
  name: string;
  description: string;
  inputSchema: unknown;
  annotations?: unknown;
};

const listings: RegistryToolListing[] = [];
for (const tool of DEFAULT_MCP_TOOL_DEFINITIONS) {
  listings.push({
    cli: deriveCliAnnotation(tool),
    name: tool.name,
    description: tool.description,
    inputSchema: tool.inputSchema,
    annotations: tool.annotations,
  });
}

const snapshotPath = new URL(
  "../../../packages/cli/src/generated/registry-snapshot.json",
  import.meta.url,
);

await Bun.write(snapshotPath, `${JSON.stringify(listings, null, 2)}\n`);

process.stderr.write(
  `Wrote ${listings.length} tool listings to ${snapshotPath.pathname}\n`,
);

const projectedChatPolicyKinds: Record<string, "internal" | "mutation"> = {};
const projectedChatGrantPolicies: Record<string, "approve-once" | "grantable"> =
  {};
for (const tool of DEFAULT_MCP_TOOL_DEFINITIONS) {
  if (
    tool.access !== "write" ||
    !WRITE_TOOL_REF_FIELD_MAP[tool.name].chatProjectable
  ) {
    continue;
  }

  projectedChatPolicyKinds[tool.name] = "mutation";
  projectedChatGrantPolicies[tool.name] = tool.annotations.destructiveHint
    ? "approve-once"
    : "grantable";
}

const generatedChatPolicyPath = new URL(
  "../../../packages/api-contract/src/mcp-chat-tool-policy.gen.ts",
  import.meta.url,
);
const generatedChatPolicy = `// GENERATED by apps/api/scripts/export-mcp-tool-registry.ts. Do not edit by hand.\n\nexport const MCP_CHAT_TOOL_POLICY_KINDS = ${JSON.stringify(projectedChatPolicyKinds, null, 2)} as const;\n\nexport const MCP_CHAT_TOOL_GRANT_POLICIES = ${JSON.stringify(projectedChatGrantPolicies, null, 2)} as const;\n`;
await Bun.write(generatedChatPolicyPath, generatedChatPolicy);
process.stderr.write(`Wrote ${generatedChatPolicyPath.pathname}\n`);

const privateOpenWorldJustification =
  "Operates within stella’s private workspace and does not change public internet or third-party state.";
const externalOpenWorldJustification =
  "May contact an external public-data provider or a selected external capability, while keeping resulting workspace changes private.";
const nonDestructiveJustification =
  "Does not delete, revoke access, overwrite irreversibly, or perform another destructive action.";

const submissionTools = Object.fromEntries(
  DEFAULT_MCP_TOOL_DEFINITIONS.map((tool) => {
    const behavior =
      "destructiveBehavior" in tool ? tool.destructiveBehavior : undefined;
    let readOnlyJustification =
      "Creates, updates, or starts work inside the user’s private stella workspace.";
    if (tool.access === "read") {
      readOnlyJustification =
        "Retrieves or computes data from the user’s authorized stella workspace or configured source without changing stored records.";
    }
    if (behavior?.type === "always") {
      readOnlyJustification =
        "Deletes or writes off the selected record in the user’s private stella workspace.";
    }
    if (
      tool.name === "upload_document_version" ||
      tool.name === "open_document_version_upload"
    ) {
      readOnlyJustification =
        "Starts or completes a private document-version upload in the user’s stella workspace.";
    }
    if (tool.name === "invoke_capability") {
      readOnlyJustification =
        "Dispatches the selected capability, which may create, update, delete, enqueue, or meter work in stella.";
    }
    if (tool.name === "manage_organization") {
      readOnlyJustification =
        "Adds or removes matter members or updates private organization settings.";
    }
    if (tool.name === "prepare_feedback") {
      readOnlyJustification =
        "Sanitizes user-provided feedback and returns draft submission links without publishing or changing any record.";
    }

    let openWorldJustification = privateOpenWorldJustification;
    if (tool.annotations.openWorldHint) {
      openWorldJustification = externalOpenWorldJustification;
    }
    if (tool.name === "prepare_feedback") {
      openWorldJustification =
        "Only prepares a GitHub issue URL and command; it does not submit or publish them.";
    }

    let destructiveJustification = nonDestructiveJustification;
    if (behavior?.type === "always") {
      destructiveJustification =
        "Can irreversibly delete or write off the selected private record and requires explicit confirmation.";
    }
    if (behavior?.type === "input-discriminator") {
      destructiveJustification =
        "Can revoke a member’s matter access; the remove_member action requires explicit confirmation.";
    }
    if (behavior?.type === "capability-catalog") {
      destructiveJustification =
        "Can dispatch a catalog capability marked destructive; destructive targets require explicit confirmation.";
    }

    return [
      tool.name,
      {
        annotations: {
          readOnlyHint: tool.annotations.readOnlyHint,
          openWorldHint: tool.annotations.openWorldHint,
          destructiveHint: tool.annotations.destructiveHint,
        },
        justifications: {
          read_only_justification: readOnlyJustification,
          open_world_justification: openWorldJustification,
          destructive_justification: destructiveJustification,
        },
      },
    ];
  }),
);
// Stella-owned dynamic tool families (skills) are exposed under per-account,
// collision-safe names that no committed file can enumerate. The submission
// schema keys `tools` by exact name and the review form matches a live scan
// the same way, so a scanned dynamic tool cannot be matched from here. The
// justification for every tool of a family is derived from the family policy
// instead, under a namespace section the schema's open root permits; a
// reviewer applies it to each scanned name carrying the family prefix.
const DYNAMIC_TOOL_READ_ONLY_JUSTIFICATIONS = {
  skill:
    "Returns the stored instructions and metadata of one skill from the user’s private stella workspace without changing stored records.",
} as const satisfies Record<StellaOwnedDynamicToolNamespace, string>;
const submissionDynamicToolNamespaces = Object.fromEntries(
  Object.keys(DYNAMIC_TOOL_READ_ONLY_JUSTIFICATIONS).flatMap((namespace) => {
    if (
      !isDynamicToolNamespace(namespace) ||
      !isStellaOwnedDynamicToolNamespace(namespace)
    ) {
      return [];
    }
    const policy = DYNAMIC_TOOL_FAMILY_POLICIES[namespace];
    return [
      [
        namespace,
        {
          tool_name_prefix: dynamicToolNamespacePrefix(namespace),
          matching:
            "Tool names under this prefix are account-specific and may carry a collision suffix; the submission form matches tools by exact name, so apply this entry to every scanned tool whose name starts with the prefix.",
          annotations: {
            readOnlyHint: policy.annotations.readOnlyHint,
            openWorldHint: policy.annotations.openWorldHint,
            destructiveHint: policy.annotations.destructiveHint,
          },
          justifications: {
            read_only_justification:
              DYNAMIC_TOOL_READ_ONLY_JUSTIFICATIONS[namespace],
            open_world_justification: privateOpenWorldJustification,
            destructive_justification: nonDestructiveJustification,
          },
        },
      ],
    ];
  }),
);
const chatgptSubmissionPath = new URL(
  "../../../chatgpt-app-submission.json",
  import.meta.url,
);
await Bun.write(
  chatgptSubmissionPath,
  `${JSON.stringify(
    {
      $schema:
        "https://developers.openai.com/plugins/schemas/chatgpt-app-submission.v1.json",
      schema_version: 1,
      ...CHATGPT_APP_SUBMISSION_PROFILE,
      tools: submissionTools,
      dynamic_tool_namespaces: submissionDynamicToolNamespaces,
    },
    null,
    2,
  )}\n`,
);
process.stderr.write(`Wrote ${chatgptSubmissionPath.pathname}\n`);

// The resource surface (spec 051 S5.4) is generated the same way: project
// `resources/list` to its wire fields so the CLI's `reference` tree never drifts
// from the server's static resources. The set is mode-independent; export the
// default-mode projection.
type ResourceListing = {
  uri: string;
  name: string;
  title?: string;
  description?: string;
  mimeType?: string;
};

const resourceListings: ResourceListing[] = [];
for (const resource of listMcpResources("default")) {
  const listing: ResourceListing = { uri: resource.uri, name: resource.name };
  if (resource.title !== undefined) {
    listing.title = resource.title;
  }
  if (resource.description !== undefined) {
    listing.description = resource.description;
  }
  if (resource.mimeType !== undefined) {
    listing.mimeType = resource.mimeType;
  }
  resourceListings.push(listing);
}

const resourceSnapshotPath = new URL(
  "../../../packages/cli/src/generated/resources-snapshot.json",
  import.meta.url,
);

await Bun.write(
  resourceSnapshotPath,
  `${JSON.stringify(resourceListings, null, 2)}\n`,
);

process.stderr.write(
  `Wrote ${resourceListings.length} resource listings to ${resourceSnapshotPath.pathname}\n`,
);

// The published CLI cannot depend on the private workspace API-contract
// package. Copy this dependency-free transport contract verbatim into its
// committed generated tree instead. API, MCP App and CLI therefore compile
// from one source file, while the existing codegen-diff guard catches a stale
// CLI projection.
const uploadTransportSourcePath = new URL(
  "../../../packages/api-contract/src/document-version-upload.ts",
  import.meta.url,
);
const uploadTransportOutputPath = new URL(
  "../../../packages/cli/src/generated/document-version-upload-transport.ts",
  import.meta.url,
);
const uploadTransportSource = await Bun.file(uploadTransportSourcePath).text();
await Bun.write(
  uploadTransportOutputPath,
  `// GENERATED by \`bun run codegen\`. Do not edit by hand.\n${uploadTransportSource}`,
);
process.stderr.write(`Wrote ${uploadTransportOutputPath.pathname}\n`);

// Bake the API-owned compatibility contract into the CLI. Published CLIs keep
// their generated minimum revision while the server can advance independently;
// Changesets package-version bumps never touch this contract.
const apiContractOutputPath = new URL(
  "../../../packages/cli/src/generated/api-contract.ts",
  import.meta.url,
);
await Bun.write(
  apiContractOutputPath,
  `// GENERATED by \`bun run codegen\`. Do not edit by hand.

export const CLI_SUPPORTED_API_PROTOCOLS = [${STELLA_API_CONTRACT.protocol}] as const;
export const CLI_MINIMUM_SERVER_REVISION = ${STELLA_API_CONTRACT.revision};
export const CLI_REQUIRED_CAPABILITIES = ${JSON.stringify(STELLA_API_CONTRACT.capabilities, null, 2)} as const;
`,
);
process.stderr.write(`Wrote ${apiContractOutputPath.pathname}\n`);

// The CLI is published independently and cannot import the private API
// workspace. Generate its stable MCP wire constants from the API-owned values
// instead of maintaining handwritten mirrors guarded by source-text tests.
const mcpContractOutputPath = new URL(
  "../../../packages/cli/src/generated/mcp-contract.ts",
  import.meta.url,
);
const cliKnownScopes = [
  ...MCP_OAUTH_PROTOCOL_SCOPES,
  ...MCP_DEFAULT_RESOURCE_SCOPES,
];
await Bun.write(
  mcpContractOutputPath,
  `// GENERATED by \`bun run codegen\`. Do not edit by hand.

export const MCP_HTTP_PATH = ${JSON.stringify(MCP_HTTP_PATH)} as const;
export const MCP_DISCOVERY_PATH = ${JSON.stringify(MCP_DISCOVERY_PATH)} as const;
export const CLI_KNOWN_SCOPES = ${JSON.stringify(cliKnownScopes, null, 2)} as const;
export const CLI_REQUIRED_RESOURCE_SCOPES = ${JSON.stringify(MCP_DEFAULT_RESOURCE_SCOPES, null, 2)} as const;
export const MCP_ERROR_CODES = ${JSON.stringify(MCP_ERROR_CODES, null, 2)} as const;
export type McpErrorCode = (typeof MCP_ERROR_CODES)[number];
export const MCP_CLI_TOOL_SCOPES = ${JSON.stringify(MCP_CLI_TOOL_SCOPES, null, 2)} as const;
export type McpCliToolScope = (typeof MCP_CLI_TOOL_SCOPES)[number];
`,
);
process.stderr.write(`Wrote ${mcpContractOutputPath.pathname}\n`);

// The registry transitively pulls in `@/api/lib/sse.ts`, which opens a
// Redis subscriber connection at import time (for cross-instance SSE
// broadcast) and never unrefs it. That's correct for the long-running API
// process but leaves this one-off script's event loop open indefinitely.
// The export is done at this point, so exit explicitly instead of waiting
// on a handle this script never needed.
process.exit(0);
