// Prints the API types apps/web consumes (`WebApiContract` in
// src/eden-contract.ts) into apps/web/src/generated/api-routes.gen.ts. apps/web
// type-checks against that snapshot instead of re-inferring the whole API
// graph. The API implementation stays the source of truth: every run asserts,
// through the compiler's identity relation, that each printed type is
// identical to the inferred one, and `--check` also fails on a stale file.
//
// Modes:
//   bun --filter @stll/api gen:web-api-types           regenerate the file
//   bun --filter @stll/api gen:web-api-types --check   CI drift guard
//
// Printing rules:
// - Types owned by a package apps/web depends on are imported by name, never
//   expanded: expansion loses generic
//   identity (`X extends UIMessage<infer T>`) and brands keyed by a unique
//   symbol the package does not export.
// - A type reached more than once, or recursively, becomes a local alias named
//   from a hash of the path where the traversal first reaches it, so adding a
//   route renames nothing elsewhere.
// - Anything the printer cannot express structurally falls back to
//   `typeToString` and is reported; the identity check then decides.

import { panic } from "better-result";
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import ts from "typescript";

import { withoutTsgoOnlyOptionDiagnostics } from "../../../packages/scripts/src/tsgo-compiler-options";
import {
  hasFlag,
  isReadonlyProperty,
  lateBoundNameType,
} from "./lib/typescript-internals";

const API_DIR = path.resolve(import.meta.dir, "..");
const REPO_ROOT = path.resolve(API_DIR, "../..");
const WEB_DIR = path.join(REPO_ROOT, "apps/web");
const CONTRACT_PATH = path.join(API_DIR, "src/eden-contract.ts");
const CONTRACT_TYPE = "WebApiContract";
const OUTPUT_PATH = path.join(WEB_DIR, "src/generated/api-routes.gen.ts");
// Served from memory, never written: asserts identity inside the API program.
const CHECK_PATH = path.join(API_DIR, "src/__web-api-contract-check__.ts");
const REGENERATE_COMMAND = "bun --filter @stll/api gen:web-api-types";
const HEADER = [
  "// Generated by apps/api/scripts/generate-web-api-types.ts from",
  `// ${CONTRACT_TYPE} in apps/api/src/eden-contract.ts. Do not edit.`,
  `// Regenerate: ${REGENERATE_COMMAND}`,
];
const ALIAS_HASH_LENGTH = 10;

// --- Program ------------------------------------------------------------------

type ApiProgramOptions = {
  virtualFiles: ReadonlyMap<string, string>;
  oldProgram?: ts.Program;
};

const createApiProgram = ({
  virtualFiles,
  oldProgram,
}: ApiProgramOptions): ts.Program => {
  const config = ts.getParsedCommandLineOfConfigFile(
    path.join(API_DIR, "tsconfig.json"),
    {},
    {
      ...ts.sys,
      onUnRecoverableConfigFileDiagnostic: (diagnostic) =>
        panic(formatDiagnostics([diagnostic])),
    },
  );
  if (config === undefined) {
    return panic("generate-web-api-types: cannot read apps/api/tsconfig.json");
  }
  const configErrors = withoutTsgoOnlyOptionDiagnostics(config.errors);
  if (configErrors.length > 0) {
    return panic(formatDiagnostics(configErrors));
  }
  const options = { ...config.options, noEmit: true, incremental: false };
  const host = ts.createCompilerHost(options);
  const { getSourceFile, fileExists, readFile } = host;
  host.fileExists = (fileName) =>
    virtualFiles.has(fileName) || fileExists.call(host, fileName);
  host.readFile = (fileName) =>
    virtualFiles.get(fileName) ?? readFile.call(host, fileName);
  host.getSourceFile = (fileName, languageVersion, ...rest) => {
    const text = virtualFiles.get(fileName);
    return text === undefined
      ? getSourceFile.call(host, fileName, languageVersion, ...rest)
      : ts.createSourceFile(fileName, text, languageVersion, true);
  };
  // Ambient declarations (asset modules) the API sources rely on.
  const ambient = config.fileNames.filter((file) => file.endsWith(".d.ts"));
  return ts.createProgram({
    rootNames: [CONTRACT_PATH, ...virtualFiles.keys(), ...ambient],
    options,
    host,
    ...(oldProgram === undefined ? {} : { oldProgram }),
  });
};

const formatDiagnostics = (diagnostics: readonly ts.Diagnostic[]): string =>
  ts.formatDiagnostics(diagnostics, {
    getCanonicalFileName: (fileName) => fileName,
    getCurrentDirectory: () => REPO_ROOT,
    getNewLine: () => "\n",
  });

// --- Package references -------------------------------------------------------

const readWebDependencies = (): ReadonlySet<string> => {
  const manifest: unknown = JSON.parse(
    readFileSync(path.join(WEB_DIR, "package.json"), "utf-8"),
  );
  const names = new Set<string>();
  for (const field of ["dependencies", "devDependencies"]) {
    const dependencies: unknown =
      typeof manifest === "object" && manifest !== null
        ? Reflect.get(manifest, field)
        : undefined;
    if (typeof dependencies === "object" && dependencies !== null) {
      for (const name of Object.keys(dependencies)) {
        names.add(name);
      }
    }
  }
  return names;
};

const WORKSPACE_PACKAGE_SOURCE = /\/packages\/([^/]+)\/src\//u;
const NODE_MODULES_PACKAGE = /\/node_modules\/((?:@[^/]+\/)?[^/]+)\//u;
// Compiler libs and runtime globals print by global name, never as imports.
const GLOBAL_TYPE_PACKAGES = new Set(["typescript", "bun-types", "@types/bun"]);

const packageOfFile = (fileName: string): string | undefined => {
  const workspace = WORKSPACE_PACKAGE_SOURCE.exec(fileName);
  if (workspace !== null) {
    return `@stll/${workspace[1]}`;
  }
  const lastNodeModules = fileName.lastIndexOf("/node_modules/");
  if (lastNodeModules === -1) {
    return undefined;
  }
  const name = NODE_MODULES_PACKAGE.exec(fileName.slice(lastNodeModules))?.[1];
  return name === undefined || GLOBAL_TYPE_PACKAGES.has(name)
    ? undefined
    : name;
};

// --- Printer --------------------------------------------------------------------

type TypeNode = {
  body: string;
  path: string;
  references: number;
  recursive: boolean;
};

type PrintResult = {
  declarations: { name: string; text: string }[];
  aliases: { name: string; text: string }[];
  symbolImports: { local: string; name: string; specifier: string }[];
  typeImports: { local: string; name: string; specifier: string }[];
  fallbacks: Map<string, number>;
  packageReferences: Map<string, number>;
};

// Narrowing guards over the compiler's flag fields, instead of assertions.
const isObjectType = (type: ts.Type): type is ts.ObjectType =>
  hasFlag(type.flags, ts.TypeFlags.Object);
const isTypeReference = (type: ts.Type): type is ts.TypeReference =>
  isObjectType(type) && hasFlag(type.objectFlags, ts.ObjectFlags.Reference);
const isTupleTarget = (target: ts.GenericType): target is ts.TupleType =>
  hasFlag(target.objectFlags, ts.ObjectFlags.Tuple);
const isTemplateLiteral = (type: ts.Type): type is ts.TemplateLiteralType =>
  hasFlag(type.flags, ts.TypeFlags.TemplateLiteral);
const isStringMapping = (type: ts.Type): type is ts.StringMappingType =>
  hasFlag(type.flags, ts.TypeFlags.StringMapping);
const isBigIntLiteral = (type: ts.Type): type is ts.BigIntLiteralType =>
  hasFlag(type.flags, ts.TypeFlags.BigIntLiteral);
const isInterfaceOrClass = (objectFlags: number): boolean =>
  hasFlag(objectFlags, ts.ObjectFlags.Interface) ||
  hasFlag(objectFlags, ts.ObjectFlags.Class);

// A declaration in a script file, or inside `declare global` in a module.
const isGlobalDeclaration = (declaration: ts.Node): boolean => {
  for (let node = declaration.parent; node !== undefined; node = node.parent) {
    if (ts.isModuleDeclaration(node)) {
      return hasFlag(node.flags, ts.NodeFlags.GlobalAugmentation);
    }
  }
  return !ts.isExternalModule(declaration.getSourceFile());
};

const TOKEN = /\uE000(\d+)\uE000/gu;
const IDENTIFIER = /^[A-Za-z_$][\w$]*$/u;
const NUMERIC_KEY = /^(?:0|[1-9]\d*)$/u;
const FUNCTION_TYPE = /[=]>/u;

type PrinterOptions = {
  program: ts.Program;
  contractSource: ts.SourceFile;
  webDependencies: ReadonlySet<string>;
};

const printContract = ({
  program,
  contractSource,
  webDependencies,
}: PrinterOptions): PrintResult => {
  const checker = program.getTypeChecker();
  const undefinedType = checker.getUndefinedType();
  const fallbacks = new Map<string, number>();
  const packageReferences = new Map<string, number>();
  const count = (map: Map<string, number>, key: string) =>
    map.set(key, (map.get(key) ?? 0) + 1);
  const fallback = (reason: string, type: ts.Type): string => {
    count(fallbacks, reason);
    return checker.typeToString(
      type,
      undefined,
      ts.TypeFormatFlags.NoTruncation,
    );
  };

  const resolveAlias = (symbol: ts.Symbol): ts.Symbol =>
    !hasFlag(symbol.flags, ts.SymbolFlags.Alias)
      ? symbol
      : checker.getAliasedSymbol(symbol);

  // Global types (lib.*.d.ts, bun-types) print by name when that name resolves
  // to the same symbol from the contract module.
  const globalsByName = new Map<string, ts.Symbol>();
  for (const symbol of checker.getSymbolsInScope(
    contractSource,
    ts.SymbolFlags.Type,
  )) {
    const declaration = symbol.declarations?.at(0);
    if (declaration !== undefined && isGlobalDeclaration(declaration)) {
      globalsByName.set(symbol.getName(), resolveAlias(symbol));
    }
  }
  const globalName = (symbol: ts.Symbol | undefined): string | undefined => {
    if (symbol === undefined) {
      return undefined;
    }
    const name = symbol.getName();
    return globalsByName.get(name) === symbol ? name : undefined;
  };

  const moduleExports = new Map<string, Map<ts.Symbol, string> | null>();
  const exportsOfModule = (
    specifier: string,
  ): Map<ts.Symbol, string> | null => {
    const cached = moduleExports.get(specifier);
    if (cached !== undefined) {
      return cached;
    }
    // Resolved from the API side so the entry is the file this program loaded
    // (and so the same symbols); apps/web resolves the same package by name.
    const resolved = ts.resolveModuleName(
      specifier,
      CONTRACT_PATH,
      program.getCompilerOptions(),
      ts.sys,
    ).resolvedModule;
    const source =
      resolved === undefined
        ? undefined
        : program.getSourceFile(resolved.resolvedFileName);
    const moduleSymbol =
      source === undefined ? undefined : checker.getSymbolAtLocation(source);
    let exports: Map<ts.Symbol, string> | null = null;
    if (moduleSymbol !== undefined) {
      exports = new Map();
      for (const exported of checker.getExportsOfModule(moduleSymbol)) {
        exports.set(resolveAlias(exported), exported.getName());
      }
    }
    moduleExports.set(specifier, exports);
    return exports;
  };

  // Unique symbols key type literals, so they are imported as values. A
  // symbol its package entry does not export is imported from its declaring
  // file.
  const symbolImports = new Map<
    string,
    { local: string; name: string; specifier: string }
  >();
  // The declaring file, reached through the package directory apps/web itself
  // resolves, so the import lands on the same declaration file (and so the
  // same unique symbol) as the package's own types in the web program.
  const declaringFileSpecifier = (
    symbol: ts.Symbol,
    fileName: string,
    packageName: string | undefined,
  ): string => {
    const packageMarker =
      packageName === undefined ? undefined : `/node_modules/${packageName}/`;
    const inPackage =
      packageMarker === undefined ? -1 : fileName.lastIndexOf(packageMarker);
    const webEntry =
      packageName === undefined || !webDependencies.has(packageName)
        ? undefined
        : ts.resolveModuleName(
            packageName,
            OUTPUT_PATH,
            program.getCompilerOptions(),
            ts.sys,
          ).resolvedModule?.resolvedFileName;
    const webRoot =
      webEntry === undefined || packageMarker === undefined
        ? -1
        : webEntry.lastIndexOf(packageMarker);
    if (packageMarker === undefined || inPackage === -1 || webRoot === -1) {
      return panic(
        `generate-web-api-types: unique symbol ${symbol.getName()} is declared in ` +
          `${path.relative(REPO_ROOT, fileName)}, which apps/web cannot import. ` +
          "Declare it in a package apps/web depends on.",
      );
    }
    const target =
      (webEntry ?? "").slice(0, webRoot + packageMarker.length) +
      fileName.slice(inPackage + packageMarker.length);
    return (
      path
        .relative(path.dirname(OUTPUT_PATH), target)
        // Import a declaration file by its JavaScript twin: `x.d.mts` as `x.mjs`.
        .replace(/\.d\.([cm]?)ts$/u, ".$1js")
        .replace(/\.tsx?$/u, "")
    );
  };

  const uniqueSymbolLocal = (type: ts.Type): string => {
    const symbol = type.symbol;
    const fileName =
      (symbol.valueDeclaration ?? symbol.declarations?.at(0))?.getSourceFile()
        .fileName ?? panic(`unique symbol without a declaration`);
    const packageName = packageOfFile(fileName);
    let specifier: string;
    if (
      packageName !== undefined &&
      webDependencies.has(packageName) &&
      exportsOfModule(packageName)?.get(symbol) === symbol.getName()
    ) {
      specifier = packageName;
    } else {
      specifier = declaringFileSpecifier(symbol, fileName, packageName);
    }
    const key = `${specifier}#${symbol.getName()}`;
    const existing = symbolImports.get(key);
    if (existing !== undefined) {
      return existing.local;
    }
    const local = `__symbol${symbolImports.size}`;
    symbolImports.set(key, { local, name: symbol.getName(), specifier });
    return local;
  };

  // Named imports, not inline `import("pkg").Name`: the compiler never marks
  // an alias used when its only reference is an import type's argument.
  const typeImports = new Map<
    string,
    { local: string; name: string; specifier: string }
  >();
  const packageReference = (type: ts.Type): string | undefined => {
    let symbol = type.aliasSymbol;
    let typeArguments: readonly ts.Type[] = type.aliasTypeArguments ?? [];
    if (symbol === undefined && isTypeReference(type)) {
      const { target } = type;
      if (isInterfaceOrClass(target.objectFlags)) {
        symbol = target.symbol;
        typeArguments = checker
          .getTypeArguments(type)
          .slice(0, target.typeParameters?.length ?? 0);
      }
    } else if (
      symbol === undefined &&
      isObjectType(type) &&
      isInterfaceOrClass(type.objectFlags)
    ) {
      symbol = type.symbol;
      typeArguments = [];
    }
    if (symbol === undefined) {
      return undefined;
    }
    const fileName = symbol.declarations?.at(0)?.getSourceFile().fileName;
    const packageName =
      fileName === undefined ? undefined : packageOfFile(fileName);
    if (packageName === undefined || !webDependencies.has(packageName)) {
      return undefined;
    }
    const exportedName = exportsOfModule(packageName)?.get(symbol);
    if (exportedName === undefined) {
      return undefined;
    }
    count(packageReferences, `${packageName}#${exportedName}`);
    const local = `${packageName.replaceAll(/^@|[^\w$]+/gu, (match) => (match === "@" ? "" : "_"))}_${exportedName}`;
    typeImports.set(local, {
      local,
      name: exportedName,
      specifier: packageName,
    });
    const printedArguments =
      typeArguments.length === 0
        ? ""
        : `<${typeArguments.map((argument, index) => at(`<${index}>`, () => print(argument))).join(", ")}>`;
    return `${local}${printedArguments}`;
  };

  // --- traversal state: shared nodes become tokens resolved after printing
  const nodes: TypeNode[] = [];
  const nodeIds = new Map<ts.Type, number>();
  const onStack = new Set<number>();
  const pathStack: string[] = [];
  const at = <T>(segment: string, run: () => T): T => {
    pathStack.push(segment);
    try {
      return run();
    } finally {
      pathStack.pop();
    }
  };
  const token = (id: number) => `\uE000${id}\uE000`;
  const memo = (type: ts.Type, body: () => string): string => {
    const existing = nodeIds.get(type);
    if (existing !== undefined) {
      const node = nodes[existing] ?? panic(`missing node ${existing}`);
      node.references += 1;
      if (onStack.has(existing)) {
        node.recursive = true;
      }
      return token(existing);
    }
    const id = nodes.length;
    const node: TypeNode = {
      body: "",
      path: pathStack.join("/"),
      references: 1,
      recursive: false,
    };
    nodes.push(node);
    nodeIds.set(type, id);
    onStack.add(id);
    node.body = body();
    onStack.delete(id);
    return token(id);
  };

  const propertyKey = (property: ts.Symbol): string => {
    const name = property.getName();
    if (name.startsWith("__@")) {
      const declaration = property.declarations?.at(0);
      const declaredName =
        declaration !== undefined && ts.isPropertySignature(declaration)
          ? declaration.name
          : undefined;
      const keyType =
        declaredName !== undefined && ts.isComputedPropertyName(declaredName)
          ? checker.getTypeAtLocation(declaredName.expression)
          : lateBoundNameType(property);
      if (
        keyType !== undefined &&
        hasFlag(keyType.flags, ts.TypeFlags.UniqueESSymbol)
      ) {
        return `[${uniqueSymbolLocal(keyType)}]`;
      }
      return `[${fallback("unresolved symbol key", checker.getTypeOfSymbol(property))}]`;
    }
    if (IDENTIFIER.test(name) || NUMERIC_KEY.test(name)) {
      return name;
    }
    return JSON.stringify(name);
  };

  // `x?: T` reads back as `T | missing`; the missing type is an undefined
  // type distinct from the real `undefined`, dropped again when printing `?`.
  const withoutMissing = (type: ts.Type): ts.Type[] => {
    const isMissing = (member: ts.Type) =>
      hasFlag(member.flags, ts.TypeFlags.Undefined) && member !== undefinedType;
    if (type.isUnion()) {
      return type.types.filter((member) => !isMissing(member));
    }
    return isMissing(type) ? [] : [type];
  };

  const signature = (sig: ts.Signature, arrow: boolean): string => {
    const typeParameters = sig.getTypeParameters() ?? [];
    const printedTypeParameters =
      typeParameters.length === 0
        ? ""
        : `<${typeParameters
            .map((parameter) => {
              const constraint = parameter.getConstraint();
              const fallbackDefault = parameter.getDefault();
              return (
                parameter.symbol.getName() +
                (constraint === undefined
                  ? ""
                  : ` extends ${at("extends", () => print(constraint))}`) +
                (fallbackDefault === undefined
                  ? ""
                  : ` = ${at("default", () => print(fallbackDefault))}`)
              );
            })
            .join(", ")}>`;
    const parameters: string[] = [];
    const thisParameter = sig.thisParameter;
    if (thisParameter !== undefined) {
      parameters.push(
        `this: ${at("this", () => print(checker.getTypeOfSymbol(thisParameter)))}`,
      );
    }
    for (const [index, parameter] of sig.getParameters().entries()) {
      const declaration = parameter.valueDeclaration;
      const isRest =
        declaration !== undefined &&
        ts.isParameter(declaration) &&
        declaration.dotDotDotToken !== undefined;
      const isOptional =
        !isRest &&
        declaration !== undefined &&
        ts.isParameter(declaration) &&
        checker.isOptionalParameter(declaration);
      const name = IDENTIFIER.test(parameter.getName())
        ? parameter.getName()
        : `arg${index}`;
      const printed = at(`(${index})`, () =>
        print(checker.getTypeOfSymbol(parameter)),
      );
      parameters.push(
        `${isRest ? "..." : ""}${name}${isOptional ? "?" : ""}: ${printed}`,
      );
    }
    const predicate = checker.getTypePredicateOfSignature(sig);
    let returned: string;
    if (predicate === undefined) {
      returned = at("=>", () => print(sig.getReturnType()));
    } else {
      const asserts =
        predicate.kind === ts.TypePredicateKind.AssertsThis ||
        predicate.kind === ts.TypePredicateKind.AssertsIdentifier;
      const subject =
        predicate.kind === ts.TypePredicateKind.This ||
        predicate.kind === ts.TypePredicateKind.AssertsThis
          ? "this"
          : predicate.parameterName;
      const narrowed = predicate.type;
      returned = `${asserts ? "asserts " : ""}${subject}${
        narrowed === undefined ? "" : ` is ${at("is", () => print(narrowed))}`
      }`;
    }
    return `${printedTypeParameters}(${parameters.join(", ")})${arrow ? " => " : ": "}${returned}`;
  };

  const objectBody = (type: ts.Type): string => {
    const members: string[] = [];
    for (const [index, sig] of checker
      .getSignaturesOfType(type, ts.SignatureKind.Call)
      .entries()) {
      members.push(at(`call${index}`, () => signature(sig, false)));
    }
    for (const [index, sig] of checker
      .getSignaturesOfType(type, ts.SignatureKind.Construct)
      .entries()) {
      members.push(`new ${at(`new${index}`, () => signature(sig, false))}`);
    }
    for (const info of checker.getIndexInfosOfType(type)) {
      const key = at("[key]", () => print(info.keyType));
      members.push(
        `${info.isReadonly ? "readonly " : ""}[key: ${key}]: ${at(`[${key}]`, () => print(info.type))}`,
      );
    }
    for (const property of checker.getPropertiesOfType(type)) {
      const optional = hasFlag(property.flags, ts.SymbolFlags.Optional);
      const key = propertyKey(property);
      const propertyType = checker.getTypeOfSymbol(property);
      if (hasFlag(property.flags, ts.SymbolFlags.Method) && !optional) {
        const signatures = checker.getSignaturesOfType(
          propertyType,
          ts.SignatureKind.Call,
        );
        if (
          signatures.length > 0 &&
          checker.getPropertiesOfType(propertyType).length === 0
        ) {
          for (const [index, sig] of signatures.entries()) {
            members.push(
              `${key}${at(`${key}#${index}`, () => signature(sig, false))}`,
            );
          }
          continue;
        }
      }
      const printed = at(key, () => {
        if (!optional) {
          return print(propertyType);
        }
        const kept = withoutMissing(propertyType);
        return kept.length === 0
          ? "never"
          : kept
              .map((member, index) =>
                at(`|${index}`, () => unionMember(member)),
              )
              .join(" | ");
      });
      members.push(
        `${isReadonlyProperty(property) ? "readonly " : ""}${key}${optional ? "?" : ""}: ${printed}`,
      );
    }
    return members.length === 0 ? "{}" : `{ ${members.join("; ")} }`;
  };

  const unionMember = (type: ts.Type): string => {
    const printed = print(type);
    return FUNCTION_TYPE.test(printed) && !printed.startsWith("\uE000")
      ? `(${printed})`
      : printed;
  };

  const tuple = (reference: ts.TypeReference, target: ts.TupleType): string => {
    const elements = checker
      .getTypeArguments(reference)
      .map((element, index) => {
        const flags = target.elementFlags[index] ?? ts.ElementFlags.Required;
        const labelNode = target.labeledElementDeclarations?.[index]?.name;
        const label =
          labelNode !== undefined && ts.isIdentifier(labelNode)
            ? labelNode.text
            : undefined;
        const printed = at(`[${index}]`, () => print(element));
        const wrapped = /[|&]|=>/u.test(printed) ? `(${printed})` : printed;
        if (hasFlag(flags, ts.ElementFlags.Rest)) {
          return label === undefined
            ? `...${wrapped}[]`
            : `...${label}: ${wrapped}[]`;
        }
        if (hasFlag(flags, ts.ElementFlags.Variadic)) {
          return label === undefined
            ? `...${printed}`
            : `...${label}: ${printed}`;
        }
        if (hasFlag(flags, ts.ElementFlags.Optional)) {
          return label === undefined ? `${wrapped}?` : `${label}?: ${printed}`;
        }
        return label === undefined ? printed : `${label}: ${printed}`;
      });
    return `${target.readonly ? "readonly " : ""}[${elements.join(", ")}]`;
  };

  const print = (type: ts.Type): string => {
    const flags = type.flags;
    if (
      (hasFlag(flags, ts.TypeFlags.Object) ||
        hasFlag(flags, ts.TypeFlags.Union) ||
        hasFlag(flags, ts.TypeFlags.Intersection)) &&
      globalName(type.aliasSymbol) === undefined &&
      !checker.isArrayType(type) &&
      !checker.isTupleType(type)
    ) {
      const reference = packageReference(type);
      if (reference !== undefined) {
        return reference;
      }
    }
    if (hasFlag(flags, ts.TypeFlags.Any)) {
      return "any";
    }
    if (hasFlag(flags, ts.TypeFlags.Unknown)) {
      return "unknown";
    }
    if (hasFlag(flags, ts.TypeFlags.Never)) {
      return "never";
    }
    if (hasFlag(flags, ts.TypeFlags.String)) {
      return "string";
    }
    if (hasFlag(flags, ts.TypeFlags.Number)) {
      return "number";
    }
    if (hasFlag(flags, ts.TypeFlags.BigInt)) {
      return "bigint";
    }
    if (hasFlag(flags, ts.TypeFlags.ESSymbol)) {
      return "symbol";
    }
    if (hasFlag(flags, ts.TypeFlags.Void)) {
      return "void";
    }
    if (hasFlag(flags, ts.TypeFlags.Undefined)) {
      return "undefined";
    }
    if (hasFlag(flags, ts.TypeFlags.Null)) {
      return "null";
    }
    if (hasFlag(flags, ts.TypeFlags.NonPrimitive)) {
      return "object";
    }
    if (hasFlag(flags, ts.TypeFlags.EnumLiteral)) {
      return fallback("enum literal", type);
    }
    if (type.isStringLiteral()) {
      return JSON.stringify(type.value);
    }
    if (type.isNumberLiteral()) {
      return String(type.value);
    }
    if (isBigIntLiteral(type)) {
      return `${type.value.negative ? "-" : ""}${type.value.base10Value}n`;
    }
    if (hasFlag(flags, ts.TypeFlags.BooleanLiteral)) {
      return checker.typeToString(type);
    }
    if (hasFlag(flags, ts.TypeFlags.UniqueESSymbol)) {
      return `typeof ${uniqueSymbolLocal(type)}`;
    }
    if (hasFlag(flags, ts.TypeFlags.TypeParameter)) {
      return type.symbol.getName();
    }
    if (isTemplateLiteral(type)) {
      const { texts, types } = type;
      const escape = (text: string) =>
        text.replaceAll(/[`\\]/gu, "\\$&").replaceAll("${", "\\${");
      let printed = `\`${escape(texts[0] ?? "")}`;
      for (const [index, span] of types.entries()) {
        printed += `\${${at(`\${${index}}`, () => print(span))}}${escape(texts[index + 1] ?? "")}`;
      }
      return `${printed}\``;
    }
    if (isStringMapping(type)) {
      const inner = at("mapping", () => print(type.type));
      return `${type.symbol.getName()}<${inner}>`;
    }
    if (isObjectType(type)) {
      return printObject(type);
    }
    if (type.isUnion()) {
      const { types } = type;
      return memo(type, () =>
        types
          .map((member, index) => at(`|${index}`, () => unionMember(member)))
          .join(" | "),
      );
    }
    if (type.isIntersection()) {
      const { types } = type;
      return memo(type, () =>
        types
          .map((member, index) => {
            const printed = at(`&${index}`, () => print(member));
            return /[|]|=>/u.test(printed) &&
              !printed.startsWith("\uE000") &&
              !printed.startsWith("{")
              ? `(${printed})`
              : printed;
          })
          .join(" & "),
      );
    }
    return fallback(`type flags ${flags}`, type);
  };

  const printObject = (type: ts.ObjectType): string => {
    if (isTypeReference(type)) {
      const reference = type;
      const { target } = reference;
      if (isTupleTarget(target)) {
        return memo(type, () => tuple(reference, target));
      }
      if (checker.isArrayType(type)) {
        const element = checker.getTypeArguments(reference).at(0);
        const name =
          reference.target.symbol.getName() === "ReadonlyArray"
            ? "ReadonlyArray"
            : "Array";
        return `${name}<${element === undefined ? "unknown" : at("[]", () => print(element))}>`;
      }
      const name = globalName(reference.target.symbol);
      if (name !== undefined) {
        const typeArguments = checker
          .getTypeArguments(reference)
          .slice(0, reference.target.typeParameters?.length ?? 0);
        return typeArguments.length === 0
          ? name
          : `${name}<${typeArguments.map((argument, index) => at(`<${index}>`, () => print(argument))).join(", ")}>`;
      }
    } else if (isInterfaceOrClass(type.objectFlags)) {
      const name = globalName(type.symbol);
      if (name !== undefined) {
        return name;
      }
    }
    // An intersection drops an empty `{}` literal member but keeps an empty
    // mapped type (an `Omit` that removed every key); an empty mapped type
    // keeps the member count, and so the identity, intact.
    if (
      hasFlag(type.objectFlags, ts.ObjectFlags.Mapped) &&
      checker.getPropertiesOfType(type).length === 0 &&
      checker.getIndexInfosOfType(type).length === 0
    ) {
      return "Record<never, never>";
    }
    return memo(type, () => objectBody(type));
  };

  // --- contract members
  const contractModule =
    checker.getSymbolAtLocation(contractSource) ??
    panic("generate-web-api-types: eden-contract.ts is not a module");
  const contractSymbol =
    checker
      .getExportsOfModule(contractModule)
      .find((symbol) => symbol.getName() === CONTRACT_TYPE) ??
    panic(`generate-web-api-types: ${CONTRACT_TYPE} is not exported`);
  const contractType = checker.getDeclaredTypeOfSymbol(contractSymbol);
  const printedDeclarations = checker
    .getPropertiesOfType(contractType)
    .map((property) => ({
      name: property.getName(),
      text: at(property.getName(), () =>
        print(checker.getTypeOfSymbol(property)),
      ),
    }));

  // --- resolve tokens: inline single-use nodes, alias shared or recursive ones
  const aliasNames = new Map<number, string>();
  const usedAliasNames = new Set<string>();
  for (const [id, node] of nodes.entries()) {
    if (!node.recursive && node.references === 1) {
      continue;
    }
    const name = `T${createHash("sha256").update(node.path).digest("hex").slice(0, ALIAS_HASH_LENGTH)}`;
    if (usedAliasNames.has(name)) {
      panic(`generate-web-api-types: alias name collision ${name}`);
    }
    usedAliasNames.add(name);
    aliasNames.set(id, name);
  }
  const inlined = new Map<number, string>();
  const resolve = (text: string): string =>
    text.replaceAll(TOKEN, (_match, rawId: string) => {
      const id = Number(rawId);
      const alias = aliasNames.get(id);
      if (alias !== undefined) {
        return alias;
      }
      const cached = inlined.get(id);
      if (cached !== undefined) {
        return cached;
      }
      const body = resolve(nodes[id]?.body ?? panic(`missing node ${id}`));
      const wrapped =
        body.startsWith("{") || body.startsWith("[") || !/[|&]|=>/u.test(body)
          ? body
          : `(${body})`;
      inlined.set(id, wrapped);
      return wrapped;
    });

  const declarations = printedDeclarations.map(({ name, text }) => ({
    name,
    text: resolve(text),
  }));
  // Only aliases reachable from the declarations, in first-use order.
  const aliases: { name: string; text: string }[] = [];
  const emitted = new Set<number>();
  const aliasIdsByName = new Map(
    [...aliasNames].map(([id, name]) => [name, id]),
  );
  const pending = declarations.map(({ text }) => text);
  while (pending.length > 0) {
    const text = pending.shift() ?? "";
    for (const match of text.matchAll(/\bT[0-9a-f]{10}\b/gu)) {
      const id = aliasIdsByName.get(match[0]);
      if (id === undefined || emitted.has(id)) {
        continue;
      }
      emitted.add(id);
      const aliasText = resolve(nodes[id]?.body ?? panic(`missing node ${id}`));
      aliases.push({ name: match[0], text: aliasText });
      pending.push(aliasText);
    }
  }

  return {
    declarations,
    aliases,
    symbolImports: [...symbolImports.values()],
    typeImports: [...typeImports.values()],
    fallbacks,
    packageReferences,
  };
};

// --- Layout ---------------------------------------------------------------------

/**
 * Breaks object types over lines, one member per line, so a route change
 * shows up as a readable diff. String and template literal contents are left
 * untouched.
 */
const layout = (text: string): string => {
  let output = "";
  let depth = 0;
  let index = 0;
  const templateDepths: number[] = [];
  const newline = () => `\n${"  ".repeat(depth)}`;
  while (index < text.length) {
    const char = text[index] ?? "";
    if (char === '"') {
      let end = index + 1;
      while (end < text.length && text[end] !== '"') {
        end += text[end] === "\\" ? 2 : 1;
      }
      output += text.slice(index, end + 1);
      index = end + 1;
      continue;
    }
    if (char === "`" || (char === "}" && templateDepths.at(-1) === depth)) {
      if (char === "}") {
        templateDepths.pop();
      }
      // Scan template text up to the closing backtick or the next `${`.
      let end = index + 1;
      while (end < text.length && text[end] !== "`") {
        if (text[end] === "\\") {
          end += 2;
          continue;
        }
        if (text[end] === "$" && text[end + 1] === "{") {
          break;
        }
        end += 1;
      }
      if (text[end] === "`") {
        output += text.slice(index, end + 1);
        index = end + 1;
      } else {
        output += text.slice(index, end + 2);
        templateDepths.push(depth);
        index = end + 2;
      }
      continue;
    }
    if (text.startsWith("{ ", index)) {
      depth += 1;
      output += `{${newline()}`;
      index += 2;
      continue;
    }
    if (text.startsWith(" }", index) && depth > 0) {
      depth -= 1;
      output += `;${newline()}}`;
      index += 2;
      continue;
    }
    if (text.startsWith("; ", index) && depth > 0) {
      output += `;${newline()}`;
      index += 2;
      continue;
    }
    output += char;
    index += 1;
  }
  return output;
};

const renderOutput = (result: PrintResult): string => {
  const lines = [...HEADER];
  const bySpecifier = new Map<string, string[]>();
  for (const { local, name, specifier } of [
    ...result.symbolImports,
    ...result.typeImports,
  ]) {
    const names = bySpecifier.get(specifier) ?? [];
    names.push(`${name} as ${local}`);
    bySpecifier.set(specifier, names);
  }
  for (const specifier of [...bySpecifier.keys()].toSorted()) {
    const specifiers = (bySpecifier.get(specifier) ?? []).toSorted();
    lines.push(`import type { ${specifiers.join(", ")} } from "${specifier}";`);
  }
  lines.push("");
  for (const { name, text } of result.declarations) {
    lines.push(`export type ${name} = ${layout(text)};`, "");
  }
  for (const { name, text } of result.aliases) {
    lines.push(`type ${name} = ${layout(text)};`, "");
  }
  return `${lines.join("\n").trimEnd()}\n`;
};

// --- Identity check ---------------------------------------------------------------

const renderIdentityCheck = (names: readonly string[]): string => {
  const specifier = path
    .relative(path.dirname(CHECK_PATH), OUTPUT_PATH)
    .replace(/\.ts$/u, "");
  return [
    `import type * as Generated from "${specifier}";`,
    `import type { ${CONTRACT_TYPE} } from "./eden-contract";`,
    // Identity, not mutual assignability: assignability forgives a lost
    // optional or readonly modifier, a dropped brand, and generic identity.
    "type Identical<A, B> = (<T>() => T extends A ? 1 : 2) extends <T>() => T extends B ? 1 : 2 ? true : false;",
    "type Assert<T extends true> = T;",
    ...names.map(
      (name) =>
        `export type Check${name} = Assert<Identical<Generated.${name}, ${CONTRACT_TYPE}["${name}"]>>;`,
    ),
  ].join("\n");
};

// Checks the file on disk, so run it after writing.
const verifyIdentity = (
  names: readonly string[],
  oldProgram: ts.Program,
): readonly ts.Diagnostic[] => {
  const program = createApiProgram({
    virtualFiles: new Map([[CHECK_PATH, renderIdentityCheck(names)]]),
    oldProgram,
  });
  const check = program.getSourceFile(CHECK_PATH);
  const generated = program.getSourceFile(OUTPUT_PATH);
  if (check === undefined || generated === undefined) {
    return panic("generate-web-api-types: identity check files not loaded");
  }
  return [
    ...program.getSyntacticDiagnostics(generated),
    ...program.getSemanticDiagnostics(generated),
    ...program.getSemanticDiagnostics(check),
  ];
};

// --- CLI --------------------------------------------------------------------------

const readCommitted = (): string | undefined =>
  existsSync(OUTPUT_PATH) ? readFileSync(OUTPUT_PATH, "utf-8") : undefined;

const main = () => {
  const args = process.argv.slice(2);
  const checkOnly = args.includes("--check");
  if (args.some((arg) => arg !== "--check")) {
    panic(`generate-web-api-types: unknown arguments ${args.join(" ")}`);
  }
  const started = performance.now();
  const program = createApiProgram({ virtualFiles: new Map() });
  const contractSource =
    program.getSourceFile(CONTRACT_PATH) ??
    panic("generate-web-api-types: eden-contract.ts not in program");
  const result = printContract({
    program,
    contractSource,
    webDependencies: readWebDependencies(),
  });
  const output = renderOutput(result);
  const outputRelative = path.relative(REPO_ROOT, OUTPUT_PATH);

  for (const [reason, occurrences] of result.fallbacks) {
    console.error(
      `generate-web-api-types: WARNING printer fallback (${reason}) x${occurrences}`,
    );
  }

  console.log(
    `generate-web-api-types: package references ${[...result.packageReferences]
      .map(([reference, uses]) => `${reference} x${uses}`)
      .join(", ")}`,
  );

  if (checkOnly && readCommitted() !== output) {
    console.error(
      `generate-web-api-types: ${outputRelative} is stale. Run \`${REGENERATE_COMMAND}\`.`,
    );
    process.exit(1);
  }

  if (!checkOnly) {
    mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true });
    writeFileSync(OUTPUT_PATH, output);
  }
  const printed = performance.now();

  const diagnostics = verifyIdentity(
    result.declarations.map(({ name }) => name),
    program,
  );
  if (diagnostics.length > 0) {
    console.error(formatDiagnostics(diagnostics));
    console.error(
      "generate-web-api-types: the printed types are not identical to the inferred API types; the printer needs a fix.",
    );
    process.exit(1);
  }

  console.log(
    `generate-web-api-types: printed in ${Math.round(printed - started)} ms, ` +
      `identity verified in ${Math.round(performance.now() - printed)} ms`,
  );
  console.log(
    `generate-web-api-types: ${checkOnly ? "verified" : "wrote"} ${outputRelative} ` +
      `(${result.declarations.length} types, ${result.aliases.length} aliases, ` +
      `${Buffer.byteLength(output)} bytes) in ${Math.round(performance.now() - started)} ms`,
  );
};

main();
