import { panic } from "better-result";
import { readdirSync } from "node:fs";

import { writeOrCheckArtifacts } from "../../../scripts/generated-artifacts";
import { FLOW_TRANSITION_SPECS_V1 } from "../src/lib/db/flow-run-transition-spec";
import {
  transitionDomainSql,
  transitionTriggerSql,
} from "../src/lib/db/transition-sql";

export const transitionMigrationName = (directories: readonly string[]) => {
  const matches = directories.filter((name) =>
    /^\d{14}_flow_run_transitions$/u.test(name),
  );
  const name = matches.at(0);
  if (matches.length !== 1 || name === undefined) {
    return panic("Expected exactly one version-one flow transition migration");
  }
  return name;
};

export const transitionMigrationDirectory = () => {
  const root = new URL("../drizzle/", import.meta.url);
  return new URL(`${transitionMigrationName(readdirSync(root))}/`, root);
};

if (import.meta.main) {
  process.exitCode = await writeOrCheckArtifacts(
    [
      {
        path: new URL("migration.sql", transitionMigrationDirectory()).pathname,
        contents: `-- GENERATED by apps/api/scripts/generate-transition-triggers.ts. Do not edit.
-- requires: 20260707080000_flows
SET LOCAL lock_timeout = '1s';--> statement-breakpoint
SET LOCAL statement_timeout = '5s';--> statement-breakpoint

${FLOW_TRANSITION_SPECS_V1.map((spec) => `${transitionDomainSql(spec).trimEnd()}--> statement-breakpoint\n\n${transitionTriggerSql(spec)}`).join("\n--> statement-breakpoint\n\n")}`,
      },
    ],
    {
      write: process.argv.includes("--write"),
      matched: "the declared flow transitions",
    },
  );
}
