import { writeOrCheckArtifacts } from "../../../scripts/generated-artifacts";
import { FLOW_RUN_TRANSITIONS_V1 } from "../src/lib/db/flow-run-transition-spec";
import {
  transitionDomainSql,
  transitionTriggerSql,
} from "../src/lib/db/transition-sql";

const directory = new URL(
  "../drizzle/20261003124600_flow_run_transitions/",
  import.meta.url,
);

if (import.meta.main) {
  process.exitCode = await writeOrCheckArtifacts(
    [
      {
        path: new URL("migration.sql", directory).pathname,
        contents: `-- GENERATED by apps/api/scripts/generate-transition-triggers.ts. Do not edit.
-- requires: 20260707080000_flows
SET LOCAL lock_timeout = '1s';--> statement-breakpoint
SET LOCAL statement_timeout = '5s';--> statement-breakpoint

${transitionDomainSql(FLOW_RUN_TRANSITIONS_V1).trimEnd()}--> statement-breakpoint

${transitionTriggerSql(FLOW_RUN_TRANSITIONS_V1)}`,
      },
    ],
    {
      write: process.argv.includes("--write"),
      matched: "the declared flow-run transitions",
    },
  );
}
