import "../src/tests/setup-env";
import { panic } from "better-result";
import path from "node:path";

import { blockSchema } from "@stll/legal-ast/document-ast";

import { formattedArtifactsLikeRepository } from "../../../scripts/generated-artifacts";
import { jsonSchemaToType } from "../src/lib/json-schema/json-schema-to-type";
import { toJsonSchema } from "../src/lib/json-schema/valibot-to-json-schema";
import * as frontendContracts from "../src/mcp/app-browser-contracts";
import { MCP_APP_OUTPUT_SCHEMAS } from "../src/mcp/app-contracts";
import { defineChatProjectionMcpToolOutput } from "../src/mcp/valibot-tool-definition";

const outputRoot = path.resolve(
  import.meta.dirname,
  "../../../packages/mcp-apps/src/shared/generated",
);
const schemas = Object.fromEntries(
  Object.entries(MCP_APP_OUTPUT_SCHEMAS).map(([name, schema]) => [
    name,
    defineChatProjectionMcpToolOutput(schema).outputSchema,
  ]),
);

// Bundle the executable projections at their API owner; browser code imports
// the generated contract without reaching the API module graph.
const built = await Bun.build({
  entrypoints: [
    path.resolve(import.meta.dirname, "../src/mcp/app-browser-contracts.ts"),
  ],
  target: "browser",
  external: ["valibot"],
});
const artifact = built.outputs.at(0);
if (!built.success || built.outputs.length !== 1 || artifact === undefined) {
  panic(
    "MCP frontend contracts require one standalone browser module",
    built.logs,
  );
}
const header =
  "// Generated by apps/api/scripts/generate-mcp-app-contracts.ts.\n";

const frontendContractTypeNames = {
  APP_SEARCH_SCHEMA: "SearchResults",
  APP_LOOKUP_SCHEMA: "LookupResults",
  APP_OPEN_DECISION_SCHEMA: "OpenDecision",
  APP_DECISION_BLOCKS_SCHEMA: "ReaderPage",
  APP_PROVISION_PREVIEW_SCHEMA: "ProvisionPreview",
} as const satisfies Record<keyof typeof frontendContracts, string>;
const typeNames = new Map(Object.entries(frontendContractTypeNames));
const declarations = Object.entries(frontendContracts).map(([name, schema]) => {
  const typeName =
    typeNames.get(name) ??
    panic(`MCP frontend contract ${name} has no type name`);
  const jsonSchema = toJsonSchema(schema, {
    errorMode: "throw",
    target: "draft-07",
    typeMode: "input",
    overrideSchema: ({ valibotSchema }) =>
      valibotSchema === blockSchema ? { $ref: "stella:Block" } : undefined,
  });
  return `export type ${typeName} = ${jsonSchemaToType(jsonSchema, { knownReferences: new Map([["stella:Block", "Block"]]), optionalPropertyUndefined: "include" })};\nexport declare const ${name}: v.GenericSchema<unknown, ${typeName}>;`;
});
const artifacts = await formattedArtifactsLikeRepository([
  {
    path: path.join(outputRoot, "schemas.json"),
    contents: `${JSON.stringify(schemas, null, 2)}\n`,
  },
  {
    path: path.join(outputRoot, "contracts.js"),
    contents: header + (await artifact.text()),
  },
  {
    path: path.join(outputRoot, "contracts.d.ts"),
    contents: `${header}import type * as v from "valibot";\nimport type { Block } from "@stll/legal-ast/document-ast";\n\n${declarations.join("\n\n")}\n`,
  },
]);
await Promise.all(
  artifacts.map(
    async ({ path: file, contents }) => await Bun.write(file, contents),
  ),
);
