/**
 * Integration test for the Workflows run pipeline: an `ai` step, a
 * `review-gate` step, and a `create-document` step chained through the
 * real state machine (`flow-executor.ts`) against a real (PGlite) Postgres
 * database, driven the same way the BullMQ worker drives it — one
 * `executeFlowStep` call per queued job.
 *
 * Only genuine external I/O is stubbed: the AI provider call, S3, the
 * derivative/extraction queues, SSE broadcast, and the BullMQ queue itself
 * (so the test never needs a live Redis). Everything else — the run/step
 * transitions, RLS-scoped reads and writes, the DOCX compiler, and entity
 * creation — is the real production code.
 */

import { Result } from "better-result";
import {
  afterAll,
  beforeAll,
  describe,
  expect,
  mock,
  setDefaultTimeout,
  test,
} from "bun:test";
import { asc, eq } from "drizzle-orm";

import { organization, user } from "@/api/db/auth-schema";
import type { SafeDb } from "@/api/db/safe-db";
import {
  flowDefinitions,
  flowRunSteps,
  properties,
  workspaces,
} from "@/api/db/schema";
import { createSafeDb, createScopedDb } from "@/api/db/scoped";
import { createSafeId, toSafeId } from "@/api/lib/branded-types";
import type { SafeId } from "@/api/lib/branded-types";
import type { FlowStep, FlowTrigger } from "@/api/lib/flows/flow-types";
import { asTestRaw } from "@/api/tests/helpers/test-tool-set";
import { getTestDb, releaseTestDb } from "@/api/tests/security/test-utils";
import type { TestDatabase } from "@/api/tests/security/test-utils";

setDefaultTimeout(60_000);

const testDb: TestDatabase = await getTestDb();

// ── Boundary mocks ───────────────────────────────────────
//
// Route both the executor's direct `rootDb` reads and its RLS-scoped writes
// (`createRootScopedDb`/`createRootSafeDb`) at the real test database, so the
// run/step transitions execute as real SQL under RLS, exactly like production.

void mock.module("@/api/db/root", () => ({ rootDb: testDb, rlsDb: testDb }));

type RootScopeArgs = {
  organizationId: SafeId<"organization">;
  userId: SafeId<"user">;
  workspaceIds: SafeId<"workspace">[];
};

void mock.module("@/api/lib/root-scoped-db", () => ({
  createRootScopedDb: ({
    organizationId,
    userId,
    workspaceIds,
  }: RootScopeArgs) =>
    createScopedDb(testDb, workspaceIds, organizationId, userId),
  createRootSafeDb: ({ organizationId, userId, workspaceIds }: RootScopeArgs) =>
    createSafeDb(testDb, workspaceIds, organizationId, userId),
}));

// The BullMQ queue is the only piece that would otherwise need live Redis.
// Capture what the executor enqueues instead so the test can drive each
// step itself, the same way the worker's job processor would.
type EnqueuedStep = { runId: string; stepIndex: number };
const enqueuedSteps: EnqueuedStep[] = [];
const enqueueFlowStepMock = mock(
  async ({ runId, stepIndex }: EnqueuedStep & { delayMs?: number }) => {
    enqueuedSteps.push({ runId, stepIndex });
  },
);
void mock.module("@/api/lib/flows/flow-run-queue", () => ({
  FLOW_RUN_QUEUE_NAME: "flow-run",
  enqueueFlowStep: enqueueFlowStepMock,
}));

void mock.module("@/api/lib/flows/flow-run-events", () => ({
  broadcastFlowRunUpdate: mock(() => undefined),
}));

const MOCK_AI_MARKDOWN =
  "# Mock Memo\n\nThis memo was generated by the mock AI adapter for the flow-run integration test.";
const generateTanStackTextForRoleMock = mock(
  async () => await Promise.resolve(MOCK_AI_MARKDOWN),
);
void mock.module("@/api/lib/tanstack-ai-generate", () => ({
  generateTanStackTextForRole: generateTanStackTextForRoleMock,
}));

const s3WriteMock = mock(async () => {});
const s3DeleteMock = mock(async () => {});
void mock.module("@/api/lib/s3", () => ({
  getS3: () => ({ write: s3WriteMock, delete: s3DeleteMock }),
}));

void mock.module("@/api/lib/search/process-extraction", () => ({
  processExtraction: mock(async () => {}),
}));

void mock.module("@/api/lib/file-derivative-queue", () => ({
  enqueueImageThumbnail: mock(async () => {}),
  enqueueImageThumbnailOrMarkFailed: mock(async () => {}),
  enqueuePdfDerivative: mock(async () => {}),
  enqueuePdfDerivativeOrMarkFailed: mock(async () => {}),
  initFileDerivativeWorker: mock(() => undefined),
}));

const { executeFlowStep, resolveFlowReviewGate } =
  await import("@/api/lib/flows/flow-executor");
const { startFlowRun } = await import("@/api/lib/flows/start-flow-run");

// ── Fixture data ─────────────────────────────────────────

const MANUAL_TRIGGER = { type: "manual" } as const satisfies FlowTrigger;

const AI_STEP: FlowStep = {
  kind: "ai",
  name: "Draft memo",
  prompt: "Draft a short legal memo.",
  includeDocuments: false,
};
const REVIEW_GATE_STEP: FlowStep = {
  kind: "review-gate",
  name: "Legal review",
  instructions: "Confirm the memo is accurate.",
};
const CREATE_DOCUMENT_STEP: FlowStep = {
  kind: "create-document",
  name: "Create document",
  documentTitle: "Flow Test Memo",
};

describe("flow run worker pipeline (ai -> review-gate -> create-document)", () => {
  let organizationId: SafeId<"organization">;
  let userId: SafeId<"user">;
  let workspaceId: SafeId<"workspace">;

  beforeAll(async () => {
    organizationId = createSafeId<"organization">();
    userId = createSafeId<"user">();
    workspaceId = createSafeId<"workspace">();
    const propertyId = createSafeId<"property">();

    await testDb.insert(organization).values({
      id: organizationId,
      name: "Flow Worker Test Org",
      slug: `flow-worker-test-${organizationId}`,
      createdAt: new Date(),
    });
    await testDb.insert(user).values({
      id: userId,
      name: "Flow Worker Test User",
      email: `${userId}@example.com`,
    });
    await testDb.insert(workspaces).values({
      id: workspaceId,
      organizationId,
      name: "Flow worker test matter",
      reference: workspaceId.slice(0, 8),
    });
    await testDb.insert(properties).values({
      id: propertyId,
      workspaceId,
      name: "File",
      status: "fresh",
      content: { type: "file", version: 1 },
      tool: { type: "manual-input", version: 1 },
    });
  });

  afterAll(async () => {
    await releaseTestDb();
  });

  test("advances through ai, an approved review gate, and create-document to completion", async () => {
    const definitionId = createSafeId<"flowDefinition">();
    await testDb.insert(flowDefinitions).values({
      id: definitionId,
      organizationId,
      name: "Contract memo flow",
      steps: [AI_STEP, REVIEW_GATE_STEP, CREATE_DOCUMENT_STEP],
      trigger: MANUAL_TRIGGER,
      enabled: true,
      createdByUserId: userId,
    });

    const safeDb = asTestRaw<SafeDb>(
      createSafeDb(testDb, [workspaceId], organizationId, userId),
    );

    const started = await startFlowRun({
      safeDb,
      organizationId,
      workspaceId,
      definitionId,
      triggerSource: { type: "manual", userId },
      inputEntityIds: [],
    });
    if (Result.isError(started)) {
      throw started.error;
    }
    const { runId } = started.value;

    // Step 0 (`ai`) was enqueued by `startFlowRun`; drive it the way the
    // worker's job processor would.
    expect(enqueuedSteps.pop()).toEqual({ runId, stepIndex: 0 });
    await executeFlowStep(
      { runId, stepIndex: 0 },
      new AbortController().signal,
    );
    expect(generateTanStackTextForRoleMock).toHaveBeenCalledTimes(1);

    // Completing the `ai` step advances and enqueues the `review-gate` step.
    expect(enqueuedSteps.pop()).toEqual({ runId, stepIndex: 1 });
    await executeFlowStep(
      { runId, stepIndex: 1 },
      new AbortController().signal,
    );

    const awaitingReview = await testDb.query.flowRuns.findFirst({
      where: { id: { eq: runId } },
      columns: { status: true },
    });
    expect(awaitingReview?.status).toBe("awaiting_review");
    // A review gate pauses for a human; the executor does not self-enqueue.
    expect(enqueuedSteps).toHaveLength(0);

    const reviewed = await resolveFlowReviewGate({
      safeDb,
      workspaceId,
      runId,
      userId,
      decision: "approved",
      note: null,
    });
    if (Result.isError(reviewed)) {
      throw reviewed.error;
    }
    expect(reviewed.value.status).toBe("running");

    // Approving advances to `create-document`.
    expect(enqueuedSteps.pop()).toEqual({ runId, stepIndex: 2 });
    await executeFlowStep(
      { runId, stepIndex: 2 },
      new AbortController().signal,
    );

    const finished = await testDb.query.flowRuns.findFirst({
      where: { id: { eq: runId } },
      columns: { status: true, currentStepIndex: true },
    });
    expect(finished?.status).toBe("completed");

    const steps = await testDb
      .select({
        index: flowRunSteps.index,
        status: flowRunSteps.status,
        output: flowRunSteps.output,
      })
      .from(flowRunSteps)
      .where(eq(flowRunSteps.runId, runId))
      .orderBy(asc(flowRunSteps.index));

    expect(steps.map((step) => step.status)).toEqual([
      "completed",
      "completed",
      "completed",
    ]);

    const aiOutput = steps[0]?.output;
    if (aiOutput?.kind !== "ai") {
      throw new Error(
        `expected an "ai" step output, got ${JSON.stringify(aiOutput)}`,
      );
    }
    expect(aiOutput.markdown).toBe(MOCK_AI_MARKDOWN);

    const reviewOutput = steps[1]?.output;
    if (reviewOutput?.kind !== "review-gate") {
      throw new Error(
        `expected a "review-gate" step output, got ${JSON.stringify(reviewOutput)}`,
      );
    }
    expect(reviewOutput.decision).toBe("approved");

    const createOutput = steps[2]?.output;
    if (createOutput?.kind !== "create-document") {
      throw new Error(
        `expected a "create-document" step output, got ${JSON.stringify(createOutput)}`,
      );
    }

    const documentEntity = await testDb.query.entities.findFirst({
      where: { id: { eq: toSafeId<"entity">(createOutput.entityId) } },
      columns: { id: true, name: true },
    });
    expect(documentEntity?.name).toBe("Flow Test Memo.docx");
    expect(s3WriteMock).toHaveBeenCalledTimes(1);
  });

  test("rejecting the review gate cancels the run instead of creating a document", async () => {
    const definitionId = createSafeId<"flowDefinition">();
    await testDb.insert(flowDefinitions).values({
      id: definitionId,
      organizationId,
      name: "Reject-path flow",
      steps: [AI_STEP, REVIEW_GATE_STEP],
      trigger: MANUAL_TRIGGER,
      enabled: true,
      createdByUserId: userId,
    });

    const safeDb = asTestRaw<SafeDb>(
      createSafeDb(testDb, [workspaceId], organizationId, userId),
    );
    const started = await startFlowRun({
      safeDb,
      organizationId,
      workspaceId,
      definitionId,
      triggerSource: { type: "manual", userId },
      inputEntityIds: [],
    });
    if (Result.isError(started)) {
      throw started.error;
    }
    const { runId } = started.value;

    enqueuedSteps.length = 0;
    await executeFlowStep(
      { runId, stepIndex: 0 },
      new AbortController().signal,
    );
    expect(enqueuedSteps.pop()).toEqual({ runId, stepIndex: 1 });
    await executeFlowStep(
      { runId, stepIndex: 1 },
      new AbortController().signal,
    );

    const rejected = await resolveFlowReviewGate({
      safeDb,
      workspaceId,
      runId,
      userId,
      decision: "rejected",
      note: "Not approved.",
    });
    if (Result.isError(rejected)) {
      throw rejected.error;
    }
    expect(rejected.value.status).toBe("cancelled");

    const run = await testDb.query.flowRuns.findFirst({
      where: { id: { eq: runId } },
      columns: { status: true },
    });
    expect(run?.status).toBe("cancelled");
    // Rejecting must never chain into the (absent) create-document step.
    expect(enqueuedSteps).toHaveLength(0);
  });
});
