/**
 * Integration test for the Workflows run pipeline: an `ai` step, a
 * `review-gate` step, and a `create-document` step chained through the
 * real state machine (`flow-executor.ts`) against a real (PGlite) Postgres
 * database, driven the same way the BullMQ worker drives it — one
 * `executeFlowStep` call per queued job.
 *
 * Only genuine external I/O is stubbed: the AI provider call, the
 * derivative/extraction queues, SSE broadcast, and the BullMQ queue itself
 * (so the test never needs a live Redis). Object storage runs the real
 * `lib/s3.ts` against an in-process store. Everything else — the run/step
 * transitions, RLS-scoped reads and writes, the DOCX compiler, and entity
 * creation — is the real production code.
 */

import { Result } from "better-result";
import {
  afterAll,
  beforeAll,
  describe,
  expect,
  mock,
  setDefaultTimeout,
  test,
} from "bun:test";
import { asc, eq } from "drizzle-orm";

import { NOTIFICATION_KIND } from "@stll/api-contract/notifications";
import { inspectDocxPackage } from "@stll/folio-core/server";

import { organization, user } from "@/api/db/auth-schema";
import type { SafeDb } from "@/api/db/safe-db";
import {
  fields,
  flowDefinitions,
  flowRunSteps,
  notifications,
  properties,
  WORK_OBLIGATION_SOURCE,
  WORK_OBLIGATION_STATUS,
  workspaceMembers,
  workspaces,
} from "@/api/db/schema";
import { createSafeDb, createScopedDb } from "@/api/db/scoped";
import { envBase } from "@/api/env-base";
import { createSafeId, toSafeId } from "@/api/lib/branded-types";
import type { SafeId } from "@/api/lib/branded-types";
import { createEntityFromBuffer } from "@/api/lib/entities/create-from-buffer";
import type { CreateEntityFromBufferDependencies } from "@/api/lib/entities/create-from-buffer";
import { createFileKey } from "@/api/lib/files/utils";
import {
  executeFlowStep,
  resolveFlowReviewGate as resolveFlowReviewGateWithDependencies,
} from "@/api/lib/flows/flow-executor";
import type { FlowStep, FlowTrigger } from "@/api/lib/flows/flow-types";
import { decideGateForTask } from "@/api/lib/flows/review-gate-task";
import { startFlowRun } from "@/api/lib/flows/start-flow-run";
import type { generateTanStackTextForRole } from "@/api/lib/tanstack-ai-generate";
import { updateTaskHandler } from "@/api/lib/tasks/update-task";
import { DOCX_MIME_TYPE } from "@/api/mime-types";
import { mintAuthProviderId } from "@/api/tests/helpers/auth-provider-id";
import { startFakeS3 } from "@/api/tests/helpers/fake-s3";
import type { FakeS3 } from "@/api/tests/helpers/fake-s3";
import { asTestRaw } from "@/api/tests/helpers/test-tool-set";
import { getTestDb, releaseTestDb } from "@/api/tests/security/test-utils";
import type { TestDatabase } from "@/api/tests/security/test-utils";

setDefaultTimeout(60_000);

const testDb: TestDatabase = await getTestDb();
type ExecuteFlowStepDependencies = NonNullable<
  Parameters<typeof executeFlowStep>[2]
>;
const flowDatabase =
  asTestRaw<NonNullable<ExecuteFlowStepDependencies["database"]>>(testDb);

// ── Boundary mocks ───────────────────────────────────────
//
// Route both the executor's direct `rootDb` reads and its RLS-scoped writes
// (`createRootScopedDb`/`createRootSafeDb`) at the real test database, so the
// run/step transitions execute as real SQL under RLS, exactly like production.

type RootScopeArgs = {
  organizationId: SafeId<"organization">;
  userId: SafeId<"user">;
  workspaceIds: SafeId<"workspace">[];
};

const makeScopedDb = asTestRaw<
  NonNullable<ExecuteFlowStepDependencies["makeScopedDb"]>
>(({ organizationId, userId, workspaceIds }: RootScopeArgs) =>
  createScopedDb(testDb, workspaceIds, organizationId, userId),
);
const makeSafeDb = asTestRaw<
  NonNullable<ExecuteFlowStepDependencies["makeSafeDb"]>
>(({ organizationId, userId, workspaceIds }: RootScopeArgs) =>
  createSafeDb(testDb, workspaceIds, organizationId, userId),
);

// The BullMQ queue is the only piece that would otherwise need live Redis.
// Capture what the executor enqueues instead so the test can drive each
// step itself, the same way the worker's job processor would.
type EnqueuedStep = { runId: string; stepIndex: number };
const enqueuedSteps: EnqueuedStep[] = [];
const enqueueFlowStepMock = mock(
  async ({ runId, stepIndex }: EnqueuedStep & { delayMs?: number }) => {
    enqueuedSteps.push({ runId, stepIndex });
  },
);
const broadcastUpdate = () => undefined;

const MOCK_AI_MARKDOWN =
  "# Mock Memo\n\nThis memo was generated by the mock AI adapter for the flow-run integration test.";
const generateTanStackTextForRoleMock = mock(
  async () => await Promise.resolve(MOCK_AI_MARKDOWN),
);
const generateTextForTest = asTestRaw<typeof generateTanStackTextForRole>(
  generateTanStackTextForRoleMock,
);
const createEntityDependencies = {
  broadcastWorkspaceResourceUpdated: () => undefined,
  enqueueImageThumbnailOrMarkFailed: async () => undefined,
  enqueuePdfDerivativeOrMarkFailed: async () => undefined,
  processExtraction: async () => undefined,
  requestNativeExtractionRun: async () => null,
} satisfies CreateEntityFromBufferDependencies;

const createEntity: typeof createEntityFromBuffer = async (input) =>
  await createEntityFromBuffer({
    ...input,
    dependencies: createEntityDependencies,
  });

const executeFlowStepWithTestModel = async (
  job: Parameters<typeof executeFlowStep>[0],
  signal: AbortSignal,
) =>
  await executeFlowStep(job, signal, {
    generateTextForRole: generateTextForTest,
    database: flowDatabase,
    makeScopedDb,
    makeSafeDb,
    enqueueStep: enqueueFlowStepMock,
    broadcastUpdate,
    createEntity,
    loadAIConfig: async () => null,
    // Governed workflow on: the gate's task must carry an obligation.
    taskFeatures: { governedWorkflow: true, legalLists: false },
  });

/** The task a run's review gate raised, with the obligation that governs it. */
const loadReviewTask = async (runId: SafeId<"flowRun">, stepIndex: number) => {
  const step = await testDb.query.flowRunSteps.findFirst({
    where: { runId: { eq: runId }, index: { eq: stepIndex } },
    columns: { reviewTaskEntityId: true },
  });
  const taskEntityId = step?.reviewTaskEntityId ?? null;
  if (taskEntityId === null) {
    throw new Error("expected the review gate to have raised a task");
  }
  const task = await testDb.query.entities.findFirst({
    where: { id: { eq: taskEntityId } },
    columns: { kind: true, name: true, status: true, workspaceId: true },
  });
  const obligation = await testDb.query.workObligations.findFirst({
    where: { entityId: { eq: taskEntityId } },
    columns: { status: true, ownerUserId: true, sourceType: true },
  });
  if (!task || !obligation) {
    throw new Error("expected the review task and its obligation to exist");
  }
  return { taskEntityId, task, obligation };
};

type ResolveReviewGateDependencies = NonNullable<
  Parameters<typeof resolveFlowReviewGateWithDependencies>[1]
>;
const reviewGateDatabase =
  asTestRaw<NonNullable<ResolveReviewGateDependencies["database"]>>(testDb);

const resolveFlowReviewGate = async (
  options: Parameters<typeof resolveFlowReviewGateWithDependencies>[0],
) =>
  await resolveFlowReviewGateWithDependencies(options, {
    broadcastUpdate,
    enqueueStep: enqueueFlowStepMock,
    database: reviewGateDatabase,
  });

// ── Fixture data ─────────────────────────────────────────

const MANUAL_TRIGGER = { type: "manual" } as const satisfies FlowTrigger;

const AI_STEP: FlowStep = {
  kind: "ai",
  name: "Draft memo",
  prompt: "Draft a short legal memo.",
  includeDocuments: false,
};
const REVIEW_GATE_STEP: FlowStep = {
  kind: "review-gate",
  name: "Legal review",
  instructions: "Confirm the memo is accurate.",
};
const CREATE_DOCUMENT_STEP: FlowStep = {
  kind: "create-document",
  name: "Create document",
  documentTitle: "Flow Test Memo",
};

describe("flow run worker pipeline (ai -> review-gate -> create-document)", () => {
  let organizationId: SafeId<"organization">;
  let userId: SafeId<"user">;
  let workspaceId: SafeId<"workspace">;
  let fake: FakeS3;

  beforeAll(async () => {
    fake = startFakeS3();
    organizationId = mintAuthProviderId<"organization">();
    userId = mintAuthProviderId<"user">();
    workspaceId = createSafeId<"workspace">();
    const propertyId = createSafeId<"property">();

    await testDb.insert(organization).values({
      id: organizationId,
      name: "Flow Worker Test Org",
      slug: `flow-worker-test-${organizationId}`,
      createdAt: new Date(),
    });
    await testDb.insert(user).values({
      id: userId,
      name: "Flow Worker Test User",
      email: `${userId}@example.com`,
    });
    await testDb.insert(workspaces).values({
      id: workspaceId,
      organizationId,
      name: "Flow worker test matter",
      reference: workspaceId.slice(0, 8),
    });
    await testDb.insert(workspaceMembers).values({
      id: createSafeId<"workspaceMember">(),
      workspaceId,
      userId,
    });
    await testDb.insert(properties).values({
      id: propertyId,
      workspaceId,
      name: "File",
      status: "fresh",
      content: { type: "file", version: 1 },
      tool: { type: "manual-input", version: 1 },
    });
  });

  afterAll(async () => {
    fake.stop();
    await releaseTestDb();
  });

  test("advances through ai, an approved review gate, and create-document to completion", async () => {
    const definitionId = createSafeId<"flowDefinition">();
    await testDb.insert(flowDefinitions).values({
      id: definitionId,
      organizationId,
      name: "Contract memo flow",
      steps: [AI_STEP, REVIEW_GATE_STEP, CREATE_DOCUMENT_STEP],
      trigger: MANUAL_TRIGGER,
      enabled: true,
      createdByUserId: userId,
    });

    const safeDb = asTestRaw<SafeDb>(
      createSafeDb(testDb, [workspaceId], organizationId, userId),
    );

    const started = await startFlowRun({
      safeDb,
      organizationId,
      workspaceId,
      definitionId,
      triggerSource: { type: "manual", userId },
      inputEntityIds: [],
      enqueueStep: enqueueFlowStepMock,
    });
    if (Result.isError(started)) {
      throw started.error;
    }
    const { runId } = started.value;

    // Step 0 (`ai`) was enqueued by `startFlowRun`; drive it the way the
    // worker's job processor would.
    expect(enqueuedSteps.pop()).toEqual({ runId, stepIndex: 0 });
    await executeFlowStepWithTestModel(
      { runId, stepIndex: 0 },
      new AbortController().signal,
    );
    expect(generateTanStackTextForRoleMock).toHaveBeenCalledTimes(1);

    // Completing the `ai` step advances and enqueues the `review-gate` step.
    expect(enqueuedSteps.pop()).toEqual({ runId, stepIndex: 1 });
    await executeFlowStepWithTestModel(
      { runId, stepIndex: 1 },
      new AbortController().signal,
    );

    const awaitingReview = await testDb.query.flowRuns.findFirst({
      where: { id: { eq: runId } },
      columns: { status: true },
    });
    expect(awaitingReview?.status).toBe("awaiting_review");
    // A review gate pauses for a human; the executor does not self-enqueue.
    expect(enqueuedSteps).toHaveLength(0);

    // The gate raised a task for the run's actor, owned and already
    // acknowledged by them, sourced from the flow so its completion routes
    // back to the gate.
    const raised = await loadReviewTask(runId, 1);
    expect(raised.task).toEqual({
      kind: "task",
      name: "Contract memo flow · Legal review",
      status: "open",
      workspaceId,
    });
    expect(raised.obligation).toEqual({
      status: WORK_OBLIGATION_STATUS.ACTIVE,
      ownerUserId: userId,
      sourceType: WORK_OBLIGATION_SOURCE.FLOW,
    });

    const reviewed = await resolveFlowReviewGate({
      safeDb,
      workspaceId,
      organizationId,
      runId,
      userId,
      decision: "approved",
      note: null,
      recordAuditEvent: async () => undefined,
    });
    if (Result.isError(reviewed)) {
      throw reviewed.error;
    }
    expect(reviewed.value.status).toBe("running");

    // Deciding the gate fulfils the task it raised.
    const settled = await loadReviewTask(runId, 1);
    expect(settled.task.status).toBe("done");
    expect(settled.obligation.status).toBe(WORK_OBLIGATION_STATUS.COMPLETED);

    // Approving advances to `create-document`.
    expect(enqueuedSteps.pop()).toEqual({ runId, stepIndex: 2 });
    await executeFlowStepWithTestModel(
      { runId, stepIndex: 2 },
      new AbortController().signal,
    );

    const finished = await testDb.query.flowRuns.findFirst({
      where: { id: { eq: runId } },
      columns: { status: true, currentStepIndex: true },
    });
    expect(finished?.status).toBe("completed");

    const steps = await testDb
      .select({
        index: flowRunSteps.index,
        status: flowRunSteps.status,
        output: flowRunSteps.output,
      })
      .from(flowRunSteps)
      .where(eq(flowRunSteps.runId, runId))
      .orderBy(asc(flowRunSteps.index));

    expect(steps.map((step) => step.status)).toEqual([
      "completed",
      "completed",
      "completed",
    ]);

    const aiOutput = steps[0]?.output;
    if (aiOutput?.kind !== "ai") {
      throw new Error(
        `expected an "ai" step output, got ${JSON.stringify(aiOutput)}`,
      );
    }
    expect(aiOutput.markdown).toBe(MOCK_AI_MARKDOWN);

    const reviewOutput = steps[1]?.output;
    if (reviewOutput?.kind !== "review-gate") {
      throw new Error(
        `expected a "review-gate" step output, got ${JSON.stringify(reviewOutput)}`,
      );
    }
    expect(reviewOutput.decision).toBe("approved");

    const createOutput = steps[2]?.output;
    if (createOutput?.kind !== "create-document") {
      throw new Error(
        `expected a "create-document" step output, got ${JSON.stringify(createOutput)}`,
      );
    }

    const documentEntity = await testDb.query.entities.findFirst({
      where: { id: { eq: toSafeId<"entity">(createOutput.entityId) } },
      columns: { id: true, name: true, currentVersionId: true },
    });
    expect(documentEntity?.name).toBe("Flow Test Memo.docx");

    // The row and the object must agree: the file field names the object the
    // step published, and the bytes under that key hash to what the row
    // recorded. A key or payload the row does not describe is a document the
    // reader cannot open.
    const currentVersionId = documentEntity?.currentVersionId ?? null;
    if (currentVersionId === null) {
      throw new Error("expected the created document to have a version");
    }
    const fileContent = (
      await testDb
        .select({ content: fields.content })
        .from(fields)
        .where(eq(fields.entityVersionId, currentVersionId))
    ).at(0)?.content;
    if (fileContent?.type !== "file") {
      throw new Error(
        `expected a file field, got ${JSON.stringify(fileContent)}`,
      );
    }

    const documentKey = createFileKey({
      organizationId,
      workspaceId,
      fileId: fileContent.id,
      mimeType: DOCX_MIME_TYPE,
    });
    expect(
      fake.requests
        .filter((request) => request.method === "PUT")
        .map((request) => request.key),
    ).toEqual([documentKey]);
    const stored = fake.objects.get(`${envBase.S3_BUCKET}/${documentKey}`);
    if (stored === undefined) {
      throw new Error(`no object was stored at ${documentKey}`);
    }
    expect(stored.contentType).toBe(DOCX_MIME_TYPE);
    expect(
      new Bun.CryptoHasher("sha256").update(stored.bytes).digest("hex"),
    ).toBe(fileContent.sha256Hex);

    // The step renders the AI step's Markdown on stella's house preset:
    // "BodyText" is absent from folio's default style catalog, so its
    // presence proves the document was composed through the owner rather
    // than a bare Markdown-to-DOCX conversion.
    const inspection = await inspectDocxPackage(stored.bytes, {
      xmlParts: ["word/styles.xml"],
    });
    expect(
      inspection.xmlParts.find((part) => part.path === "word/styles.xml")?.text,
    ).toContain('w:styleId="BodyText"');
  });

  test("closing the gate's task through a task status change approves the gate", async () => {
    const definitionId = createSafeId<"flowDefinition">();
    await testDb.insert(flowDefinitions).values({
      id: definitionId,
      organizationId,
      name: "Task-decided flow",
      steps: [AI_STEP, REVIEW_GATE_STEP, CREATE_DOCUMENT_STEP],
      trigger: MANUAL_TRIGGER,
      enabled: true,
      createdByUserId: userId,
    });
    const safeDb = asTestRaw<SafeDb>(
      createSafeDb(testDb, [workspaceId], organizationId, userId),
    );
    const started = await startFlowRun({
      safeDb,
      workspaceId,
      organizationId,
      definitionId,
      inputEntityIds: [],
      triggerSource: { type: "manual", userId },
      enqueueStep: enqueueFlowStepMock,
    });
    if (Result.isError(started)) {
      throw started.error;
    }
    const runId = started.value.runId;
    expect(enqueuedSteps.pop()).toEqual({ runId, stepIndex: 0 });
    await executeFlowStepWithTestModel(
      { runId, stepIndex: 0 },
      new AbortController().signal,
    );
    expect(enqueuedSteps.pop()).toEqual({ runId, stepIndex: 1 });
    await executeFlowStepWithTestModel(
      { runId, stepIndex: 1 },
      new AbortController().signal,
    );
    const raised = await loadReviewTask(runId, 1);

    // The task panel, the kanban board, and the save_task capability all
    // change a task's status this way; for a gate task that is the decision.
    const updated = await Result.gen(() =>
      updateTaskHandler({
        safeDb,
        workspaceId,
        userId,
        recordAuditEvent: async () => undefined,
        body: { taskId: raised.taskEntityId, status: "done" },
        features: { governedWorkflow: true, legalLists: false },
        decideGate: async (options) =>
          await decideGateForTask(options, {
            broadcastUpdate,
            enqueueStep: enqueueFlowStepMock,
            database: reviewGateDatabase,
          }),
      }),
    );
    if (Result.isError(updated)) {
      throw updated.error;
    }

    const run = await testDb.query.flowRuns.findFirst({
      where: { id: { eq: runId } },
      columns: { status: true, currentStepIndex: true },
    });
    expect(run).toEqual({ status: "running", currentStepIndex: 2 });
    expect(enqueuedSteps.pop()).toEqual({ runId, stepIndex: 2 });
    const settled = await loadReviewTask(runId, 1);
    expect(settled.task.status).toBe("done");
    expect(settled.obligation.status).toBe(WORK_OBLIGATION_STATUS.COMPLETED);
  });

  test("rejecting the review gate cancels the run instead of creating a document", async () => {
    const definitionId = createSafeId<"flowDefinition">();
    await testDb.insert(flowDefinitions).values({
      id: definitionId,
      organizationId,
      name: "Reject-path flow",
      steps: [AI_STEP, REVIEW_GATE_STEP],
      trigger: MANUAL_TRIGGER,
      enabled: true,
      createdByUserId: userId,
    });

    const safeDb = asTestRaw<SafeDb>(
      createSafeDb(testDb, [workspaceId], organizationId, userId),
    );
    const started = await startFlowRun({
      safeDb,
      organizationId,
      workspaceId,
      definitionId,
      triggerSource: { type: "manual", userId },
      inputEntityIds: [],
      enqueueStep: enqueueFlowStepMock,
    });
    if (Result.isError(started)) {
      throw started.error;
    }
    const { runId } = started.value;

    enqueuedSteps.length = 0;
    await executeFlowStepWithTestModel(
      { runId, stepIndex: 0 },
      new AbortController().signal,
    );
    expect(enqueuedSteps.pop()).toEqual({ runId, stepIndex: 1 });
    await executeFlowStepWithTestModel(
      { runId, stepIndex: 1 },
      new AbortController().signal,
    );

    const rejected = await resolveFlowReviewGate({
      safeDb,
      workspaceId,
      organizationId,
      runId,
      userId,
      decision: "rejected",
      note: "Not approved.",
      recordAuditEvent: async () => undefined,
    });
    if (Result.isError(rejected)) {
      throw rejected.error;
    }
    expect(rejected.value.status).toBe("cancelled");

    // A rejection is a decision too: the review task is done, not abandoned.
    const settled = await loadReviewTask(runId, 1);
    expect(settled.task.status).toBe("done");
    expect(settled.obligation.status).toBe(WORK_OBLIGATION_STATUS.COMPLETED);

    const run = await testDb.query.flowRuns.findFirst({
      where: { id: { eq: runId } },
      columns: { status: true },
    });
    expect(run?.status).toBe("cancelled");
    // Rejecting must never chain into the (absent) create-document step.
    expect(enqueuedSteps).toHaveLength(0);
  });

  test("approving a final review gate completes the run and files its pointer", async () => {
    // The worker never sees this terminal path: the gate is the last step, so
    // `completeStepAndAdvance` is not what finishes the run. Without the
    // review-resolution branch the advertised completion notification would
    // exist only for runs that end on some other kind of step.
    const definitionId = createSafeId<"flowDefinition">();
    await testDb.insert(flowDefinitions).values({
      id: definitionId,
      organizationId,
      name: "Gate-terminated flow",
      steps: [AI_STEP, REVIEW_GATE_STEP],
      trigger: MANUAL_TRIGGER,
      enabled: true,
      createdByUserId: userId,
    });

    const safeDb = asTestRaw<SafeDb>(
      createSafeDb(testDb, [workspaceId], organizationId, userId),
    );
    const started = await startFlowRun({
      safeDb,
      organizationId,
      workspaceId,
      definitionId,
      triggerSource: { type: "manual", userId },
      inputEntityIds: [],
      enqueueStep: enqueueFlowStepMock,
    });
    if (Result.isError(started)) {
      throw started.error;
    }
    const { runId } = started.value;

    enqueuedSteps.length = 0;
    await executeFlowStepWithTestModel(
      { runId, stepIndex: 0 },
      new AbortController().signal,
    );
    expect(enqueuedSteps.pop()).toEqual({ runId, stepIndex: 1 });
    await executeFlowStepWithTestModel(
      { runId, stepIndex: 1 },
      new AbortController().signal,
    );

    const approved = await resolveFlowReviewGate({
      safeDb,
      workspaceId,
      organizationId,
      runId,
      userId,
      decision: "approved",
      note: null,
      recordAuditEvent: async () => undefined,
    });
    if (Result.isError(approved)) {
      throw approved.error;
    }
    expect(approved.value.status).toBe("completed");
    expect(enqueuedSteps).toHaveLength(0);

    const filed = await testDb
      .select({
        userId: notifications.userId,
        organizationId: notifications.organizationId,
        kind: notifications.kind,
        entityId: notifications.entityId,
        metadata: notifications.metadata,
      })
      .from(notifications)
      .where(eq(notifications.idempotencyKey, `flow-run-completed:${runId}`));

    expect(filed).toEqual([
      {
        userId,
        organizationId,
        kind: NOTIFICATION_KIND.FLOW_RUN_COMPLETED,
        entityId: runId,
        metadata: { flowName: "Gate-terminated flow" },
      },
    ]);
  });
});
