export type DocSource = {
  dependencies: readonly [string, ...string[]];
  url: string;
};

export type NoLlmsTxtExclusion = {
  checkedAt: string;
  dependency: string;
  explanation: string;
  expiresAt: string;
  reason: "no-llms-txt";
};

export const DOC_SOURCES = {
  Elysia: {
    dependencies: ["elysia", "@elysia/cors", "@elysia/eden"],
    url: "https://elysiajs.com/llms.txt",
  },
  Drizzle: {
    dependencies: ["drizzle-orm", "drizzle-kit", "eslint-plugin-drizzle"],
    url: "https://orm.drizzle.team/llms.txt",
  },
  TanStack: {
    dependencies: [
      "@tanstack/ai",
      "@tanstack/ai-anthropic",
      "@tanstack/ai-bedrock",
      "@tanstack/ai-client",
      "@tanstack/ai-code-mode",
      "@tanstack/ai-codex",
      "@tanstack/ai-gemini",
      "@tanstack/ai-mcp",
      "@tanstack/ai-mistral",
      "@tanstack/ai-openai",
      "@tanstack/ai-openrouter",
      "@tanstack/ai-persistence",
      "@tanstack/ai-react",
      "@tanstack/ai-sandbox",
      "@tanstack/devtools-vite",
      "@tanstack/eslint-plugin-query",
      "@tanstack/eslint-plugin-router",
      "@tanstack/react-devtools",
      "@tanstack/react-form",
      "@tanstack/react-hotkeys",
      "@tanstack/react-query",
      "@tanstack/react-query-devtools",
      "@tanstack/react-router",
      "@tanstack/react-router-devtools",
      "@tanstack/react-router-ssr-query",
      "@tanstack/react-store",
      "@tanstack/react-table",
      "@tanstack/react-table-devtools",
      "@tanstack/react-virtual",
      "@tanstack/table-core",
    ],
    url: "https://tanstack.com/llms.txt",
  },
  TanStackStart: {
    dependencies: ["@tanstack/react-start"],
    url: "https://tanstack.com/start/latest/llms.txt",
  },
  React: {
    dependencies: ["react", "react-dom", "@types/react", "@types/react-dom"],
    url: "https://react.dev/llms.txt",
  },
  ReactEmail: {
    dependencies: ["@react-email/components", "@react-email/render"],
    url: "https://react.email/docs/llms.txt",
  },
  BaseUI: {
    dependencies: ["@base-ui/react"],
    url: "https://base-ui.com/llms.txt",
  },
  Valibot: {
    dependencies: ["valibot", "@valibot/to-json-schema"],
    url: "https://valibot.dev/llms.txt",
  },
  TipTap: {
    dependencies: [
      "@tiptap/core",
      "@tiptap/extension-bold",
      "@tiptap/extension-document",
      "@tiptap/extension-hard-break",
      "@tiptap/extension-heading",
      "@tiptap/extension-history",
      "@tiptap/extension-italic",
      "@tiptap/extension-list",
      "@tiptap/extension-mention",
      "@tiptap/extension-paragraph",
      "@tiptap/extension-placeholder",
      "@tiptap/extension-text",
      "@tiptap/pm",
      "@tiptap/react",
      "@tiptap/suggestion",
      "@hocuspocus/provider",
      "@hocuspocus/server",
      "prosemirror-commands",
      "prosemirror-history",
      "prosemirror-keymap",
      "prosemirror-model",
      "prosemirror-state",
      "prosemirror-view",
      "y-prosemirror",
    ],
    url: "https://tiptap.dev/docs/llms.txt",
  },
  Tauri: {
    dependencies: ["@tauri-apps/api", "@tauri-apps/cli"],
    url: "https://v2.tauri.app/llms.txt",
  },
  Vite: {
    dependencies: ["vite", "@vitejs/plugin-react"],
    url: "https://vite.dev/llms.txt",
  },
  Expo: {
    dependencies: [
      "expo",
      "expo-constants",
      "expo-linking",
      "expo-router",
      "expo-status-bar",
      "expo-system-ui",
      "react-native-safe-area-context",
      "react-native-screens",
    ],
    url: "https://docs.expo.dev/llms.txt",
  },
  ReactNative: {
    dependencies: ["react-native"],
    url: "https://reactnative.dev/llms.txt",
  },
  MCP: {
    dependencies: [
      "@modelcontextprotocol/client",
      "@modelcontextprotocol/ext-apps",
      "@modelcontextprotocol/server",
    ],
    url: "https://modelcontextprotocol.io/llms.txt",
  },
  AWSSDK: {
    dependencies: [
      "@aws-sdk/client-cloudwatch",
      "@aws-sdk/client-s3",
      "@aws-sdk/client-sesv2",
      "@aws-sdk/client-sts",
      "@aws-sdk/s3-request-presigner",
      "@smithy/fetch-http-handler",
    ],
    url: "https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/llms.txt",
  },
  AGUI: {
    dependencies: ["@ag-ui/core"],
    url: "https://docs.ag-ui.com/llms.txt",
  },
  Bun: {
    dependencies: ["bun-types"],
    url: "https://bun.sh/llms.txt",
  },
  BetterAuth: {
    dependencies: [
      "better-auth",
      "@better-auth/api-key",
      "@better-auth/core",
      "@better-auth/oauth-provider",
    ],
    url: "https://better-auth.com/llms.txt",
  },
  Turborepo: {
    dependencies: ["turbo"],
    url: "https://turborepo.dev/llms.txt",
  },
  PostHog: {
    dependencies: ["posthog-js", "posthog-node", "@posthog/react"],
    url: "https://posthog.com/llms.txt",
  },
  Zustand: {
    dependencies: ["zustand"],
    url: "https://zustand.docs.pmnd.rs/llms.txt",
  },
  Oxlint: {
    dependencies: [
      "oxlint",
      "@oxlint/plugins",
      "oxc-transform-react",
      "oxfmt",
      "oxlint-tsgolint",
    ],
    url: "https://oxc.rs/llms.txt",
  },
  Streamdown: {
    dependencies: [
      "streamdown",
      "@streamdown/cjk",
      "@streamdown/math",
      "@streamdown/mermaid",
    ],
    url: "https://streamdown.dev/llms.txt",
  },
} as const satisfies Record<string, DocSource>;

const NO_LLMS_TXT_EXPLANATION =
  "The canonical project documentation did not publish an llms.txt endpoint when checked.";
const NO_LLMS_TXT_CHECKED_AT = "2026-08-26T00:00:00.000Z";
const NO_LLMS_TXT_EXPIRES_AT = "2026-09-25T00:00:00.000Z";

const noLlmsTxt = (dependency: string): NoLlmsTxtExclusion => ({
  checkedAt: NO_LLMS_TXT_CHECKED_AT,
  dependency,
  explanation: NO_LLMS_TXT_EXPLANATION,
  expiresAt: NO_LLMS_TXT_EXPIRES_AT,
  reason: "no-llms-txt",
});

export const DOC_SOURCE_EXCLUSIONS = [
  "@astrojs/check",
  "@astrojs/react",
  "@astrojs/sitemap",
  "@astrojs/starlight",
  "@atlaskit/pragmatic-drag-and-drop",
  "@atlaskit/pragmatic-drag-and-drop-auto-scroll",
  "@atlaskit/pragmatic-drag-and-drop-hitbox",
  "@atlaskit/pragmatic-drag-and-drop-live-region",
  "@babel/core",
  "@changesets/changelog-github",
  "@changesets/cli",
  "@electric-sql/pglite",
  "@faker-js/faker",
  "@firecrawl/anydoc",
  "@fontsource-variable/source-serif-4",
  "@formatjs/icu-messageformat-parser",
  "@google/genai",
  "@hyzyla/pdfium",
  "@jitl/quickjs-wasmfile-release-asyncify",
  "@libpdf/core",
  "@litko/yara-x",
  "@mcp-ui/client",
  "@opentelemetry/api-logs",
  "@opentelemetry/exporter-logs-otlp-http",
  "@opentelemetry/resources",
  "@opentelemetry/sdk-logs",
  "@playwright/test",
  "@resvg/resvg-js",
  "@silurus/ooxml",
  "@sinclair/typebox",
  "@stricli/core",
  "@t3-oss/env-core",
  "@tailwindcss/vite",
  "@types/hast",
  "@types/node",
  "@types/nodemailer",
  "@typescript-eslint/utils",
  "@typescript/native",
  "astro",
  "better-result",
  "buffer",
  "bullmq",
  "cheerio",
  "class-variance-authority",
  "client-zip",
  "clsx",
  "cobe",
  "crossws",
  "diff",
  "disposable-email-domains-js",
  "domhandler",
  "driver.js",
  "eslint",
  "expect-type",
  "expo-doctor",
  "fast-check",
  "i18n-unused",
  "immer",
  "input-otp",
  "ip-address",
  "jose",
  "jszip",
  "knip",
  "lefthook",
  "lucide-react",
  "nodemailer",
  "onnxruntime-node",
  "pdfjs-dist",
  "postal-mime",
  "prism-react-renderer",
  "quickjs-emscripten",
  "quickjs-emscripten-core",
  "re2-wasm",
  "react-grab",
  "react-native-web",
  "rollup-plugin-visualizer",
  "scslre",
  "sherif",
  "slimdom",
  "squawk-cli",
  "ssf",
  "tailwind-merge",
  "tailwindcss",
  "thinking-orbs",
  "tsdown",
  "typescript",
  "ultracite",
  "unified",
  "uqr",
  "use-debounce",
  "use-intl",
  "uuid",
  "yjs",
].map(noLlmsTxt);
