name: autofix.ci

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - bun.lock

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  dependabot-bun-dedupe:
    uses: stella/.github/.github/workflows/dependabot-bun-dedupe.yml@699affd63b2d956f71b9833fbed239245aff7e86
