name: Contributor signature notification
defaults:
  run:
    shell: bash

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
concurrency:
  group: ${{ github.workflow }}-pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true
permissions: {}
jobs:
  notify:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Request trusted signature verification
        run: ":"
