name: Release PR

on:
  push:
    branches: [main]

concurrency:
  group: release-pr-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  version:
    name: Maintain Version Packages PR
    permissions:
      contents: read
    uses: stella/.github/.github/workflows/changeset-release-pr.yml@c47bb87cc82047b5fdc2540983148d4e3efa9a37 # v1.3.0
    with:
      bun-version-file: package.json
    secrets:
      CHANGELOG_APP_ID: ${{ secrets.CHANGELOG_APP_ID }}
      CHANGELOG_APP_PRIVATE_KEY: ${{ secrets.CHANGELOG_APP_PRIVATE_KEY }}
